### ISSUE TITLE
FR: Add path property in firestore.Query

### ISSUE THREAD

**Issue by vajahath** [firebase/firebase-js-sdk#1142]
### [REQUIRED] Describe your environment

  * Operating System version: Win 10
  * Firebase SDK version: 5.4.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
`firebase.firestore.DocumentReference` and `firebase.firestore.CollectionReference` has a `path` property. It would be very nice if we have this property in `firebase.firestore.Query` too.
Currently I can't see any field in the `Query` object that identifies the collection being queried.

#### Relevant Code:
```javascript
const collRef = firestore.collection('Cats');
collRef.path // 'Cats'

const docRef = firestrore.collection('Cats').doc('kity');
docRef.path // 'Cats/kity'

const qRef = firestore.collection('Cats').limit(5);
qRef.path // it would be nice if this returned the collection name 'Cats'
```

**Comment by davideast** [comment]
Hi @vajahath! We don't allow this because there's a fundamental difference between a `query` and a `collection`. Queries are not always tied back to a single path. For example, we intend to allow you to query across collections, to more directly solve problems like these https://stackoverflow.com/questions/46573014/firestore-query-subcollections.
