### ISSUE TITLE
FR: allow number as index in CollectionReference.doc() (automatically cast to string)

### ISSUE THREAD

**Issue by simonhaenisch** [firebase/firebase-js-sdk#1155]
### Environment

  * Operating System version: macOS 10.13.5
  * Browser version: Chrome 68
  * Firebase SDK version: `5.4.0`
  * Firebase Product: firestore

### Problem

When I use a number as a doc index:

```js
var db = firebase.firestore();
db.settings({ timestampsInSnapshots: true });

db
  .collection('a-collection')
  .doc(123)
  .set({ foo: 'bar' });
```

I get the following error:

```
Function CollectionReference.doc() requires its first argument to be of type string, but it was: <number>
```

### Solution

I can of course work around this with:

```js
db
  .collection('a-collection')
  .doc((123).toString())
  .set({ foo: 'bar' });
```

However I would want the doc index to be cast into a string automatically so I don't have to worry about casting it myself and potentially forgetting it somewhere.

I also understand that indexes being strings apparently is a requirement (didn't know that before) and auto-casting might hide that fact, so feel free to close if that was an intentional decision 🤓

**Comment by samtstern** [comment]
@simonhaenisch thanks for the well-written feedback.

This is an intentional design decision.  While in your case you may be consciously passing a number, most people who do so are making a mistake.  Plus when you consider the many difficulties of working with numeric types in JavaScript, we find it's better to enforce that users have created a properly-specified string document ID *before* they pass it to the Firestore SDK.

The exact constraints on document IDs are listed here, and we plan to enforce those in the SDKs whenever possible:
https://firebase.google.com/docs/firestore/quotas#collections_documents_and_fields
