### ISSUE TITLE
FR: Improve Firestore Rules

### ISSUE THREAD

**Issue by rwmb** [firebase/firebase-js-sdk#1177]
* Operating System version: All
  * Browser version: All
  * Firebase SDK version: *
  * Firebase Product: firestore (auth, database, storage, etc)

### Feature
Better Firestore rules in javascript (or any other language) for allowing or not an operation against a document, or the ability to attach a function to existing rules. Right now I cannot create complex operations in a maintainable way, or even create them at all. e.g. Imagine writing something like this with Firestore rules right now (this is a dummy example but yes, I have a much more complex cases than this one)
```
let canRead = false;
if (group.private) {
  isInGroup = user.groups.groupId == groupId;
  isInChat = group.usesChat ? user.chatActive == groupId : true;
  isActive = group.access.hasToBeActive ? group.active && user.active : true;
  canRead = isInGroup && isInChat && isActive;
}
return canRead;
```
For my current case I can do that by retrieving the data from a cloud function and running the documents against a verification function to allow(or not)/filter the data.
It would be nice to have more flexibility with firestore rules and be able to use the client sdk for more complex operations.

**Comment by samtstern** [comment]
@rwmb thank you for the feedback! 

Let me address some of your feedback.

Firestore rules are written in their own domain specific language for a number of reasons.  They have to be extremely performant, since they run in front of every request.  We also need to be able to reason about them in complex ways to enable essential features like query rules.  If we moved to a general-purpose language like JavaScript, we'd have no way of making the guarantees we currently make.

That said, we do intend to make the language much more user friendly!  For instance we have already been looking at a proposal to add intermediate variables, like the ones you're demonstrating.  This and other proposals will address many of your concerns.

I am going to close this issue because it's not something we can actually fix in the JS SDK (or even something JS-specific).  However that doesn't mean we have to end the discussion. You're welcome to keep commenting here or email me personally.

**Comment by rwmb** [comment]
Indeed, variables would help already. I understand the other concerns, and javascript was just a suggestion, but thanks for taking the time to respond.
