### ISSUE TITLE
startAt() and startAfter() methods don't work

### ISSUE THREAD

**Issue by wujekbogdan** [firebase/firebase-js-sdk#1235]
* Operating System version: macOS 10.13.6
  * Browser version: Chrome 69.0.3497.92
  * Firebase SDK version: ^5.5.0
  * Firebase Product: firestore

#### Steps to reproduce:

Write any query using `startAt()` or `startAfter()` methods. They are supposed to move the query cursor to the specified position. But they don't work at all. The result of a query does not depend on the values passed to `startAt()` / `startAfter()`, the cursor is always set on the `0` index.

#### Relevant Code:

https://stackblitz.com/edit/firebase-issue-sandbox-bi2zx3

```javascript
const startAt = 10; // Choose any value. The result of the query is always the same. The value is ignored.
const limit = 10;

const ref = db.collection('companies')
  .orderBy('name')
  .startAt(startAt)
  .limit(limit)
  .get()
  .then((data) => {
    // Always returns the same set of results.
    // No matter what the `startAt` value is the query aleays returns as it was `0`
  });
```

**Comment by mikelehen** [comment]
I can't run your example due to permissions, but from the code, I think you are expecting startAt() and startAfter() to work as an offset, but that's not in fact what they do.  Given an ordered list of documents, they let you move to the document with a specific _field value_ in the list (not to a numeric offset within the list).

So for your example you'd need to do something like `orderBy('name').startAfter('three')` to skip to the entries with a `name` field that is > `three`.

Hope this helps.  Unfortunately there's no way to do an arbitrary numeric offset via the Cloud Firestore SDK as there's no way for the backend to efficiently implement this.  It would still have to read every document that you're trying to skip, which is slow and expensive.

**Comment by wujekbogdan** [comment]
@mikelehen
Omg. So I misunderstood the [documentation completely]!(https://firebase.google.com/docs/firestore/query-data/query-cursors). Examples given in the docs are a bit misleading. 

For example this one:

```
citiesRef.orderBy("population").startAt(1000000)
```

I missed the fact that the field is named `population`, so I thought that `1000000` is an index, not a field value.

Thanks for the explanation, but IMO the documentation should be more clear about it.

**Comment by alexg33** [comment]
Thanks for the feedback! We'll take a look at how we can improve the documentation and example code snippets to be clearer on our next revision of that doc.

**Comment by jefelewis** [comment]
So is this why the docs user a variable "lastVisible" to reference the last document returned to use as a starting point?

https://firebase.google.com/docs/firestore/query-data/query-cursors#use_a_document_snapshot_to_define_the_query_cursor

**Comment by var-const** [comment]
@jefelewis Yes, that is correct.

**Comment by jefelewis** [comment]
Thank you! It’s a very subtle detail that the docs don’t mention in enough detail

**Comment by daniel** [comment]
The documentation is still very confusing, and I was also confused by this discussion. The confusing thing for me was that startAt can take both a DocumentSnapshot *or* an array of field values. I was trying to use a DocumentSnapshot but that gave me only EntityTooLarge errors (probably because a document snapshot can be quite large).

**Comment by wilhuff** [comment]
@daniel You shouldn't be getting EntityTooLarge when using `startAt` with a DocumentSnapshot. Would you mind sharing the [debug logs](https://gist.github.com/katowulf/0475fb7a5907ed757f687aab6ed15878) from when this happened?
