### ISSUE TITLE
Fast subscribing/unsubscribing doesn't stop listening to changes

### ISSUE THREAD

**Issue by Len-art** [firebase/firebase-js-sdk#1296]
* Operating System version: macOS Mojave, have been able to reproduce on other OSes as well
  * Browser version: Chrome Version 69, unknown Safari version
  * Firebase SDK version: 5.5.2.
  * Firebase Product: firestore (auth, database, storage, etc)

With a collection of 1000+ documents that are constantly being updated, i'm trying to listen to a single document at the time. I have a single listener variable that i assign the listener to (specifically, the unsubscribe function). Before i re-assign it i check if an unsubscribe function exists. If so, i invoke it and re-assign the variable to a new listener.
Doing this quickly sometimes doesn't actually unsubscribe the listener. So even though i invoke the unsubscribe function and set the variable with a new one, i sometimes still get the old listeners' data to the onSnapshot callback.

It's hard to create an example because the data has to be constantly changing for the snapshots to fire, but it's essentially something like this:

```javascript
/* subscribe*/
const listener = firestore
          .collection('collection')
          .doc(id)
          .onSnapshot(...); //set a callback for snapshots
/* on change subscription id */
if (listener) {
          listener();
}
listener = (...) // resubscribe to another document
```

Essentially, if i change the subscriptions quicky, sometimes old snapshots keep coming in.
I have checked for many different possible bugs on my end (listener not in scope, typos, etc...), but all logs seem to be okay (listener is a function which when invoked should stop propagation of the snapshots).

**Comment by mikelehen** [comment]
Thanks for the report!  I think the problem is that our unlisten code does an async dispatch before running: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/core/firestore_client.ts#L461

So that means there's the opportunity for some number of events to slip through before the unlisten actually takes effect. :-/

This may not be an easy fix, but we'll take a look.

**Comment by mikelehen** [comment]
[I deleted my last reply because I realized I overlooked something]

This really shouldn't be possible because we have code to synchronously "mute" the listener when you unsubscribe (https://github.com/firebase/firebase-js-sdk/blob/7a41fe71fd3effd71b61548546e290015f58456b/packages/firestore/src/api/database.ts#L1012 and https://github.com/firebase/firebase-js-sdk/blob/7a41fe71fd3effd71b61548546e290015f58456b/packages/firestore/src/util/async_observer.ts#L49).

Is there any way you could provide a repro that demonstrates this happening?

**Comment by cristlee** [comment]
I have the same problem

**Comment by mikelehen** [comment]
@cristlee Can you provide a repro?

**Comment by Len-art** [comment]
So, i have been doing some digging on this. I can't provide a repo right now because that would require setup of a whole firebase project with some changing data (so snapshots would fire), but it's something on my todo list.
What i think might be going on here, however, is: if you have one variable you store the listener to, upon changing the listener to a different document before the original listener has had the chance to create (let's say a bad connection or really quick changes), the unsubscribe function you invoke doesn't go through because the listener wasn't created yet on the backend? Afterwards, when the subscription eventually gets created, it obviously uses the same callback for any snapshot as the subscription after it.
Since it's impossible to know if the unsubscription has made it through this makes for some really convoluted frontend code, having to check whether the incoming snapshot actually is for a document you're currently listening to, and if not, trying to unsubscribe from it again and again, until at some point it gets through.
Is it possible to return some sort of reply upon invoking unsubscribe function, to let the client know subscribe actually happened?

**Comment by mikelehen** [comment]
@Len-art I'm sorry, I'm afraid I don't really follow what you're suggesting.  unsubscribe should work regardless of whether the listen has made it to the backend or not. So I'm not sure what "Is it possible to return some sort of reply upon invoking unsubscribe function, to let the client know subscribe actually happened?" means exactly.

**Comment by mikelehen** [comment]
If anybody is still running into this, please provide a repro and we'll investigate.  Thanks!
