### ISSUE TITLE
value events not firing properly when offline

### ISSUE THREAD

**Issue by k1r0s** [firebase/firebase-js-sdk#1314]
From docs: https://firebase.google.com/docs/database/web/read-and-write#listen_for_value_events
related with offline capabilities: https://github.com/firebase/firebase-js-sdk/issues/17

![image](https://user-images.githubusercontent.com/6052309/47124505-8abaa480-d27e-11e8-94d9-69774d993513.png)

### [REQUIRED] Describe the problem

Value events should fire when ever a change occurs within the whole path. This is supposed to work offline as well, and it does! but not in the same way: 

#### Steps to reproduce:

for example: 

```json
{ "todos": {
    "0001": { "text": "something", "uid": "0001" },
    "0002": { "text": "dumy", "uid": "0002" },
    "0003": { "text": "some text", "uid": "0003" }
  }
}

```
listening for event values on root ("todos"): `ref('todos').on('value', f)`

`f` should be called when: 
1. pushing a new reference to the collection: `ref('todos').push({ "text": "a" })`
2. replacing the whole collection: `ref('todos').set(..)`

however offline. `f` only gets called when change occur directly on the explicit updated spot.

For example if I'm listening with: `ref('todos').on('value', f)` and I go offline case 2 works but case 1 does not.

#### Relevant Code:
- online
```
ref('todos').on('value', f)
ref('todos').push({ foo: 2 })
ref('todos').set({ bar: 1 })
```
> `f` should be called twice
- __offline__
```
ref('todos').on('value', f)
ref('todos').push({ foo: 2 })
ref('todos').set({ bar: 1 })
```
> `f` should be called twic, __but gets called once (by set trigger)__

### [REQUIRED] Describe your environment

  * Operating System version: __Linux k1r0s-N2x0WU 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux__
  * Browser version: __Chromium Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)__
  * Firebase SDK version: __"firebase": "^5.5.4"__
  * Firebase Product: __database__

**Comment by mikelehen** [comment]
This is a subtle but expected behavior.  The Firebase Realtime Database SDK attempts never to raise 'value' events with partial data.  In your example, push() will create a child underneath /todos, but since the SDK doesn't have the rest of the data for the /todos/ location, it can't raise a proper value event containing the entire /values/ location.

If you were to add your 'value' listener and wait for an initial event (even if it's empty) before going offline, then the subsequent push() call would generate an event since the SDK has complete data for /todos/.

In your case, you may find that listening to child_added, child_changed, and child_removed events will meet your needs better.  If you had a 'child_added' listener instead of 'value', then it would fire for your push() call, even while offline, since we'd have complete data for the added child.

Hope this helps.

**Comment by k1r0s** [comment]
Mmmm yeah..well

**Comment by k1r0s** [comment]
I get the point

**Comment by k1r0s** [comment]
Thanks
