### ISSUE TITLE
Cannot find module 'firebase/app' - Angular apps stops compiling

### ISSUE THREAD

**Issue by m-sureshraj** [firebase/firebase-js-sdk#1342]
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra v10.13.6
  * Browser version: Chrome v69
  * Firebase SDK version: v5.5.6
  * Firebase Product: app, messaging
  * Angular version: v5.2.0
  * Angular CLI version: v1.7.4
  * Node version: v8.11.1

#### Relevant Code:

```javascript
import * as firebase from 'firebase/app';
import 'firebase/messaging';

constructor() {
  firebase.initializeApp({
      messagingSenderId: environment.fireBase.messagingSenderId
  });
}
```
Build fails with `error TS2307: Cannot find module 'firebase/app'`. This issue forces me to use Firebase SDK v4.8.2 which has no typings issue.

Thanks.

**Comment by Feiyang1** [comment]
Do you have a folder under node_modules/firebase/app?

**Comment by m-sureshraj** [comment]
@Feiyang1 Yes, I do have a folder called "app" under my node_modules/firebase and node_modules/@firebase.

<img width="239" alt="screen shot 2018-10-30 at 9 01 30 am" src="https://user-images.githubusercontent.com/12813750/47694278-08899300-dc23-11e8-99aa-b90719669177.png">
<img width="235" alt="screen shot 2018-10-30 at 9 01 58 am" src="https://user-images.githubusercontent.com/12813750/47694280-08899300-dc23-11e8-85d7-716080c89634.png">

**Comment by Feiyang1** [comment]
Another thing to check is the tsconfig.json. what's the value of "moduleResolution"? make sure the value is set to "node"

**Comment by m-sureshraj** [comment]
<img width="363" alt="screen shot 2018-10-30 at 11 48 14 pm" src="https://user-images.githubusercontent.com/12813750/47740676-63140500-dc9e-11e8-9bc9-f8070d861578.png">

**Comment by Feiyang1** [comment]
that's weird. I don't what else could be the issue. Can you try deleting the node_modules and the lock file and making a clean install to see if it makes it go away?

**Comment by m-sureshraj** [comment]
@Feiyang1 I created a repo to reproduce the issue https://github.com/m-sureshraj/firebase-pkg-typing-issue-in-angular-app

**Comment by Feiyang1** [comment]
Great! I'm able to reproduce the issue using your repo. It appears typescript compiler when invoked by angular-cli ignores the "typings" field in package.json and just looks for the default "index.d.ts". Since firebase/app's typing file is specified by "typings" field, you got the error. 

I googled a bit, but was not able to find an existing issue like this, so it's possible that it can be solved by a configuration change somewhere, but I'm not sure. 

I suggest you open an issue with angular-cli and see if they have any suggestion.
Also I noticed you are on Angular 5. Are you able to upgrade to angular6 or 7 to see if the problem persist? AngularFire project doesn't seem to have this problem and they are on angular6: https://github.com/angular/angularfire2
Maybe you can use angularFire in your project?

**Comment by m-sureshraj** [comment]
@Feiyang1 Thanks  🙌 for your time & responses. I should use `angularFire2` in my project, I think it will solve the typing issues and more importantly, it provides a more angular ish way to communicate with firebase services. Thanks!

**Comment by chrisshepard** [comment]
npm install firebase @angular/fire --save

if you installed @angular/fire but not firebase you will get the error, make sure you download them both.
