### ISSUE TITLE
unauthorized write triggers a new onSnapshot with server data  

### ISSUE THREAD

**Issue by giladv** [firebase/firebase-js-sdk#1418]
* Operating System version: osx 10.13 (17A365)
* Browser version: chrome 70.0.3538.110
* Firebase SDK version: 5.5.9
* Firebase Product: firestore

use case:
- 'posts' collection allows read for everyone and write for authorized users only
- i listen to posts/someid
- i try to post a change without being authorised
- i receive a snapshot with local modifications first as expected
- i receive an error for insufficient privileges as expected
- __unexpected:__ i receive a new snapshot with fresh data from server
why do i need a new snapshot if a modification failed?
this seems like a bug and potentially a security issue to me.

**Comment by mikelehen** [comment]
Can you explain why you don't expect the second snapshot?  Once the write fails (due to permissions), it's reverted on the client to return you to the correct state of the data, and so you should indeed see a new snapshot without your local change (since it was rejected).

**Comment by giladv** [comment]
sure, if the write failed the local data should suffice, i have no problem with a  second snapshot containing the reverted data but why a fresh new copy from __server__? 

the problem is there isn't a way to detect that it's a fallback snapshot following a write reject.
use cases where you want to simulate writes locally (even if the server rejects) are impossible this way.

suggestion: snapshots will contain the reason they were created: initial_snapshot, local-change, remote-change, local-change-revert 

thanks!

**Comment by mikelehen** [comment]
Just to be clear, when you say "a fresh new copy from the *server*", that's not exactly what's happening.  We're just raising an event with the latest server data we've received (after discarding the local write that failed). We're not fetching new data from the server or anything.

Thanks for your suggestion regarding an event reason.  I think it gets a little complicated though.  In some cases, the new event will purely be a "revert" back to the original state before your local write, but consider this:

1. You perform local write, triggering an event with local data.
2. We receive an update from the server because somebody else performed a write.  This will *not* trigger a local event, because your local write is still outstanding and so it supersedes the server update.
3. Your local write is rejected.  Now you get an event with the up-to-date version from the server (which is what we received in step 2, rather than the data we had at step 1, meaning it's *not* just a revert).  So 'local-change-revert' isn't really accurate.

In general, the API is optimized for apps that mostly perform writes that are allowed by the app's security rules.  If you want to explain more about your use case, I may be able to provide a suggested workaround or help formulate a feature request that we could consider for the future.

**Comment by giladv** [comment]
thanks @mikelehen solved. (sorry for late response)

**Comment by mikelehen** [comment]
Great, thanks for confirming!
