### ISSUE TITLE
query snapshot reorders immediately after received - js sdk

### ISSUE THREAD

**Issue by giladv** [firebase/firebase-js-sdk#1426]
Operating System version: osx 10.13 (17A365)
Browser version: chrome 70.0.3538.110
Firebase SDK version: 5.7.0
Firebase Product: firestore

so this is a weird bug/unexpected behaviour to explain:
__queries are written here serialized for simplicity__

1. listen to /docs?where=category=='something'&orderBy=proiority
snapshot received with changes:
```
(change, documentId, newIndex, oldIndex)
added doc11 0 -1
added doc10 1 -1
added doc1 2 -1
```

2. listen to /docs?limit=7
3. unlisten to first query

expected snapshot received from step 2:
```
(change, documentId, newIndex, oldIndex)
added doc1 0 -1
added doc2 1 -1
added doc3 2 -1
added doc4 3 -1
added doc5 4 -1
added doc6 5 -1
added doc7 6 -1
```

actual snapshots received from step 2
```
(change, documentId, newIndex, oldIndex)
added doc1 0 -1
added doc2 1 -1
added doc3 2 -1
added doc4 3 -1
added doc5 4 -1
added doc10 5 -1
added doc11 6 -1

and then another snapshot with
removed doc10 -1 5
removed doc11 -1 5
added doc6 5 -1
added doc7 6 -1
```

- no data was changed while testing
- does not reproduce in the admin version of the sdk only the client js version
- no other listeners of /docs were active during the test

is this normal?

**Comment by mikelehen** [comment]
I think this may be expected.  The first snapshot is likely coming from cache, based on whatever you've listened to previously, and the snapshot will have metadata.fromCache == true.  The second snapshot happens once we've gotten the full resultset from the backend (and so will have metadata.fromCache == false).

If that doesn't explain what you're seeing, please provide more details (exact code you're running as well as what data exists in the database, etc.) and we can take a closer look.

**Comment by giladv** [comment]
notice the first query have a filter and a sort on it, the second query no filter and has default sort.
i would expect the second query to no return anything from cache because its so different and it was not used before. 
also, it causes a flicker of wrong data initially because after the update (which happens immediately but enough to flicker) 2 of the items change to different docs.

here is a working example, for this DB: https://orkan-site.firebaseio.com

```js
const kill1 = nativeFirestore.collection('docs')
	.where('category', '==', 'general')
	.orderBy('priority', 'asc')
	.onSnapshot(snapshot => {
		console.log('snap first')
		snapshot.docChanges().forEach(change => {
			console.log('change', change.type, change.doc.id, change.newIndex, change.oldIndex);
		});
	});
await sleep(4000);

const kill2 = nativeFirestore.collection('docs')
	.limit(7)
	.onSnapshot(snapshot => {
		console.log('snap second')
		snapshot.docChanges().forEach(change => {
			console.log('change', change.type, change.doc.id, change.newIndex, change.oldIndex);
		});
	});

kill1();
await sleep(4000);
kill2();
```


and here is the produced log, notice the remove and then adding
```
snap first
change added what-is-orkan 0 -1
change added getting-started 1 -1
change added query-data 2 -1
snap second
change added getting-started 0 -1
change added query-data 1 -1
change added what-is-orkan 2 -1
snap second
change removed what-is-orkan -1 2
change added admin-customizing 0 -1
change added admin-setup 1 -1
change added managing-users 3 -1
change added test1 5 -1
change added test10 6 -1
```

i mean, i love optimistic ui but in this case, the SDK causes a flicker of wrong data for a split second.
why do i need 'what-is-orkan' if it's not 100% sure it will still be there once the data from server arrived? 

many thanks:)

**Comment by mikelehen** [comment]
@giladv Thanks for the extra details! This is very helpful.

This is indeed working as designed.  The web/mobile Firestore SDKs are designed to work well while offline or with poor internet connectivity and so they intentionally use cache data to immediately raise snapshot events rather than waiting for the server (which could be slow or completely unavailable depending on your network circumstances).  In some cases, like this, that means you may see a flicker on the first time you run a query you've never run before.

The admin SDK on the other hand is designed to run on your backend servers, with an extremely high-quality network connection.  So it doesn't do the same kind of caching.

The fact that your two queries are different doesn't matter to the SDK.  It just runs the query against whatever documents are in the local cache (from previous queries you've run).

If you are okay waiting for server results and want to avoid the flicker, you can just filter out the initial snapshot like so:
```
const kill2 = nativeFirestore.collection('docs')
	.limit(7)
	.onSnapshot({includeMetadataChanges: true}, snapshot => {
                if (snapshot.metadata.fromCache) {
                  console.log('Skipping snapshot from cache.');
                  return;
                }
		console.log('snap second');
                 console.log(snapshot.docs);
	});
```

Note that I'm using snapshot.docs instead of snapshot.docChanges for simplicity.  If you need snapshot.docChanges, you'll need to do something slightly more sophisticated, since the second snapshot changes will be relative to the first one (e.g. you could batch up any fromCache=true snapshots and then render them all right in a row once you get a fromCache=false snapshot).

**Comment by mikelehen** [comment]
Thanks for the suggestions.  We have optimized for making it easy to build apps that work seamlessly offline and with poor internet connections, but I definitely understand the concern that this can result in unexpected behavior.  We'll keep your feedback in mind as we consider how to evolve the API and behavior over time.  Thanks!
