### ISSUE TITLE
Update @firebase/polyfill dependency "whatwg-fetch" from "2.0.4" to "3"

### ISSUE THREAD

**Issue by ryanwhite04** [firebase/firebase-js-sdk#1452]
I'm importing firebase using <https://unpkg.com> from https://unpkg.com/firebase@5.5.5/dist/index.esm.js?module.
which imports <https://unpkg.com/@firebase/polyfill@0.3.3?module>
which imports <https://unpkg.com/whatwg-fetch@2.0.4?module>
which resolves to <https://unpkg.com/whatwg-fetch@2.0.4/index.js?module>
which doesn't exist as the "main" field of the package.json is "fetch.js" not "index.js"

I submitted an [issue](https://github.com/unpkg/unpkg.com/issues/145) with unpkg.com, but it's not there error as apparently whatwg-fetch should be using a module field, and publishing an esm module build.

I checked, and whatwg-fetch does actually already do this, but only as of version 3.

If you upgrade the whatwg-fetch dependency in the @firebase/polyfill repository it might stop working as I assume there were breaking changes from 2 to 3, but I haven't tested it out yet so i'm not sure.

**Comment by Feiyang1** [comment]
It appears we can't upgrade to whatwg-fetch@3.0.0 without making some packaging changes. whatwg-fetch@3.0.0 doesn't work in nodejs anymore and because we always load all polyfills, the nodejs use case will break.

I'm not sure if any supported firebase feature in nodejs uses fetch. It looks like only messaging uses it, but it is not supported in the nodejs, so we might be able to remove the fetch polyfill from the nodejs build, then we can upgrade to 3.0.0 (It would require some packaging changes). Or we can switch to isomorphic-fetch, so it works in both browser and node.

@mikelehen Does firestore/database use fetch api ?

**Comment by mikelehen** [comment]
@Feiyang1 No, they don't.

**Comment by Feiyang1** [comment]
Upon further investigation, I realize the firebase package currently can't support this use case without removing the polyfills. Besides the fetch polyfill, we also bundle some polyfills from the `core-js` package which only has commonjs builds, so updating whatwg-fetch to 3.0 won't fix the problem.

For this use case, I would suggest using `@firebase/app` and the scoped component packages in your project, since they don't include the problematic polyfills.
