### ISSUE TITLE
RxFire does not have Release Notes / Changelog

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-js-sdk#1459]
### Describe your environment
Not Applicable

### Describe the problem
Currently without inspecting the source changes in a commit range it is impossible to know what changes were made to rxfire between releases.

#### Steps to reproduce:
Not applicable

**Comment by Feiyang1** [comment]
Thanks for your interest in this project! rxFire changes are included as part of the firebase release note. https://firebase.google.com/support/release-notes/js

Most of the time you don't see rxFire specific notes because there is no change in the rxFire itself, but changes in the firebase packages it depends on.
