### ISSUE TITLE
Prevent FieldValue.serverTimestamp from triggering document modification in onSnapshot

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#1460]
Currently when setting a `onSnapshot` listener we will get a "modified" document change trigger even when the only thing that was "modified" is a `FieldValue.serverTimestamp` being "executed" and filled in with the actual timestamp on the server.

In other words what happens:
1. Open a `onSnapshot` listener
2. Locally I update a single field to `FieldValue.serverTimestamp`
3. `onSnapshot` listener triggers a "local" change for the document
4. `onSnapshot` listener triggers a "server" change for the document

If I update a local field to just a `string` or `number` instead, **I do not get step 4** → the `onSnapshot` listener won't trigger a server change on regular values!

Can we prevent step 4 from happening after setting a local field to `FieldValue.serverTimestamp`?

Best regards,

**Comment by mikelehen** [comment]
This is intentional behavior since the value _is_ changing, and so if you're showing it in your UI or something, then we want to make sure you're seeing the correct value.

There isn't an explicit way to opt out of it, but you could look at the `snapshot.metadata.hasPendingWrites` flag to tell if the snapshot is from a local write, and optionally suppress it or something.  Note that if you're using the metadata flags, you should probably pass `{includeMetadataChanges: true}` to your snapshot listener to make sure you always get events when metadata changes.

If you have a specific use case that you're trying to solve, I may be able to provide more specific guidance.

**Comment by mesqueeb** [comment]
@mikelehen Thank you very much.

Since I didn't require server timing precision, I solved it by using `new Date()` on the client, which is then transformed to a "timestamp" object by firestore on the server side, but without calling the onSnapshot change.

I realise that there is a slight difference in timing (of x seconds) but that was acceptable in my case.

**Comment by mikelehen** [comment]
@mesqueeb Ah, excellent.  Just keep in mind that occasionally devices in the wild may have their clocks set wrong, so if this code is running on unknown users' devices, you could occasionally end up with data in the past or future.
