### ISSUE TITLE
As ES6 module not working

### ISSUE THREAD

**Issue by pshihn** [firebase/firebase-js-sdk#1516]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS
  * Browser version: Chrome 71
  * Firebase SDK version: 5.8.2
  * Firebase Product:app

### [REQUIRED] Describe the problem

When importing firebase app as an es module, it fails because one of the dependencies (find.js)
uses `require`

#### Steps to reproduce:

Create an HTML file with following and see the console. 
```html
<body>
  <script type="module" src="./node_modules/firebase/app/dist/index.esm.js"></script>
</body>
```

It also happens if you are simply importing in any other module
```javascript
import * as firebase from 'firebase';
```

**Comment by hsubox76** [comment]
I can't seem to reproduce this at the moment using either import method.  Can you paste in the console error message you are seeing?  Also, does the error go away if you roll back to a previous version of firebase?

**Comment by pshihn** [comment]
Here's the error:
```
find.js:1 Uncaught ReferenceError: require is not defined
    at find.js:1
```

Tested with 5.7 and it *does not* happen

To reproduce this, I'd try in a clean workspace (node_modules) and installing v5.8.2

**Comment by pshihn** [comment]
I quickly checked a few versions. 5.7.2 is the latest version that works. 
Since the code is in a dependency, I suspect the later version of a dependency does not provide valid esm

**Comment by hsubox76** [comment]
I was able to reproduce using Webpack, and checking commits between 5.7.2 and 5.7.3 it seems like https://github.com/firebase/firebase-js-sdk/pull/699 might possibly be the cause because it deals with bundling and commonjs compatibility, specifically the removal of the plugins from @firebase/polyfill's rollup config: https://github.com/firebase/firebase-js-sdk/pull/699/files#diff-b63d69dff0c673fd93c711e0772b361a

The dependency in question is core-js (required by @firebase/polyfill) and the version of that package has not been changed since it was first installed, so it's not the dependency itself.

I'll try to see if reverting some of the code from that commit fixes this problem.

**Comment by mmermerkaya** [comment]
My understanding is that the purpose of the `module` field (at least for now) isn't to point to a build that can be used natively in a browser. The `module` field is used by module bundlers, and [enables them to do their magic](https://github.com/rollup/rollup/wiki/ES6-modules).

[Here's](https://github.com/rollup/rollup/wiki/pkg.module) a more detailed explanation from Rollup's wiki. Also see "Typical Usage" [here](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md#typical-usage), and the comment (and configuration) [here](https://github.com/rollup/rollup-starter-lib/blob/master/rollup.config.js#L20).

I disagree with bundling our library's dependencies in our NPM builds. Installing dependencies of a library is what NPM does, and it's up to the users of our library to either use our `module` (or `main`) build with Rollup or Webpack or any other module bundler, which would also process the dependencies; or use our `browser` build without any further processing.

I'd say this is WAI.

**Comment by Feiyang1** [comment]
I agree that we shouldn't bundle dependency's code in our build. 
@pshihn You can use @firebase/app instead, since it doesn't include the polyfill libraries that are causing the problem. I guess you probably don't need any of those polyfills anyway since you are using a modern browser to load esm natively.

**Comment by pshihn** [comment]
Normally I would bundle when I'm releasing, but like a lot of developers, when developing, I skip the "build" step for quick changes.
I suppose I could use @firebase/app but I may need my own polyfills, etc when bundling.

**Comment by pshihn** [comment]
btw, @mmermerkaya I doubt the purpose `module` was added to html spec for bundlers only. Google itself promote using modules directly in browser for many examples and demos. 
I agree you should not bundle dependencies but at some point have to be wary on how well behaved the dependencies are. 
For now, I am up and running using @firebase/app instead.

**Comment by Feiyang1** [comment]
Thanks for the update! We will probably stop shipping polyfills with firebase in the future. It's probably better that developers choose what polyfill to include in the app since you know your target audience the best.

**Comment by mmermerkaya** [comment]
Sorry if it wasn't clear, I was talking about `package.json` spec, not HTML spec.
