### ISSUE TITLE
Importing firebase in Polymer Starter Kit fails

### ISSUE THREAD

**Issue by iceflow19** [firebase/firebase-js-sdk#1541]
### [REQUIRED] Describe your environment

  * Operating System version: Fedora 28
  * Browser version: Chromium 71.0.3578.98
  * Firebase SDK version: 5.8.3
  * Firebase Product: All

### [REQUIRED] Describe the problem

When served using `polymer serve`, importing firebase into polymer starter kit causes:

```
Uncaught ReferenceError: require is not defined
    at find.js:1
(anonymous) @ find.js:1
```

#### Steps to reproduce:
1. Clone the latest version of the polymer starter kit.
2. Add firebase through yarn/npm.
3. Add `import firebase from "firebase";` to my-app.js
4. Run polymer serve.

**Comment by Feiyang1** [comment]
The error is coming from the polyfills firebase includes, because they don't provide esm builds (probably doesn't make sense for them to do so) and polymer loads files using native ESM.

The workaround is to use the scoped firebase packages that doesn't bundle polyfills. For example, if you use Auth and Firestore, you would do the following instead:

```javascript
import firebase from '@firebase/app';
import '@firebase/auth';
import '@firebase/firestore'

...
```

**Comment by arjunyel** [comment]
Is there any examples using the scoped firebase packages by chance? Ive been struggling hard with this :(

**Comment by Feiyang1** [comment]
@arjunyel You would use it the same way as how you use `firebase` package. `firebase` is just a wrapper for scoped packages. Are you facing any particular issue? Can you please open a new issue with the details?

**Comment by arjunyel** [comment]
Basically I'm confused because the @firebase/app initalize app returns type of FirebaseApp while the regular firebase library returns firebase.app.App so the typings are different. For example using with rxFire the functions are looking for firebase.app.App.

If thats not clear I'd be happy to make a new issue, in just not sure if it's an issue or I just don't understand the differences. Thanks!

**Comment by Feiyang1** [comment]
Ah I see. This is unfortunate.
We define typings in both scoped packages and `firebase` package (ideally they should share the same typings, but unfortunately they don't). 
There are discrepancies between the two, e.g. names are different, so if you mix them together (rxFire references `firebase`), they appear to be incompatible.

To be perfect clear, you get the same object by using either scoped package or `firebase` package, They just appear to be incompatible because of how typings are defined. 

If you use rxFire, you are recommended to use `firebase`. But if you have to use scoped packages because of the issue reported here, you will have to do some type casting to pass typescript checks, unfortunately!

**Comment by arjunyel** [comment]
Should I file an issue to change the rxFire typings? Cuz basically rxFire is designed for any framework but I can't use it in stenciljs because it chokes on the Requires that the regular firebase package has. Btw I appreciate your help :D

**Comment by Feiyang1** [comment]
`firebase` package is the recommended way to use firebase, so rxFire is using the correct types in this sense.
I don't think we should change the rxFire typings, otherwise it won't work with `firebase` package.

I assume you load native ES6 modules in browser? Using scoped firebase package is the workaround for this use case and you have to cast firebaseApp (or whatever object that's incompatible) to `any` type when you pass it to rxFire. Does it make sense?

**Comment by iceflow19** [comment]
@arjunyel @Feiyang1 

Here is another workaround if @arjunyel would use polymer-cli as a library in a custom gulp script. This will make the polyfill inert. 

https://github.com/t2ym/live-localizer/issues/79

**Comment by austinn** [comment]
> ```js
> import '@firebase/auth';
> import '@firebase/firestore'
> ```

When I do this I get a warning `[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.` and am not able to build the project.
