### ISSUE TITLE
includeMetadataChanges does not provide docChanges

### ISSUE THREAD

**Issue by jacwright** [firebase/firebase-js-sdk#1546]
When using `includeMetadataChanges` to be notified when your data has been committed, `docChanges()` is empty.

```javascript
ref.onSnapshot({ includeMetadataChanges: true }, snapshot => {
  if (snapshot.metadata.hasPendingWrites) {
    console.log(snapshot.docChanges().length, 'changes written locally');
  } else {
    // This will show 0 changes when it is a change coming from this client.
    console.log(snapshot.docChanges().length, 'changes committed remotely');
  }
});
```

In order to know _what_ was committed you have to store pending changes like this (aka the workaround):

```javascript
const pending = [];

ref.onSnapshot({ includeMetadataChanges: true }, snapshot => {
  if (snapshot.metadata.hasPendingWrites) {
    pending.push(...snapshot.docChanges());
    console.log(snapshot.docChanges().length, 'changes written locally');
  } else {
    // This will show 0 changes when it is a change coming from this client.
    console.log(pending.length, 'changes committed remotely');
    pending.length = 0;
  }
});
```

I do not know if this solution/workaround is accurate. If `docChanges()` could contain the changes after a `metadata.hasPendingWrites` change, that would help know what exactly is committed.

**Comment by rsgowman** [comment]
Hey @jacwright,

You're right that the docChanges() method only includes things that have actually changed since the last snapshot, so if you want to see what was committed, that's probably not your best option. (That said, although I haven't tested it out, I don't see a major problem with your workaround, though there's a few details you'll need to account for. See below.)

But if you're just looking to see when your data was committed, it might be easier to approach the problem from the perspective of the writer (rather than the listener). i.e. somewhere in your code, you're probably doing this:

```
docref.set(data);  // or docref.update(data)
```

Those methods return a Promise that will let you know when the data was successfully committed. Depending on how you've structured your project, it may be easier to key off of that, i.e.:

```
docref.set(data).then( () => {
  console.log("changes committed remotely");
});
```

Would that approach work?


Caveats re docChanges(): If you want to go this route, watch out for the following:
* `ref.onSnapshot()` will return the initial snapshot, containing all the existing data, and will also return data committed by other clients. You've protected that by putting everything within a `hasPendingWrites` check, so I think you've got this one covered.
* This won't play nicely with transactions. (Transactions are completed entirely server side, so you'll never get a snapshot with `hasPendingWrites==true`). Even if you don't use transactions today, it's possible you'll add them in the future, so this is something to keep in mind.

**Comment by jacwright** [comment]
Should I change this to a feature request that the promise returned from a `set` contains the response from the server? This is for using features like timestamps or FieldValues. I want to have the latest data from the server and right now onSnapshot is the only way to get the updated data.

```javascript
docref.set({
  ...data,
  committed: firebase.firestore.FieldValue.serverTimestamp()
}).then(data => {
  console.log("changes committed remotely at", data.committed.toDate());
});
```

**Comment by rsgowman** [comment]
Hm... I think there's two somewhat orthogonal issues here:

1. Getting the latest data from the server as soon as it's available. For this, use onSnapshot().
2. Determining when the local write has been sync'd to the server. For this, check the returned promise from docref.set(). 

But it sounds like you want to combine them? i.e. get the latest data subject to the constraint that all your local writes have completed? Or maybe you just want to get the resolved server timestamp? (Or if both of these are incorrect, could you provide some more details about your use case?)

If you just want to get the resolved server timestamp, then I *think* this would work:

```
docref.set({
  ...data,
  committed: firebase.firestore.FieldValue.serverTimestamp()
}).then(() => {
  docref.get({source: "cache"}).then( docsnap => {
    console.log("changes committed remotely at ", docsnap.data().committed);
  });
});
```

Generalizing slightly to only get the latest data subject to your write completing:

```
docref.set(...).then(() => {
  docref.get({source: "cache"}).then( docsnap => {
    console.log("changes committed remotely: ", docsnap.data());
  });
});
```

The `source:"cache"` part prevents Firestore from making another round trip to the server. You could drop that if you like.

**Comment by jacwright** [comment]
I didn't know about `source:"cache"`. That should work great, thank you.
