### ISSUE TITLE
Electron - Offline Support

### ISSUE THREAD

**Issue by joruro** [firebase/firebase-js-sdk#1636]
### Environment

  * Operating System version: macOS HIghSierra (10.13.6)
  * Browser version: N/A
  * Firebase SDK version: 5.9.1
  * Firebase Product: Firestore
  * Electron version: 4.1.1

### Problem

When enabling persistence storage for offline support on an Electron instance, I get the following error

```
Error enabling offline storage. Falling back to storage disabled: FirebaseError: [code=unimplemented]: This platform is either missing IndexedDB or is known to have an incomplete implementation. Offline persistence has been disabled
```

**Comment by mikelehen** [comment]
@joruro Thanks for the feedback!  Unfortunately I'm not very familiar with Electron internals, but it [claims to support IndexedDB and localStorage](https://electronjs.org/docs/faq#how-to-share-data-between-web-pages) and so in theory Firestore offline should work fine.  

Is it possible your code is somehow running in a node.js context instead of a browser context or something?  (again, I'm not really clear on electron internals so sorry if this doesn't make sense).

**Comment by joruro** [comment]
@mikelehen I found out that if I import the SDK via the script tags, it works with electron. But it would nice if it would work as well via `npm install` as suggested here https://firebase.google.com/docs/firestore/quickstart

**Comment by mikelehen** [comment]
@joruro Great to hear, thanks!  I agree that it would be nice if that worked or somehow gave better feedback about what's going on.  I have pinged a couple folks internally to see if we can do a better job with our Electron support / docs.
