### ISSUE TITLE
Error (firestore persistency mac chrome?): Uncaught (in promise): AbortError: Version change transaction was aborted in upgradeneeded event handler.

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#1644]
### [REQUIRED] Describe your environment
The exception/error occurs with some users. So it depends on their environment. However, what I've been able to piece together:

  * Operating System version: I think the error occurs on Mac only
  * Browser version: chrome
  * Firebase SDK version: 5.9.1
  * Firebase Product: I think the issue is with firestore persistency

### [REQUIRED] Describe the problem
Since I re-enabled firestore persistency last week in our application, certain people get constant error messages.
It seems to be the combination of firestore + persistency + Mac + chrome 73 for now which gives problems.

![image](https://user-images.githubusercontent.com/1098243/55150258-100a8500-514c-11e9-8912-42c3b97ed028.png)

the information I got from logging the user got this:
![image](https://user-images.githubusercontent.com/1098243/55150343-3f20f680-514c-11e9-8802-d9aa55be5e6b.png)

**Comment by mikelehen** [comment]
@LanderBeeuwsaert Thanks for the report.  Unfortunately there aren't any known issues with mac + chrome 73 and without a way to reproduce this, it's going to be difficult to isolate.  Would it be possible to enable logging (with `firebase.firestore.setLogLevel('debug')`) and have one of your users capture the log output from the console?  You can paste it here (redacting any sensitive information) or email it to me at michael@firebase.com.

**Comment by LanderBeeuwsaert** [comment]
@mikelehen well, for the moment not, the three users I know about are all of them not in my country and don't belong to our testers.
However, I'll keep an eye out, the moment I can reproduce with debug logging I'll provide it to you guys.

**Comment by louisameline** [comment]
Hi guys, I think I know what this is, it just happened to me (Windows 7, Chrome Version 80.0.3987.42 (Build officiel) beta (64 bits))

It's because Chrome has been notified that an upgrade is available:

![image](https://user-images.githubusercontent.com/371814/72189831-31e4a800-33fe-11ea-9de9-0b931d76fb8d.png)

Reloading the browser and emptying all storage (indexDB, cookies and all) does not fix it, but upgrading the browser does.

Thanks

![image](https://user-images.githubusercontent.com/371814/72189151-69525500-33fc-11ea-9a0e-c9596a12b396.png)
![image](https://user-images.githubusercontent.com/371814/72189409-0614f280-33fd-11ea-9594-ecf27f9f8b89.png)

**Comment by LanderBeeuwsaert** [comment]
@louisameline Hi Louis, I seem to be missing something here.
My users have this problem (well, some of them anyway) on version 79 of chrome. Which is the latest stable released version of chome.
But you are on chrome 80? Canary version then? And it asks you to upgrade?
Call me confused :-)

**Comment by louisameline** [comment]
This is the version I have after the upgrade, right now. I actually don't know what version I had before I pushed the upgrade button.
