### ISSUE TITLE
Package with firebase works when published but not locally (nuxt, vue, vuex, npm, rollup)

### ISSUE THREAD

**Issue by SumNeuron** [firebase/firebase-js-sdk#1714]
### [REQUIRED] Describe your environment

  * Operating System version: _____ macOS 14+
  * Browser version: _____ Firefox (latest)
  * Firebase SDK version: _____ latest
  * Firebase Product: _____ (auth, database, storage, etc) auth, firestore, storage

#### Steps to reproduce:

1. Write a package which uses firebase.
2. use Rollup to bundle package
3. publish to npm
4. install published bundle into app
    + app works
5. install local bundle into app (so you don't have to publish every 5 minutes)
   + app doesn't work

#### Relevant Code:

Note: a codesandbox can not be provided as it is specific to local modules

Nuxt project repo: https://gitlab.com/SumNeuron/fsmd-nuxt
package using firebase: https://gitlab.com/SumNeuron/fsmd

- clone both repos
- `cd <path-to-fsmd>`
- `npm i`
- `npm run r:build`
- `cd <path-to-fsmd-nuxt>`
- `npm install <path-to-fsmd>`
- `npm install`
- `npm run dev`
- open browser to ` localhost:3000/blog/posts/test` results in error from firebase
- `ctrl-c`in terminal
- `npm install fsmd` (load from `npm`)
- `npm run dev`
- open browser to ` localhost:3000/blog/posts/test`
- no firebase errors

What are the issues?
depends on whether if firebase is in `devDependencies` or `dependencies`. In the later, nuxt with throw ServerError Module `firebase/app` not found. (although firebase is there. The former will claim there is no app initalized. However, since the _published_ package works, we know that this is a different error. There is a plugin in `fsmd-nuxt/plugins/firebase.init.js` which initalizes the app

**Comment by hsubox76** [comment]
Is there any reason you're not including firebase as a dependency in `fsmd` (not `fsmd-nuxt`)?  Once I included it, it seemed to work.  It seems like it should be included there since that repo contains code which calls it.

I think when you `npm install` straight from the `fsmd` dir, it copies the entire `fsmd` repo into the `fsmd-nuxt/node_modules`, including its own `node_modules`.  So when `fsmd` code tries to import firebase, it's looking for firebase inside the `fsmd-nuxt/node_modules/fsmd/node_modules` dir, but since it's not a dependency of `fsmd`, it's not there, it only exists in the top level `fsmd-nuxt/node_modules`.

When you package it and install the package (either by doing `npm publish` and installing from the npm repo, or by using `npm pack` and installing from the created tgz) you'll notice `fsmd-nuxt/node_modules/fsmd` no longer has its own `node_modules` folder and is now looking for `firebase/app` in the top level `node_modules`, which it finds.  I don't think you want to depend on this, though, you should probably include firebase as a dependency in any package that uses it (`fsmd` in this case).

Also have you looked into using `npm link`? It seems like it might be a smoother workflow than npm installing from the other dir every time.  It is also just using the whole directory as is, so you'll run into the same issue if you don't include firebase as a dependency though.

**Comment by SumNeuron** [comment]
@hsubox76 yes. This is meant to be demo for how to write firebase / vue / vuex modules that can be integrated into other projects. So those projects will have firebase and this one can get the app from the global namespace there.

So your first guess is somewhat right (npm will symlink the directory there). However that has nothing to do with the run-time error as the bundle is told to get firebase from the global namespace. npm link has the same error (because it is both sym link). 

Your second guess doesnt make sense as the bundle is bundled. If it is bundled with firebase, why would it look for firebase in the global namespace if when retrieved from npm? Since it is not bundled with firebase it always looks there. Hence the packaged works from npm. 

It is likely this error is an npm issue, not strictly firebase.

**Comment by hsubox76** [comment]
I think the best thing to do would be to just include firebase as a dependency, as it works and solves your problem and is pretty common practice, but if you don't want to do that for some reason, I think your only option is to keep doing your current workaround (or use `npm pack` and install the tgz if you're not online).
