### ISSUE TITLE
Can I do a for loop on FireStore Where?

### ISSUE THREAD

**Issue by benjoabrasado25** [firebase/firebase-js-sdk#1752]
this.afs.collection('categories', ref=>{
  		return ref
  		
  		for(var i=0; i<2;i++){
  			.where('test', '==', 'asdas')
  		}
  	})

**Comment by jeremynevans** [comment]
Hey @benjoabrasado25 - I would try creating the collection object and then modifying it in each iteration in your loop. Something like:

```
var dbReference = this.afs.collection('categories')

for(var i=0; i<2; i++) {
  dbReference = dbReference.where('test', '==', 'asdas_' + i)
}

// OUTPUT
// this.afs.collection('categories').where('test', '==', 'asdas_0').where('test', '==', 'asdas_1')
```

Does that help?

**Comment by var-const** [comment]
@benjoabrasado25 Can you please provide more context on what you're trying to achieve? The syntax from your original post won't work. If it did, it appears that it would attach two identical `where` clauses, which probably isn't what you want. Are you trying to attach two similar but different `where` clauses? Are you trying to get a certain number of elements from the collection?

**Comment by wilhuff** [comment]
The code snippet suggested by @jeremynevans is correct.

Feel free to follow up here if you have additional questions, though in general stack overflow is a better venue for this kind of question. You may get better answers if you try to describe what problem you're trying solve at a higher level rather than asking this specific for-loop question.
