### ISSUE TITLE
It is not possible to do meaningful paging of query results because IN queries are not supported 

### ISSUE THREAD

**Issue by serdarosmanonur** [firebase/firebase-js-sdk#1777]
As of now, IN/OR queries are not supported in firebase as discussed here: https://stackoverflow.com/questions/46632042/how-to-perform-compound-queries-with-logical-or-in-cloud-firestore 
I know it is an old thread but the point is still valid. 

So, the alternative way is to 
1- Create multiple "where" queries, 
2- Collect the promises in a "promises" array,
3- Get the results with `Promise.all(promises).then()`,
4- Get the results, do the paging on the client side and display the results. 

Step 4 is where this all fails. Because it is not possible to do meaningful paging in this case. Assume you want to page using creationDate of documents, which is usually the case for many scenarios. Each set of results could only be ordered within itself, consecutive results would not be ordered. 
Without meaningful paging, this alternate way of IN query implementation seems useless to me. I was wondering if there are any ways to do this. And if not, when are you considering to fix this problem?

**edit: more info**
In my case, there are documents with tags. t1, t2, t3 etc.  These tags are stored in an array, so in my parallelly executed where queries I am using "array-contains" statements:

```
where("tags", "array-contains", t1)
where("tags", "array-contains", t2)
where("tags", "array-contains", t3)
```
pushing them in a "promises" array, then calling `Promise.all(promises)`.

Tags are not a pre-determined set. Tags can be generated by users and added to docs, let's say a CAR doc.
USER docs also have their own sub-set of tags.
So, there is a superset of tags, a tag cloud let's say, and the documents that I want to query (CAR documents) and the USER documents have their own subset of tags.

> CAR1
>  - tags : [t1, t2, t3, t7, t9]
> CAR2
>  - tags : [t2, t7, t9]
> CAR3
>  - tags : [t1, t9]
> CAR4
>  - tags : [t2]
> CAR5
>  - tags : [t7]
> 
> USER1
>  - tags: [t2,t7]

According to the above structure, I want to get the list of CAR documents that have either t2, or t7 inside their tags array, then order them by creationDate. And of course, do paging.

Thanks a lot.
Serdar

**Comment by rsgowman** [comment]
Hi Serdar,

As you noted, IN/OR queries aren't supported. There are several workarounds for this, but they often are somewhat specific to the exact problem that you're trying to solve, and will sometimes require reworking your schema a bit. Are you able to provide more details? Ideally the queries that you're running in step 1, as well as your data schema.

As more general advice, checkout the following links:

- Array Contains: https://firebase.google.com/docs/firestore/query-data/queries#array_membership
This is relatively new, so you might not be aware of it yet. It may or may not suite your problem.
- https://blog.oasisdigital.com/2018/querying-without-or-in-firestore/
This isn't written by one of us, but it does detail a number of approaches for working around the IN/OR limitation. Again, it may or may not solve your problem, but is definitely worth a read.

**Comment by serdarosmanonur** [comment]
Hey there. I appreciate the response, thanks...

1- I am aware of array-contains queries. Actually, in my case, that is exactly what I am using.
2- I have read the second link you have sent, that won't resolve my problem. On that post, guys are working on a pre-determined set of states. Easy :)

I am adding additional info you asked for into the original question above so that the problem description stays nice and tidy.

Cheers.

**Comment by wilhuff** [comment]
@serdarosmanonur In your original description of your solution you're missing a step 3.5: you need to merge the results together to match the ordering you want to use for paging.

So, in your example, if you're wanting to page by `creationDate`, you'll need to merge the various results into a single list first, ordered by `creationDate`.

The easy way to do this is to just drop the documents in a list and then sort the list by that property. However, you can do this more efficiently with a [k-way merge](https://en.wikipedia.org/wiki/K-way_merge_algorithm) if you're inclined.

Note that in general, stackoverflow is a better venue for this kind of question, since it really isn't specific to Firestore (though I understand that it's a Firestore limitation that's causing you to solve this problem in the first place).

Good luck!

**Comment by serdarosmanonur** [comment]
Hello there @wilhuff. Thanks a lot for the response.

I thought about that already. I didn't write it as a step because it is not the right way to do that. 

If you think about it, as you fetch new sets of results and re-order the complete/cumulative set you have fetched up to that point, you will see documents flying around jumping between pages, getting out of users view area' some older documents getting back into the view area etc. All kinds of weird behavior from the users' perspective.

**Comment by wilhuff** [comment]
I'm not sure I understand your concern. 

Firestore guarantees a stable ordering by implicitly sorting by the document path after any other criteria. You can do the same thing in your sort. This means that any order by clause you can supply to Firestore you can replicate client-side.

Assuming you had the capability to write an `IN` query, you would need to supply order by clauses to order those results as you wanted to present them. Without that, `IN` doesn't help you. Whether your sort client side or on the server makes no difference.

**Comment by serdarosmanonur** [comment]
Hi @wilhuff, thanks for the response.  

I am running multiple parallel queries and get the results at once with Promise.all(). Do this again and again as the user presses on a "MORE" button, hence a new page renders with new results on his phone's screen. 

How can I get a healthy ordering with this by creationDate without all the weird behavior I mentioned above? 

I mean, each parallel query will have its own **lastReturnedDoc** reference for getting the next set of docs for paging. Once I get the new page of results and re-order the cumulative results, some of the documents that result from 2nd execution of let's say query2 (which returns CARS with t2 tag) will actually be newer than the 1st execution of let's say query7 (which returns CARS with t7 tag) and I am ordering from newer to older. Now, this 2nd results that came from the execution of query2 must be above the results that came from 1st execution of query7 and instead of displaying them in the second page, as a result of cumulative ordering, these new items will be on page 1 and user will be viewing page 2. 

@rsgowman

**Comment by wilhuff** [comment]
Query cursors aren't magic, you can use any document as the starting point for your next query, even if it wasn't in the prior result. Use the final document from the page you're viewing to compute the startAfters for the next page.

Let's say you have the following data set (ordered by created date):

| Name | Created | Tags |
| ----- | ----- | ----- |
| CAR1 | T1 | a, b |
| CAR2 | T2 | a |
| CAR3 | T3 | b |
| CAR4 | T4 | b |
| CAR5 | T5 | a, b |

Now, create a paged view, where each page is 2 rows. You want to see cars with tags `a` or `b`.

Here's a node.js test app that shows it working:
```javascript
const firebase = require('@firebase/testing');

const app = firebase.initializeTestApp({
  projectId: "test-project",
  auth: { uid: "alice", email: "alice@example.com" }
});

let db = app.firestore();
const pageSize = 2;

function names(docs) {
  return docs.map((doc) => {
    return doc.data().name;
  })
}

function queryTag(tag) {
  return db.collection('cars')
      .where('tags', 'array-contains', tag)
      .orderBy('created')
      .limit(pageSize);
}

function compare(a, b) {
  if (a < b) {
    return -1;
  } else if (a > b) {
    return 1;
  } else {
    return 0;
  }
}

function merge(...docLists) {
  // Concatenate all
  const result = [];
  for (docs of docLists) {
    result.push(...docs);
  }

  // Sort
  result.sort((a, b) => {
    let cmp = compare(a.data().created, b.data().created);
    if (cmp != 0) return cmp;

    return compare(a.id, b.id);
  });

  // Keep only unique documents
  return result.filter((doc, i, array) => {
    return i == 0 || array[i - 1].id != doc.id;
  });
}

async function showPage(lastDoc, ...tags) {
  const results = [];
  for (const tag of tags) {
    let q = queryTag(tag);
    if (lastDoc != null) {
      q = q.startAfter(lastDoc);
    }

    const snap = await q.get();
    results.push(snap.docs);
  }

  const merged = merge(...results);
  const page = merged.slice(0, pageSize);

  for (let i = 0; i < tags.length; i++) {
    console.log(`Q(${tags[i]}): `, names(results[i]));
  }

  console.log('M:    ', names(merged));
  console.log('V:    ', names(page));

  if (page.length < pageSize) {
    return null;
  } else {
    return page[pageSize - 1];
  }
}

async function run() {
  const cars = db.collection('cars');
  const existing = await cars.get();
  for (const car of existing.docs) {
    await car.ref.delete();
  }

  const car1 = await cars.add({name: 'CAR1', created: 1, tags: ['a', 'b']});
  const car2 = await cars.add({name: 'CAR2', created: 2, tags: ['a']});
  const car3 = await cars.add({name: 'CAR3', created: 3, tags: ['b']});
  const car4 = await cars.add({name: 'CAR4', created: 4, tags: ['b']});
  const car5 = await cars.add({name: 'CAR5', created: 5, tags: ['a', 'b']});

  const tags = ['a', 'b'];

  let pageNumber = 1;
  let lastDoc = null;
  do {
    console.log(`page ${pageNumber}`);
    lastDoc = await showPage(lastDoc, ...tags);
    console.log('');
    pageNumber += 1;
  } while (lastDoc);
}

run().then(() => process.exit(0)).catch(console.error);
```

And the output:

```
page 1
Q(a):  [ 'CAR1', 'CAR2' ]
Q(b):  [ 'CAR1', 'CAR3' ]
M:     [ 'CAR1', 'CAR2', 'CAR3' ]
V:     [ 'CAR1', 'CAR2' ]

page 2
Q(a):  [ 'CAR5' ]
Q(b):  [ 'CAR3', 'CAR4' ]
M:     [ 'CAR3', 'CAR4', 'CAR5' ]
V:     [ 'CAR3', 'CAR4' ]

page 3
Q(a):  [ 'CAR5' ]
Q(b):  [ 'CAR5' ]
M:     [ 'CAR5' ]
V:     [ 'CAR5' ]
```

Good luck!

**Comment by serdarosmanonur** [comment]
Hello, @wilhuff thanks a lot for the example. Sorry I have been traveling so I am getting back a little late.
I have examined your example, here it seems like you are getting all the results at once and sorting them before displaying. In a collection of millions of records that is not you would like to do. And that is not what I am trying to do either. I want to fetch the records incrementally from the firestore. Let's say 10 results for each tag, order them and show them in a paged way, then get another set of results from the server (again 10 results for each tag), then again sort and page them on the user's device. That is where it all fails to do meaningful paging. 

For example in a test data like below:

> const car1 = await cars.add({name: 'CAR1', created: 1, tags: ['a']});
>   const car2 = await cars.add({name: 'CAR2', created: 2, tags: ['a']});
>   const car3 = await cars.add({name: 'CAR3', created: 3, tags: ['c']});
>   const car4 = await cars.add({name: 'CAR4', created: 4, tags: ['c']});
>   const car5 = await cars.add({name: 'CAR5', created: 5, tags: ['a']});
>   const car6 = await cars.add({name: 'CAR6', created: 6, tags: ['a']});
>   const car7 = await cars.add({name: 'CAR7', created: 7, tags: ['b']});
>   const car8 = await cars.add({name: 'CAR8', created: 8, tags: ['b']});
>   const car9 = await cars.add({name: 'CAR9', created: 9, tags: ['b']});
>   const car10 = await cars.add({name: 'CAR10', created: 10, tags: ['b']});


I will first get car1,car2 for tag-a + car7,car8 for tag-b (since tag-a and tag-b queries will be running separately, in parallel). 

Then I will display them in a result like this:

page1:
> const car1 = await cars.add({name: 'CAR1', created: 1, tags: ['a']});
>   const car2 = await cars.add({name: 'CAR2', created: 2, tags: ['a']});

page2: 
>   const car7 = await cars.add({name: 'CAR7', created: 7, tags: ['b']});
>   const car8 = await cars.add({name: 'CAR8', created: 8, tags: ['b']});

Then, the next query will fetch another set of results from firestore which will be  car5,car6 for tag-a and car9,car10 for tag-b.

Result will be:

page1:

> const car1 = await cars.add({name: 'CAR1', created: 1, tags: ['a']});
>   const car2 = await cars.add({name: 'CAR2', created: 2, tags: ['a']});

page:2
>   const car5 = await cars.add({name: 'CAR5', created: 5, tags: ['a']});
>   const car6 = await cars.add({name: 'CAR6', created: 6, tags: ['a']});

page3:
>   const car7 = await cars.add({name: 'CAR7', created: 7, tags: ['b']});
>   const car8 = await cars.add({name: 'CAR8', created: 8, tags: ['b']});

page4:

>   const car9 = await cars.add({name: 'CAR9', created: 9, tags: ['b']});
>   const car10 = await cars.add({name: 'CAR10', created: 10, tags: ['b']});

As you can see, when I first got the initial set of data from firestore, car7,car8 was on page 2, after fetching the second set of results from firestore and sorting them before displaying, page 2 will display car5,car6, and car7,car8 will be moved to page 3. The user had already seen car7,car8 on page2, now he will be again presented with them on page 3, and the newly fetched car5,car6 will be left behind on page 2.

**Comment by wilhuff** [comment]
Please actually try the code :-). If I add your sample data to my toy example and run, this is what I get:

```
page 1
Q(a):  [ 'CAR1', 'CAR2' ]
Q(b):  [ 'CAR7', 'CAR8' ]
M:     [ 'CAR1', 'CAR2', 'CAR7', 'CAR8' ]
V:     [ 'CAR1', 'CAR2' ]

page 2
Q(a):  [ 'CAR5', 'CAR6' ]
Q(b):  [ 'CAR7', 'CAR8' ]
M:     [ 'CAR5', 'CAR6', 'CAR7', 'CAR8' ]
V:     [ 'CAR5', 'CAR6' ]

page 3
Q(a):  []
Q(b):  [ 'CAR7', 'CAR8' ]
M:     [ 'CAR7', 'CAR8' ]
V:     [ 'CAR7', 'CAR8' ]

page 4
Q(a):  []
Q(b):  [ 'CAR9', 'CAR10' ]
M:     [ 'CAR9', 'CAR10' ]
V:     [ 'CAR9', 'CAR10' ]

page 5
Q(a):  []
Q(b):  []
M:     []
V:     []
```

The `V` lines show the view for each page, and this doesn't have the problem you're articulating.

Responding to a few specific concerns you raise:

> it seems like you are getting all the results at once and sorting them before displaying

This isn't how it works. For each page, each query applies a limit of the page size.

> I want to fetch the records incrementally from the firestore, order them and show them in a paged way, then get another set of results from the server, then again sort and page them on the user's device.

You can fetch results incrementally (as my example does), it's just that you can't directly use any of the results past the page size.

> I will first get car1,car2 for tag-a + car7,car8 for tag-b (since tag-a and tag-b queries will be running separately, in parallel).
>
> Then I will display them in a result like this:

This is the heart of the misunderstanding. You don't have enough data to display page 2 at this point. Only `pageSize` worth of data is usable because you only queried for `pageSize` documents from each query.

Walking through it, to generate page 1, it ran these two queries:

```
db.collection('cars')
  .where('tags', 'array-contains', 'a')
  .orderBy('created')
  .limit(pageSize);  // => [ 'CAR1', 'CAR2' ]
db.collection('cars')
  .where('tags', 'array-contains', 'b')
  .orderBy('created')
  .limit(pageSize);  // => [ 'CAR7', 'CAR8' ]
```

The merged list includes `[ 'CAR1', 'CAR2', 'CAR7', 'CAR8' ]`. However you can't just count these as pages 1 and 2 because there's the possibility that there are more cars for tag 'a'--and indeed there are.

To generate page 2, you have to query again, but now starting after `CAR2`:

```
db.collection('cars')
  .where('tags', 'array-contains', 'a')
  .orderBy('created')
  .limit(pageSize)
  .startAfter(car2);  // => [ 'CAR5', 'CAR6' ]
db.collection('cars')
  .where('tags', 'array-contains', 'b')
  .orderBy('created')
  .limit(pageSize)
  .startAfter(car2);  // => [ 'CAR7', 'CAR8' ]
```

In this iteration, the merged result is `[ 'CAR5', 'CAR6', 'CAR7', 'CAR8' ]` from which only `[ 'CAR5', 'CAR6' ]` are directly usable.

It's only on page 3 that you actually end up using `[ 'CAR7', 'CAR8' ]`.

In summary, it's definitely possible to get the right result using this approach. The (totally valid) complaint against it is that it's wasteful: to display a page of `n` results from `k` alternatives in a disjunctive query you'll need to read up to `n * k` documents. Adding direct support for `IN` queries will solve the overselection problem and reduce costs, but it doesn't change what's possible.

One thing to note is that **if your data is relatively static**, you can solve the overselection problem client-side as well. The solution comes from the observation that at each iteration, any unused results must be the first results for that alternative.

To exploit this, keep separate buffers for each alternative and drain them into the view. Then at each iteration instead of requerying with a limit of `pageSize` starting after the last displayed document in the view, you could instead query for enough documents to refill the buffer up to `pageSize` elements, starting from the last document fetched into the buffer. In that implementation, pages 2 and 3 wouldn't requery for documents matching tag 'b' because the buffer would be full.

Note that this isn't a panacea: the reason this approach applies to data that's relatively static is that it does not respond well to changes to documents that are past the end of the current view but before the buffered results. For example, if after page 1 was displayed, `CAR3` were modified to also have tag 'b', then the buffer-draining approach would miss it, while the requerying approach would still catch it and show it as part of page 2.

Cheers!

**Comment by serdarosmanonur** [comment]
Hey @wilhuff thanks for bearing with me. You have been very helpful, I appreciate it... Sorry for not paying attention, now I see. Thanks a lot!

You said: 

> to display a page of n results from k alternatives in a disjunctive query you'll need to read up to n * k documents

With k alternatives, do you mean k number of tags? So, as the number of tags increases so does the wastefulness. Which I would definitely agree.

I also like the buffer solution. I could definitely use that.

Cheers
