### ISSUE TITLE
Database not working on IE11

### ISSUE THREAD

**Issue by pjc0247** [firebase/firebase-js-sdk#1781]
### [REQUIRED] Describe your environment

  * Operating System version:  Windows 10 64bit
  * Browser version: IE11.706.17134.0
  * Firebase SDK version: 5.9.1
  * Firebase Product: database

### [REQUIRED] Describe the problem

There are two errors, only happens with IE11.

1. No such method 'find'.<br>
firebase-database.js (1,111040)
```js
  private validateEventType_(eventType: string) {
    assert(
      this.allowedEvents_.find(function(et) {
        return et === eventType;
      }),
      'Unknown event: ' + eventType
    );
  }
```

2. infoData_ is `null` or `undefined`.
Repo.ts (319,5)
at t.prototype.updateInfo_ (https://www.gstatic.com/firebasejs/5.9.1/firebase-database.js:1:149863)
```js
 private updateInfo_(pathString: string, value: any) {
    const path = new Path('/.info/' + pathString);
    const newNode = nodeFromJSON(value);
    this.infoData_.updateSnapshot(path, newNode);
    const events = this.infoSyncTree_.applyServerOverwrite(path, newNode);
    this.eventQueue_.raiseEventsForChangedPath(path, events);
  }
```

**Comment by schmidt-sebastian** [comment]
In order to reduce our SDK size, we no longer ship the Polyfils that are required for some older browsers. This was one of the changes in the [6.x release](https://firebase.google.com/support/release-notes/js)

Please take a look at https://firebase.google.com/support/guides/environments_js-sdk for a guide on how to manually [enable Polyfills](https://firebase.google.com/support/guides/environments_js-sdk#polyfills) as required.
