### ISSUE TITLE
Firestore document Set with mergeFields when creating a document does not work as expected

### ISSUE THREAD

**Issue by jimmykane** [firebase/firebase-js-sdk#1834]
### [REQUIRED] Describe your environment

  * Operating System version: OSX
  * Browser version: Chrome 74
  * Firebase SDK version: 6.1/0
  * Firebase Product: database

#### Steps to reproduce:
Hi I am saving a documemnt with a batch write like so:

```
batch.set(admin.firestore().collection('suuntoAppWorkoutQueue').doc(generateIDFromParts([serviceToken.userName, payload.workoutKey])), <QueueItemInterface>{
          userName: serviceToken.userName,
          workoutID: payload.workoutKey,
          retryCount: 0,
          processed: false, 
        }, {mergeFields: ['retryCount']});
```

According to the docs:

> Changes the behavior of set() calls to only **replace** the specified field paths. Any field path that is not specified is ignored and remains untouched.

Above it is said that it will only replace. 

However, when I write a new document, eg the doc ID is does not exist the `mergeFields ` only writes the `retryCount ` field. 

Is that by design? 

Shouldn't then be saying: 

> Changes the behavior of set() calls to only **write**  

Instead of: 

> Changes the behavior of set() calls to only **replace** 

Or am I missing something and this is just a bug? 

I don't understand why one could use the `mergeFields` since the "merge" from what I understand happens on the client.

**Comment by schmidt-sebastian** [comment]
@jimmykane I think in your case you can just pass `{ 'merge': true }`. We will then use a mask based on the input you provide and merge all given fields into the document. You should only need to use `mergeFields` if your intend is to only merge a subset of the object that you are passing to us.

**Comment by wilhuff** [comment]
So, unfortunately, there's a bunch of different options you could conceivably want when writing data:
  * Is the value to write document shaped or is it a list of paths + values to update?
  * Do you want to replace the document on the server wholesale or just partially?
  * Do you want partial updates to succeed when applied to non-existent documents?

As you can see, we have two methods and some options, but not eight. These pick and choose properties based on what we reasoned were the most useful combinations.

  * Use `set` to write complete documents.
  * If you want to partially change a document:
      * Use `set` with `merge` or `mergeFields` when you're OK with a partial document existing if it's applied to a non-existent document
      * Use `update` with pairs of things you want to change when you want to avoid creating a partial document.

Set with merge is useful when the document itself represents some kind of collection or aggregate object.

Use `update` when you just want to apply a change to a few fields.

The documentation on `set` could be clearer on this point, but essentially the "replace" in there is conditioned on the fact that if a document doesn't exist when the set+merge is applied an empty one is created first.

Note that update/merge operations are performed on the server. The client also estimates the results of those changes locally so that it can show you results even when offline.

**Comment by jimmykane** [comment]
I am very very confused here. 

@schmidt-sebastian no merge set to true does update the whole properties in the payload. 


@wilhuff  can you please help a bit? 

I want to create a document with the payload as in the example (properties) and if that document exists only update parts of the payload. 

For example imagine a task queue.  

I want: 

- If the item exists then only update a specific  and leave the others intact 
- If the item does not exist set it up 

As seen above and explained here there is no way to achieve this without preforming a read operation. 

Example: 


```
batch.set(admin.firestore().collection('suuntoAppWorkoutQueue').doc(generateIDFromParts([serviceToken.userName, payload.workoutKey])), <QueueItemInterface>{
          userName: serviceToken.userName,
          workoutID: payload.workoutKey,
          retryCount: 0,
          processed: false, 
        }, {mergeFields: ['retryCount']});
```

The above should: 

- Update only the retryCount -> it doesnt. It drops all other fields of the document if it exists! 

^ the above is not expected!  

Also why is the issue closed with no response?

**Comment by jimmykane** [comment]
@schmidt-sebastian Could you reopen the issue please? See above comment!

**Comment by schmidt-sebastian** [comment]
Can you please send us your logs? Since you are using the Node SDK, invoke `setLogFunction` (admin.firestore.setLogFunction in your case) with `console.log` as the argument. 

The following snippet:

```
    const ref = randomCol.doc('doc');
    await ref.set({a:true, b:true});
    const batch = firestore.batch();
    batch.set(ref, {a:false}, {mergeFields:['a']});
    await batch.commit();
    await ref.get().then(snapshot => {
      console.log(snapshot.data());
    });
```
prints `{ a: false, b: true }` for me. If you don't mind, can you tell me what it prints for you?
