### ISSUE TITLE
FR: FieldValue.serverTimestamp to be supported inside arrays

### ISSUE THREAD

**Issue by krzcho** [firebase/firebase-js-sdk#1849]
* Firebase SDK version: 6.1.0
  * Firebase Product: database

As described here: https://github.com/firebase/firebase-ios-sdk/issues/1164
I am not sure why it was closed when not being resolved

I am raising the issue here as a placeholder to be able to subscribe for change notifications

**Comment by mikelehen** [comment]
firebase/firebase-ios-sdk#1164 was closed because the poster thought they were getting the error even though they weren't using an array, but this was a misunderstanding and they were in fact using an array, so the error message was correct.

I apologize but this isn't the right place to track this feature request, because it's not something we can add to the SDKs until the backend adds support to the protocol, and nobody on the backend team will see this request if it's logged here.  The best place to log this would be https://issuetracker.google.com/savedsearches/5337669.  Please be sure to include your use cases so as to help us prioritize appropriately.  Thanks and sorry for the runaround.

**Comment by wilhuff** [comment]
Also note FieldValue.serverTimestamp can't supported inside arrays without a major overhaul of the way Firestore works, sorry.

Basically, all of the transformations in FieldValue need to be able to name a path to the field they're changing. A server timestamp is a transformation indicating the server should insert the current time of the request in some specific field.

Firestore field paths don't have array subscripts, so there's no way to name the thing to change. We're not planning on adding support for this because it adds significant complexity while being mobile unfriendly. The usual workarounds of using maps or separate documents are considerably more mobile friendly so we just recommend using those patterns instead.

**Comment by krzcho** [comment]
thx for the info - I have switched from array to collection
