### ISSUE TITLE
FR: Persistent anonymous user for testing

### ISSUE THREAD

**Issue by surajbarkale-dolby** [firebase/firebase-js-sdk#185]
### Describe your environment

  * Operating System version: macOS Sierra 10.12.6
  * Firebase SDK version: 4.5
  * Firebase Product: auth

### Describe the problem
We are using firebase as auth provider for our backend services. We have some tests using firebase nodejs SDK to cover the API exposed by this service. These tests must use an authenticate user (email/password) and an anonymous user.

_We have found that there is no way to persist identity of anonymous user in nodejs client SDK._ Because of this, we get a lot of anonymous users every time tests are executed. So we are requesting some API to save & load anonymous user credentials in nodejs client SDK.

**Comment by bojeil-google** [comment]
Do you mean, you want `firebase.auth().signInAnonymously()` to always return the same user?

**Comment by surajbarkale-dolby** [comment]
I need some way to store credentials for user returned by `firebase.auth().signInAnonymously()` so I can login again with the same user. one way of achieving this is to add `FILE` option to `
firebase.auth.Auth. Persistence` enumeration so I can persist each users session in a different file.

**Comment by bojeil-google** [comment]
I still don't understand why you need that capability. Here are some options:
1. You can initialize multiple auth instances and sign in anonymously on one of them while testing other methods of sign in on other instances:
```
var app2 = firebase.initializeApp(config, 'copy2');
var auth2 = app2.auth();
```
2. If you are using this for testing, you can re-sign in with the same anonymous user using custom tokens. As long as you know the `uid` of the anonymous user, you can sign in with it. Though, `isAnonymous` will be marked as false.

In general, you don't want to return the same anonymous user unless already signed in. This is for security reasons. Anonymous users are not meant to persist cross device as you don't have proof it is the same user.

**Comment by surajbarkale-dolby** [comment]
I need this capability so our console does not fill up with anonymous users created by tests. Our tests use 10 anonymous users. Which means at least 100 users created per day. We can mark these users with a specific display name & run scripts to clean up and end of test run & also periodically. However, it would be great to have option to reuse a set of anonymous users over and over in tests. Custom tokens are not a viable option as processing these will require extra logic in servers.

I understand the security risks of reusing anonymous users and there does not seem to be an easy way of running tests with them. We shall go with the cleanup route.

One request is to attach a `displayName` to anonymous user at the time of creation so there are only a few dangling users.

**Comment by bojeil-google** [comment]
Anonymous user cleanup is a common problem. I agree. This is a problem for real users. Some users sign in anonymously and never go back to the app.
I think many applications regularly clean up inactive users, otherwise they would grow indefinitely. In fact, some applications do this for inactive non-anonymous users too, especially if it's a free service.

For clean up, we have exposed a new API `listUsers` in our Admin node.js SDK to lookup all users programmatically:  https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#listUsers
This would facilitate lookup and deletion.

If you are creating an anonymous user for testing, you can always delete them at the end of the script:
`firebase.auth().currentUser.delete()`

You also can easily add a `displayName` for a user via `firebase.auth().currentUser.updateProfile({displayName: 'bla'})`

Adding display name for anonymous users on creation is uncommon.

**Comment by surajbarkale-dolby** [comment]
@bojeil-google Thanks for all your help!
