### ISSUE TITLE
Unable to catch the errors using async/await with auth methods

### ISSUE THREAD

**Issue by skylite21** [firebase/firebase-js-sdk#1881]
#1708 
It seems when I try to use auth methods with async/await and try/catch, the error can not be caught properly here is a simple example function:

```javascript
async function logIn() {
  const email ='test'
  const password = '123456'
  try {
    const user = await firedb.auth().signInWithEmailAndPassword(email, password);
    return user;
  } catch(error) {
    throw error.message;
  }
}
```

And then when I do something like this:

```javascript
logIn().then( response => {
 // all good
}).catch(e => {
  console.log('error during login: ',e);
});
```

The console.log appears but after that I still have an Uncaught M
![Screen Shot 2019-06-13 at 22 11 17](https://user-images.githubusercontent.com/7330136/59464302-5953a200-8e28-11e9-8821-2ab6851f04ad.png)

I'm using the following environment which could be relevant here:
firebase: ^6.1.1,
webpack: ^4.29.6,
webpack-cli: ^3.3.0,
webpack-dev-server: ^3.2.1,
 @babel/polyfill: ^7.4.0,

**Comment by hsubox76** [comment]
Thanks for creating an updated issue!

Turns out the problem is that the auth library relies on the Closure library's Promise implementation which doesn't have the exact same behavior as the ECMA Promise spec.  Specifically, it throws errors asynchronously under certain conditions, causing them not to be contained by the try/catch block.

The only solution on our side is to switch all usages of Closure promises to using native promises, which unfortunately would require a big overhaul of the code.  We hope to do so the next time the Auth codebase is due for a big refactor but until then this behavior can't really be fixed.

The only options for now are to either accept the extra console errors or avoid using `async/await` on auth methods.  Sorry this isn't optimal but there's not much that can be done without a large rewrite.

**Comment by CurtisHughes** [comment]
Ran into this issue today 😞.  In my case I wanted to catch the error from a function higher up in the call stack. So my work around was to wrap the method in a new promise and return that instead. Then in the top level function I could catch and handle the error appropriately.

```typescript
public login(username: string, password: string): Promise<any> {
        return new Promise((resolve, reject) => {
            return this.auth.signInWithEmailAndPassword(username, password)
                .then((user) => resolve(user))
                .catch((err) => reject(err));
        });
}
```

**Comment by p12y** [comment]
@hsubox76 is it only the auth library that uses the Closure library Promise implementation? I want to know if I'm safe to use try/catch with firestore methods.

**Comment by Feiyang1** [comment]
@p12y correct, only auth uses Closure Promise.

**Comment by p12y** [comment]
> @p12y correct, only auth uses Closure Promise.

Shouldn't this be mentioned in the docs? Maybe they already are, in which case my bad, but I'm sure this causes a lot of head scratching for people. If that is indeed the only module in which you can't use try/catch then I should think that is something worth mentioning in the official documentation.

**Comment by carlosfaria94** [comment]
@Feiyang1 what are the reason to close this issue? It's still an issue.
