### ISSUE TITLE
[6.2.1] Unable to resolve async-storage

### ISSUE THREAD

**Issue by KazuyaHara** [firebase/firebase-js-sdk#1898]
Since upgrading to v6.2.1 from 6.2.0, app unable to resolve async-storage correctly. My environment is

  * Firebase SDK version: 6.2.1
  * Expo SDK version: 33.0.6

Maybe it occurred by [this commit](https://github.com/firebase/firebase-js-sdk/commit/5856b9d60ea6c98b5f534a1893572d8437c04a43) and I know it was made to correspond to [this change](https://github.com/firebase/firebase-js-sdk/issues/1847#issue-452686444).
> Starting from RN0.59 AsyncStorage is deprecated from react-native and moved into its own package react-native-async-storage.

It seems like expo-related error that app doesn't return 'MODULE_NOT_FOUND' exception as described in following code but can we have some workaround by firebase side?
https://github.com/firebase/firebase-js-sdk/blob/master/packages/app/index.rn.ts#L34-L36

**Comment by paarasbhandari** [comment]
I'm having the same problem. 
![Simulator Screen Shot - iPhone X - 2019-06-21 at 00 20 38](https://user-images.githubusercontent.com/31348197/59897380-676e6900-93ba-11e9-8a0d-f3872c9d1c5e.png)

**Comment by aiham** [comment]
Looks like it's related to https://github.com/firebase/firebase-js-sdk/commit/5856b9d60ea6c98b5f534a1893572d8437c04a43

**Comment by aiham** [comment]
Would be great to have a workaround for Expo, thanks.

**Comment by hsubox76** [comment]
This is caused by this recent change: https://github.com/firebase/firebase-js-sdk/pull/1879

I think that the problem is that it's only checking for the very specific error code 'MODULE_NOT_FOUND' and perhaps a different error code is being thrown in Expo.  Currently working on a fix that will try to require the React Native core bundled AsyncStorage after any error on the first require call.

In the meantime, the quickest fix would be to install `@react-native-community/async-storage` into your React Native project as it will be required in the future anyway (React Native is deprecating the version bundled with React Native core).

We're also working on getting documentation to reflect this.

**Comment by hsubox76** [comment]
Sorry, it turns out that workaround won't work.  I tried it out in Expo and wasn't able to get it working which turns out to be because Expo currently doesn't allow adding additional native modules without ejecting: https://github.com/react-native-community/async-storage/issues/72

I'm still working on the Firebase code fix to let it correctly fall back to requiring the included `AsyncStorage`.

**Comment by hsubox76** [comment]
I'm just going to do a rollback of the change as conditional require statements apparently are not supported in React Native.  In the meantime, please use Firebase version 6.2.0.  The breaking change was introduced in 6.2.1.

**Comment by hsubox76** [comment]
Just rolled it back and released Firebase 6.2.2.  Working to get release notes up but the package is released.

**Comment by rjdiogo28** [comment]
Hello @hsubox76, I believe the version firebase@6.2.3 should have fixed this issue. However, I am facing this problem yet. Do you have any solution for that?

**Comment by hsubox76** [comment]
I guess the above account was deleted? But has anyone else seen this error recur from firebase@6.2.2 on?

**Comment by TMcLoone** [comment]
I'm facing this issue right now with firebase 6.3.1

**Comment by hsubox76** [comment]
Replying to comment left on PR (https://github.com/firebase/firebase-js-sdk/pull/1879):

> This error completely broken down my dev environment. I deleted yarn, node_modules, reset metro, clear cache, AND re-created a completely new project. But still, It is showing me the error `Unable to resolve module react-native-community/async-storage`
> How is this even possible? Where is this thing locating the package I deleted??

In order to get the fix you must be using firebase@6.2.2 or later.  I've also found it can be tricky to clear the linked package from the project as once you link it, it's also referenced in a number of native Android/iOS build files, not just the JS files.

I know @leochoo mentioned starting a totally new project, so just wanted to double check the Firebase version in your case?  Additionally, are you bringing in any other libraries in addition to Firebase that may depend on that async-storage package?
