### ISSUE TITLE
FR: Option to retrieve all unique values for fields in firestore collection

### ISSUE THREAD

**Issue by Shanzid01** [firebase/firebase-js-sdk#1901]
Having something like `collection.get().distinct(..` to get all distinct values from a specific field in a collection would be a great addition.

At the moment I'm having to fetch all collections and then search for unique values, and not only is this time-consuming to download all the data, but it is also costly to perform since I'm having to read through all the documents for every request, every single time - a nightmare for scalability.

A possible alternative would be to create another collection to store all unique values, but it may complicate things down the line when I have to conditionally retrieve unique values.

**Comment by var-const** [comment]
Thank you for the report! We understand the utility of this feature request; however, a lot of things will need to change for this to become feasible. Because this would be a product-wide change, could you please file a new feature request at the [Cloud issue tracker for Firestore](https://issuetracker.google.com/savedsearches/5337669) ([docs on trackers](https://cloud.google.com/support/docs/issue-trackers)) and post a link to the newly-created issue here?

**Comment by Shanzid01** [comment]
Sure @var-const ! Here's the link:
https://issuetracker.google.com/135857830
