### ISSUE TITLE
[6.3.3] can't do initializeApp, crash with Firebase service named 'database' already registered (app/duplicate-service)

### ISSUE THREAD

**Issue by wzFLE** [firebase/firebase-js-sdk#2040]
A maintenance script used for long time worked well with former versions incl. firebase@6.3.2

When upgrading to 6.3.3, it crashes with 

```
(node:19464) UnhandledPromiseRejectionWarning: FirebaseError: Firebase: Firebase service named 'database' already registered (app/duplicate-service).
    at Object.registerService (C:\dev\ng\backend\node_modules\@firebase\app\dist\index.node.cjs.js:359:33)
    at registerDatabase (C:\dev\ng\backend\node_modules\firebase-admin\node_modules\@firebase\database\dist\index.node.cjs.js:15245:39)
    at Object.<anonymous> (C:\dev\ng\backend\node_modules\firebase-admin\node_modules\@firebase\database\dist\index.node.cjs.js:15268:5)
    at Module._compile (module.js:653:30)
```

Downgrading to 6.3.2, good again. 

It crashes very early at the admin.initializeApp(...). Put some console.log to ensure is is called only once. 

Imported packages in the script are: 

```
import firebase from "firebase/app";
import "firebase/auth";
import "firebase/database";
import "firebase/firestore";
import "firebase/storage";
import "firebase/functions";
import admin from "firebase-admin";
```

Win10, node 8

**Comment by Feiyang1** [comment]
Thanks for reporting this! We recently removed `@firebase/app` from `firebase-admin` to solve a version [conflict](https://github.com/firebase/firebase-js-sdk/issues/1696#issuecomment-501546596) when `firebase-admin` and `firebase` are used together. 

You are getting this error because you have `import "firebase/database"` and `firebase-admin` also `import "firebase/database"`. 
You can remove your `import "firebase/database"` statement and it should solve the problem.

**Comment by wzFLE** [comment]
Thanks a lot, it is the solution. Works again great !
