### ISSUE TITLE
react native UI frozen by push() of firebase.database.ref(myref).push()

### ISSUE THREAD

**Issue by deflorilemarului** [firebase/firebase-js-sdk#2076]
IOS UI gets stuck while calling push(obj)  for the firebase.database().ref(myref)
push never returns and UI is completelly frozen.

please help.

**Comment by hsubox76** [comment]
The first thing we need to do to pinpoint the issue is reproduce the bug.  Any additional information you provide would be helpful in this, such as:

- Version of Firebase SDK you are using (and if this was working in a previous version but broke on upgrade, what was the last version where it was working for you)
  - Additionally, even if this is the first version you've tried, if you have time, could you try an older version of Firebase and confirm you are still seeing the problem?
- Version of React Native
- With or without Expo
- Lines of code for importing Firebase
- Lines of code for making the method call that is causing problems
- Any error logs or console warnings
- (most helpful if possible) a minimum reproduction of your repo - remove all extraneous code, leave the minimum amount of files and lines needed to reproduce the bug, and upload it as a repo to Github and send us the link

Any or all of the above would be really helpful in narrowing it down, thanks.
