### ISSUE TITLE
Regression: User auth state not being persisted 

### ISSUE THREAD

**Issue by brunolemos** [firebase/firebase-js-sdk#223]
### Environment

  * React Native: 0.48.2
  * Operating System version: macOS 10.12.6
  * Firebase SDK version: 4.5.1
  * Firebase Product: auth

### Problem

After upgrading to 4.5.1, user persistence stopped working.

Every time I close and reopen the app,
`firebase.auth().onAuthStateChanged` is triggered with `null` value.

Downgrading to 4.3.1 fixes the problem.

**Comment by bojeil-google** [comment]
The solution is here as you are aware by your comment on that post:
https://stackoverflow.com/questions/46637992/the-current-environment-does-not-support-the-specified-persistence-type?noredirect=1#comment80242595_46637992

This is not Auth related. It is App service related.

**Comment by brunolemos** [comment]
@bojeil-google the solution provided says to use `import firebase from 'firebase'` but that's what I've been using already.

> This is not Auth related. It is App service related.

Should I post this elsewhere?

**Comment by brunolemos** [comment]
@bojeil-google no, I never user the second way

**Comment by bojeil-google** [comment]
Hmm, I'll investigate. Auth hasn't made any change related to that since 4.3.1.

**Comment by brunolemos** [comment]
Ok, thank you.

**Comment by brunolemos** [comment]
It's probably specific to react native. I noticed the packages got separated when upgrading, like @firebase/auth or something like that. Maybe for some reason it's not loading this file: 

https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.react-native.js

**Comment by jshcrowthe** [comment]
@brunolemos thank you a bunch for the report! It seems we omitted the `react-native` property from the package.json in the `4.5.1` update.

Can you try downgrading to `4.5.0` and see if that fixes the issue?

**Comment by bojeil-google** [comment]
Hey @brunolemos, I just tested this.
I discovered 2 issues in the core component and packaging:
1. AsyncStorage is not getting required. @jshcrowthe's PR above should fix it. Only none persistence will work due to that.
2. firebase.SDK_VERSION is not getting substituted in the placeholder  "${JSCORE_VERSION}". I filed an issue for that: https://github.com/firebase/firebase-js-sdk/issues/225 

Both issues were introduced in `4.5.1`. Downgrading to `4.5.0` should fix it. My test app confirms that.
On behalf of my colleagues, I would like to apologize for this inconvenience. I was just as surprised as you were. Clearly we should improve our testing after making huge refactors such as the one we made the past week.

**Comment by brunolemos** [comment]
@jshcrowthe @bojeil-google thanks guys for the quick look into this issue, appreciate it! 🙌

**Comment by stivaliserna** [comment]
Is this fixed in `4.5.2`? I'm having the issue described in #230 using `4.5.2`, and downgrading to `4.5.0` makes the issue disappear.

**Comment by jshcrowthe** [comment]
@stivaliserna, I have confirmed that this issue has been addressed in my RN environment.
