### ISSUE TITLE
firebase/firestore breaks Next.js builds due to grpc limitations

### ISSUE THREAD

**Issue by ctavan** [firebase/firebase-js-sdk#2299]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.6 (18G103)
  * Browser version: any
  * Firebase SDK version: 7.1.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Using `firebase/firestore` in Next.js apps currently breaks serverside builds (`next build` command), see https://github.com/zeit/next.js/issues/7894.

`next build` uses node `worker_thread`'s to pre-render/optimize SSR pages. If there are multiple pages that `import 'firebase/firestore';§` the build fails with:

```
Error: Failed to load /node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node. Module did not self-register.
```

The underlying issue seems to be that `grpc` (native) does not support multiple threads: https://github.com/grpc/grpc-node/issues/778

At first I thought https://github.com/firebase/firebase-js-sdk/issues/2010#issuecomment-513319783 was a similar issue and I tried fiddling around with webpack `externals` config as suggested in https://github.com/firebase/firebase-js-sdk/issues/1455#issuecomment-455712500 but to no success.

An obvious "fix" would be to finally migrate to `@grpc/grpc-js` as suggested in https://github.com/firebase/firebase-js-sdk/issues/1783

Any other idea on how to work around this issue?

#### Steps to reproduce:

See https://github.com/zeit/next.js/issues/7894#issuecomment-545410475

**Comment by thebrianchen** [comment]
@ctavan Thanks for reporting! Migrating to `@grpc/grpc-js` results in a breaking change due to the higher node version requirement, and we will reassess if the migration is acceptable. It should be released with the next major version bump, but that date is currently not yet set. We're also looking into adding support for using custom implementations of grpc, similar to the functionality on the server SDKs, but that would be a more substantial task. 

In the meantime, the best workaround is to use a custom version of the Firebase SDK with the [PR](https://github.com/firebase/firebase-js-sdk/commit/47711840afa61b27b4dfeeac0a6dd292658c140f) introducing `@grpc/grpc-js` rebased on top.

**Comment by ctavan** [comment]
Thanks for your feedback!

For the time being this was resolved in Next.js (https://github.com/zeit/next.js/pull/9199) by disabling `worker_threads` by default and therefore avoiding the lack of multithreading support in `grpc`.

So while this is no longer urgent to me I personally believe that the SDK would generally benefit (interoperability-wise) from migrating away from the native `grpc` bindings to a pure JS implementation.
