### ISSUE TITLE
Firebase database transaction fails with maxretry when using Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-js-sdk#2304]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: `macOS 10.14.6`
  * Firebase SDK version: `8.6.1`
  * Firebase Product: `database`
  * Node.js version: `v10.16.3`

#### Steps to reproduce:

When using a transaction to set an already set property to `Number.MAX_SAFE_INTEGER`, the transaction fails with `maxretry`.

Note that if the transaction sets a property from a different value to `Number.MAX_SAFE_INTEGER` it succeeds.

Log output for below code:

```
Removed testNode
Transaction 1 [committed:true]: { maxSafeInteger: 9007199254740991, value: 'Hello, world!' }
Failed: Error: maxretry
    at Repo.rerunTransactionQueue_ (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:14518:67)
    at Repo.rerunTransactions_ (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:14425:10)
    at /WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:14405:19
    at /WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:11865:17
    at PersistentConnection.onDataMessage_ (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:11894:17)
    at Connection.onDataMessage_ (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:11211:14)
    at Connection.onPrimaryMessageReceived_ (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:11205:18)
    at WebSocketConnection.onMessage (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:11106:27)
    at WebSocketConnection.appendFrame_ (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:10698:18)
    at WebSocketConnection.handleIncomingFrame (/WORKSPACE/node_modules/@firebase/database/dist/index.node.cjs.js:10748:22)
```

#### Relevant Code:

https://firebase-issue-sandbox-r8hkry.stackblitz.io

```js

const admin = require('firebase-admin')
admin.initializeApp()

function update(data) {
   if (!data) data = {}
   data.value = 'Hello, world!'
   data.maxSafeInteger = Number.MAX_SAFE_INTEGER
   return data
}

const ref = admin.database().ref('testNode')
ref.remove().then(() => {
   console.log('Removed testNode')
   // This transaction works
   return ref.transaction(update).then(({ committed, snapshot }) => {
      console.log(`Transaction 1 [committed:${committed}]:`, snapshot.val())
      // This transaction fails
      return ref.transaction(update).then(({ committed, snapshot }) => {
         console.log(`Transaction 2 [committed:${committed}]:`, snapshot.val())
      })
   })
}).catch(err => {
   console.error('Failed:', err)
}).finally(() => admin.database().app.delete())

```

**Comment by rommelpe** [comment]
Thanks @rhodgkins. I was able to replicate this. I'll confirm internally to see if this is an intended behavior or bug (b/144360691), and I'll let you know once I have an update.

**Comment by mikelehen** [comment]
@rhodgkins Thanks for the report!  This isn't intended behavior, but it's not too surprising and it's probably not something we will fix unfortunately.

For context, Number.MAX_SAFE_INTEGER is (as the name implies) the largest integer that can be precisely represented in JavaScript before things start getting weird.  If you e.g. try to add 1 to it, you'll get back the same number.  Basically, math operations stop working correctly at this point.

The way transactions work, we create a hash of the current value in the SDK and send that to the backend along with our write so that the backend can verify the hash before applying the write (to guarantee nobody else has modified the value in the meantime).  If the backend checks the hash and it doesn't match, then the transaction will retry.  And if it retries too many times, you get the error you're seeing.  I'm guessing that our hash algorithm is failing with numbers that are too close to MAX_SAFE_INTEGER.  It's probably a bug / limitation of this code (https://github.com/firebase/firebase-js-sdk/blob/988017f45bb0960c125224bbb17d9b09bd7e96e9/packages/database/src/core/util/util.ts#L425) that converts the number into a string representation.

So this is a valid bug but it's probably been around for many years at this point and it's not something we'll likely tackle in the foreseeable future given that it's an edge case and most of our development effort is focused on the Firestore SDKs.  If you're interested in putting together a PR to fix it, we might be able to merge it, assuming it was not particularly risky (but unfortunately, modifying the doubleToIEEE754String() code is likely to be at least somewhat risky).
