### ISSUE TITLE
Analytics: Failed to execute 'put' on 'IDBObjectStore' (transaction not active)

### ISSUE THREAD

**Issue by cNille** [firebase/firebase-js-sdk#2311]
### Environment

  * Operating System version: Android 8.0.0
  * Browser version: Webview in Cordova
  * Firebase SDK version: 7.2.2
  * Firebase Product: analytics 

### The problem

Hi! 👋 

I am getting errors when trying to track events and views on firebase analytics. 
It works as without fail on a browser (chrome, mac os), but fails when using it in a Cordova app (both android and ios tested).

Error message: 
```
DOMException: Failed to execute 'put' on 'IDBObjectStore': The transaction is not active. (...)
```
The error is catched and the app doesn't crash, but nothing is registered on firebase analytics dashboard.

Any ideas on what might be wrong? 

Note: As I aim to do "on the air" update I've added the `firebase` and `firebase/analytics` in my javascript bundle with help of gulp. I downloaded the files from the CDN and added them manually. But I don't think it should affect anything. 

#### Relevant Code:

```
window.firebase.initializeApp(firebaseConfig);
var analytics = window.firebase.analytics();
analytics.logEvent('trackevent', { ... } ) 
````

**Comment by Feiyang1** [comment]
Hi, Thanks for the report! While we try to reproduce the issue, I'd like to understand how you include the firebase library. 
If I understood you correctly, you downloaded `firebase` and `firebase/analytics` from CDN and bundled them using gulp, is it correct? What exact 2 files did you download?

**Comment by cNille** [comment]
Yes that is correct! 
The 2 files a downloaded are: 
https://www.gstatic.com/firebasejs/7.2.1/firebase-app.js
https://www.gstatic.com/firebasejs/7.2.1/firebase-analytics.js

Thanks for helping :)

**Comment by Feiyang1** [comment]
Thanks for the info! 
I was not able to reproduce the issue. My test cordova app runs without any error, but no event was sent. It appears that cordova serves all resources using `file:///` instead of `http://`, so the cookie is not available for use.
It is an issue because FirebaseAnalytics replies on gtag.js which uses cookies to manage user and session.
Unless you know a way to make Cordova to switch to `http://`, FirebaseAnalytics is not going to work in Cordova.

An alternative is to host your website in a http server and load this website in your Cordova app using `InAppBrowser`. You might have other constraints, e.g. need offline support, so it might not be an ideal solution for you.
