### ISSUE TITLE
FR: pagination offset

### ISSUE THREAD

**Issue by karatakis** [firebase/firebase-js-sdk#2320]
### [REQUIRED] Describe your environment

  * Operating System version: Windows10
  * Browser version: Chrome
  * Firebase SDK version: 7.2.2
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem
Hello,
I have a paginated message client and I want to let users jump from page 1 to page 5.
My problem is that I have to load pages 2,3,4 so I can keep the anchor (lastVisited) document.
I couldn't figure a way to skip pages 2,3,4 without loading them.

### Request
Are there any future plans of implementing an offset feature ?
Is there another way I can do it ?

**Comment by mikelehen** [comment]
@karatakis The backend actually supports an offset feature and we expose it in our admin / server-side SDKs (e.g. https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/Query#offset) but we don't expose it in the Firebase mobile / web SDKs because:

1. There's no way to make this sort of query work while offline (since you need all of the skipped documents available locally in order to know where page 5 starts), which is a primary use case for the mobile / web SDKs.
2. It is inefficient and expensive for you.  In order to do offset(500).limit(10), the backend has to read the first 500 documents that match the query in order to skip them. This is somewhat slow and you are billed for 500 document reads rather than just 10.

So your options are probably either:
1. Avoid exposing a "skip to arbitrary page" UX (e.g. think about gmail that lets you perform arbitrary searches to find emails of interest but then you need to page through them 1 page at a time).
2. Implement it yourself somehow (you could use offset() server-side; try to maintain an "index" that maps page numbers to items; or do a full query and then post-filter down to the items on the desired page).
3. Look into another database option other than Cloud Firestore.

Thanks / sorry!
