### ISSUE TITLE
Did Firebase.js 7.x break compatibility with Typescript 2.6.x?

### ISSUE THREAD

**Issue by zarko-tg** [firebase/firebase-js-sdk#2335]
Reposting from SO (https://stackoverflow.com/questions/58657228/did-firebase-js-7-x-broke-compatibility-with-typescript-2-6-x) since we aren't getting anywhere.

(All) Ionic 3 apps cannot compile since Firebase 7.0.0. Was compatibility with Typescript 2.6.x abandoned without checking or informing about it?

Steps to reproduce:
1. npm i -g ionic
2. cd ~/temp && ionic start i3 blank --type=ionic-angular && cd i3
3. npm i firebase
4. Add the following line along the other imports in src/app/app.component.ts
`import * as firebase from 'firebase/app';`
5. ionic serve

Compilation fails, see the SO issue for output log.

The pretty standard tsconfig.json used is:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

Environment:
   Ionic CLI          : 5.4.5
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2
   NodeJS : v12.13.0
   npm    : 6.12.0
   OS     : macOS Catalina

**Comment by hsubox76** [comment]
Yes, it did break compatibility with Typescript versions prior to 2.8.  It wasn't intentional, but we used a conditional type for analytics that is not recognized by pre-2.8 versions of Typescript.  Are you able to upgrade your Typescript version?  I was able to `npm i typescript@latest` in my test Ionic project and run it successfully but I don't know if you have other constraints that prevent you from upgrading.

We are looking into what we might be able to do to fix it for users of earlier Typescript versions but if you are able to safely upgrade Typescript to 2.8+ this may be the quickest way to unblock you for now.

**Comment by zarko-tg** [comment]
Thank you for the quick response. I don't think it's a viable option (for larger Ionic/projects) but I can give it a go (again) asap.

**Comment by zarko-tg** [comment]
We'll try out running with TS 2.8.4 as the compilation seems fine with it.
You probably want this minimum requirement documented (someplace right).

Feel free to close this issue when you see fit.

**Comment by rommelpe** [comment]
Thanks for the input, @zarko-tg. We are pleased to let you know that we have added this info on our [release notes](https://firebase.google.com/support/release-notes/js#version_700_-_september_26_2019).

> Breaking change: For TypeScript users, the required minimal TypeScript version is 2.8.0.
