### ISSUE TITLE
Firestore is too slow

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-js-sdk#242]
I didn't find a Firestore repo, so I'm reporting this here.

I have a very minimal test case:

The firestore database contains a collection "users" with three documents, each with a single "name" property.

In ngOnInit:

```
    this.userCollections = this.afs.collection('users');
    this.users = this.userCollections.valueChanges();
```

Template:

```
<div *ngFor="let user of users | async">
  User: {{user.name}}<p>
</div>
```

<b>IT TAKES 4-8 <i>SECONDS</i> BEFORE THE USER NAMES APPEAR</b>

Completely unacceptable. Offline mode is, well, off. Compiling with --aot and deploying to firebase.com didn't help.

If I switch to the RTDB, it takes subsecond.

Is this expected?

**Comment by samtstern** [comment]
@ghost I apologize that you never got a meaningful response from a human here.  We have made a _a ton_ of improvements to the speed of Cloud Firestore since October.  Anecdotally, I hardly hear any speed complaints at all anymore.

I am going to close this issue since it's very old and I think the speed should be improved by now but feel free to let me know if I am wrong!

**Comment by hoangvuanhdevelopervn** [comment]
Me too. Firestore very very very slow. I just call 10 documents each time but it's take 5, 6 minutes to finish. My netwok is strong, i also using another back-end server and it's fast, firestore is too slow, worst back-end i ever use.
