### ISSUE TITLE
How to query all the information in Firebase in reference-id like a relationship ?

### ISSUE THREAD

**Issue by karthickms** [firebase/firebase-js-sdk#2437]
In following result, how to get the results of video in post object ? when we store the video id
{
  "posts": {
    "postId1": {
      "createdAt": "15/05/2014 15:03:45",
      "section": "trending",
      "type": "videoPost",
      "videoId": "7hPMmzKs62w"
    },
    "postId2": {
      "createdAt": "15/05/2014 11:03:45",
      "section": "home",
      "type": "videoPost",
      "videoId": "Lp9GgdCgMXk"
    }
  }
  ,
  "videos": {
    "7hPMmzKs62w": {
      "credits": "The War on Drugs",
      "duration": "2:53",
      "title": "Red Eyes"
    },
    "Lp9GgdCgMXk": {
      "credits": "Shamir",
      "duration": "2:57",
      "title": "On the Regular"
    }
  }
}

**Comment by rommelpe** [comment]
You can create a query that match the specified `video_key` value and join for each video:

`firebase.database().ref('posts').orderBy('videoId').equalTo('<video_key>')`

Maybe, you're wondering whether doing a client-side join is going to be too slow, it typically isn't because the Firebase Database client can pipeline these requests. See Puff's answer [here](https://stackoverflow.com/questions/35931526/speed-up-fetching-posts-for-my-social-network-app-by-using-query-instead-of-obse?answertab=votes#tab-top).
