### ISSUE TITLE
Expose enableNetwork/disableNetwork

### ISSUE THREAD

**Issue by connor-odoherty** [firebase/firebase-js-sdk#244]
* Operating System version: Ionic 2
  * Firebase SDK version: 4.5.2
  * Firebase Product: Firestore

I am using Firestore in an Ionic 2/Angular 2 project, but I do want to automatically sync with my external server when online. Ideally, I would like to be able to permanently enable offline mode, and only contact the server when the client chooses. I see that there are internal enableNetwork and disableNetwork commands. Would it be possible to expose these to the developer? And if not, is there a better way to take Firestore permanently offline?

**Comment by mikelehen** [comment]
We've discussed exposing these.  Can you explain a little more about your use case?  How and when would the user choose to sync with the backend?

**Comment by connor-odoherty** [comment]
A simple feature from my app:

My app is used by customers who often need to use our product when cell networks are not available. Prior to this offline period, the user activates a sync button to pull their most recent documents for download to view offline. While offline, they may view and edit these documents. When they regain connection, they manually sync again to upload their changes.

We prefer an explicit execution of the sync as opposed to the automatic syncing for a few reasons:

- Customers themselves enjoyed the manual syncing more
- Manual syncing requires less data
- It makes it easier on our end to resolve conflicts and monitor the system
- It makes it easier for us to maintain consistency with our desktop model without having to completely refactor to introduce Firebase
- Testing is easier

Curious, what other reasons have been proposed? And what are your reservations?

**Comment by mikelehen** [comment]
Thanks for explaining!  We're currently optimizing for sync on-demand rather than an explicit sync model like you're talking about, but it's a totally reasonable request. We don't have any strong reasons not to expose the disableNetwork() / enableNetwork() APIs other than to keep the public surface area minimal and because we didn't have compelling use cases (and therefore didn't know if the APIs would be sufficient to solve the use cases).

On that note, if we exposed these APIs, do you think that would be enough? How would you tell when you're "done syncing" and could call disableNetwork() again? :-) For caching data locally I think you'd basically need to add onSnapshot() handlers for all of the data that you want cached offline and wait for events with isFromCache==false.  But syncing your pending offline writes is more problematic. You'd probably need to know all of the documents you modified (which might be difficult) and add onSnapshot() handlers to them that wait for hasPendingWrites==false.  Once both of those conditions have been met you could perhaps safely call disableNetwork().

So I think just exposing these 2 methods might not be enough (or at least would still be extremely inconvenient). If you have thoughts on the ideal API, feel free to share them here.  In the meantime, I'll bring up exposing disableNetwork() / enableNetwork() with the team as I can see the value of it even just for tests, etc.

**Comment by mikelehen** [comment]
We agree. :-)  @gsoltis has exposed them in https://github.com/firebase/firebase-js-sdk/commit/60c9d4acaf5b89448f5789d6bb7dc4072da16d78 which is currently in the firestore-api-changes branch. It should be merged into master and released in the next couple weeks.

**Comment by mikelehen** [comment]
This is now available in the 4.9.0 release!

**Comment by i2chris** [comment]
@mikelehen  Is there a way to see the network status of Firestore?  i.e. can you see if it has been disabled by calling disableNetwork?   

This would be useful to show in the settings of my app.  THanks!

**Comment by wilhuff** [comment]
There isn't currently a way to do it, though it would be straightforward to add. The actual state is in the [RemoteStore](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/remote/remote_store.ts#L145). A PR that plumbs this out would be welcome!
