### ISSUE TITLE
Signing in using a disabled account, using signInWithPopup, returns an 'Internal Error'

### ISSUE THREAD

**Issue by pmullot** [firebase/firebase-js-sdk#245]
### Version info

**Angular:** 4.4.3

**Firebase:** 

**AngularFire:** 4.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** no

### How to reproduce these conditions
When you try to sign in using a Disabled account (via the Firebase Console), using signInWithPopup, it returns an 'Internal Error'.

**Steps to set up and reproduce**
With a typical login function, as described in all examples and tutorials

```
login() {
	const provider = new firebase.auth.GoogleAuthProvider();
	this.afAuth.auth.signInWithPopup(provider)
		.then(credential =>  {
	        // use credential observable to get user data ...
		// with a disabled user, this is not reached
		})
		.catch(error => {
		  console.log(error);
		  // error =  {code: "auth/internal-error", message: "An internal error has occurred."}
		});
}
```

### Expected behavior

Returned error should specify "User disabled" or something similar

### Actual behavior

Returned error isn't specific enough. It's also misguiding since it refers to an internal error
`{code: "auth/internal-error", message: "An internal error has occurred."}`

**Comment by rommelpe** [comment]
@pmullot, I believed this issue was fixed in the tagged commit. I was able to confirm it with [my sample repro](https://stackblitz.com/edit/angular-hxsaia) using Angular:4.4.3 with @angular/fire:5.0.0 (the old AngularFire was [depreciated](https://www.npmjs.com/package/angularfire2) so I’ve used the older version of new @angular/fire). Let us know if you are still having issues.
