### ISSUE TITLE
Firestore Pagination query on collection group data

### ISSUE THREAD

**Issue by ravi-pandit14** [firebase/firebase-js-sdk#2456]
**Title**: I am facing issue regarding pagination on collection group in Firestore

**Description**: I want to implement infinite scroll in React-Native with firebase and i want to paginate on collection group data for instant result in my app. Error is shown in screenshot.

**My code:**
```javascript
//First time fetch data
var ref = firestore().collectionGroup('user_posts').orderBy('time_stamp', 'desc').limit(5);
    ref.get().then(snapshot => {
      var posts = []
      var lastVisible = snapshot.docs[snapshot.docs.length - 1];
      this.setState({ last_Visible: lastVisible });
snapshot.forEach((doc) => {
console.log("data first5:",doc.data());
})
      }); 


// This code executed when scroll down FlatList
console.log("last_visible data:",this.state.last_Visible);
var next = firestore().collectionGroup('user_posts').orderBy('time_stamp', 'desc')
          .startAfter(this.state.last_Visible)
          .limit(5);
 next.get()
        .then(FirestoreDocumentSnapshot => {
          var lastVisible = FirestoreDocumentSnapshot.docs[FirestoreDocumentSnapshot.docs.length - 1];
          this.setState({ last_Visible: lastVisible });
FirestoreDocumentSnapshot.forEach((doc) => {
console.log("data:",doc.data());
})
})
```
**Please help, what i am doing wrong?**
![download_20191212_112936](https://user-images.githubusercontent.com/30682376/71144686-f1ea3500-2244-11ea-8d05-ff2d29fdfc3f.png)

> my package.json
"react-native": "0.60.5",
"@react-native-firebase/app": "6.0.4",
"@react-native-firebase/auth": "^6.0.4",
"@react-native-firebase/firestore": "^6.0.4",
"@react-native-firebase/storage": "^6.0.4",
"firebase": "^5.0.4",

**Comment by var-const** [comment]
Apologies for the slow reply. From the error message, it appears that your application is passing a document ID string as the argument to `startAfter` in a collection group query that's ordered by document ID. This is incorrect; instead, it should pass either the whole document snapshot (probably the easiest) or else the full path to the document (if necessary). To illustrate:
```javascript
const docSnapshot = someDocumentSnapshot();
const cgQuery = firebase.firestore()
    .collectionGroup('foo')
    .orderBy(firebase.firestore.FieldPath.documentId());
// Ok -- passing a document snapshot
const next = cgQuery.startAfter(docSnapshot);
// Also ok -- passing the full path
const next = cgQuery.startAfter(docSnapshot.ref.path);
// Incorrect -- passing just the document ID will trigger an error
const next = cgQuery.startAfter(docSnapshot.id);
```

However, one thing I don't understand is how your application is triggering the error. In the code snippets you posted, the collection group is sorted by a field named `time_stamp`. What is the type of the field? The error from the original post can only be triggered when the collection group is ordered by document ID, and I presume that the type of `time_stamp` is _not_ document key. Moreover, it appears that the snippet you have posted would not trigger the error, because `this.last_Visible` should be a `DocumentSnapshot`, but from the error message, it's clear that what's being passed to `startAfter` is just a plain string. There doesn't seem to be anything in the code snippet that would convert one to the other, with the exception of `this.setState` function.

Could you please double-check if any other parts of your application are also calling `startAfter`? Could it be that the error is actually triggered by some other collection group query in your code?

Also, I see there is some debug logging in the code snippet you posted:
```
console.log("last_visible data:",this.state.last_Visible);
```
What output does it produce?

**Comment by ravi-pandit14** [comment]
@var-const Thanks for reply! 
**My answer of asking your some questions.**
**Question1:** What is the type of the field?
**Ans:** it's a number type (new Date().getTime()) But i have changed to firebase server timestamp.
**Question2:** Can you share the implementation of setState?
**Ans:** [here is react-native link](https://facebook.github.io/react-native/docs/state)
**Question3:** What output does it produce (`console.log("last_visible data:
",this.state.last_Visible);`)?
**Ans:** ![Screenshot 2019-12-21 at 5 56 35 PM](https://user-images.githubusercontent.com/30682376/71307918-5eb72800-241b-11ea-814a-03e6b7f29e7d.png)

**Comment by var-const** [comment]
Thanks for the additional information! At the first glance, it seems like the code you posted should not trigger the error message you're seeing. However, it has occurred to me that when I tried to reproduce the issue, I wasn't using the React Native packaging of Firestore; I will give it another try using `"@react-native-firebase/firestore"` in case it's the culprit.

**Comment by var-const** [comment]
Sorry about the long delay (due to holiday season). I can repro the issue using React Native packaging of Firestore. We'll look at it further, but it's very likely there is nothing we can do about it -- the issue appears to be with React Native version of Firestore. In the meantime, the easiest workaround is to pass the full document path instead of the document snapshot. That is, you can try replacing
```javascript
.startAfter(this.state.last_Visible)
```
with
```javascript
.startAfter(this.state.last_Visible.ref.path)
```

Please let me know if this solves the issue you're seeing, and once again, apologies about the delay.

**Comment by var-const** [comment]
Update: upon further investigation, the issue appears to be in React Native version of Firestore. I have opened a bug in the appropriate repo.

**Comment by ravi-pandit14** [comment]
@var-const Thanks for reply!
I had use `.startAfter(this.state.last_Visible.ref.path)` in my code as your documentation.
This is fixed my error but next data is same as last data and it's coming again and again after calling getNextData().

**Comment by var-const** [comment]
@ravi-pandit14 Upon a glance, it looks like the code snippets you posted should work correctly. Can you post the console output you get? I'm interested in seeing the first 5 documents, the value of `lastVisible`, and the next 5 documents (please make sure to remove any confidential information. I really only need the IDs and the `time_stamp` fields).

**Comment by ravi-pandit14** [comment]
@var-const Thank you very much!
**First 3 data screenshot:**
![Screenshot 2020-01-10 at 10 14 24 AM](https://user-images.githubusercontent.com/30682376/72126650-f06ae300-3392-11ea-8e7f-4f9e2cc059ca.png)

**lastVisible console screenshot:**
![Screenshot 2020-01-10 at 10 19 57 AM](https://user-images.githubusercontent.com/30682376/72126663-ffea2c00-3392-11ea-8fbc-ace72b7eb167.png)


**Next 3 data console screenshot:**
![Screenshot 2020-01-10 at 10 15 16 AM](https://user-images.githubusercontent.com/30682376/72126655-f82a8780-3392-11ea-876c-304572b2c1ff.png)

**Comment by var-const** [comment]
Can you please try changing your code to the following:
```
var next = firestore().collectionGroup('user_posts').orderBy('time_stamp', 'desc')
          .orderBy(firebase.firestore.FieldPath.documentId(), 'desc')
          .startAfter(this.state.last_Visible.get('time_stamp'), this.state.last_Visible.ref.path)
          .limit(5);
 ```
Apologies for the partially incorrect code snippet I posted above. The arguments given to `startAfter` should correspond to the `orderBy` fields, so since your code is ordering by `time_stamp`, the argument given to `startAfter` should also be a `time_stamp` value. However, in case two documents have the same timestamp value, a tiebreaker is necessary, so it's still useful to additionally order by document ID and use the full ID of the last visible document as an additional argument to `startAfter`.

I tested the snippet above with ReactNative, and it should work. Please let us know if you have any further questions.

**Comment by var-const** [comment]
Note: the issue was [fixed](https://github.com/invertase/react-native-firebase/issues/3063#issuecomment-581468347) in the ReactNative repo. Once the fix is released, the code from your original post in this thread should start working with Firestore ReactNative.
