### ISSUE TITLE
Realtime Database child_changed fires twice when value is set to ServerValue.TIMESTAMP

### ISSUE THREAD

**Issue by perrosnk** [firebase/firebase-js-sdk#2461]
* Firebase SDK version: latest
  * Firebase Product: database (auth, database, storage, etc)

The `.on('child_added)` listener is called twice when the value is set to `ServerValue.TIMESTAMP`.

#### Steps to reproduce:
```javascript
        const updates = {};
        updates[`/user-chats/${user.id}/${chatId}`] = database.ServerValue.TIMESTAMP;
        database().ref().update(updates);

       userChatsRef.on('child_changed', (snap) => { console.log('called') })
```

Edit: I also receive different timestamp values

**Comment by puf** [comment]
This is the expected behavior: when you write a server-side timestamp, the client gets two events. 

1. The first  event that fires is a local estimate of the server timestamp, based on the local time, and the detected latency between the client and server. 

1. The second event is the actual value as the server determined it.

If you're writing the timestamp to a new node, the first of these events will typically be a `child_added`, while the second will be a `child_changed`.
