### ISSUE TITLE
Nested Database Transactions Not Working as Expected

### ISSUE THREAD

**Issue by lonerz** [firebase/firebase-js-sdk#2488]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 10.14.6
  * Browser version: N/A
  * Firebase SDK version: @firebase/database 0.5.17 (SDK version 6.3.2)
  * Firebase Product: database

#### Steps to reproduce:
I am trying to do a database transaction in another database transaction. Essentially, I want to decrease a counter under two different paths by 1 atomically with transactions. I came up with a simple case where I have two counters and if the first counter is greater than 0, we run a transaction on the second counter and once that is greater than 0, we decrement and also decrement the first counter.

However, it seems like the inner transaction (the one decrementing the second counter) finishes AFTER the outer transaction (the one decrementing the first counter). Moreover, the outer transaction is deleting the first counter, so I assume the outer update function that is asynchronously waiting for the inner transaction is returning null.

The code is below with the test case I used.

#### Relevant Code:

Data:
```
/counter1: 5
/counter2: 5
```

```javascript
const { committed: outer_committed, snapshot: outer_snapshot } = await admin
    .database()
    .ref(`/counter1`)
    .transaction(async counter1 => {
      console.log('counter1:', counter1);
      if (counter1 === null) {
        return 0;
      } else if (counter1 > 0) {
        const {
          committed: inner_committed,
          snapshot: inner_snapshot,
        } = await admin
          .database()
          .ref(`/counter2`)
          .transaction(counter2 => {
            if (counter2 === null) {
              return 0;
            } else if (counter2 > 0) {
              return counter2 - 1;
            } else {
              return;
            }
          });

        console.log(
          'inner transaction finished:',
          inner_committed,
          inner_snapshot.val(),
        );

        if (inner_committed) {
          return counter1 - 1;
        }
        return;
      }
      return;
    });

  console.log(
    'outer transaction finished:',
    outer_committed,
    outer_snapshot.val(),
  );```

**Comment by puf** [comment]
Nesting transactions like this won't work, because of the way Firebase Database transactions work. They are optimistic, compare-and-set operations, instead of the pessimistic, lock-and-write operations that you seem to expect.

When you start a transaction in a Firebase client, the following happens:

1. The client calls your callback with its best guess as to the current value of the location that you run the transaction on. Initially this will often be `null`. 
2. Your code then returns what the value at the location should become. 
3. Both the guess and your update are sent to the server, which then compares the guess to the actual value. 
4. If the database location matches with the guess of the client, the server writes the value you returned to the database. 
5. If it guessed wrong, it returns the actual value to the client, which then again calls your handler with its new guess. 
6. This can go on for up to 25 times, in cases there's a lot of contention on the location.

If you want to update two locations transactionally, you'll want to run a single transaction that covers both locations. In your example that would mean that you'd run a transaction on the root of the database. Since the return value of your callback is rejected if the database value at the location has changed, any write to the entire database will trigger a retry. For this reason it is common to isolate transactions in your JSON. The more local the transaction runs, the less chance there is of contentious write operations.

**Comment by schmidt-sebastian** [comment]
I am closing this issue for now. Please follow the advise outlined above (thanks @puf!).

If there is more feedback, we can consider supporting this use case directly.

**Comment by lonerz** [comment]
@puf @schmidt-sebastian I ended up going with the validations path.

However, with simultaneous writes, it seems like Firebase tries to write the data, which listeners on that data pick up the attempted write, and if it doesn't satisfy validations, it then reverts the write, which listeners on the data also pick-up.

Is this supposed to happen? Where both the failed write and the reverted write are sent to listeners?

**Comment by puf** [comment]
That is indeed the expected behavior. The client where the write is performed sees optimistic events, which are then reconciled if the server rejects the write. 

If you have additional questions about this, please post on Stack Overflow. This repo is specific to the JavaScript SDKs, and there a lot more folks who can help on Stack Overflow.
