### ISSUE TITLE
Realtime Database reorders puts/listens issued before the connection is established

### ISSUE THREAD

**Issue by ryanpbrewster** [firebase/firebase-js-sdk#2501]
When the RTDB SDK has a live websocket connection, code like this:
```
db.ref().set(42);
db.ref().once("value");
```
reliably sends two messages, a write and then a listen, in that order.

If the websocket handshake has not completed, the same code will instead send a listen and then a write (the opposite order).

I believe the issue is due to this code here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/src/core/PersistentConnection.ts#L928

This can make it difficult to write an order-sensitive sequence of operations. For instance, if I have database security rules that only allow a user to view data if their id is in a specific location then they need to write the id and _then_ request the data.

Could we preserve the relative ordering of puts/listens and issue them in the same order they were constructed in `restoreState_`? I see a comment saying

>    Puts depend on having received the corresponding
>    data update from the server before they complete, so we
>    must make sure to send listens before puts.

which I don't understand.

**Comment by mikelehen** [comment]
In principle, it might be possible to modify the SDK to preserve the order of operations and re-send them in the same order, but in practice this would be a major change because we don't treat listens as "operations", we just keep track of the current set of active listens (since listens are long-lived and need to be re-sent every time we disconnect/reconnect, etc.)

Regarding:
> Puts depend on having received the corresponding data update from the server before they complete, so we must make sure to send listens before puts.

This is explaining why we have to send the puts before the listens and not vice-versa.  Basically we rely on our writes showing up to our listeners before the writes are ack'd.  If the write were ack'd first, then we would stop latency-compensating the write, and your listener would momentarily flip back to the old server version, before the listener caught up with the newly written version.

So it's relatively safe (ignoring security rules I guess) to re-establish all of your active listens, and then send your pending puts.  But the opposite order would _not_ be okay.  I _think_ if you preserved ordering and intermixed them, that could work, but it'd be a non-trivial change and it's probably not worth doing, since the existing behavior has been around for 7+ years.

So for this case, I think if your reads depend on your writes, then you just need to write your code to make that explicit and wait for your set() to complete before starting the read. 🤷‍♂

**Comment by mikelehen** [comment]
FWIW, preserving order might additionally be complicated by the fact that there isn't a 1-1 mapping between API calls and backend operations.  E.g.:

```
ref.on('value', ...)
ref.child('foo/bar').set(...)
ref.child('baz').on('value', ...)
```

Because the two listens are redundant, we'll only send a single listen on `ref`.  Do we send it before or after the set?

**Comment by ryanpbrewster** [comment]
The two listens are only redundant if the first one succeeds. If it fails then we have to fall back to the child, right?

**Comment by mikelehen** [comment]
As implemented, we will fail both listeners.  We generally assume that apps are written so that they don't try to read / write data they don't have access to, so we don't try to handle this gracefully.

**Comment by WriterDuet** [comment]
Thanks for taking up this issue! I hit this issue in our live app, and it's not so simple to wait for a write to complete before starting listeners when considering offline mode. Our use-case is we need users to be able to create new documents which is done by writing to a location that's only writeable if you're "claiming" it by inserting your UID (if it's currently empty) and immediately start listening to that document, even if offline.

I didn't realize this ordering wasn't a core requirement of Firebase, maybe I'm wrong about this being a big problem but it certainly was surprising. I can work around my issue by retrying the listeners when they get permission denied, but I was hoping that wouldn't be necessary since it creates weird coding requirements for us.

**Comment by WriterDuet** [comment]
Thanks for taking up this issue! I hit this issue in our live app, and it's not so simple to wait for a write to complete before starting listeners when considering offline mode.

I didn't realize this ordering wasn't a core requirement of Firebase, maybe I'm wrong about this being a big problem but it certainly was surprising. I can work around my issue by retrying the listeners when they get permission denied, but I was hoping that wouldn't be necessary.

**Comment by mikelehen** [comment]
@WriterDuet Good to see you're still pounding on things and causing issues. 😛 

Another possible workaround would be to change your security rules so that you're allowed to read the document if it doesn't exist (yet).  That way your listener can succeed even if the write hasn't gone through.  If by some chance a different user writes the document and puts their own uid in, your listener would immediately lose permission and get rejected, so there's no security concern.

**Comment by WriterDuet** [comment]
Good call @mikelehen! I'll find some more stuff to keep you on your toes.

**Comment by schmidt-sebastian** [comment]
Based on the comments above, we are likely not moving forward with a fix.I will close this issue for now and we can re-asses the situation if the workarounds mentioned here are not adequate
