### ISSUE TITLE
[Question and Help] Bugged pricing modal?

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-js-sdk#2541]
I couldn't find any info online after digging for awhile so I am asking two important pricing questions below.

#1 From Firebase Video from https://www.youtube.com/watch?v=6NegFl9p_sE&feature=emb_logo Todd Kerpelman says that when you send messages in 1 on 1  chat in 10 minutes, there will be roughly 60 writes and 120 reads. I don't know why it is 120 reads? Shouldn't it be 60 writes and 60 reads from the other person? When you send a message, why would that count as 1 write AND 1 read? Why we have to pay more 1 read whenever you write once to a document?

#2 Does this mean when I do addSnapshotListenerWithIncludeMetadataChanges: instead of mere addSnapshotListener:, would I would get twice as more reads? Whenever you send a message, it would be 1 write, 1 read when hasPendingWrites = true, and 1 read when hasPendingWrites = false?

Thank you for answering my questions. Seems like Firebase will be pretty costly for messaging apps.

**Comment by thebrianchen** [comment]
@coolcool1994  Thanks for writing in! For every message in a 2 person chat room, there would be 1 read and 2 writes. To clarify the video, if you store the messages for each chatroom in their own document, you would update each user's chatroom by adding a snapshot listener on the corresponding document. So in this case:

1. Alice sends a message (1 write). 
2. Alice's snapshot listener fetches the update with her message (1 read).
3. Bob's snapshot listener fetches the update with Alice's message (1 read).

Reads are charged based on when the Firestore SDK fetches data from the server, and not based on when snapshot listeners fire. Writing to a document will result in reads for snapshot listeners attached to the document across different clients. So, in the case where you get a subsequent snapshot because of metadata changes (such as `fromCache=true`), you will not be billed a second time.

**Comment by coolcool1994** [comment]
Thank you for such a thorough answer! As a small follow up question, if you were to attach and detach snapshot listener many times within 30 minutes (white cache doesn't expire and re-billed) when there is NO document changes, would you get billed multiple times or would you get billed nothing?

**Comment by thebrianchen** [comment]
As long the underlying documents have not changed and you have persistence enabled, you would not be billed again within the 30 minute threshold. However, if you have persistence disabled while attaching and detaching a snapshot listener, you would be billed every time you re-attach the snapshot listener.

Please note -- our best practices [guide](https://firebase.google.com/docs/firestore/best-practices) discourages frequently adding and removing snapshot listeners, as it can result in increased notification latency.
