### ISSUE TITLE
When Firestore persistence is enabled, queries get sigificantly slower as cache size is increasing

### ISSUE THREAD

**Issue by ricardodebeijer** [firebase/firebase-js-sdk#2579]
### Describe your environment
  * Operating System version: Android 8.1.0
  * Browser version: Ionic 3
  * Firebase SDK version: 6.6.2
  * Firebase Product: firestore

### Describe the problem
We have an app (Ionic 3) which retrieves data so it can be used offline. For this to work we call `enablePersistence`.

The problem we are seeing is that each time we retrieve a new set of data, the query to retrieve that set takes longer.
For example to download the first set, it takes 10 seconds.
When downloading a second set, which contains exactly the same data (only firestore Ids are different), it takes 29 seconds. 
On the third set it takes 38 seconds, on the fourth we are above 1 minute and with set 20 we are hitting 5 minutes. 
Just to be clear: all data sets have the exact same fields and are equal in size, only firestore Ids are different in order to have unique documents.

Things we tried:
* Went to app settings in Android and pressed "clear cache", no change.
* Also in app settings in Android: pressed "clear data", this removes everyting and is like clean install. After this: the query is fast again for the first set, so we found a reset, but it keeps increasing in duration, so same problem.
* Removed the `enablePersistence`, with this disabled: all queries take the same amount of time (and are even faster then with persistence enabled)
* Manually removing the firestore indexDB from the Chrome Developer Console: this also works as a reset, fast for the first set, but still keeps increasing.
* Used the `clearPersistence` method in app startup, before retrieving a new data set: this also keeps the queries equally fast

So the question/bug is:
* When the persistence cache/indexDB is increasing, would that explain why the queries keep taking longer and longer?
* How many entries in the indexDB is considered 'large'? Right now after a clean install and retrieving 1 data set, we have 260 entries in /remoteDocuments and 980 entries in /targetDocuments.
* How to use the `clearPersistence` in run-time? Right now we only get it to work in the app initialize. We tried the following combination of `firebase.firestore().waitForPendingWrites()`, then `firebase.firestore().terminate()`, followed by `firebase.firestore().clearPersistence()`. So far so good,  but it crashes when we try to use `firebase.firestore()` again with the error "app is already terminated"

**Comment by schmidt-sebastian** [comment]
@ricardodebeijer Thanks for your questions!

To be clear, we do have some ways to go to make Firestore on IndexedDB as snappy as we would like it to be. 

There are some ways you can improve performance:
- Download less data for offline consumption
- Decrease the cache size (https://firebase.google.com/docs/reference/js/firebase.firestore.Settings.html#cachesizebytes)
- Split your data into smaller collection
- Instead of using queries with different properties, use the same queries again. Repeatedly executed queries run faster than queries the client has not seen before.

If only document inserts are slow, you may also be able to speed the SDK up by temporarily removing all onSnapshot() listeners while you are downloading new data. The SDK then does not have to evaluate whether any of the inserted documents affects the current listeners.

`clearPersistence()` is meant more to make testing/local development faster. It is not intended to be used while the client is active.

We are actively investigating how we can make our clients faster. Unfortunately, there are no immediate actions that we can take based on this issue - that's why I am going to close it for now. Thank you for your feedback!
