### ISSUE TITLE
[Feature request] Firestore is prohibitively expensive for messaging/chat app

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-js-sdk#2621]
Firestore needs to update its pricing, and go easy on read ($0.06/100,000) and write ($0.18/100,000) and go harder on storage and egress costs, because read and write costs are ridiculous, prohibitively expensive which should prevent anyone who is building messaging/chat app with typing indicator, read receipt, and notifications.

One message send is 7 document reads and 4 document writes, with typing indicator, read receipt, and notifications, also given the fact that the other user is online listening for messages. (Just think thoroughly, at the very least, you need 7 reads and 4 writes. hint: you need to look up the other person's notification ids every time you send a message, send typing indicator, read receipt update).

To send 100,000 messages, it costs at least $1.20 in Firestore, given each message send cost 7 reads and 4 writes (just in the time of sending). This is ridiculous. This is why I cannot launch my app right now and start from stretch using Real Time Database. Google is very good at misleading people, and this is one of the prime examples. The docs and representatives from Google including Todd Kepperman in YouTube pricing video and etc., all said Firestore is good for Chat. Take a look at the docs for architecting messaging apps... it even gives you how chat will work out okay for pricing in Firestore. With all misleading posts from Google and all the budging from Google to use this brand new shiny baby Firestore, I so innocently used it for the chat/messaging app. Horrible idea. Infeasible idea, unless I want to donate millions of dollars to Firestore. Firestore pricing plan is broken. Plain and simple: the current pricing plan will prevent so many others from using it. Sending mere 100,000 messages cost $1.20 purely from just document reads and writes (not including loading entire conversation or history), not counting any other costs like for storage, egress, and other Firebase product costs such as Cloud functions and storage.

So disappointing and sad, but I expect you guys to take months if not years to update the pricing to fit all the diverse modals out there, if you guys ever attempt to do that. You could offer multiple paid plans that the user could opt into like one that is heavy on storage just like real time database or current Firestore plan. The fact that I need to recode everything and move back to the legacy product of real time database is not a happy feeling, all because Firestore is prohibitively expensive for messaging/chat apps. I hope I could encourage Firebase to rethink the pricing modal for Firestore, and if you are a developer, and you are thinking of building high quality apps that would pretty much require lots of document reads and writes, FORGET IT AND GET OUT OF FIRESTORE. Use real time database instead. I would also imagine that you will have more egress in terms of memory in Firestore (though cheaper) since you cannot fetch partial document.

**Comment by samtstern** [comment]
@coolcool1994 thank you for the feedback, it's very interesting to read.  We try to be very transparent with our pricing, we don't want anyone to get a bill that is surprising.  As you may have seen we actually used a chat app as an example for our most complete pricing example:
https://firebase.google.com/docs/firestore/billing-example

It sounds like you've made some architectural choices that increase the cost of running your app on Firestore.  It should be possible to implement a chat app that uses less than 11 document operations per message.  I also see that you're trying to implement typing indicators ("presence") in Firestore but we actually [recommend using RTDB for that](https://firebase.google.com/docs/firestore/solutions/presence).

If you're very price sensitive and unable to change your app's architecture you may want to consider a regional instance of Firestore rather than the default multi-regional instance.  You sacrifice some availability (99.99% not 99.999%) but you can pay ~40% less for reads and writes in some cases (ex: Northern Virginia vs. US Central):
https://cloud.google.com/firestore/pricing
