### ISSUE TITLE
collectionData() returns a single array full of objects rather than a sequenced observable.

### ISSUE THREAD

**Issue by Iskereat** [firebase/firebase-js-sdk#2812]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OSX 10.15.3
  * Browser version: Google Chrome 80.0
  * Firebase SDK version: 7.13
  * Firebase Product: RXFire 3.11

### [REQUIRED] Describe the problem

collectionData() returns a single array full of objects rather than a sequenced observable.

#### Steps to reproduce:

see below

#### Relevant Code:

const tribeNames = collectionData(databaseRef.collection('tribes'), 'id').pipe(tap(x => console.log(x))))

Should return
// {document one}
// {document two}

AFAIK (I may be wrong) the above is how observables should emit values, one at a time.

however it returns
// [{document one}, {document two}]

An array of objects, rather than each object emitted one by one.

**Comment by Feiyang1** [comment]
This method streams snapshots of changes returned by a query. Each snapshot can have multiple documents that have changed. `document one` and `document two` in your case belongs to the same snapshot, that's why you see them together.

Once your collection changes again, you should receive another snapshot with changed documents.
Closing as It is working as designed.
