### ISSUE TITLE
quota exceeded error could be more descriptive

### ISSUE THREAD

**Issue by josh-m-sharpe** [firebase/firebase-js-sdk#2824]
* Operating System version: Android
  * Browser version: Chrome 80.0.3987
  * Firebase SDK version: 7.12.0
  * Firebase Product: auth, firestore - possibly all of firebase

I occasionally see this error, in production, in small quantities: `The project's quota for this operation has been exceeded.`.   It looks like it's Firebase, smells like it's firebase, and matches this firebase error here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/error_auth.js#L420

My sentry.io error report looks like this:

<img width="660" alt="Screen Shot 2020-03-29 at 9 45 37 AM" src="https://user-images.githubusercontent.com/39473/77850670-19389280-71a2-11ea-9b7a-4039e61bd096.png">
<img width="644" alt="Screen Shot 2020-03-29 at 9 45 43 AM" src="https://user-images.githubusercontent.com/39473/77850671-19389280-71a2-11ea-874f-fd9578bdccaf.png">

This error is not very clear.  The error is an `Error` not a `FirebaseError`.  The message doesn't mention firebase, the firebase product or the quota in question. As such, it leaves me with minimal recourse to identify the issue and correct it.

It would be better if the error had additional information:

1) Make it a FirebaseError
2) Identify the product/api call that triggered the error
3) Identify the quota that is in violation

**Comment by cajones314** [comment]
We started getting this error recently as well.  I have checked all of our Google Quota's and could not find one that was exceeded.  Would be great if we could get details as to which quota is being exceeded.

**Comment by scottcrossen** [comment]
This looks like an error from the backend related to phone auth to me. Can you verify what type of auth you are trying to do so that we can make this a better experience? In truth we are already doing something that should help with displaying this better.

https://github.com/firebase/firebase-js-sdk/blob/575b3fe82d75697824232be870754c776f3e1107/packages/auth/src/rpchandler.js#L2823

**Comment by josh-m-sharpe** [comment]
@scottcrossen  I've only seen it from production, so it's unclear.  We only use anonymous and email auth though, so it has to be one of those two.

**Comment by cajones314** [comment]
@schmidt-sebastian we use custom auth.  Not sure it is related to email, etc.  In addition, the error is being reported way after login for us, as we are updating firestore records.

**Comment by jwngr** [comment]
To give you another data point: I'm using custom auth and seeing this issue with less than 50 total users who very infrequently sign in.

**Comment by samhorlbeck** [comment]
This seems like a bug, not a feature request. Tracking internally in b/159061125

**Comment by AmandavZ** [comment]
Some of my users are also getting this error. Angular 9 app (@angular/fire@5.4.2, firebase@7.15.1). Email/Password provider only. No FCM messaging.

400 error - securetoken.googleapis.com
code: auth/quota-exceeded
message: this project's quota...

Header response: code 400, message: QUOTA_EXCEEDED status: INVALID_ARGUMENT

**Comment by AoDev** [comment]
I also have this issue (or related) that I tracked with Sentry. 

Per the message, it seems it's related to analytics.
<img width="641" alt="Screenshot 2020-07-06 at 12 40 17" src="https://user-images.githubusercontent.com/1526150/86585048-1958e300-bf86-11ea-88a3-e99a2e4c5397.png">

The real quota problem aside, **it is a big issue for us that this throws an error**. 
This just flight into the face of our users. (they get a crash report due to unhandled error)

* Couldn't this be just a warning in the console?

* How should we handle this error?  
The code is simply

```js
// bootstrap somewhere
const analytics = firebase.analytics()

// in other places
firebase.analytics.logEvent('sign_up', {method: 'upgrade-google.com'})
```

Should we wrap all logEvent in a try catch ?

**Comment by MeghaB** [comment]
Hi @AoDev - this issue relates to the Auth Quota exceeded errors not being descriptive enough - if you could file a separate issue around the analytics quota messages, the team can prioritize/route that bug accordingly!

**Comment by AoDev** [comment]
@MeghaB I can but the issue title is not about auth in particular, and the OP did fill `"Firebase Product: auth, firestore - possibly all of firebase"` in the template so I suggest these to be updated.

**Comment by Benny739** [comment]
> Some of my users are also getting this error. Angular 9 app (@angular/fire@5.4.2, firebase@7.15.1). Email/Password provider only. No FCM messaging.
> 
> 400 error - securetoken.googleapis.com
> code: auth/quota-exceeded
> message: this project's quota...
> 
> Update: In my case it was related to the firebase db listener triggering refresh tokens on every call.

How did you fix this? I'm having the exact same issue atm for a few users.

**Comment by jwngr** [comment]
> How did you fix this? I'm having the exact same issue atm for a few users.

There's been no fix. It happens seemingly randomly and does not provide enough information to actually debug it or create a full bug report. It seems to be thrown asynchronously within the Firebase SDK since I've been unable to actually catch it in any of my calls to the Firebase SDK.

**Comment by tlackemann** [comment]
Hi, pinging here because we are hitting the exact wall and it's throwing errors to our users. I'm unsure what version caused this but it started after we upgraded to 7.x

Reports are exactly what I'm seeing in the Sentry logs above.

Is there something we can do in the immediate? We're getting customer complaints and have very little insight to the problem itself.

**Comment by Benny739** [comment]
Same here, still couldn't figure out what's wrong.

**Comment by rickymerby** [comment]
I have same issue... our client complaint because image doesnt load and we dont know hos to solve it...

**Comment by hsubox76** [comment]
> I also have this issue (or related) that I tracked with Sentry.
> 
> Per the message, it seems it's related to analytics.
> <img alt="Screenshot 2020-07-06 at 12 40 17" width="641" src="https://user-images.githubusercontent.com/1526150/86585048-1958e300-bf86-11ea-88a3-e99a2e4c5397.png">
> 

I just want to be clear, if anyone is referring to this message (screenshotted here), it is not the same as the one in the original post and seems to be unrelated. The one in this screenshot right here happens with Analytics, and seems to be thrown by a browser's native LocalStorage API, not a Firebase server.

There as an issue for it here: https://github.com/firebase/firebase-js-sdk/issues/3398

**Comment by VagnerGon** [comment]
+1

**Comment by patrickk** [comment]
+1, are there any updates/workarounds to this issue? Some of our users are also getting these errors.

**Comment by samhorlbeck** [comment]
Hi folks,

Unfortunately still no updates to this issue. The team is currently working on rewriting the full auth SDK. Going back to the original issue: in this new version all errors will be instances of `FirebaseError` and will be tagged with Auth, which will hopefully aid in debugging.

**Comment by patrickk** [comment]
@samhorlbeck do you know which Firebase version won't show this issue? We rely on the later version for other dependencies. 

Or if you know of any workarounds any insight would be amazing.

**Comment by Wtrapp** [comment]
+1

**Comment by Wtrapp** [comment]
Thanks, @patrickk where does a user update their clock to the latest time? Is that done at the computer or some kind of network level?

**Comment by patrickk** [comment]
> Thanks, @patrickk where does a user update their clock to the latest time? Is that done at the computer or some kind of network level?

Yes for us, it was a user on a windows machine where they didn't have enough privileges to sync their clock. They went into their machine's settings -> clock -> sync time. Ended up having their IT team sync it for the user since their sync button was disabled.

**Comment by AyoAyomide** [comment]
Uncaught Error in snapshot listener: FirebaseError: Quota exceeded
this is the error am getting on my firebase app 
the daily reads limit is about 50,000 and I only use 700 reads all am getting now is this error message

**Comment by samhorlbeck** [comment]
@AyoAyomide that sounds like a Firestore or RTDB quota issue (this thread's issue is about a quota error message in Auth). Regardless, please consider reaching out to Firebase Support so that they can take a look at the details.

https://firebase.google.com/support

**Comment by rozhanroukhosh** [comment]
i am facing the same problem. randomly i get this issue while trying to refresh the user tokenid

**Comment by samhorlbeck** [comment]
Hi everyone, for those of you seeing this issue related to clock time, please update your SDK version to 8.2.1 or later. (See this issue: https://github.com/firebase/firebase-js-sdk/issues/3222 for more info). If you're unsure what's causing Auth quota errors, it may be worth updating just to see if it fixes the issue for you.

**Comment by AyoAyomide** [comment]
> Uncaught Error in snapshot listener: FirebaseError: Quota exceeded
> this is the error am getting on my firebase app
> the daily reads limit is about 50,000 and I only use 700 reads all am getting now is this error message

After weeks of debugging, I discover cloudfirestore reads counter is not actually counting all the reads to see all your read use [google cloud console](https://console.cloud.google.com/appengine/quotadetails) you will see your quota details 
For the **Quota exceeded** error this is because you already exceed your daily 50k read 
--- hint about what might cause this --
1
We store each userID as a document on firestore 
when we open the firebase site and navigate to firestore it loads all users document this count as a read
(we got a lot of users this allow us to exceed the 50k read very fast)
2
Our mobile app dev also used **set state** (flutter) inside the set state they called a document on firestore this caused an infinite loop that results in quota exceed 

A quick workaround was to upgrade to blaze plan, then we debug our code line-by-line to figure this error out

**Comment by dwanderton** [comment]
Just saw this error with a user today. Email Auth. Looking on Google Cloud Platform Metrics Explorer I can't find any Quota Exceeded Errors.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

**Comment by 0xdevalias** [comment]
> > I also have this issue (or related) that I tracked with Sentry.
> > Per the message, it seems it's related to analytics.
> > <img alt="Screenshot 2020-07-06 at 12 40 17" width="641" src="https://user-images.githubusercontent.com/1526150/86585048-1958e300-bf86-11ea-88a3-e99a2e4c5397.png">
> 
> I just want to be clear, if anyone is referring to this message (screenshotted here), it is not the same as the one in the original post and seems to be unrelated. The one in this screenshot right here happens with Analytics, and seems to be thrown by a browser's native LocalStorage API, not a Firebase server.
> 
> There as an issue for it here: #3398

@hsubox76 @josh-m-sharpe @sam-gc (guessing who to tag based on contributor status/etc) Would it be possible to get the title updated to more specifically relate to what this issue is about, and maybe also to edit the original post to direct users to the 'correct issue' if their error relates to firebase analytics/etc. Might save some of the unrelated 'me too' noise here + more quickly direct people to the right place.

**Comment by hsubox76** [comment]
I'm closing this issue as the full rewrite that Sam mentions did occur and was released in Aug 2021.

If you are still experiencing the same issue with the latest version of the Firebase JS SDK, please open a new issue with as much information as you can provide about how you are currently experiencing it. Thank you!
