### ISSUE TITLE
Using withConverter on a document reference does not trigger toFirebase callback on document update

### ISSUE THREAD

**Issue by majuric** [firebase/firebase-js-sdk#2842]
###  Describe your environment

  * Operating System version: macOS Mojave 10.14.6
  * Browser version: Chrome 80.0.3987.149
  * Firebase SDK version: 7.13.1
  * Firebase Product: firestore

### Describe the bug

Using withConverter on a document reference does not trigger toFirebase callback on document update

### Expected behaviour

withConverter 'toFirebase' callback is called on document update.

#### Steps to reproduce:

https://stackblitz.com/edit/firebase-issue-sandbox-rdj443?file=index.html

**Comment by thebrianchen** [comment]
@majuric This is because `CollectionReference.add()` can take in a custom object as a parameter ([link](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#add)), whereas `DocumentReference.update()` does not support custom objects ([link](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#update)). `update()` takes in `UpdateData`, which contains field paths mapped to values. 

I'm going to close this issue, but feel free to reply if you have any more questions!

**Comment by majuric** [comment]
@thebrianchen, thanks for a quick response. Understood. It might be only me but documentation could make this clear, or the sdk might catch that as well and return some warning that using a converter with 'update' is futile basically :) 

Docs are a bit misleading "When you call set(), get(), etc." .. this etc. part implies that there are other uses other than set() and get() .. and update() is basically the last thing remaining :)
