### ISSUE TITLE
npm install firebase @angular/fire --save  | Not working in Angular 7

### ISSUE THREAD

**Issue by BenJohnThird** [firebase/firebase-js-sdk#2902]
npm install firebase @angular/fire --save

I am currently using Angular 7, I tried installing Angular/fire and firebase but I keep seeing errors.

**Comment by hsubox76** [comment]
Since you're trying to install both at the same time, I don't know which one is giving you the errors.  You can try to install them with separate commands and figure out which one is giving you the error.  If it is firebase, please show us the exact errors you are seeing.

If it is AngularFire please file an issue at the angularfire repo: https://github.com/angular/angularfire
