### ISSUE TITLE
Nuxt + Firebase (possible old core-js version)

### ISSUE THREAD

**Issue by Coooi** [firebase/firebase-js-sdk#2968]
### Describe your environment

  * Operating System version: MacOS 10.15.3
  * Browser version: Chrome 80
  * Firebase SDK version: 7.14.1
  * Firebase Product: npm package

### Describe the problem
I'm having issues when adding Firebase to my project.
I've already reported it on nuxt's -> https://github.com/nuxt/nuxt.js/issues/7258
It seems firebase is using an old version of core-js.

#### Steps to reproduce:
I've created a fresh Nuxt sample project to demonstrate the issue.
Clone: https://github.com/Coooi/nuxt-typescript-firebase-issue
`yarn add firebase`
`yarn dev`

**Screenshots**
![image](https://user-images.githubusercontent.com/3846028/80002270-b6e06280-84bf-11ea-99d0-b58bb577da6e.png)

You'll see that the build is broken.
Without Firebase, the project builds just fine.

**Comment by Feiyang1** [comment]
`core-js` is a dependency of Firebase and there is nothing special about it. And you are not using firebase in your code as far as I can tell.

The problem is `nuxt`/`@nuxt/babel-preset-app` is not able to locate the right version of `core-js` when there are multiple versions of `core-js` in `node_modules`, which is a common situation in the npm ecosystem. If anything, it is something `nuxt` should address.

That said, as a workaround, you can install scoped firebase packages to avoid pulling in `core-js`.
so instead of installing with `npm install firebase`, you can install individual SDKs like the following:
```
npm install @firebase/app

// install individual packages, depending on what products you are going to use.
npm intall @firebase/auth
npm install @firebase/firestore
```

**Comment by Coooi** [comment]
@Feiyang1 Thank you! I'll give it a try.
