### ISSUE TITLE
Cloud Firestore (not Realtime) only works under a paid plan with Algolia? 

### ISSUE THREAD

**Issue by andesappal** [firebase/firebase-js-sdk#3104]
https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/tutorials/firebase-algolia/#paid-firebase-plan

"Paid Firebase plan
To link Algolia with Firebase, you need to be on a paid Firebase plan. The Firebase free plan only allows network requests to other Google APIs, therefore it doesn’t allow requests to Algolia."

**Comment by andesappal** [comment]
We are on the initial phase for using Algolia with Firebase. And Algolia is recommended by Firebase. 

Do we have to pay for Firebase for initial testing?

**Comment by andesappal** [comment]
Also, could Firebase provide this documentation in TypeScript, since `firebase deploy` offers TS? https://firebase.google.com/docs/firestore/solutions/search

I could not find documentation in TS, and the JS doc for TS did not work, despite me having translated what was needed into TS.

**Comment by dconeybe** [comment]
Although you *do* need to use a Firebase paid plan, your credit card will not be charged if your traffic falls below the daily free usage limits. This is documented at https://firebase.google.com/pricing and https://firebase.google.com/support/faq#pricing.

As for the request to include TypeScript sample code in https://firebase.google.com/docs/firestore/solutions/search, please make this request by clicking the "Send Feedback" button at the bottom of that page.

For support with using Algolia with TypeScript, try making a request at https://www.algolia.com/support/ to contact the correct people.

I will close this ticket because I believe all questions have been addressed. Feel free to respond if there are outstanding questions though.
