### ISSUE TITLE
FR: Ability to contribute to the Auth module

### ISSUE THREAD

**Issue by barakd** [firebase/firebase-js-sdk#32]
It seems that currently, it is not possible to contribute to the Auth module.
Unless I missed something in my findings, as can be seen at [auth.build.js](https://github.com/firebase/firebase-js-sdk/blob/master/src/auth.build.js).
The whole of Auth module is already checked in in a post build file.
Thus creating PRs to improve this module is impossible at the moment.
The Auth module is one of the greatest features of Firebase and It a shame that the community can't contribute to improve this important piece of Firebase.
My request is simply to allow a way to contribute to the original pre-built file.
Would very appreciate your feedback on this matter, 
Thanks!

**Comment by jshcrowthe** [comment]
Hey @barakd thanks for your interest in contributing to the SDK! We are working on open sourcing the Auth module, so stay tuned to future updates.

cc: @bojeil-google

**Comment by leonardodino** [comment]
any updates on this @bojeil-google? the source code would alleviate some pressure on the support, where documentation is kinda scarce.

---

my use-case is implementing a  `react-native` `js only` solution to the following methods:
`auth.signInWithPhoneNumber/user.reauthenticateWithPhoneNumber/user.linkWithPhoneNumber`
using a WebView, to handle captcha, but it's not clear how to pass an anonymous logged in user from the `react-native` js side to the WebView.

(with the source code, i would navigate my way through it to find a solution instead of cluttering the support channels with more questions)

**Comment by bojeil-google** [comment]
Hey @leonardodino, it's in the works.
By the way, do not use webviews. They are insecure. Google sign-in for example no longer works in an embedded webview. You need to use an SFSafariViewController for iOS or Chrome custom tab for android.
