### ISSUE TITLE
Service installations is not available

### ISSUE THREAD

**Issue by jsakas** [firebase/firebase-js-sdk#3366]
### Describe your environment

  * Operating System version: macOS Mojave 10.14.6 
  * Browser version: Google Chrome Version 83.0.4103.116
  * Firebase SDK version: 7.15.5
  * Firebase Product: analytics

### Describe the problem

Uncaught exception when initializing `firebase.analytics()` in my app.

```
Uncaught Error: Service installations is not available
    at Provider.getImmediate
```

Not sure if this is related, but we recently moved analytics properties to a different project. The link is showing up properly in both Firebase and Google Analytics, and even tried removing and re-linking it.  Also tried with a fresh project (default analytics project ownership) and same issue. 

#### Steps to reproduce:

This happens only when I call `firebase.analytics()` in my app. The config object has a `measurementId` and the config is copied directly from the firebase UI. Below is how we initialize the app

#### Relevant Code:

```javascript
import * as firebase from 'firebase/app';
import 'firebase/firestore';
import 'firebase/storage';
import 'firebase/auth';
import 'firebase/functions';
import 'firebase/analytics';

const app = firebase.initializeApp(CONFIG.firebase);

if (CONFIG.firebase.measurementId) {
  firebase.analytics();                                                 // <-- this line throws
}

```

**Comment by jsakas** [comment]
I was able to resolve this issue by running `yarn upgrade --latest` and upgrading some other packages in the project.

I was already on the latest version of firebase (7.15.5 at the time) and that package was not upgraded by yarn.

Not clear what the issue was but maybe it will help someone.

**Comment by tad3j** [comment]
I wanted to add 'firebase/analytics' to my web project (works on mobile/native one) and I'm experiencing the same issue with `"firebase": "^7.16.0"` (yarn.lock has `"@firebase/analytics@0.3.9"`). I'm also providing the whole config (including `measurementId` value) to `initializeApp()` but I'm still getting exception bellow:
```
Error: Service installations is not available
▶ 7 stack frames were collapsed.
Module.<anonymous>
C:/Users/User/WebstormProjects/project/packages/web/src/services/firebase/index.js:16
  13 | export const db = firebase.firestore()
  14 | export const auth = firebase.auth()
  15 | export const functions = firebase.functions()
> 16 | export const analytics = firebase.analytics()
```

Above happens in my firebase service:

```
import firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/firestore'
import 'firebase/functions'
import 'firebase/analytics'
import config from '../../config'

//firebase app init
firebase.initializeApp(config.firebase)

// exports
export default firebase
export const db = firebase.firestore()
export const auth = firebase.auth()
export const functions = firebase.functions()
export const analytics = firebase.analytics()  //  <-------------- FAILING LINE

if (window.location.hostname === 'localhost') {
  //FUNCTIONS emulator
  functions.useFunctionsEmulator('http://localhost:5001')

  //FIRESTORE emulator
  db.settings({
    host: 'localhost:8080',
    ssl: false,
    experimentalForceLongPolling: true,
  })
}

```

And the config for `firebase.initializeApp` (all of the environment variables are provided to "react-native start" command):
```
const config = {
  firebase: {
    apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
    authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
    databaseURL: process.env.REACT_APP_FIREBASE_DATABASE_URL,
    projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
    storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.REACT_APP_FIREBASE_APP_ID,
    measurementId: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
  }
}
```

I think my usage of analytics module is correct  and all of the other firebase modules were fully functional before adding code for analytics so I was wondering if this might be an issue with the module?

**Comment by Feiyang1** [comment]
@tad3j Can you remove `node_modules`, `yarn.lock` and do a clean installation, and see if the problem goes away?

**Comment by tad3j** [comment]
@Feiyang1, sorry for late response, I only got to test this today and even with removing `node_modules` and `yarn.lock` + running `yarn install` after, I get the same error, `Service installations is not available`.

Here is a bit more detailed screenshot of the exception:
![image](https://user-images.githubusercontent.com/4150904/87993032-d6e8e780-cae9-11ea-9c01-cd3b23531442.png)

**Comment by hsubox76** [comment]
I'm not able to reproduce this, but in the past this usually happens when a repo has multiple versions of firebase, which usually happens when you have another dependency that also depends on firebase, and requests a conflicting version. Can you provide a minimal reproduction (a complete repo with the minimum code necessary that reproduces this problem when cloned and installed)? At the very least, would like to see your `package.json` dependencies.

**Comment by tad3j** [comment]
@hsubox76, will do my best to isolate the issue, but may not be easy because my setup is a bit complex. I'm using firebase in a monorepo (managed by lerna) with 4 packages (each having it's own package.json): 
- react web app (uses this library, `firebase-js-sdk`), 
- react native app (uses [react-native-firebase](https://github.com/invertase/react-native-firebase)) 
- firebase aka. backend ([firebase-admin](https://github.com/firebase/firebase-admin-node) + [firebase-functions](https://github.com/firebase/firebase-functions))
- shared (constants mostly for re-use in other module, almost no dependencies)

All of the 4 packages dependencies get installed into the root `node_modules` so my project only uses 1 version of each dependency. 
![image](https://user-images.githubusercontent.com/4150904/88107340-39ec8400-cba7-11ea-95ee-928d039e352b.png)

I was thinking, could any dependency mentioned above be conflicting with`firebase-js-sdk` in this setup? `

My project is in a private repo, but if you still need package.json files (there are actually 5, 1 in root + 4 packages I described above) let me know and I will publish them somewhere.

Btw, any chance you could share the issues from the past, maybe I can find traces there?

**Comment by hsubox76** [comment]
firebase-admin has a dependency on some Firebase packages which has previously caused problems when firebase and firebase-admin share the same node_modules folder and have conflicting versions. See https://github.com/firebase/firebase-admin-node/issues/714 (This is not the same issue, this describes another issue caused by a version conflict between firebase JS SDK and firebase-admin.) firebase-functions has a dependency on firebase-admin.

The quickest way to make sure is probably to uninstall the firebase-admin and firebase-functions deps, remove yarn.lock, remove node_modules, reinstall, and just start up your client app, which hopefully doesn't require those libraries just to start up.

If it's another dependency, you can check the package.json of any dependency you suspect and just see if it includes firebase, and what version.

**Comment by tad3j** [comment]
Removing `firebase-admin`, `firebase-functions` didn't help, but I also had `@firebase/testing` and `firebase-functions-test` (forgot to mention last 2 before) and seems like one of them was causing the issue....removing both + a clean yarn install made the error go away. Then I've started adding back one by one and made sure I'm using the latest version and everything seems to work fine now. Sorry for false positive and thank your for pointing me into the right direction.

**Comment by hsubox76** [comment]
Great, glad it helped.
