### ISSUE TITLE
FR: Allow setting gtag.js config configurations in firebase.analytics() constructor to allow cross-domain setup

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-js-sdk#3377]
### Describe your environment

  * Operating System version: n/a
  * Browser version: n/a
  * Firebase SDK version: 7.15.5
  * Firebase Product: auth

### Describe the problem
Currently, a cross-domain setup (website on www.example.com, WebApp on app.example.com) with Firebase JS SDK does not seem to be possible in a way that users keep one session even if moving over to the other domain.

In gtag.js, there is the option to set `linker` options as described here: https://developers.google.com/analytics/devguides/collection/gtagjs/cross-domain

This allows to treat separate (sub-)domains as one in terms of keeping the session for one user (including its source, campaign etc. information).

#### Steps to reproduce:
* Have two or more domains: www.example.com, app.example.com
* Use the same Firebase JS SDK config for both
* Navigate from one page via a regular link to the other one
=> The user's session is killed when moving to the second domain. The second page (app.*) has the first one (www.*) as referrer even if the session started on `www.*` had an explicit source/medium set with custom campaign information (`www.example.com?utm_source=....&...`).
This unfortunately also breaks Google Ad campaign information so it is not possible to attribute Firebase conversions made on `app.*` correctly back to the Google Ad that initiated the user visit.
And there is currently no workaround as far as I know.

#### Proposal
My **proposal** is now to give the possibility to set the `linker` option in the `firebase.analytics()` constructor to be able to setup this linker behavior in gtag also when using it via firebase:

```
    firebase.analytics({
        'linker': {
            'domains': ['example.com', 'www.example.com', 'app.example.com']
        }
    }
```

When using this, it should hopefully work to track cross-domains with Firebase JS SDK.

**Comment by hsubox76** [comment]
I did some investigating using gtag.js only, to understand `linker` behavior and it seems to be the case that while it does work as described for GA Web properties (ones with IDs that begin with "UA-"), it doesn't work for GA App+Web properties (ones with IDs that begin with "G-"). Unfortunately GA properties linked to Firebase projects are App+Web, so I don't think this would work even if we added the linker code to the SDK.

I suspect this is because it requires a referral exclusion list (mentioned in the "Note" on the [gtag cross-domain measurement docs](https://developers.google.com/analytics/devguides/collection/gtagjs/cross-domain), which links to the [referral exclusion docs](https://support.google.com/analytics/answer/2795830)) and while I did find this setting for Web properties (and it seemed to be already pre-populated with my domain name), I didn't find a similar option for App+Web properties.

I'm not sure if the GA team is planning to add this option to App+Web properties or if developers are supposed to achieve the same functionality another way, I can check with them.

**Comment by sceee** [comment]
@hsubox76 Hi Christina, thanks for your update. Would be great if you could check with the GA team if they know a possibility to achieve this.

**Comment by amardeepsingh20** [comment]
https://github.com/firebase/firebase-js-sdk/issues/3971#issuecomment-828331735

**Comment by hsubox76** [comment]
This functionality is now available in the modularized SDK, which is in beta.

See docs: https://firebase.google.com/docs/reference/js/v9/analytics.md#initializeanalytics

Setting a linker would look something like:
```
const analytics = initializeAnalytics(app, { config: { linker: ... } });
```
