### ISSUE TITLE
Uncaught errors being thrown by analytics due to quota errors

### ISSUE THREAD

**Issue by AoDev** [firebase/firebase-js-sdk#3398]
### [REQUIRED] Describe your environment

  * Operating System version: any
  * Browser version: any
  * Firebase SDK version: 7.15.1
  * Firebase Product: Analytics

### [REQUIRED] Describe the problem
I have this issue that I tracked with Sentry. 

Per the message, it seems it's related to analytics.
<img width="641" alt="Screenshot 2020-07-06 at 12 40 17" src="https://user-images.githubusercontent.com/1526150/86585048-1958e300-bf86-11ea-88a3-e99a2e4c5397.png">

The real quota problem aside, **it is a big issue for us that this throws an error**. 
This just flies into the face of our users. (they get a crash report due to unhandled error)

* Couldn't this be just a warning in the console?

* How should we handle this error?  
The code is simply

```js
// bootstrap somewhere
const analytics = firebase.analytics()

// in other places
logEvent('sign_up', {method: 'upgrade-google.com'})
```

Should we wrap all logEvent in a try catch ?

#### OS

Android 7.1.2
Android 8.1.0
Android 6.0.1
Android 9
Windows 7
Android 7.0
Android 5.1.1
Android 8.0.0
Windows 10
Android 6.0

#### Devices

XiaoMi Redmi 4A
XiaoMi Redmi 4X
XiaoMi Redmi Note 5A
XiaoMi Redmi 5A
XiaoMi Redmi 5
Samsung SM-G532G
Asus Z00ED
XiaoMi Redmi Note 4
M5
XiaoMi Redmi 3S

#### Browsers

Chrome Mobile
Chrome
Chrome Mobile WebView
Facebook
MiuiBrowser
Opera Mobile
Samsung Internet
Opera
Yandex Browser
Safari

**Comment by hsubox76** [comment]
The only places in Firebase Analytics that pass through raw errors are on Gtag calls, which seems to indicate an error is happening in Gtag code. Looking around, the QuotaExceededError seems to be a common error thrown by browsers when writing to localStorage in environments that don't permit it, and Gtag does some local writes though I thought only to cookies.

Since the Brave browser blocks a lot of permissions, such as cookies, it's possible this is what's happening.

I don't think a try/catch would work because I believe that's a console.error() and not a thrown error.

To prevent users from seeing the message, you can use `firebase.setLogLevel()` to set it to "silent": https://firebase.google.com/docs/reference/js/firebase#setloglevel

If you still want to send the error message to yourself or somewhere else, you can use `firebase.onLog()` to add a custom handler.

Finally, we're working on an `isSupported()` method for analytics that does some runtime environment checks to see if Firebase analytics is supported in the current environment, and this can be used as a conditional to prevent initialization of `firebase.analytics()`. I'm not 100% sure what the environment mismatch (if it is one) is in this specific case but if it's something we're not catching in the check, we can add it.

**Comment by AoDev** [comment]
@hsubox76 

This issue is not just for Brave. Sorry my mistake in the template (I copied this from another issue).
I'll edit the first post.

> I don't think a try/catch would work because I believe that's a console.error() and not a thrown error.

It can not be a `console.error`. `console.error()` wouldn't be picked by Sentry or a window `"error" event listener`.

**Comment by hsubox76** [comment]
I was confused because the screenshot says "console" and "logger: console" and I'm not familiar with Sentry. Also, the `@firebase/analytics` prefix is appended by a logger utility function in the Firebase codebase that I believe only calls `console.error()` and does not throw. If there is a separate uncaught error at the same time, it could be something happening asynchronously in `Gtag` code, do you see any other logged messages that happen the same time?

Can you reproduce this locally in one of those environments reported by Sentry? Does try/catch work?

**Comment by AoDev** [comment]
@hsubox76 

These errors have been reported by some of our users and I could find them in Sentry.

* We had around 222000 active users in the past 28 days.
* Sentry reported this issue 7400 times for 1800 users.
* First occurrence was 2 months ago, last occurrence was 2 hours ago.

I personally haven't seen this error and I don't know where the quota limit is. 
There is no "Red alert" message in Firebase/analytics console or in analytics.google.com.

I haven't tried to try/catch all events so far. We would need to include it in our next release.

**Comment by hsubox76** [comment]
I'll try to keep looking for the root cause, but I think it happens in the Gtag code, which is a separate codebase managed by another team, and may take some time.

In the meantime, to help with your immediate problem:

If it is only logging an error with `console.error` which it looks like(?), it can be suppressed using `firebase.setLogLevel()` https://firebase.google.com/docs/reference/js/firebase#setloglevel which will suppress all Firebase error logs.

If it is throwing, it won't prevent that, and would have to be caught with a try/catch.

If it's possible, do you physically (or virtually) have one of those environments (OS/Device/Browser combo) that Sentry reports this error for, so you can reproduce the error locally? That would probably be ideal for better diagnosing the exact problem, such as pinpointing whether there's a thrown error, a logged error, or both, and if both, whether they're the same.

**Comment by AoDev** [comment]
@hsubox76 Thanks for your time. I'll set the logLevel to `silent` and see if there is a change.

**Comment by AoDev** [comment]
@hsubox76 Just for info, setting the log level to `silent` did not change the situation.

Regarding the quota issue itself though, when does it actually happen? Is there any place in Firebase / Google Analytics where I can have more info about it? or is it a client side issue?

**Comment by hsubox76** [comment]
As mentioned in the initial reply, the logged error seems to be a native DOM error (the text "QuotaExceededError" isn't in our codebase) that occurs when the browser's local storage either does not permit writes, or when writes exceed the quota for that browser.

As far as I know, our analytics wrapper does not write to local storage. To be clear, Firebase Analytics JS SDK is a wrapper around [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs). It's possible that gtag writes to local storage, and I'd have to talk to that team to find out more.

Analytics also relies on an internal dependency @firebase/installations, which does write to the browser's indexedDB. However if that doesn't exist or isn't accessible, the error usually happens on initialization of analytics (`firebase.analytics()`). We recently added a new API, [`firebase.analytics.isSupported()`](https://firebase.google.com/docs/reference/js/firebase.analytics#issupported) that can be used to check before initialization if the environment has cookies and indexedDB support. But I haven't seen any of those unsupported environments cause that specific error.

**Comment by AoDev** [comment]
@hsubox76 Cool. I'll try `firebase.analytics.isSupported()`

**Comment by 00111000** [comment]
Hi, just to clarify, we are supposed to do something like..

```
firebase.analytics.isSupported()
.then(() => firebase.analytics());
```

**Comment by 0xdevalias** [comment]
FYI, while it's not about firebase analytics (it's firebase performance in this case), there is a similar old issue about this that I stumbled across via google:

- https://github.com/firebase/firebase-js-sdk/issues/2522

**Comment by AoDev** [comment]
3 years later... don't ask me for more info lol
