### ISSUE TITLE
FR: Make snapshots only read changed documents from server (currently reads all docs including cached)

### ISSUE THREAD

**Issue by zaptrem** [firebase/firebase-js-sdk#3422]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.15.5
  * Browser version: React Native
  * Firebase SDK version: N/A
  * Firebase Product: Firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

When subscribing to collection snapshots, users are charged a read for every document returned (as the snapshot system goes straight to the cloud given the chance), even if the document hasn't changed since it was last updated on the local cache. Instead, the snapshot system should read from the local cache, then query only for documents that have changed since the last time the cache was updated. This way, if a user makes no changes and restarts the app we would be charged 0 reads instead of 15 (if the user is viewing 15 documents). See my POC below:

#### Steps to reproduce:

I used the current API to build this into a React Native component. However, it's not elegant and likely filled with edge cases. 

```
import React, { Component } from "react";
import firebase from '@react-native-firebase/app';

export default class RecordingList extends Component {

  constructor(props) {
    super(props);
    // this.props.recordingPath leads to recording document
    let uid = firebase.auth().currentUser.uid;

    recordingsRef = firebase
      .firestore()
      .collection("users")
      .doc(uid)
      .collection("recordings")
    // Don't call this.setState() here! 
    this.state = {
      limit: 15,
      liveRecordings: [],
      oldRecordings: [],
      recordings: [],
      currentUser: firebase.auth().currentUser,
      recordingsPath: recordingsRef,
      activeSections: []

    }
    recordingsRef
      .orderBy('lastModified', 'desc')
      .limit(1)
      .get({source: "cache"})
      .then(async (CollectionSnapshot) => {
        try{
          this.setState({
            lastUpdated: CollectionSnapshot.docs[0].data().lastModified}, 
            () => this.registerUpdateListener());
        }catch(e){
          this.setState({
            lastUpdated: 0
          }, () => this.registerUpdateListener())
        }
      });
    
    
  }
  
  async registerUpdateListener(){
    if(this.firestoreUnsubscribe) await this.firestoreUnsubscribe();
    this.firestoreUnsubscribe =
    recordingsRef
        .where('lastModified',  '>', this.state.lastUpdated)
        .onSnapshot(this.onResult.bind(this), this.onError.bind(this));
  }

  onResult(CollectionSnapshot) {
    console.log('Got live recordings snapshot');
    this.refreshRecordings();

    let lastDoc;
    
  }

  onError(error) {
    console.error(error);
  }

  async refreshRecordings(){
    this.state.recordingsPath
      .orderBy('date', 'desc')
      .limit(this.state.limit)
      .get({source: "cache"})
      .then(async (CollectionSnapshot) => {
        let lastUpdated = 0;
        const recordings = CollectionSnapshot.docs.map(doc => {
          const firebaseData = doc.data();
          firebaseData.id = doc.id;
          if(firebaseData.lastModified) lastUpdated = firebaseData.lastModified;
          //console.log("recording: ");
          //console.log(firebaseData);
          return firebaseData;
        });

        this.setState({
          recordings: recordings,
          lastUpdated: lastUpdated
        })
        
      });
  }

  async onLoadEarlier() {
    this.setState({
      limit: this.state.limit + 15
    }, () => this.refreshRecordings())
  }


  componentDidMount() {}

  componentWillUnmount() {
    console.log("LIST UNMOUNTING");
    this.listener1.remove();
    this.listener2.remove();
    this.listener3.remove();
    if(this.firestoreUnsubscribe) this.firestoreUnsubscribe();
  }

  render() {}
}
```

**Comment by wilhuff** [comment]
Firestore already only queries for changed documents, using a mechanism known as a _resume token_. Results from the server include this token which can be used to resume the query at a later time. This implicitly asks for changes since the last query.

However, after 30 minutes, the server stops tracking changes to the query on behalf of the client (to conserve resources, see a [previous mailing-list discussion for more details](https://groups.google.com/g/google-cloud-firestore-discuss/c/A7vMrtmV4U8/m/0zhwBOOoBgAJ)). When a client resumes after this point, the server has to re-run the whole query to see what changed.

The problem with just querying for a last-modified timestamp is that you won't see any document deletions. While this may work in your case, this doesn't work in the general case so we can't directly use this strategy. A secondary problem is that creating an index on such a timestamp necessarily limits throughput to the collection to about 500 writes/second. Again, this may work in your case (perhaps because you've segregated the data in a way that isolates it), but doesn't work in the general case.

We have discussed the possibility of creating a special kind of incremental sync index that would keep a time-limited window of document deletions that would make this kind of thing easier to implement, but due to other commitments, we haven't been able to prioritize this work.

For now, if this kind of solution is working for you, then feel free to use it, but unfortunately, we can't adopt it in the SDKs.

**Comment by zaptrem** [comment]
@wilhuff One of the emails contains this:
```
If you really want to pre-synchronize a data set there is a way to do it that avoids the cost. It works like this:
In each document you write, include an update_time field with a server timestamp value
When you want to synchronize, first run the query with the CACHE source to determine the maximum update_time you already have
Then run the query with source SERVER with a constraint on update_time >= the update time you found
This is essentially a manual implementation of a feature we're working on.
```

What was that feature? was it ever released?

Re: Deletion syncing issue.
Wouldn't it be possible to store a list of deleted documents with each collection and send the updates to that list when sending the other update info?

**Comment by wilhuff** [comment]
The "working on" in that email thread was discussion and initial design of the incremental sync index I described, but like I said here, due to other commitments we haven't been able to prioritize additional work on it.

Storing deletions in a single document is even worse for the general case: we'd be limited to 1 MB worth of document keys or IDs and throughput would be limited to ~1 deletion per second due to contention on that document. There are workarounds for this that involve multiple documents full of deletions, but ultimately these all cause problems for high throughput applications for which we also have to design.
