### ISSUE TITLE
Multi factor auth support in different countries

### ISSUE THREAD

**Issue by jamesbenns** [firebase/firebase-js-sdk#3538]
### [REQUIRED] Describe your environment

  * Firebase Product: auth

#### Steps to reproduce:

Try enrolling/verifying SMS second factor for a number from Guernsey

I understand MFA is in beta, but SMS messages aren't being delivered to some mobile numbers from Guernsey (and elsewhere I imagine), despite it being in a list of supported countries for phone auth. The same implementation is working well with a UK number.

**Comment by malcolmdeck** [comment]
Hey there, Malcolm from Firebase here! 

For this kind of issue, we recommend opening a ticket with [Firebase support](https://firebase.google.com/support) so that we can ask more detailed information about the failure you're seeing without exposing your PII across the internet :) 

I hope that helps!
~Malcolm
