### ISSUE TITLE
signing in with apple overwrites existing users

### ISSUE THREAD

**Issue by 59inu** [firebase/firebase-js-sdk#3712]
### [REQUIRED] Describe your environment

  * Firebase SDK version: ^7.19.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

when users who has signed up with email and password try signing in with apple with same email,
it overwrites existing users and replace auth provider with apple, not adding 'apple' to existing providers

and not as in swift, can't not edit scopes in apple login.
so, couldn't find a way to avoid this user overwriting.
is there a reason to forbid scope-specific permissions in WEB unlike IOS SDK?

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by rosalyntan** [comment]
Thanks for filing this issue! This is actually working as intended -- because Sign in with Apple is a verified provider, the previous unverified login is unlinked to prevent malicious users (who don't own the email) from gaining access to the account. However, if the email is verified, then the accounts will instead be linked upon signing in with another verified provider (i.e. Sign in with Apple).

So in order to prevent the account from being overwritten, the user should go through email verification for their email/password account.
