### ISSUE TITLE
ERROR TypeError: Object(...)(...).firestore is not a function

### ISSUE THREAD

**Issue by manel00** [firebase/firebase-js-sdk#3743]
```
main.459c2903aa8293371012.js:1 ERROR TypeError: Object(...)(...).firestore is not a function
    at main.459c2903aa8293371012.js:1
    at e.invoke (polyfills.6a757adabc27cc17898f.js:1)
    at t.run (polyfills.6a757adabc27cc17898f.js:1)
    at t.runOutsideAngular (main.459c2903aa8293371012.js:1)
    at new t (main.459c2903aa8293371012.js:1)
    at main.459c2903aa8293371012.js:1
    at ao (main.459c2903aa8293371012.js:1)
    at so (main.459c2903aa8293371012.js:1)
    at t.get (main.459c2903aa8293371012.js:1)
    at so (main.459c2903aa8293371012.js:1)
Se @ main.459c2903aa8293371012.js:1
main.459c2903aa8293371012.js:1 ERROR Error: Uncaught (in promise): TypeError: Object(...)(...).firestore is not a function
TypeError: Object(...)(...).firestore is not a function
    at main.459c2903aa8293371012.js:1
    at e.invoke (polyfills.6a757adabc27cc17898f.js:1)
    at t.run (polyfills.6a757adabc27cc17898f.js:1)
    at t.runOutsideAngular (main.459c2903aa8293371012.js:1)
    at new t (main.459c2903aa8293371012.js:1)
    at main.459c2903aa8293371012.js:1
    at ao (main.459c2903aa8293371012.js:1)
    at so (main.459c2903aa8293371012.js:1)
    at t.get (main.459c2903aa8293371012.js:1)
    at so (main.459c2903aa8293371012.js:1)
    at P (polyfills.6a757adabc27cc17898f.js:1)
    at P (polyfills.6a757adabc27cc17898f.js:1)
    at polyfills.6a757adabc27cc17898f.js:1
    at e.invokeTask (polyfills.6a757adabc27cc17898f.js:1)
    at Object.onInvokeTask (main.459c2903aa8293371012.js:1)
    at e.invokeTask (polyfills.6a757adabc27cc17898f.js:1)
    at t.runTask (polyfills.6a757adabc27cc17898f.js:1)
    at g (polyfills.6a757adabc27cc17898f.js:1)
```

### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04
  * Browser version: Google chrome

Ionic info:

Ionic:

   Ionic CLI                     : 6.11.7 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 16 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (~/Android/Sdk)
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : Linux 4.13

App stuck when creating a PWA using Ionic 4 because of the error from Above

#### Steps to reproduce:

Build PWA app with angular/pwa

#### Relevant Code:
```javascript
const functions = require('firebase-functions')
const cors = require('cors')({ origin: true });

exports.notificationNewXstory = functions.https.onRequest((request, response) => {
    return cors(request, response, () => {
        functions.firestore
            .document('app/{{mydocument}}')
            .onCreate((snap, context) => {
                response.setHeader('Access-Control-Allow-Origin', '*');
                const data = snap.data();
                //console.log(data)
                const name = data.name.val()
                const title = data.title.val()
                const message = `${name} uploaded ${title}, this one looks interesting :P`
                response.send(message);
            });
    });
});```

**Comment by hsubox76** [comment]
I'm not sure what the architecture of your app is because I was under the impression PWAs are client side apps, while `firebase-functions` is a library for writing functions that run in the cloud. Additionally, functions.firestore.document().onCreate() is a top level function, like functions.http.onRequest, and not a command to nest in a response.

Functions should generally not be part of a client side bundle but deployed to the cloud using the CLI. More about Functions: https://firebase.google.com/docs/functions/get-started . If you need more help with functions usage I would suggest asking on Stack Overflow or looking around for examples.

If you have a special use case I'm not understanding, please let me know. Also, if you're definitely intending to use the Functions library here and not the JS SDK, and you're still having trouble with it, you probably want to file an issue in the firebase-functions repo: https://github.com/firebase/firebase-functions#readme
