### ISSUE TITLE
firebase/database/dist/index.esm.js is not a valid esm due to bare imports

### ISSUE THREAD

**Issue by backspaces** [firebase/firebase-js-sdk#3840]
### [REQUIRED] Describe your environment

  * Operating System version: mac os x 10.14.6
  * Browser version: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
  * Firebase SDK version: 7.21.0
  * Firebase Product: database

### [REQUIRED] Describe the problem
I need an esm for firebase-database. I could not find one on your cdn or on others.
I installed locally: yarn add firebase
I found the database esm and attempted to use it:

>    import * as FB from './node_modules/@firebase/database/dist/index.esm.js'

It resulted in the expected bare import error:

> Uncaught TypeError: Failed to resolve module specifier "@firebase/app". Relative references must start with either "/", "./", or "../".

#### Steps to reproduce:

Run the attached html.

NOTE: I did find a Rollup that eventually worked. Here's the segment I needed:

```
{other imports not related to this}
import { nodeResolve } from '@rollup/plugin-node-resolve'
export default [
    {
        input: 'node_modules/@firebase/database/dist/index.esm.js',
        output: {
            file: 'vendor/firebase.js',
            format: 'esm',
        },
        plugins: [nodeResolve()],
    },
    {lots more}
]

```

This Issue can be looked at in multiple ways:
- Simply have a CDN provide esm's for firebase projects
- Fix the npm repo to have working esm's for each project
- Documentation. The simplest solution is Rollup. Not Webpack, too complex

Love the product, btw!

#### Relevant Code:

```
<head></head>
<body>
  <script type="module">
    import * as FB from './node_modules/@firebase/database/dist/index.esm.js'
  </script>
</body>
</html>
```

Note that replacing that import with:
>    import * as FB from './vendor/firebase.js'

..works correctly

**Comment by Feiyang1** [comment]
It is expected that npm packages can't run in browser directly. You'd need to use some tool to either bundle them or covert the bare imports to urls/paths.

Besides bundling, you have a few options:
There are CDN networks that support importing npm packages in browser directly, such as `unpkg.com` and `https://www.skypack.dev/`. It could be a good option if you don't want any build process.

Also take a look at snowpack especially this [section](https://www.snowpack.dev/#using-npm-dependencies). It builds your npm dependencies separately into a single file where bare imports are converted to relative paths. 

I'm closing the issue now since it is not an issue with the SDK or its npm distribution.
