### ISSUE TITLE
FR : serverTimestamps option for onSnapshot

### ISSUE THREAD

**Issue by Pitouli** [firebase/firebase-js-sdk#3848]
Let's say you have a listener that is listening for all the messages received after the current time.

You will have something like `firestore().collection(`messages`).where('date', '>', new Date()).onSnapshot(...)`

And when you post a message, you will have something like `firestore().collection(`messages`).add({ message: "...", date: firestore.fieldValue.serverTimestamp()})`

This works well when you are online. 
But if you are offline, you do not receive your own messages.

I believe it's because the `date` is `null` since the message has not been synced yet with the server, and therefore is not `>` to the initial `new Date()`.

**Would it be possible to add a `serverTimestamps` option to the onSnapshot, with `"estimate" | "previous" | "none"` values?** 

Currently, the only solution I can imagine is to have a second listener that specifically listen to documents where date is `null`, and use `doc.data({ serverTimestamps: "estimate" })` to check if the document should be kept or not. 

It's doable of course, but it means to maintain 2 listeners, one of which is useful only when offline, plus checking the estimated date of each message (since it could be an "old" message from a previous offline usage that have not synced yet). And there would be probably some duplicates between the two listeners: the message would trigger the "null" one first,  then trigger the "normal" one once it has been synced and received a date...

Edit: in fact, the realistic solution is to use `new Date()` instead of `firestore.fieldValue.serverTimestamp()`, but it as some drawbacks, especially if the user computer is not at the correct hour :p (And it has security issues since you cannot reliably control the time)

**Comment by schmidt-sebastian** [comment]
@Pitouli Thanks for filing. This is indeed an interesting request, but at this point I am not (yet) convinced that we should expand our API to address this specific case. We can certainly look at this if we get more feedback.

You can already use the `orderBy` API for the specific case you mentioned. This would look as such:

```
firestore().collection('messages').orderBy('date').startAfter(new Date())
```

This should return all documents with newer timestamps than `new Date()` as well as all unresolved ServerTimestamps, since they sort higher than any timestamp values.
