### ISSUE TITLE
Firebase functions @0.5.1 dependency on global `fetch` (needs an import or polyfill)

### ISSUE THREAD

**Issue by brianmhunt** [firebase/firebase-js-sdk#3941]
### [REQUIRED] Describe your environment

  * Operating System version: _____Linux
  * Browser version: _____n/a
  * Firebase SDK version: _____firebase@7.18.0:
  * Firebase Product: _____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

In `firebase/functions/dist/index.cjs.js`

> 658 registerFunctions(firebase__default['default'], fetch.bind(self));^M

references a bald `fetch` global, but that needs a polyfill on the command-line.

I see the dependency for `node-fetch` was recently added, i.e. a yarn.lock diff shows:

```patch
-"@firebase/functions@0.4.51":
-  version "0.4.51"
-  resolved "https://registry.yarnpkg.com/@firebase/functions/-/functions-0.4.51.tgz#97be571cfe3b9ee3bf289b9dc5194e3ae49a4819"
-  integrity sha512-PPx8eZcr4eoU9BITOUGUVurs4WZu8Thj3uCWx766dU3mV1W/7kRgtiptmW0XJUB18FZ1PT3+Hadd6V6vjtLgYw==
+"@firebase/functions@0.5.1":
+  version "0.5.1"
+  resolved "https://registry.yarnpkg.com/@firebase/functions/-/functions-0.5.1.tgz#fa0568bdcdf7dfa7e5f4f66c1e06e376dc7e25b6"
+  integrity sha512-yyjPZXXvzFPjkGRSqFVS5Hc2Y7Y48GyyMH+M3i7hLGe69r/59w6wzgXKqTiSYmyE1pxfjxU4a1YqBDHNkQkrYQ==
   dependencies:
     "@firebase/component" "0.1.19"
     "@firebase/functions-types" "0.3.17"
     "@firebase/messaging-types" "0.5.0"
-    isomorphic-fetch "2.2.1"
+    node-fetch "2.6.1"
     tslib "^1.11.1"
```

### Steps to reproduce:

Import `@firebase/functions` without having a defined `fetch` polyfill.

### Workaround

Define the `globalThis` or `global` variable `fetch = require('node-fetch')`.

### Possible fixes

Import `fetch` from `node-fetch` in the node environment.

### Impact

I suspect this breaks some existing CI environments (including ours), in rather non-obvious ways.

**Comment by brianmhunt** [comment]
Thanks @hsubox76 , that's helpful.

The issue is occurring via webpack->babel-typescript bundling, which _did_ work prior to the upgrade / version change.

We're importing it with:

```
import * as firebase from "firebase/app"
import "firebase/auth"
import "firebase/firestore"
import "firebase/functions"
import "firebase/storage"
```

and a fairly vanilla webpack configuration.

I hope that helps diagnose.

**Comment by hsubox76** [comment]
Is this a Node-only application? If so, can you set Webpack to prioritize `main` in `resolve.mainFields`?

https://webpack.js.org/configuration/resolve/#resolvemainfields

This will get you the Node-specific bundle from all packages that have one available.

My only guess for why it would work before and not now is if you have something else that polyfills fetch on the global object, either a directly installed package, or something that comes in with another package you have, and that the polyfill is created after Firebase initialization but before the httpsCallable call. Because in the latest change the first reference of global fetch has been moved from during httpsCallable to during initialization.

If it doesn't work, can you show the exact error you are seeing?  And when/how are you calling httpsCallable and was it definitely working before?

**Comment by brianmhunt** [comment]
Thanks @hsubox76 .  We get this when running e.g. jest, and it looks like this:

```
    ReferenceError: fetch is not defined

      54 | /******/     // mode & 4: return value when already ns object
      55 | /******/     // mode & 8|1: behave like require
    > 56 | /******/     __webpack_require__.t = function(value, mode) {
         |                        ^
      57 | /******/             if(mode & 1) value = __webpack_require__(value);
      58 | /******/             if(mode & 8) return value;
      59 | /******/             if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;

      at eval (webpack-internal:/node_modules/@firebase/functions/dist/index.cjs.js:658:49)
      at Object../node_modules/@firebase/functions/dist/index.cjs.js (services/app/build/libs.js:1033:5)
      at __webpack_require__ (services/app/build/libs.js:56:23)
      at eval (webpack-internal:/node_modules/firebase/functions/dist/index.esm.js:2:77)
      at Module../node_modules/firebase/functions/dist/index.esm.js (services/app/build/libs.js:2181:5)
      at __webpack_require__ (services/app/build/libs.js:56:23)
      at eval (webpack-internal:/services/app/src/lib-globals.ts:15:76)
      at Module../services/app/src/lib-globals.ts (services/app/build/libs.js:2831:5)
      at __webpack_require__ (services/app/build/libs.js:56:23)
      at eval (webpack-internal:/services/app/src/libs.ts:3:70)
      at Module../services/app/src/libs.ts (services/app/build/libs.js:2847:5)
      at __webpack_require__ (services/app/build/libs.js:56:23)
      at services/app/build/libs.js:248:10
      at Object.<anonymous> (services/app/build/libs.js:250:3)
```

where `lib-globals.ts` is importing along the lines of this:

```ts
import * as firebase from "firebase/app"
import "firebase/auth"
import "firebase/firestore"
import "firebase/functions"
import "firebase/storage"
```

I tried the `resolve:{... mainFields: ['main'] }` with an assortment of options but to no avail.

The only fix has been the `globalThis.fetch = require('node-fetch')`

Looking at index.cjs.js there is seems to be a reference to the global `fetch` at top level.

**Comment by hsubox76** [comment]
Yes, that is correct.

That's why you need to not use `index.cjs.js` but `index.node.cjs.js`. If you take a look at the second file, it uses `node-fetch`.

If you're not able to get webpack to grab that file from the 'main' field, you may want to ask around for webpack help. The fact it is still grabbing `functions/dist/index.cjs.js` instead of the Node version means that the config is somehow still prioritizing the "browser" field over the "main" field.

This is where you can see which bundles are provided for each field in the `@firebase/functions` package.json:
https://github.com/firebase/firebase-js-sdk/blob/79b04937537b90422e051086112f6b43c2880cdb/packages/functions/package.json#L6

**Comment by brianmhunt** [comment]
Thanks @hsubox76 , that's quite helpful.  I reported this issue essentially only because it was a breaking change from .4 to .5, and I think the information you've shared here essentially documents the reason and fix for future readers.

Since my project is moving away from webpack shortly (to esbuild), this particular problem may no longer apply to us (though the import preference knowledge is just as applicable).  On that basis, I'll close this issue (since I'll have nothing further to contribute), but please don't hesitate to re-open if you feel there's more that might be helpful here.

**Comment by r9software** [comment]
I'm having the same issue, just imported firebase into my app, and it is not detecting fetch on server rendering, any idea on how to fix it?

**Comment by r9software** [comment]
Forget it in case someone has this error like me:
https://stackoverflow.com/questions/44908044/babel-not-polyfilling-fetch-when-using-babel-preset-env/64791611#64791611

**Comment by hsubox76** [comment]
Generally for server side rendering, you should make sure you are using a bundler config that prefers the "main" field over "browser". Most server-side rendering setups have separate bundler (e.g. webpack) config files for server side and client side, and Firebase works best if the server-side config prefers the "main" field, because it will import the Node bundle for any Firebase package if it exists.

The functions Node bundle already includes a fetch polyfill so if you're getting that bundle correctly (see above comments about this bundle and the "main" field) you shouldn't need to add your own polyfill.

**Comment by r9software** [comment]
@hsubox76 I removed the custom polyfill but now I'm getting a different error, navigator is not defined, I'm trying to install firebase into a React App, and I can't find the way to do it correctly.

**Comment by r9software** [comment]
web-midi-api, installing that extra dependency fixed the navigator required.

**Comment by brianmhunt** [comment]
@r9software Seeing as this issue is closed it may not get any visibility from the Firebase team. It may be worthwhile to open a new issue and reference this one.

**Comment by hsubox76** [comment]
It sounds like a separate issue anyway so yes, I'd recommend opening a new one, with more details about your specific case.
