### ISSUE TITLE
Environment error when using Auth in Electron application

### ISSUE THREAD

**Issue by joostfarla** [firebase/firebase-js-sdk#400]
### [REQUIRED] Describe your environment

* Operating System version: MacOS High Sierra
* Firebase SDK version: 4.8.1
* Firebase Product: auth

### [REQUIRED] Describe the problem

When trying to use auth in an Electron (renderer) environment, the console reports the following error:

```
This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.
```

In a dev environment, my application runs on `http:` protocol (through webpack-dev-server). When I disable the `fireauth.util.isNativeEnvironment()` check, everything is working as expected. The application is bundled with Webpack using the `electron-renderer` target, so it probabvly detects the environment as a server-side Node environment. 

In a production environment (when the app is packaged), it will run on `file:` protocol, so I guess it should detect Electron env based on the user agent.

Other services (e.g. Firestore) are running fine within the Electron environment.

**Comment by bojeil-google** [comment]
I am not an expert on electronjs, but if we can't verify the origin of an application, OAuth sign-in should be disabled.
If the origin is a file origin, then no OAuth credential should be passed back to the application for security reason. Otherwise, anyone can steal your public API key and basically sign in your OAuth users to their electronjs application, effectively compromising your user's data.
If you are comfortable with the risks, then you should render your sign-in UI in a separate traditional browser and then pass the credential to your application via some secure mechanism and then `signInWithCredential` from there. Many applications use a similar flow.
Firestore and all other Firebase services rely on Auth for the authentication part. So obviously they will work correctly without any need for the same level of security checks that Auth runs.

**Comment by joostfarla** [comment]
Thanks for your comment, @bojeil-google! I'm using simple e-mail / password authentication, so there is no redirection involved. When I would use OAuth, the Electron renderer could easily be run as a Node.js server over http (localhost) instead of file protocol. But still, the SDK would detect the environment as a Node.js native runtime. Electron renderer is a Chromium browser with partial Node.js runtime capabilities, so that's probably the cause of the env mismatch?

**Comment by bojeil-google** [comment]
I see. Thanks for the clarification. This requires more investigation. In general, even if you can get it to work as localhost, all applications have localhost whitelisted by default. This is intended for development and not production as it will be impossible to tell different production apps apart and unsuspecting apps could be vulnerable for phishing attacks.

**Comment by malcolmdeck** [comment]
This topic is addressed more thoroughly in this thread: https://github.com/firebase/firebase-js-sdk/issues/2478
