### ISSUE TITLE
v8.0.2 Regression in Firebase Auth: IDBFactory.open() called in an invalid security context

### ISSUE THREAD

**Issue by vieira** [firebase/firebase-js-sdk#4113]
### Describe your environment

  * Operating System version: macOS Catalina (10.15.7)
  * Browser version: Safari 13.1.3 (with Intelligent Tracking Protection turned on, which is the default)
  * Firebase SDK version: 8.0.2 (also tested with 8.1.0, 8.1.1)
  * Firebase Product: auth

### Describe the problem

When `firebase/auth` is loaded in a cross-domain iframe an error is produced `Unhandled Rejection (SecurityError): IDBFactory.open() called in an invalid security context` and `onAuthStateChanged` never runs.

Downgrading to 8.0.1 solves the issue. I see that there was a change in firebase/auth related with IndexDB in 8.0.2, so I assume that #4059 introduced the regression.

I believe that previously, when it was not possible to use IndexDB for some reason it would fallback to `localStorage`?

Let me know if there is any other information we can provide.

**Comment by hsubox76** [comment]
May be related to https://github.com/firebase/firebase-js-sdk/issues/2393 where we had to add an async `isSupported` check to several packages that use IndexedDB to validate not just that window.IndexedDB exists but that no error is thrown on IDBFactory.open(), before trying to use IndexedDB.

The check logic is a bit convoluted because IndexedDB is quirky, and is here: https://github.com/firebase/firebase-js-sdk/blob/c76e1ffb87b7ce5482b3371c18934d49e1fe7392/packages/util/src/environment.ts#L150 

If auth needs to run something similar I guess it would have to be copied since auth code is Closure.

**Comment by iwiedenm** [comment]
I'm experiencing something similar where I can't use Firebase at all inside an Electron app with custom protocols. I can confirm that it does not work on any version above 8.0.1 so I downgraded to that for now.

**Comment by strom2357** [comment]
Thanks for reporting.  This is being tracked internally at b/174244535

**Comment by samhorlbeck** [comment]
Hi everyone, thanks for your patience. @vieira would you mind checking to see if this is fixed for you in `8.1.2`?

**Comment by vieira** [comment]
Hello @samhorlbeck,

The issue is no longer present in 8.1.2. Tested again with 8.1.1 (issue present) versus 8.1.2 (issue not present) under same configuration (Safari 13.1.3 with Prevent cross-site tracking).

Thanks!

**Comment by samhorlbeck** [comment]
Awesome, thanks for checking!
