### ISSUE TITLE
FR: Removal of 10,000 writes/second/database limit

### ISSUE THREAD

**Issue by vigneshksaithal** [firebase/firebase-js-sdk#4121]
* Operating System version: windows 10
  * Browser version: chrome 
  * Firebase SDK version: 8.0.0
  * Firebase Product: firestore

Describe the problem
Why hard limit of 10,000 writes/ second / database because, it causes problems when scaling. 

Because when we scale our number of writes also increases.
It causes problems for like a to-app/budgeting app like mint.(which we are developing)

**Comment by dconeybe** [comment]
Unfortunately, this is not the correct forum for raising this request because it is not something we can address in the SDK. Please open a request at https://cloud.google.com/support/docs/issue-trackers (search for "Create new Firestore issue") so that the correct audience and consider it. Thank you!

**Comment by dconeybe** [comment]
To add some additional context, we're well aware that this limitation causes issues; however, it exists to ensure we can provide isolation between projects (among other benefits). We're working to raise this limit but can't make any promises around if or when there will be any changes. If you're a paying Firestore customer then consider contacting support because there are engineers they can help potentially change your application to fit this limit.
