### ISSUE TITLE
[Bug] Field type reference in QueryDocumentSnapshot is not an instance of DocumentReference

### ISSUE THREAD

**Issue by mandalornl** [firebase/firebase-js-sdk#4125]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04
  * Browser version: Chrome 86
  * Firebase SDK version: ^8.1.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When querying documents from a collection, the field type `reference` does not return an instance of `DocumentReference` anymore. Therefore calling e.g. `get()` will result in an `is not a function` error. Example code can be found in the link below.

#### Relevant Code:

https://stackblitz.com/edit/firebase-issue-sandbox-z9mwhw

**Comment by dconeybe** [comment]
Thank you for reporting this issue. The stackblitz link was super helpful! At first glance, this definitely appears to be a regression in 8.1.0 (compared to 8.0.2). I'll do some investigation and reply back. Just a heads-up, since it's a long weekend in the US, I may not have a meaningful response until next week.
