### ISSUE TITLE
PLESE healp i got this issue and i cant solve. Module not found: Can't resolve '@firebase/app'

### ISSUE THREAD

**Issue by faizkhan7896** [firebase/firebase-js-sdk#4141]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by hsubox76** [comment]
We really need more specifics, can you provide what code you are using to import/call Firebase? Try to provide the minimum amount possible to reproduce the error.

**Comment by faizkhan7896** [comment]
`
[debug.log](https://github.com/firebase/firebase-js-sdk/files/5650734/debug.log)
`

**Comment by hsubox76** [comment]
Pasted from the other issue you opened:

If you find a bug you want to report, feel free to open an issue here, but you need to provide at least a minimal amount of info that helps us understand what the bug is (such as your own code that results in the error, not just the text of an error message). I don't know if the device/browser you are using is only showing the issue "title" text field, but you need to put the information in the text area below it. There's a form template in that text area that you can fill out with a lot of the information we would need.
