### ISSUE TITLE
Firebase dynamic link inside iframe not working

### ISSUE THREAD

**Issue by amstrad** [firebase/firebase-js-sdk#4157]
Sorry if this is not the best repo for reporting this, but didn´t find any repo related to dynamic links web.

When adding a dynamic link inside and Iframe, this works on some OS (Win10 that we tested, several browsers) and not on others (OSX that we tested, several browsers).. I see the dynamic link has a [X-Frame-Options = SAMEORIGIN](https://securityheaders.com/?q=https%3A%2F%2Fbnc10.page.link%2FCg3VayTee9cDUwMe6) header, so probably is not intended to work as we need. 
Why is it doing fine on Windows(response 302) but not osx (response 200)?.
OSX
![mac](https://user-images.githubusercontent.com/772421/100992463-7fa55a00-3554-11eb-9ccf-d021925a85bd.png)
WIN
![win](https://user-images.githubusercontent.com/772421/100992476-82a04a80-3554-11eb-9b95-a01dd6db0920.png)

**Comment by samtstern** [comment]
@amstrad I'm transferring this to `firebase-js-sdk` because that's where we have the most Web experts.  If nobody here knows the answer to this issue you may be better off asking Firebase support (firebase.google.com/support) because they will file a bug with the Dynamic Links engineers.

**Comment by bradconnolly** [comment]
Hi all, are there any updates on this issue?

**Comment by abdoulayediak** [comment]
It would be very nice to have an answer or just a hint concerning this issue, please.

**Comment by hsubox76** [comment]
Just to clarify, this is the repo for the JS client SDK. We don't maintain dynamic link functionality, Sam just thought someone on this team might have some guesses by virtue of us working on web and having web knowledge in general. I don't think anyone's had any so far.

We're not able to provide official updates because, again, this isn't our team's product. If you need to contact the Dynamic Links team and get updates, I'd suggest contacting support like Sam suggested.
