### ISSUE TITLE
 PLESE healp i got new issue and i cant solve and i dont no what is it. Module not found: Can't resolve 'translate' {in react navigation v5 (drawer)}.

### ISSUE THREAD

**Issue by faizkhan7896** [firebase/firebase-js-sdk#4178]
`

### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by hsubox76** [comment]
This doesn't seem related to Firebase and you seem to be having some problems with the Github UI in this and your other issue. If you need general help with using Firebase, you can contact Firebase Support. If you need general help with your app, try Stack Overflow or another community forum.

If you find a bug you want to report, feel free to open an issue here, but you need to provide at least a minimal amount of info that helps us understand what the bug is (such as your own code that results in the error, not just the text of an error message). I don't know if the device/browser you are using is only showing the issue "title" text field, but you need to put the information in the text area below it. There's a form template in that text area that you can fill out with a lot of the information we would need.
