### ISSUE TITLE
Could not reach Cloud Firestore backend

### ISSUE THREAD

**Issue by oslearningbear** [firebase/firebase-js-sdk#4209]
A small % of users https://flurly.com keep hitting this bizarre error of "Could not reach Cloud Firestore backend". I have no way to reproduce, but it seems pretty consistent day by day. Can someone take a look? I attached a stacktrace a user sent me below.

![github](https://user-images.githubusercontent.com/46176773/102131054-7cd51f80-3e06-11eb-8cfa-26d6159e34fc.jpg)

**Comment by wilhuff** [comment]
What you've sent over isn't much to go on so I can't help with this issue directly. If you have a user that's experiencing this you may be able to get them to collect the information required to debug this.

The most likely cause of this issue is that some of your users are behind firewalls or are using anti-virus software that interfere with Firestore's ability to get or listen to changes from the server. See #1674 for information on how you can debug this and an [`experimentalForceLongPolling`](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#optional-experimentalforcelongpolling) workaround you can employ.

In addition, we've recently added some experimental code that can auto-detect this condition and apply the workaround automatically. You can also try using [`experimentalForceLongPolling`](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#optional-experimentalforcelongpolling) to see if this helps your customers. We're still collecting data on whether or not this is safe enough to enable by default.

If the debugging steps in #1674 don't point to a clear cause we'll need more information. The best place to start would be to collect logs by [enabling debug logging](https://gist.github.com/katowulf/0475fb7a5907ed757f687aab6ed15878).

**Comment by LanderBeeuwsaert** [comment]
@wilhuff 
Hi, well we have this issue as well.
Funny thing is that we're actually running an angular application against the emulator (all of them except hosting) for our e2e testing in playwright in a CI pipeline.
Most of the time it works without issues, however sometimes (+- 1 in 20 browser refreshes) we have a bad apple/bad browser refresh.
We do complicate the matter by launching multiple browser instances semi-simulateously; so the load on the server at that time is +- 100% CPU/disk usage for quite some seconds.
So we think (are pretty sure) it's related to that.
If we spread the loading of the browser instances out over 10 seconds, it happens a lot less.

**Comment by BrunoViera** [comment]
I'm having the same issue in a brand new project with create react app.

**Comment by schmidt-sebastian** [comment]
@LanderBeeuwsaert / @BrunoViera Have you tried the `experimentalForceLongPolling` setting suggested above? If this also does not help, I would be happy to look at your debug logs.

**Comment by LanderBeeuwsaert** [comment]
@schmidt-sebastian nope I didn't. For now we don't get the issue anymore by starting the different browser instances staggered with 10 seconds delay between them. I'll try the experimentalForceLongPolling next time we have it.
