### ISSUE TITLE
[alpha] ESM imports rely on webpack/rollup-specific module interop

### ISSUE THREAD

**Issue by developit** [firebase/firebase-js-sdk#4214]
### Describe your environment

  * Operating System version: MacOS
  * Browser version: Chrome 88
  * Firebase SDK version: @exp (0.0.900-exp.a9388d5b2)
  * Firebase Product: auth

### Describe the problem

The ESM bundle for `@firebase/auth` attempts to import `{ SDK_VERSION }` from `@firebase/app`, however that module only provides a default export (which is an object with an SDK_VERSION property). The result is that the ESM version only works if it is transpiled to CJS or if CommonJS "interop" is applied to the modules.

The solution (from what I can tell) seems to be to change the source to use object properties and the default export from `firebase/app`:

```diff
import {ErrorFactory, isBrowserExtension, isMobileCordova, isReactNative, querystring, FirebaseError, base64Decode, createSubscribe, isIE, getUA, isEmpty} from '@firebase/util';
-import {SDK_VERSION, _getProvider, _registerComponent, registerVersion} from '@firebase/app';
+import firebase from '@firebase/app';
+const {SDK_VERSION, _getProvider, _registerComponent, registerVersion} = firebase;
import {Logger, LogLevel} from '@firebase/logger';
import {Component} from '@firebase/component';
```

**Comment by Feiyang1** [comment]
Are you using `@firebase/app@exp`? It seems you might be using `@firebase/auth@exp` with the production version of `@firebase/app` which uses default export. `@firebase/app@exp` only provides named exports. See the builds here - https://unpkg.com/browse/@firebase/app@0.0.900-exp.a9388d5b2/dist/

Basically alpha packages don't interop with production packages, so you can't use them side by side. When trying alpha packages, I suggest installing `firebase@exp` instead of installing individual scoped packages to avoid this kind of issues.
