### ISSUE TITLE
onAuthStateChanged not triggered after linking anonymous account with email and password credential

### ISSUE THREAD

**Issue by Jwiggiff** [firebase/firebase-js-sdk#4227]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro
  * Browser version: Chrome v87
  * Firebase SDK version: 8.1.2
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
In my application, I authenticate the user anonymously. If they choose to create an account with email and password, then I'd like to link this new account with the anonymous account they are already logged in to. I can see in the Firebase Console that it is in fact linking the anonymous account with the new email and password, however the onAuthStateChanged function is not called after it is linked. I can also see that the `firebase.auth().currentUser` is updated after linking, so it is signing in to the new account.

#### Steps to reproduce:

- Authenticate user anonymously
- Attempt to link with email/password credential
#### Relevant Code:

```javascript
let credential = firebase.auth.EmailAuthProvider.credential(email, password);
firebase.auth()..currentUser.linkWithCredential(credential)
  .then((user) => {
    console.log(user); // This runs
    user.user.updateProfile({ displayName: name });
  })
  .catch((error) => {
    alert(error.message);
    console.log(error);
  });
```

**Comment by Mattinton** [comment]
I'm getting the same issue and I'm unsure whether its intentional or not.

**Comment by markwilson** [comment]
Have you found any workaround for this? I thought `user.user.reload()` might do the trick, but it doesn't seem to make any difference.

**Comment by samhorlbeck** [comment]
Hi folks, `onAuthStateChanged` ([docs](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged)) executes when a user logs in, logs out, or _changes_ (i.e. a _different_ user signs in). It will _not_ trigger for the current user being updated through e.g. linking.

There is a related method called `onIdTokenChanged` ([docs](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged)) Linking should cause this to trigger, it would be worth testing out instead of `onAuthStateChanged`. `onIdTokenChanged` will additionally trigger if a token is refreshed (i.e. if you force refresh the user: `currentUser.reload(true)`)
