### ISSUE TITLE
Custom OAuthProvider

### ISSUE THREAD

**Issue by prilutskiy** [firebase/firebase-js-sdk#4307]
Hello,

Is there a way to add a new OAuthProvider implementation? I'm trying to setup authentication using Slack, but it's not yet supported. Should I just wait for it to be released with the SDK? Does it make sense to issue a PR with the feature? Are there any docs / examples of custom `OAuthProvider` implementations?

**Comment by Vloz** [comment]
I cant tell for the mobile, but for the web i am using [custom-auth](https://firebase.google.com/docs/auth/web/custom-auth) to connect Firebase with Blizzard oAuth, following this tutorial:
https://firebase.googleblog.com/2016/10/authenticate-your-firebase-users-with.html
(The server part can now be done using Firebase Cloud Functions)

**Comment by malcolmdeck** [comment]
Vloz has one correct answer: use Custom Auth. The blog post that they've linked should help explain things.

The alternative is that you use [Identity Platform](https://cloud.google.com/identity-platform), which is the enterprise offering equivalent of Firebase Authentication. That allows you to specify your own [OIDC](https://cloud.google.com/identity-platform/docs/web/oidc), and [SAML](https://cloud.google.com/identity-platform/docs/web/saml) providers. Slack supports the OIDC protocol, so that would work for you.
