### ISSUE TITLE
API returns 200 when de token is unregistered

### ISSUE THREAD

**Issue by GGamezZylk** [firebase/firebase-js-sdk#4318]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04
  * Browser version: Chrome 87.0.4280.141 (Build oficial) (64 bits)
  * Firebase Product: FCM 

#### Steps to reproduce:
- Normal use of FCM tokens; When updating a token, the updated token does not get deactivated.
- When making use of FCM tokens I'm observing that when validating the tokens I've generated for each device, there are more tokens that those I should expect.
I made use of FCM from 5 devices (2 browsers on desktop-Ubuntu, 2 brosers on desktop-windows and one browser-android), and I can see how those tokens have been updated over time, but the ones that have been replaced have not been deactivated from the service, resulting this unexpected behaviour in the following situation: there are more tokens than the ones I'm actually sending notifications to. This is quite a problem, as rightnow I'm not able to tell how many devices actually recieved notifications, because the number of sended notifications is missleading (there is actually only 5 active tokens or devices that do recieve notifications and these devices do not recieve duplicated messages, beeing 19 devices the ones that firebase specifies a notification is sended to).

Problem:
- I'm recieving HTTP/1.1 200 OK when testing over  https://fcm.googleapis.com/fcm/send using dry_run = true, whereas I should recieve
1) HTTP/1.1 200 OK for 5 tokens
2) 200 + error:NotRegistered for 13 tokens

¿Why is this happening? ¿Shouldn't a new token for the same device deactivate the previous token?

¿How could I solve this problem?

The API I'm using for testing token validity is: https://fcm.googleapis.com/fcm/send
#### Relevant Code:
We get the same response (HTTP/1.1 200 OK) for each one of the 19 tokens.

```javascript
{"multicast_id":-1,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"fake_message_id"}]}
HTTP/1.1 200 OK
 checkFCMToken responseJson = {"canonical_ids":0,"success":1,"failure":0,"results":[{"message_id":"fake_message_id"}],"multicast_id":-1}
checkFCMToken success = 1
checkFCMToken failure = 0
checkFCMToken resultArray = [{"message_id":"fake_message_id"}]
checkFCMToken resultItem = {"message_id":"fake_message_id"}
```

**Comment by Feiyang1** [comment]
It seems to be a backend issue rather than a SDK issue. @zwu52 Can you confirm?

For backend issues, please file a ticket with our support at https://firebase.google.com/support/troubleshooter/fcm

**Comment by zwu52** [comment]
Hello @GGamezZylk,
I think you are asking two questions here:
1. How do I know if my tokens are still valid? 
2. How do I know if my messages are delivered? 

For  1, the fact that you are getting success response from the Send API means that __all__ 19 tokens are valid. You could have multiple FCM tokens associated with one FIS ID. In other words, you are not looking at "updated" tokens, but "another" token. 

The more interesting questions is 2, generally you should rely on delivery metrics that are generated from clients. The reason is that having the sender reporting success code wouldn't guarantee that the receivers have received (maybe the mail is lost in transaction) . FM provides 2 ways to look up delivery status: 
- from firebase console or
- from Bigquery export. 

You can find more details [here](https://firebase.google.com/docs/cloud-messaging/understand-delivery#message-delivery-reports).


I think there is a doc on how to manage your FM token but I need to find it. Let me circle back with that

**Comment by zwu52** [comment]
@GGamezZylk ,
Thanks for reporting. Yes! The expected behavior should be that you get a failure response when sending to an invalid token. Because if you can't invalidate through the send request,
- your token stored will be ever-growing. Costs to store.
- The reported delivery rate (open, receive) in the firebase console and BQ will be smaller than it actual is since the send count is always over-counted. 
Please file a bug through the link above to our backend team.
