### ISSUE TITLE
Date field is null right after setting it via FieldValue.serverTimestamp()

### ISSUE THREAD

**Issue by kossnocorp** [firebase/firebase-js-sdk#4344]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 87.0.4280.141
  * Firebase SDK version: 8.2.4
  * Firebase Product: Firestore

#### Steps to reproduce:

When I add a document with a date field set via `FieldValue.serverTimestamp()` to a collection and then immediately request it via `query`, I got cached document data with the field equal `null`.

Is it expected behavior? It feels like a bug to me, but I can see that it might be a trade-off. I would prefer to have a not entirely accurate date for a moment, but I can see that it might cause other problems.

I use [a type-safe ODM](https://typesaurus.com/) to fetch data, and if it's expected behavior, I can never assume that required date fields aren't null. Am I correct?

**Comment by wilhuff** [comment]
This is expected behavior. Until the client has seen a response from the server that fixates the timestamp, the client doesn't know what the value is. Our experience has been that local clocks are wildly inaccurate so depending on them to generate pending values can lead to surprising behavior. For example, a very common case is the local clock being an hour off during daylight savings time; when using its values as estimates, the dates you show your users will jump by an hour when the value is fixated by the server.

Internally, Firestore does capture a timestamp whenever you perform a write containing `FieldValue.serverTimestamp()` and documents ordered by a field you're writing with this will order correctly. Our recommendation is to show a "pending" or similar label on entries whose timestamp hasn't been fixated yet.

With that said, Firestore does offer options on how snapshots handle non-fixated server timestamps. The [`data`](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot#data) method takes an optional [`SnapshotOptions`](https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotOptions) object with which you can request that Firestore substitute the local write time as an estimate or you can request that it pass through any previous value which can be useful if you're overwriting an existing field with a server timestamp.

**Comment by kossnocorp** [comment]
Thank you so much for the elaborate answer! ♥
