### ISSUE TITLE
Error: Cannot find module 'firebase-admin'

### ISSUE THREAD

**Issue by danbraik** [firebase/firebase-js-sdk#4473]
### [REQUIRED] Describe your environment

  * Operating System version: _____Linux
  * Browser version: _____
  * Firebase SDK version: _____9.3.0
  * Firebase Product: rules testing

#### Steps to reproduce:

`npm i @firebase/rules-unit-testing`

```
// js file
const firebase = require('@firebase/rules-unit-testing');
```

#### Relevant Code:
(node:1984) UnhandledPromiseRejectionWarning: Error: Cannot find module 'firebase-admin'
Require stack:
- ..../node_modules/@firebase/rules-unit-testing/dist/index.cjs.js
- ..../test-firestore/seed-local-emulator.js

Maybe a missing dependency ?

**Comment by vincentcaitech** [comment]
I haven't looked into this issue very extensively, but when ran ```npm i @firebase/rules-unit-testing```, I received the following npm warnings about dependencies:

```
npm WARN @firebase/rules-unit-testing@1.2.0 requires a peer of @google-cloud/firestore@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @firebase/rules-unit-testing@1.2.0 requires a peer of firebase-admin@^9.0.0 but none is installed. You must install peer dependencies yourself.
```

So maybe firebase wants you to install it yourself?

**Comment by vincentcaitech** [comment]
Hi @danbraik, I saw in `packages/rules-unit-testing/package.json`, the "firebase-admin" package is located under "peerDependencies" and not "dependencies", so firebase probably wants you to install it separately.

Therefore, when you run `npm i @firebase/rules-unit-testing`, you'll get the following warning:

```
npm WARN @firebase/rules-unit-testing@1.2.0 requires a peer of firebase-admin@^9.0.0 but none is installed. You must install peer dependencies yourself.
```

I could open a pull request asking firebase to move it into "dependencies", but I'm not sure if it will be accepted because firebase probably has their reasons to list it as a peer dependency. Thoughts?

**Comment by danbraik** [comment]
Hi Vincent,
ok I missed the peerDependency thank you. Maybe to avoid an overload if the user is not using an adminApp ?
But as Firebase is intended to be used by everyone and that adminApp is necessary to set up some test data in Firestore (for example), I think it could be required as dependency.

Regards

**Comment by DellaBitta** [comment]
HI @danbraik,

Checking in to see if this is still blocking your development. Thanks!
