### ISSUE TITLE
Too big: The data requested exceeds the maximum size that can be accessed with a single request.

### ISSUE THREAD

**Issue by JorisPhilipsen** [firebase/firebase-js-sdk#4661]
### Environment

  * Operating System version: Mac OS: 11.2.1
  * Firebase SDK version: 8.3.0
  * Firebase admin: 9.5.0
  * Firebase Product: Realtime Database
  * Node.js version: 14.3.0
  * NPM version: 6.14.5

### The problem
I get the error:
`Error: too_big at /collection-name: The data requested exceeds the maximum size that can be accessed with a single request.`

When I do the following: 

```
    let query = ref.orderByKey()
    
    if (startAt) { 
      query = query.startAt(startAt) 
    }

    const snapshot = await query.limitToFirst(2).once('value')
```

I do this on different collections, there's only an issue with doing this on really large collections. When I debug the request using: `admin.database.enableLogging(console.log)` it still gives the same error. The same happens in the firebase console.

I am able to get the data using: /collection-name/collection-name, but that's not desirable.

#### Steps to reproduce:

See above, but it seems to happen with really large collections, with more than 70000 child nodes.

#### Relevant Code:

You need to have a really large collection and do the following to get the error: 

```
    let query = admin.database().ref(`/collection-name`).orderByKey()
    
    if (startAt) { 
      query = query.startAt(startAt) 
    }

    const snapshot = await query.limitToFirst(2).once('value')
```

**Comment by looptheloop88** [comment]
Firebase Realtime Database has a limit on the size of data that can be downloaded from the database at a single location. It should be less than 256 MB for each read operation. Using `limitToFirst()` method sets a maximum number of children to be synced for a given event.

Just to confirm, even though you're already using the `limitToFirst()` method, you're still getting the error? Also, this only happens when the reference node has more than 70K child nodes?
