### ISSUE TITLE
Cloud Firestore Issue 

### ISSUE THREAD

**Issue by maureSs** [firebase/firebase-js-sdk#4675]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 pro
  * Browser version: Chrome 89
  * Firebase SDK version: 8.3.0
  * Firebase Product: auth/cloud firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem
Hello,
I have an all app which I can dynamically enter things to a list, which are stored in a database in cloud firestore, each item has a name and a userId. In my App I have all the authentication done, everything works wonderfully, every time I enter something to the list, each item has the userId of the respective user. The problem is that I am in the final stage where I want each user to have their own list, and not be able to access another user's list and vice versa. So I am changing the database **rules** but i ran into problems. When entering things to my list, these things are added to the database, with their respective name and user id, but they do not appear in the application! It doesn't show me the items in the app, but the items exist in the database.
 //Attached two links for the console error and the current database rules.

![rules](https://user-images.githubusercontent.com/75447117/112392692-9a086c80-8cd8-11eb-829c-aaae724a0342.PNG)
![error](https://user-images.githubusercontent.com/75447117/112382939-404d7580-8ccb-11eb-80d9-4e227d0a1863.PNG)

**Comment by yuchenshi** [comment]
As you can probably guess from the error message, your listener was closed due to permission denied. How was your listener defined? i.e. can you provide a code snippet on how you watched the list, e.g. `app.firestore().........onSnapshot(...)`?

For rules denies like this, we don't expose a lot of debug information in production for security reasons, which makes the emulator a better tool for troubleshooting. Have you tried this with the Firestore Emulator? It gives a more detailed error message and you can even dig into the coverage report to see what are the values of the expressions that led to denial.

**Comment by maureSs** [comment]
@yuchenshi Here you have some code, i can give you the full code as a link if u need it. Im sure that something in my code is not okay & i dont know exactly what tho. Im pretty new using Firebase.

![code2](https://user-images.githubusercontent.com/75447117/112542091-edd78c00-8d92-11eb-827c-99161f563adf.PNG)

**Comment by yuchenshi** [comment]
Try changing your rules to say `allow read: if authed() && (resource == null || resource.data == null || matchesUser(resource.data))`. Please note that this is a GitHub repo for the JS SDK, and rules questions are better discussed elsewhere, such as Stack Overflow or [Firebase Support](https://firebase.google.com/support). You'll also get help much faster if you can provide a minimal repro (ideally using the emulator as well) over there.
