### ISSUE TITLE
 Detected an object of type "Timestamp" that doesn't match the expected instance

### ISSUE THREAD

**Issue by ebeloded** [firebase/firebase-js-sdk#4734]
### Environment

  * Operating System version: OS: macOS 11.2.3
  * Browser version: Node 12
  * @firebase/rules-unit-testing: "1.2.6"
  * firebase-admin: "9.6.0",

### Problem

When I stub Firestore with data `Timestamp.now()`, I get an error.

#### Steps to reproduce:

1. Instantiate test admin Firestore:
```ts
import * as testFirebase from '@firebase/rules-unit-testing'
const adminFirestore = testFirebase
    .initializeAdminApp({ projectId })
    .firestore()
```
2. Add data with timestamp:
```ts
const { Timestamp } = testFirebase.firestore

adminFirestore.doc('docs/first-doc').set({createdTime: new Timestamp()})

```
3. This will result in an error:

> Value for argument "data" is not a valid Firestore document. Detected an object of type "Timestamp" that doesn't match the expected instance (found in field "createdTime"). Please ensure that the Firestore types you are using are from the same NPM package.)

--

This error popped up as we tried to transition to `@firebase/rules-unit-testing` from the deprecated `@firebase/testing`. In 
the old library, there was no error

--

Workaround: If I use `Timestamp` from `firebase-admin`, leaving everything else as-is, the error disappears. This makes the error message extra confusing

**Comment by thebrianchen** [comment]
@ebeloded Thanks for writing in with a clear issue! The `testFirebase` is the *web* SDK, but since you initialized an *admin* app, you'll need to use the Timestamp from the *admin* SDK instead. This is definitely confusing, and we currently have an internal ticket to improve the developer experience here. For more context and examples, see #3910 and #4129.

I'm going to mark this issue as closed, but feel free to comment if you have any more questions.
