### ISSUE TITLE
Custom prototype objects cannot be stored

### ISSUE THREAD

**Issue by Karasuni** [firebase/firebase-js-sdk#476]
`AngularFireStoreCollection.add()` has a hard validation for the type `object`. I notice that the validator does not accept any objects with a 'custom' prototype:

https://github.com/firebase/firebase-js-sdk/blob/6abd6484730971e2390b2b9acbb61800852fb350/packages/firestore/src/util/input_validation.ts#L241-L251

My question is what the reasoning is behind this hard check against the Object prototype?

When you're using custom objects as we do in Typescript the action fails even though the type is defined as `add(data: T): Promise<DocumentReference>;` - a type definition that implies any Object can be used.
 
Related to https://github.com/firebase/firebase-js-sdk/issues/311.

**Comment by wilhuff** [comment]
Our reasoning here essentially in two parts.

We can't read data back into custom objects and since we can't reconstitute your object at read time we don't want to half-implement object mapping.

The second part is that even if we did support custom objects for the obvious cases, inevitably people will be dissatisfied by what we've done. For example:
  * Should we serialize all properties of the immediate object or traverse the prototype chain?
  * Should we provide some mechanism for customizing the names properties?
  * Should we serialize properties from `Object.defineProperty`?
  * Should we support classes that implement toJSON? Should date-like strings that come out of that be dates or strings? Should try to parse them to find out?

I realize you "just" want to store custom objects but really this opens a kind of Pandora's box that creates just as many problems as it solves.

**Comment by samtstern** [comment]
Thanks @wilhuff for the answer.  Closing this issue as we consider this decision final.
