### ISSUE TITLE
Unable to initialize auth due to component auth-exp not being registered yet (v9 beta.1)

### ISSUE THREAD

**Issue by zeusdeux** [firebase/firebase-js-sdk#4819]
### Describe your environment

  * Operating System version: macOS 10.15.7
  * Browser version: Chrome 89.0.4389.114
  * Firebase SDK version: 9.0.0-beta.1
  * Firebase Product: auth 

### Describe the problem

Upon invoking `getAuth` on the result of a successful `initializeApp` call, it throws the following error —

`Error: Component auth-exp has not been registered yet`

#### Steps to reproduce:

1. Invoke `initializeApp` on a valid firebase config
2. Pass the result of step 1 as a parameter to `getAuth`

#### Relevant Code:

```javascript
const firebaseApp = initializeApp(firebaseConfiguration);
const firebaseAuth = getAuth(firebaseApp); // throws
```

**Comment by looptheloop88** [comment]
Hi @zeusdeux, thanks for the report. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample project that I can run locally to replicate the issue?

**Comment by zeusdeux** [comment]
@sam-gc @looptheloop88 I'll try and get the reproducible example this week. 
At Mr. Bot, chill my dude, some of us like having vacation.

**Comment by lukechu10** [comment]
I am having the same problem using SvelteKit and SSR. When I start the SvelteKit dev server (Vite), it initially does not work. Then I get `[vite] new dependencies found: @firebase/app, @firebase/firestore, updating...` and the issue is resolved on future builds. Maybe this has something to do with a one-time setup code?

The error is thrown here:
https://github.com/firebase/firebase-js-sdk/blob/fad44a5533b63703a2714c7ff55ae48468a8a696/packages/component/src/provider.ts#L233
