### ISSUE TITLE
What the point of scopes in signInWithPopup if we cant use them?

### ISSUE THREAD

**Issue by rendomnet** [firebase/firebase-js-sdk#4838]
for example I'm asking for scopes in `signInWithPopup`

      `provider.addScope('https://www.googleapis.com/auth/calendar.events');`

And in my auth flow user is asked to give permission for calendar scopes.
But after login I do not have access to calendar.

What the point of providing this scopes then?

**Comment by looptheloop88** [comment]
Hi @rendomnet, you can't directly access the calendar information associated to a user after just adding the scope. This isn't automatically added to the [currentUser](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#currentuser) object.

When you give permission to a scope, it means that the user can use the [Calendar API](https://developers.google.com/identity/protocols/oauth2/scopes#calendar). See this [OAuth 2.0 Scopes for Google APIs](https://developers.google.com/identity/protocols/oauth2/scopes) documentation for more information.

**Comment by rendomnet** [comment]
@looptheloop88 but access token provided by firebase auth for google.com is expired in a hour. What the point if getting this access token at all?

**Comment by looptheloop88** [comment]
Hi @rendomnet, the access token expiration is for security purposes. Usually, when the access token expires, the application will require the user to authenticate or sign-in again. Since an access token is used to allow application to access an API, refreshing access token ensures that an actual user is the one making the requests.
