### ISSUE TITLE
Failed to load resource: Could not connect to the server

### ISSUE THREAD

**Issue by mishushakov** [firebase/firebase-js-sdk#4844]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.3
  * Browser version: Safari 14.1, Firefox 88
  * Firebase SDK version: 8.4.1, 8.4.2
  * Firebase Product: Realtime Database

#### Steps to reproduce:

Try connecting to firebase realtime database

1. Connection to the database using firebase SDK fails
2. Firebase console does not load any realtime db content

my adblocker is disabled

#### Relevant Code:

Safari

```
[Error] Failed to load resource: Could not connect to the server. (.lp, line 0)
```

Firefox

```
Loading failed for the <script> with source “https://crescasapp-default-rtdb.firebaseio.com/.lp?start=t&ser=40173457&cb=4&v=5&p=1:153063981723:web:4384ee48af941efccbbc3e”.
```

then throws an error

```
Error: Error: Client is offline.
```

**Comment by looptheloop88** [comment]
Hi @mishushakov, I can't replicate this issue. It could be that your machine or network isn't able to connect with Firebase Realtime Database services.

Since you're unable to load the contents of Firebase Realtime Database, you may want to file a ticket via [Firebase support](https://firebase.google.com/support) channel. It would help if you could provide them a [HAR file](https://toolbox.googleapps.com/apps/har_analyzer/) generated from the browser logs when the error occurred while loading the database.
