### ISSUE TITLE
Firebase 9 versus Firebase 8 webpack bundle sizes

### ISSUE THREAD

**Issue by jmc420** [firebase/firebase-js-sdk#4916]
### [REQUIRED] Describe your environment

  * Operating System version: ___OSX 11.3__
  * Browser version: ___90__
  * Firebase SDK version: _9.0.0-beta.2____
  * Firebase Product: ___auth and firestore__ (auth, database, storage, etc)

When you webpack Firebase, you get 2 entries @firebase and firebase.

In firebase 8, @firebase is large and firebase is tiny (barely visible in webpack-visualizer).

In firebase 9, @firebase is a lot smaller than the firebase8 @firebase but firebase is a lot bigger.

See images here:

https://stackoverflow.com/questions/67550022/firebase-9-and-bundle-sizes

What does this mean?

#### Steps to reproduce:

Run webpack --mode='production' --profile --json > compilation-stats.json on a firebase 8 and a firebase 9 project and then load the stats into http://chrisbateman.github.io/webpack-visualizer

**Comment by geoffgscott** [comment]
FWIW compiled sizes are much smaller using V9. For me using webpack bundle analyzer and a codebase that uses just auth/firestore functionality I got:

V7:
@Firebase: Stat Size: 1.1Mb - Parsed Size: 590kb - gzip: 154kb
   Firebase: Negligible, and for me only from storage API which is unused in my V9 flow. 
V9:
@Firebase: Stat Size 861kb - Parsed Size: 125kb - gzip: 32kb
   Firebase: Stat Size 367kb - Parsed Size: 118kb - gzip: 21kb
         Total: Stat Size 1.23Mb - Parsed Size 243kb - gzip: 53kb

Overall my V9 parsed bundle is 41% of the V7 bundle and the gzip is only 34% of the V7 size. Results will vary depending on how much you import and what can be tree-shaken out obviously.

**Comment by Feiyang1** [comment]
`firebase` is the umbrella package that you install to get all firebase product SDKs. It has no implementation, and delegates everything to the scoped packages. For example, `firebase/app` delegates to `@firebase/app`, `firebase/firestore` delegates to `@firebase/firestore`. That said, it's just how we package our SDKs, and you shouldn't need to know or care.

And in my experience, the bundle analyzing tools are not perfect, and may attribute code incorrectly. Package `firebase` should have negligible size as I mentioned earlier.

As @geoffgscott said, the bundle size depends on what you import in v9. If you can share your code, I can try to analyze its bundle size on my side.

**Comment by jmc420** [comment]
I was using Typescript with an es5 target so tree shaking was not working.

webpack-bundle-analyzer with es5 and firebase 8 says reports @firebase as:

Stat Size: 1.08Mb - Parsed Size: 581kb - gzip: 150kb

webpack-bundle-analyzer with es9 and firebase 9 says reports firebase as:

Stat Size: 1.17Mb - Parsed Size: 380kb - gzip: 111kb

This seems to indicate that Firebase 9 is smaller (the parsed size after webpack has run).

Any idea why with es6 code it reports "firebase" and with es5 code it reports "@firebase".

**Comment by Feiyang1** [comment]
I'm not sure how `webpack-bundle-analyzer` attributes code to packages. You can use the scoped packages directly to eliminate the noises. For example, import `@firebase/app' instead of 'firebase/app'.

Can you share the imports you use for v8 and v9 respectively?

Keep in mind the total package size in v9 is not very meaningful because you won't include the entire package in your app. The size of firebase you will include in your app depends on what you import. 

For example, the size of firebase should be very small if you only use sign in with email and password from firebase auth using
``` 
import { signInWithEmailAndPassword, getAuth } from 'firebase/auth';
```

**Comment by jmc420** [comment]
With Firebase 8, I import:

import { FirebaseOptions } from '@firebase/app-types';
import app from 'firebase/app';
import 'firebase/firestore';
import 'firebase/auth';
import { User, UserCredential } from '@firebase/auth-types';

With Firebase 9:

import { FirebaseOptions } from '@firebase/app-types';
import { collection, CollectionReference, doc, DocumentReference, FirebaseFirestore, getDoc } from "firebase/firestore";
import { getFunctions, httpsCallable } from "firebase/functions";
import { collection, CollectionReference, deleteDoc, doc, DocumentReference, FirebaseFirestore, getDoc, getDocs, setDoc } from "firebase/firestore";
import { getFirestore, FirebaseFirestore, useFirestoreEmulator } from "firebase/firestore";
import { Auth, createUserWithEmailAndPassword, getAuth, fetchSignInMethodsForEmail, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword, signOut, updatePassword, useAuthEmulator, UserCredential } from "firebase/auth";
import { collection, CollectionReference, doc, DocumentReference, FirebaseFirestore, getDoc, onSnapshot, setDoc } from "firebase/firestore";
import { FirebaseApp, initializeApp } from "firebase/app";
import { Functions, getFunctions, useFunctionsEmulator } from "firebase/functions";

**Comment by dmitry-zaets** [comment]
> I'm not sure how `webpack-bundle-analyzer` attributes code to packages. You can use the scoped packages directly to eliminate the noises. For example, import `@firebase/app' instead of 'firebase/app'.
> 
> Can you share the imports you use for v8 and v9 respectively?
> 
> Keep in mind the total package size in v9 is not very meaningful because you won't include the entire package in your app. The size of firebase you will include in your app depends on what you import.
> 
> For example, the size of firebase should be very small if you only use sign in with email and password from firebase auth using
> 
> ```
> import { signInWithEmailAndPassword, getAuth } from 'firebase/auth';
> ```

I've just tried to replicate the minimal example with `import { initializeApp } from 'firebase/app'` and 
`import { getAuth, onAuthStateChanged } from 'firebase/auth'`and it looks like it still includes the whole `@firebase/auth` into the bundle. You can see the details in the [following issue](https://github.com/firebase/firebase-js-sdk/issues/5719).
Also, I've tried to use direct imports like you suggested import `@firebase/app'` instead of `'firebase/app'` - this has no effect as well.

[Here is a repo to test the minimal setup with webpack and one js file](https://github.com/dmitry-zaets/webpack-firebase-auth-9)

Any other suggestions?

**Comment by Feiyang1** [comment]
@dmitry-zaets It's caused by your build configuration. There are 2 issues there:
1. You are building a development build which includes all the white spaces and comments. You need to change your build command from `webpack --mode=development`  to `webpack --mode=production`
2. You are using `eval-source-map` which inlines the source map and bloats the bundle. Change it to `source-map`.

After making these changes, I see ~22kb gzipped size using your repo.
