### ISSUE TITLE
use[FIREBASEPRODUCT]Emulator conflicts with react hooks

### ISSUE THREAD

**Issue by codesby** [firebase/firebase-js-sdk#4930]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home 21H1
  * Browser version: Microsoft Edge Version 90.0.818.62 (Official build) (64-bit)
  * Firebase SDK version:^9.0.0-beta.1
  * Firebase Product: _____ (storage, firestore)

### [REQUIRED] Describe the problem
Can't use the naming convention useSomethingEmulator with react  it throws a 
 error  React Hook "useFirestoreEmulator" cannot be called at the top level. React Hooks must be called in a
React function component or a custom React Hook function  react-hooks/rules-of-hooks
#### Steps to reproduce:
Attempting to use any emulator suite within a react app

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
useFirestoreEmulator(getFirestore(), "localhost", 8080)
```

**Comment by codesby** [comment]
The workaround I came up with
```javascript
//Create a React Hook Function
const EnableEmulators = () => {
  useFirestoreEmulator(getFirestore(), "localhost", 8080)
  useStorageEmulator(getStorage(), 9199)
}

useEffect(() => {
  //Call the function is the useEffect hook
  if (window.location.hostname === "localhost") EnableEmulators()
})
```

**Comment by Feiyang1** [comment]
Hmm, That's an unfortunate coincidence.

You can rename the import to workaround it:
`import { useFirestoreEmulator as applyFirestoreEmulator } from 'firebase/firestore'`

@yuchenshi, @samtstern, should we consider renaming the functions to avoid the conflict with react? (Given that React is really popular, so people are likely to run into this confusion).

@jhuleatt, any thoughts?

**Comment by codesby** [comment]
No problem at all the import as definitely is a better approach

**Comment by jhuleatt** [comment]
@Feiyang1's import solution will definitely solve it. Otherwise, since this is just an [eslint rule](https://www.npmjs.com/package/eslint-plugin-react-hooks), you can [disable the warning with an `eslint-disable-next-line` comment](https://eslint.org/docs/user-guide/configuring/rules#:~:text=To%20disable%20a%20specific%20rule%20on%20a%20specific%20line%3A):

```js
// eslint-disable-next-line react-hooks/rules-of-hooks
useFirestoreEmulator(getFirestore(), "localhost", 8080);
```

Either solution (renaming the import or the eslint ignore) will work for any of the emulator setup functions: `useAuthEmulator`, `useDatabaseEmulator`, `useFirestoreEmulator`, `useFunctionsEmulator`, `useStorageEmulator`.

**Comment by hsubox76** [comment]
If you don't like one-off line disables there's also some suggestions in this issue for configuring eslint to only apply the react eslint rules to files that use react. https://github.com/facebook/react/issues/15227#issuecomment-557556991
