### ISSUE TITLE
Firestore query "isEqual" returns false for identical queries that use a converter

### ISSUE THREAD

**Issue by gavingolden** [firebase/firebase-js-sdk#4989]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.4
  * Browser version: react-native in Expo
  * Firebase SDK version: 8.2.3
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Firestore `query.isEqual(otherQuery)` returns false for identical queries that are using a converter.

If this is solved by using the same converter instance then adding a note about this to the method documentation could prevent some tricky bugs.

#### Steps to reproduce:
Compare two identical queries that use a converter. Each query uses a separate converter instance.

#### Relevant Code:

```ts
function converter<T>() {
  return {
    toFirestore: (data: T) => data,
    fromFirestore: (snap: firebase.firestore.QueryDocumentSnapshot) => snap.data() as T,
  };
}

type A = object

const firstQuery = app.firestore().collection('A').withConverter(converter<A>())
const otherQuery = app.firestore().collection('A').withConverter(converter<A>())

const equal = firstQuery.isEqual(otherQuery) //   false
```

**Comment by schmidt-sebastian** [comment]
Hi @gavingolden, we are not able to compare JavaScript objects for semantic equality, since JavaScript only provides reference equality. While we debated allowing the user to specify a custom equality function, this would add complexity to our API that most user will not need. Instead, our `isEqual` check compares the references of the converters directly. Your queries should be considered equal if you provide the same instance of the converter:

```
function converter<T>() {
  return {
    toFirestore: (data: T) => data,
    fromFirestore: (snap: firebase.firestore.QueryDocumentSnapshot) => snap.data() as T,
  };
}

type A = object

const converterInstance = converter<A>();

const firstQuery = app.firestore().collection('A').withConverter(converterInstance)
const otherQuery = app.firestore().collection('A').withConverter(converterInstance)

const equal = firstQuery.isEqual(otherQuery) //   true
```
