### ISSUE TITLE
FR: allow skipping the precondition check in firestore's .update()

### ISSUE THREAD

**Issue by jessetane** [firebase/firebase-js-sdk#502]
Please consider allowing users to skip the precondition check in `.update()`. Passing `{ merge: true }` as the final argument to `.set()` does not do the same thing. As currently implemented, the API provides no way to replace a nested object without first doing a read to make sure the parent document actually exists.

I noticed at least two places in this module where the precondition check is hardcoded:
https://github.com/firebase/firebase-js-sdk/blob/453677f005d04e47be2324b9c1577051139652c0/packages/firestore/src/api/database.ts#L669
https://github.com/firebase/firebase-js-sdk/blob/453677f005d04e47be2324b9c1577051139652c0/packages/firestore/src/api/database.ts#L817

Note that the realtime database enforces no such precondition check for `.update()`, and that the firestore module for nodejs already allows passing a custom precondition via the final argument:
https://github.com/googleapis/nodejs-firestore/blob/51e076e19095217b6896c5ecd1d9a1b55d108e97/src/write-batch.js#L329

**Comment by mikelehen** [comment]
Can you explain why .set() with { merge: true } doesn't do what you want?

**Comment by jessetane** [comment]
> no way to replace a nested object without first doing a read to make sure the parent document actually exists

**Comment by jessetane** [comment]
Merge is great to have, I'm very glad it's been added! It doesn't provide a way to do what I described above though. Let me know if what I'm talking about is still unclear.

**Comment by jessetane** [comment]
Another way of describing the functionality I am missing might be "top-level-only merge".

**Comment by mikelehen** [comment]
It would be helpful if you could explain your use case more, but from your comments I'm going to guess that given a document that may not exist at all or may have contents like:

```
{
  top: {
    known_field: ...,
    unknown_field1: ...,
    ...
  }
}
```
You want to do:
```
doc.update('top', { known_field: 'new' });
```
And be guaranteed that any unknown fields are deleted...  In this case, `set(..., {merge: true})` would not be an option because if you just did:
```
doc.set({ top: { known_field: 'new' } }, { merge: true });
```
Then unknown_field1 would not be deleted.

Note that you _can_ do:
```
doc.set({ top: { known_field: 'new', unknown_field1: firebase.firestore.FieldValue.delete() } }, { merge: true });
```
But that's only an option if you know the fields you want to delete. If they are actually unknown, then you are correct that there is no single API call that accomplishes this.

There's a subtle and confusing history around the behavior of `set()` and `update()` and we're not eager to expose Preconditions in the mobile SDKs because they don't really play well with latency compensation.

Part of our assumption is that people will have a relatively static schema and therefore the presence of unknown fields won't be the common case. And when you do a partial update, you likely have some knowledge of the document's existence and do not want to accidentally create a partial document.

So in an effort to evolve the API in an optimal way, can you provide more details about your use case? What data you're storing and what kind of user experience you're building, including the exact circumstances that motivate the feature that you're asking for...  Thanks!

**Comment by jessetane** [comment]
Sorry for the delay - your example is exactly right.

Specifically, I had some data coming back from an external API where I couldn't know the exact structure and it would have been a bit uncomfortable to use a separate collection. So, I want to be able to create nested objects under a key, and always replace them completely whenever I get new data.

I don't actually think exposing preconditions is a good idea either (and from what you're saying about latency perhaps there's more to the story here). What I really want though is for firestore to get rid of set completely - `.update()` can optionally accept `{ merge: true }`, no?

There is never a time I care about the difference between update and create, so having to write a bunch of fussy code to choose the right verb is just annoying. If there was some special circumstance where I really did care, I would do a read first or use a transaction. RTDB had this right from a UX standpoint, why change?

**Comment by jessetane** [comment]
I should say `update()` _could_ accept the merge options - obviously that would mean changing the api.

**Comment by mikelehen** [comment]
Thanks for the feedback. I think I understand your use case now.  Comparing update() to RTDB is a bit of a red herring because in RTDB, update() was essentially just a batch set(), and Firestore has a specific batch write API for that.

In Firestore, update() exists as a convenient way to update an existing document that basically does two things differently than set:

1. It uses a precondition to verify the document exists to ensure that in the face of concurrent writers you don't end up accidentally creating a malformed document, e.g. because you did an update() after somebody else deleted it.
2. It interprets the passed object as a set of fields to update instead of as a document to write. This is subtle, but update() lets you do `update({top.nested.field: 'value'})` to update a single nested field in the document (`{top: { nested: { field: 'value' } } }`), whereas set() would create a top-level field named "top.nested.field" instead.

I think the API that would solve your use case and fit best with our design to date might be:
```
doc.set({ top: { ... } }, { mergeFields: ['top'] });
```

This would tell us that rather than merge everything, we would only merge the field `top`, overwriting any existing contents.  I'll bring this up with the team for consideration.

**Comment by jessetane** [comment]
Altering `set` so that it can (optionally) behave like `update` would be fine by me as well. I really do want the exact `update` functionality though, including dot-nested field addressing etc. Update the way it is great and works just the way I expect it to. I don't have problem 1. you describe (if I did I would make sure to use a transaction?) and just want the ability to use a single method to invoke all my write operations.

**Comment by jessetane** [comment]
Edit: `update` works just the way I expect it to... except for the precondition check.

**Comment by wilhuff** [comment]
Sorry for dropping the ball on this, but we did release a [`mergeFields`](https://firebase.google.com/docs/reference/js/firebase.firestore.SetOptions.html#mergefields) option to `set` as part of the [Firebase 5.0.0 release](https://firebase.google.com/support/release-notes/js#5.0.0) last May.
