### ISSUE TITLE
setDoc throws error when specifying documentReference that has an id set

### ISSUE THREAD

**Issue by jasonford** [firebase/firebase-js-sdk#5117]
Simple bug report for latest beta release (9.0.0 beta 6)

Seems like this is a reasonable thing to do to create a document with a specified id:
```javascript
addDoc(
  doc(
    collection(getFirestore(), "my-collection-name"),
    "SOME-SPECIFIED-ID"
  ),
  { documentData: 'here' }
)
```

But doing so results in:
```Uncaught FirebaseError: Invalid document reference. Document references must have an even number of segments, but my-collection-name/SOME-SPECIFIED-ID/koRSViiU5e1HStUVa5WY has 3.```

Looks like a generated id is being naively appended anyway...

Using setDoc(... instead of addDoc(... works just fine.

**Comment by looptheloop88** [comment]
Hi @jasonford, this is working as intended. If you use `addDoc`, Cloud Firestore will generate an auto ID for you. On the other hand, you must specify an ID for the document when you use `setDoc`. See this [documentation](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document) for your reference.

Since you've used `addDoc`, the ID is appended to the path and the reason for throwing the error.

**Comment by jasonford** [comment]
Makes sense, thank you.

Maybe a better error message is warranted here then, since with the new v9 API you can pass in a reference that has an id set for the doc added. Surely low priority on the backlog though... Thanks again!
