### ISSUE TITLE
Wiki documentation for running integration tests no longer work

### ISSUE THREAD

**Issue by pinarx** [firebase/firebase-js-sdk#516]
Running integration test Wiki no longer seems to work:

```
cd integration/messaging
yarn test

yarn run v1.3.2
error Command "test" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What is the best way to run directory specific tests.

@gauntface @jshcrowthe

**Comment by hsubox76** [comment]
Strange, none of the versions of this file during the time the issue was filed up til now would have had a nonexistent "test" script in package.json.  Test running is disabled, but typing the above series of commands currently results in a terminal message explaining tests were disabled due to flakiness.

Looking into fixing the actual tests should probably be an issue in itself though.
