### ISSUE TITLE
Firebase Error: Firebase Storage: `path` param cannot contain '..' (storage/invalid-argument)

### ISSUE THREAD

**Issue by pranab-witbybit** [firebase/firebase-js-sdk#5180]
* Operating System version: Windows 10 / Windows 11
  * Browser version: Chrome/91.0.4472.164
  * Firebase SDK version: 8.7.1
  * Firebase Product: storage

### Problem Description
Files with double dot in name not downloading in web, with the error given in the header.

#### Steps to reproduce:

- Upload a file with double dot in its name (such as test..txt). It will successfully upload. 
- Generate its downloadable url with its relative path
- Download

#### Relevant Code:

```javascript
   const storageRef = firebase.storage().ref(pathReference);
      storageRef
        .getDownloadURL()
        .then((url) => {
          window.open(url);
        })
        .catch((err) => { });
```

**Comment by looptheloop88** [comment]
Hi @pranab-witbybit, thanks for the report. I was able to replicate this issue when trying to get the download URL using path reference if the file type extension `(.txt)` is following a dot `(.)` character. I also confirmed that dot `(.)` character in between the file name is okay.

Not working
```
const pathReference = "images/test..txt";
const storageRef = firebase.storage().ref(pathReference);
storageRef.getDownloadURL()
  .then((url) => {
    console.log(url);
  })
  .catch((err) => { 
    console.log(err);
  });
```

Working
```
const pathReference = "images/te.st.txt";
const storageRef = firebase.storage().ref(pathReference);
storageRef.getDownloadURL()
  .then((url) => {
    console.log(url);
  })
  .catch((err) => { 
    console.log(err);
  });
```

On the other hand, it's also working fine if you get the download URL from the upload task snapshot.
```
storageRef.child(file.name).put(file, metadata).then(function (snapshot) {
  snapshot.ref.getDownloadURL().then(function (url) {
    console.log(url);
  });
}).catch(function (error) {
  console.log(error);
});
```

I am yet to find out if this is an intended behavior, since the SDK is able to catch the error. Let me check this out and update this if I have any information to share.

**Comment by nikhilag** [comment]
@looptheloop88 Kindly note that Android works fine with path containing double dots. Hence my guess that this behaviour is not intended.
