### ISSUE TITLE
I upgraded tslib deps to `^2.1.0` and this was released in 8.3.1. Let me know if it's still a problem.

### ISSUE THREAD

**Issue by jmargolisvt** [firebase/firebase-js-sdk#5199]
> I upgraded tslib deps to `^2.1.0` and this was released in 8.3.1. Let me know if it's still a problem.

_Originally posted by @hsubox76 in https://github.com/firebase/firebase-js-sdk/issues/4633#issuecomment-802321527_

I am still getting this issue with version 8.8.0.   Additionally, I am getting this error.

```
×
TypeError: Object(...) is not a function
Module.<anonymous>
node_modules/@firebase/firestore/dist/esm5/prebuilt-e10b3b00-01f089b3.js:4699
  4696 | /** Name of the IndexedDb object store. */ vr.store = "namedQueries", vr.keyPath = "name";
  4697 | 
  4698 | // Visible for testing
> 4699 | var mr = e(e([], e(e([], e(e([], e(e([], [ rr.store, ir.store, or.store, ar.store, hr.store, nr.store, lr.store, fr.store ]), [ pr.store ])), [ cr.store ])), [ dr.store ])), [ yr.store, vr.store ]), gr = "The current tab is not in the required state to perform this operation. It might be necessary to refresh the browser tab.", wr = /** @class */ function() {
  4700 |     function t() {
  4701 |         this.onCommittedListeners = [];
  4702 |     }

**Comment by hsubox76** [comment]
Can you give me the exact version of tslib your project has installed? `npm ls tslib` in your project should do it. (There might be multiple versions if you have multiple deps that require it.)

**Comment by jmargolisvt** [comment]
I was able to resolve this issue with `npm i ts-lib@latest` (which is 2.3.0).  I didn't need to have this manually installed previously.  It's true, I do have multiple deps that require it.  I see that a few of them are using `tslib@1.14.1` but my app is building ok again even with these version mismatches.

**Comment by hsubox76** [comment]
If you were stuck with an older version of tslib, a fresh npm install (sometimes requires first deleting `/node_modules` and `package-lock.json` or `yarn.lock` if using yarn) usually fixes it, since firebase's package.json specifies a range for tslib.

Anyway if anyone else is having this issue, do a `npm ls tslib` in your project and if the one under `firebase` isn't 2.1.0 or higher, try the fresh npm install or manually install the latest tslib if that doesn't work.
