### ISSUE TITLE
ReCaptchaV3Provider Typescript

### ISSUE THREAD

**Issue by zifahm** [firebase/firebase-js-sdk#5258]
Version 8.9.0

```

firebase
  .appCheck()
  .activate(
    new firebase.appCheck.ReCaptchaV3Provider(
      process.env.REACT_APP_RECAPTCHA_KEY
    ),
    true
  );

ts error: Argument of type 'ReCaptchaV3Provider' is not assignable to parameter of type 'AppCheckProvider'.
  Property 'getToken' is missing in type 'ReCaptchaV3Provider' but required in type 'AppCheckProvider'.
```

BTW the new version does not reflect the docs specified

Docs previous to version 8.9.0
```
firebase.initializeApp({
  // Your firebase configuration object
});

const appCheck = firebase.appCheck();
// Pass your reCAPTCHA v3 site key (public key) to activate(). Make sure this
// key is the counterpart to the secret key you set in the Firebase console.
appCheck.activate(
  'abcdefghijklmnopqrstuvwxy-1234567890abcd',

  // Optional argument. If true, the SDK automatically refreshes App Check
  // tokens as needed.
  true);
  ```

**Comment by kroikie** [comment]
FYI: this is also showing up in our [snippets repo](https://github.com/firebase/snippets-web/pull/216/checks?check_run_id=3281393210#step:7:20) which was bumped to `8.9.0`

**Comment by hsubox76** [comment]
There is a typings error in the main index.d.ts file. Fix is pending in https://github.com/firebase/firebase-js-sdk/pull/5261.

Both the provider argument and the string sitekey argument should be accepted (when the SDK is working correctly). Until the fix is released, you may be able to get around this temporarily with a `//@ts-ignore`.
