### ISSUE TITLE
Error messages are no longer human-readable with v9

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-js-sdk#5305]
As an example to illustrate the problem, let's say you are using the `auth` API to create a new account with `createUserWithEmailAndPassword` using the new version _9.0.0-beta.7_ of the SDK. If you pass an email address of an existing account, an error is thrown.

The problem I have is that with v9, the `message` property of the error object is not human-readable.

With v9, using `error.message` with the previous example, you get:

> Firebase: Error (auth/email-already-in-use).

Using v8:

> The email address is already in use by another account.

Is it an expected breaking change? More generally, is there a utility method or something with v9 to retrieve the default human-readable English message associated with an error code?

**Comment by Feiyang1** [comment]
yup, it is working as designed, and there is an [API](https://firebase.google.com/docs/reference/js/v9/auth.md?authuser=0#debugerrormap) to enable the detailed description. You'd need to import `debugErrorMap` and use `initializeAuth()` instead of `getAuth`:
```
import { debugErrorMap, initializeAuth } from 'firebase/auth';

initializeAuth(app, {errorMap: debugErrorMap});
```

You probably don't want include `debugErrorMap` in your prod build because it takes a lot of space.
