### ISSUE TITLE
FIrefox Private Browsing: A mutation operation was attempted on a database that did not allow mutations

### ISSUE THREAD

**Issue by piperone** [firebase/firebase-js-sdk#5377]
* Operating System version: _____macOS Big Sur 11.5.2
  * Browser version: _____ Firefox Developer Edition 92.0b6 (64bit)
  * Firebase SDK version: _____8.3.1
  * Firebase Product: _____ auth, firestore

#### Steps to reproduce:

I'm seeing the error "A mutation operation was attempted on a database that did not allow mutations" when starting my app in Firefox' private browsing mode. This was reported in #4069 and fixed in #4146 (8.1.2) so could this be a regression?

Exact error message:
`Uncaught (in promise) IndexedDbTransactionError: IndexedDB transaction 'getHighestListenSequenceNumber' failed: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

**Comment by dconeybe** [comment]
I've merged a fix to improve the error message: #5396.

Note that when you try to enable persistence in a Firefox private browsing session it is failing to open an IndexedDB connection and therefore is falling back to "memory persistence", a.k.a. no persistence. So firestore will still work just fine, but there will effectively be no persistence. Maybe this is acceptable since it is a private browsing session anyways which I'd expect wouldn't persist stuff.

**Comment by piperone** [comment]
- [x] Thanks for your work on this, I appreciate it. Even though fixing the error isn't possible at your end currently, a more descriptive error-message should help devs in the future.

For my particular app, I'll probably disallow using private browsing sessions; it's an app used by a small number of expert users. It doesn't make sense with private browsing in my usecase anyway. 

Thanks again!
