### ISSUE TITLE
Session Management with Service Worker with Session Persistence

### ISSUE THREAD

**Issue by dr-aiuta** [firebase/firebase-js-sdk#5404]
Hi, my question is very simple. The suggested approach on Firebase Docs for managing sessions with Service Workers only works if you use firebase.auth.Auth.Persistence.LOCAL while log in. I tried the same approach with firebase.auth.Auth.Persistence.SESSION and NULL is always returned from firebase.auth().onAuthStateChanged.

Is there an approach to use Service Workers with firebase.auth.Auth.Persistence.SESSION or do I have to stick with firebase.auth.Auth.Persistence.LOCAL? And, also, I think this should be stated on Firebase Docs, would save me a lot of time.

**Comment by sam-gc** [comment]
Hi @dr-aiuta, thanks for reaching out. Session is simply an implementation around [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) and therefore does not work in worker contexts. Thanks for the note about the docs, we can look into clearing that up. Would you mind linking to the specific docs page you were working from?

**Comment by dr-aiuta** [comment]
Thank you @sam-gc . The link is: https://firebase.google.com/docs/auth/web/service-worker-sessions

**Comment by maucaro** [comment]
I am having the same issue and would like to accomplish the same thing as @dr-aiuta . I opened this other [one](https://github.com/firebase/snippets-web/issues/235) prior to finding this one. If it helps, here is the [POC](https://github.com/maucaro/Concepto/tree/master/WebApp/wwwroot) code that works with the default (LOCAL) but doesn't work with SESSION. It is also based on the same service worker session post cited by @dr-aiuta .

**Comment by maucaro** [comment]
@sam-gc , can you please take a look at this again? I get it that Session would not work in worker contexts; the issue, however, is that if the UI (FirebaseUI) is set to use LOCAL (thus IndexedDB) as storage, things work as expected. If, however, the same UI opts for using Session (sessionStorage) the worker events are not fired as @dr-aiuta points out. I am seeing the same and have a pointer to POC code. I believe there is a code bug here. This is not simply a question or a documentation bug. Happy to answer any questions or perform any tests you think would help. Thanks!

**Comment by sam-gc** [comment]
Hi @maucaro, Firebase UI will interface with whichever Auth instance you give it. From the other issue you linked (https://github.com/firebase/snippets-web/issues/235), it sounds like you're setting session persistence in the DOM context (i.e. where Firebase UI is running) and then that value is not propagating to the worker. This is intended behavior---by setting session persistence in the DOM context w/ Firebase UI, all Auth actions within that context will be isolated to that session and by design won't update the workers. The only way to have Auth state shared between the page and the worker is to use `indexedDB` (by setting LOCAL persistence)
