### ISSUE TITLE
Package path . is not exported from package

### ISSUE THREAD

**Issue by rendomnet** [firebase/firebase-js-sdk#5456]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Electron 13
  * Firebase SDK version: "9.0.1"
  * Firebase Product: firebase js

### [REQUIRED] Describe the problem

I'm trying to add firebase to react-electron-boilerplate and after adding  "firebase": "9.0.1" to my package.json and running yarn.
I have this error.

```
ERROR in dll renderer renderer[14]
Module not found: Error: Package path . is not exported from package PATH\boiler\node_modules\firebase (see exports field in PATH\boiler\node_modules\firebase\package.json)

webpack compiled with 1 error
```

If I delete  "firebase": "9.0.1" from package.json then there is no error.

#### Steps to reproduce:
install react-electron-boilerplate and add firebase
https://github.com/electron-react-boilerplate/electron-react-boilerplate

firebase is the only package that gives me such error

**Comment by Feiyang1** [comment]
How do you import firebase? Note that `firebase` is not a valid import in v9, you need to import from sub modules like `firebase/app` , `firebase/auth`, etc.

**Comment by rendomnet** [comment]
@Feiyang1 it happens on the stage of installing firebase. 'yarn add firebase'. there is no imports added yet.

**Comment by jthegedus** [comment]
Vite.js started reporting these types of warnings recently as well:

- SvelteKit users seeing this from the internal Vite server: https://github.com/sveltejs/kit/issues/2384
- Vite.js code that silenced some of these warnings: https://github.com/vitejs/vite/pull/4873
- Vite.js package resolution errors being bubbled up: https://github.com/vitejs/vite/pull/4822

So yarn and Vite have started showing users errors with package resolution which seem to previously been hidden.

**Comment by Feiyang1** [comment]
@rendomnet What is the version of yarn? I couldn't reproduce it with `1.22.11`.

As I mentioned above, The "."  export is deliberately not defined for the `firebase` package, because it's not a valid import path. Tooling should not throw an error just because "." export is not defined, which is a perfectly fine use case.

**Comment by rendomnet** [comment]
@Feiyang1 yarn version 1.22.10

**Comment by hsubox76** [comment]
It looks like it's not actually a yarn install issue, it's something specific to the `electron-react-boilerplate` project (you said react-electron-boilerplate, but I'm guessing it's the same one or a very similar one). That project has a postinstall step that runs after yarn, which attempts to build the bundle with webpack. The "dll renderer" in the error messages (that's the name of the webpack config) indicates that this step is where the error is happening. If you can't figure out what that webpack config does, perhaps you can file an issue with `electron-react-boilerplate` and ask them if this is expected behavior.

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/2528e688ebfc8b477ab59b75d9a0cb5d49fb8988/package.json#L12
