### ISSUE TITLE
v9 Firebase Authentication session not persisting in localstorage

### ISSUE THREAD

**Issue by kisonay** [firebase/firebase-js-sdk#5481]
### Describe your environment

  * Operating System version: Mac OS 11.5.2
  * Browser version: All Latest Versions
  * Firebase SDK version: v9.0.2
  * Firebase Product: Authentication

### Describe the problem
I've decided to upgrade my application from v8 to v9, in v8 everything was working as expected but in v9 I am having issues with authentication persisting.

When I log in initially, I see the authentication object appear in localstorage/indexeddb (I've tried both) and all request to firestore, cloud functions, etc. work as expected and include the authorization header in their requests.

When I refresh the page (simple click of the reload button of the browser) this all changes. I see the localstorage/indexeddb key/value pair disappear. All future requests that require authentication fail since the authorization header is no longer present. 

The odd thing is that "onAuthChange" does see the session and acknowledges that the user is logged in but this information is not in localstorage and not used in any requests.

This all worked without issue in v8.

#### Steps to reproduce:

1. log in to create a session
2. navigation to confirm everything functions
3. reload browser window
4. functions no longer work

#### Relevant Code:
v9 sign in:
```javascript
export const auth = getAuth(firebaseApp);

export const firebaseSignIn = (email: string, password: string) => {
  return setPersistence(auth, browserLocalPersistence)
    .then(() => {
      return signInWithEmailAndPassword(auth, email, password)
        .then((userCredential) => userCredential)
        .catch((error) => ({
          error: 'Invalid username or password',
        }));
    })
    .catch((error) => ({
      error: 'Problem with authentication persistence.',
    }));
};
```
v9 on auth change (which detects the session on reload)
```javascript
export const auth = getAuth(firebaseApp);

onAuthStateChanged(auth, (user: any) => {
  console.log('AuthChange Detected', user)
   if (user) {
    // do something with user
  } else {
    signOut();
  });
```

localstorage after login:
<img width="1303" alt="localstorage-after-login" src="https://user-images.githubusercontent.com/1854267/132934729-9c2bdd9d-3477-438e-8e0f-c9a7cb564769.png">

localstorage after simple reload:
<img width="1303" alt="localstorage-after-simple-refresh" src="https://user-images.githubusercontent.com/1854267/132934732-e2f6eabe-0414-4622-bdab-b4fa36775a0f.png">

function call after login:
<img width="1232" alt="function-call-after-login" src="https://user-images.githubusercontent.com/1854267/132934765-0b4d674e-abaa-48ba-81dc-8ac148ca5ef9.png">

function call after simple reload:
<img width="1235" alt="function-call-after-simple refresh" src="https://user-images.githubusercontent.com/1854267/132934771-53bac79c-e27f-43ab-b8b6-6696813dc3d6.png">

**Comment by kisonay** [comment]
To add... I experience the same behavior using the old auth methods with firebase/compat and v9

**Comment by sam-gc** [comment]
Thanks @kisonay for the report. I will dig into it. In the mean time, you can likely mitigate this by initializing Auth manually with `browserLocalPeristence` and avoiding the call to `setPersistence` entirely. For example, instead of `getAuth()`, you would do:

```js
const auth = initializeAuth(app, {
  persistence: browserLocalPersistence,
  popupRedirectResolver: browserPopupRedirectResolver
});

// And to sign in:
export const firebaseSignIn = (email: string, password: string) => {
  return signInWithEmailAndPassword(auth, email, password)
      .then((userCredential) => userCredential)
      .catch((error) => ({
        error: 'Invalid username or password',
      }));
  });
};
```

**Comment by kisonay** [comment]
@sam-gc , thanks. Just tried initializedAuth as above and am still seeing the same behavior. Works great until the page reloads, then the localstorage key is cleared and all further communication is not authorized.

**Comment by kisonay** [comment]
I just tried to update my example repo with this change and it is actually working as expected. 

Within my actual app I am seeing the same behavior of the session being cleared from local storage. Aside from a handful of dependencies and the fact that the other project is TypeScript, I'm not sure why they would be behaving differently. 

Would a TypeScript implementation make a difference?

**Comment by kisonay** [comment]
I tried to update my example repo with this change and it is actually working as expected.

After a lot of digging within my app, I determined that this occurs when the signOut module is loaded (it does not need to be called, just exported)

```
export const firebaseSignOut = signOut(auth).catch((error) => console.error(error));
```

I added a new branch with the above code replicating the issue.

https://github.com/kisonay/firebase-auth-example/tree/initilize-auth

Additionally, if you change firebaseSignOut to the following, the issue is no longer present:

```
export const firebaseSignOut = () => signOut(auth).catch((error) => sendError(error));
```

**Comment by hsubox76** [comment]
In the first line you've actually called `signOut()` and you're assigning the result of that call to `firebaseSignOut`. In the second line you've created a function that calls `signOut()`, which I believe is what you want.

**Comment by sam-gc** [comment]
@kisonay is this issue resolved?

**Comment by kisonay** [comment]
@sam-gc yes, when getAuth and setPersistance is used, the issue is reproducible. (this can been seen in the master branch of my example repo.)

The workaround does wok once I address the signout function.

**Comment by sam-gc** [comment]
I just tried the snippet. A couple things are going on here I think...

1. `getAuth()` preferentially initializes with `indexedDB` persistence as well as `localStorage`. Because `indexedDB` is available when the auth library initializes, _the SDK moves the user persistence out of `localStorage` and into `indexedDB`_. To verify this, click over into the indexedDB tab and click the "refresh" icon (indexedDB inspector won't update automatically)... you'll see the user. This is why the user does show up in the `onAuthStateChanged` callback. If you inspect the `auth` object, you'll also see that `auth.currentUser` is populated correctly _after onAuthStateChanged fires_.
2. Functions and Firestore are not authenticated correctly... This bit is the part that needs debugging, I think. Without seeing the code it's hard to say what's going on. How soon after initialization do you call functions? The call should happen _after_ `onAuthStateChanged` fires for the first time. `getAuth()` returns synchronously with an `auth` object, but initialization is async... it won't have the `currentUser` field immediately.

As an aside, why does the code `setPersistence` to `localStorage` before performing the sign in? This seems like a bit of an antipattern---if you only want to use `localStorage`, you should use `initializeAuth` with only `browserLocalPersistence`. Not only will this reduce the bundle size by removing the `indexedDB` code, it will also prevent data bouncing around between multiple persistence layers.
