### ISSUE TITLE
Firebase: Error (auth/popup-closed-by-user) in Firefox v92.0

### ISSUE THREAD

**Issue by harry-herskowitz** [firebase/firebase-js-sdk#5491]
When using signInWithPopUp for Google login, I am receiving this error:
`Firebase: Error (auth/popup-closed-by-user).`
Sign in works perfectly in Chrome.

**Comment by jbalidiong** [comment]
Hi @roldyclark, thanks for reporting this. I tried replicating this behavior on `compat` and modular auth with `firebase@9.0.0` but I wasn't able to encounter the same behavior. However, at first I encountered `auth/popup-blocked` because of the default setting of Firefox. After allowing the pop-up, I successfully signed-in. Here is a sample snippet for v9:

```
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";

    firebaseApp = initializeApp(firebaseConfig);

  const signInWithGoogle = async (e) => {
    const provider = new GoogleAuthProvider();
    signInWithPopup(firebaseAuth, provider)
      .then((result) => {
        console.log(details.isNewUser);
      })
      .catch((error) => {
        console.log(error);
      });
  };
```

If you could provide me with a reproducible code, it will help me have a better look into it.

**Comment by roldyclark** [comment]
Thanks for the response! Here's some code:
```
const app = initializeApp(firebaseConfig)

export const auth = getAuth()

export const googleProvider = new GoogleAuthProvider()

export function googleLogin() {
  signInWithPopup(auth, googleProvider)
}
```
I'm using onAuthStateChanged instead of .then

**Comment by jbalidiong** [comment]
Thanks for the additional details. I forgot to add that I've also used the `onAuthStateChanged` and it's working as intended. I'll wait for your minimal, but complete sample of a project that I can run locally.
