### ISSUE TITLE
rawNonce missing from credential - Firebase Auth v9

### ISSUE THREAD

**Issue by roldyclark** [firebase/firebase-js-sdk#5553]
rawNonce missing from OAuthProvider credential.
Code:
```
  const provider = new OAuthProvider('apple.com')
  const credential = provider.credential({
    idToken: result.credential?.idToken,
    rawNonce: result.credential?.nonce
  })
  console.log(credential)
```
Result:
```
idToken: <myIDToken>
pendingToken: null
providerId: "apple.com"
signInMethod: "apple.com"

```

**Comment by sam-gc** [comment]
Hi, thanks for reaching out! A couple of things are going on here: for one, the `nonce` field was never getting set in the credential since the SDK didn't pass it through correctly to the underlying method. Separately from that, the `nonce` field was not documented in v8 and it is not exposed in any of our other SDKs. So while the PR linked will set the field correctly (so that e.g. `signInWithCredential` will work as expected), the field itself will now be marked `private`.
