### ISSUE TITLE
OAuthCredential.fromJSON() doesn't work

### ISSUE THREAD

**Issue by koroman17** [firebase/firebase-js-sdk#5608]
I want to auto link  a user credential signed in with facebook provider to its google user
```
const handleGetRedirectResult = async () => {
        try {
                const result = await getRedirectResult(auth)
                if (result.user) {
                        const savedCredential = window.sessionStorage.getItem('credential')
                        if (savedCredential) {
                                const credential = OAuthCredential.fromJSON(savedCredential)
                                linkWithCredential(result.user, credential)
                                        .then((linkResult) => {
                                                const linkCredential = OAuthProvider.credentialFromResult(linkResult);
                                                return signInWithCredential(auth, linkCredential);
                                        })
                                        .catch((error) => {
                                                console.log("Account linking error", error.message);
                                        });
                        }
                }
        } catch(error) {
                if (error.code === 'auth/account-exists-with-different-credential') {
                        const credential = FacebookAuthProvider.credentialFromError(error)
                        window.sessionStorage.setItem('credential', credential.toJSON())
                        signInWithGGRedirect()
                }
        }
}
```
but after it runs to `const credential = OAuthCredential.fromJSON(savedCredential)`, it silently stops without saying anything

**Comment by sam-gc** [comment]
Hi @koroman17, thanks for reaching out.

I think what's happening here is the initial saving of the credential is incorrect. The `toJSON()` function returns an object with the serialized values (see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior)), but it doesn't convert the value to a string. Since `sessionStorage` only operates on strings, bad values end up getting written instead (in Chrome, for example, your code would write `'[object Object]'` to `sessionStorage`. Instead, you should call `JSON.stringify(credential)` which will use the `toJSON()` method under the hood.

I'm not sure why the `fromJSON` function isn't throwing an error (it does in my tests), but regardless this code should work:

```js
sessionStorage.setItem('credential', JSON.stringify(credential));

// Later
const cred = OAuthCredential.fromJSON(sessionStorage.getItem('credential'));
await signInWithCredential(auth, cred);
```

Please give that a shot and see if it fixes the problem.

**Comment by koroman17** [comment]
It works now. Thanks a lot!
