### ISSUE TITLE
Warning when starting new React Native project using firebase

### ISSUE THREAD

**Issue by ottob** [firebase/firebase-js-sdk#5641]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.6
  * Browser version: n/a
  * Firebase SDK version: 9.1.3
  * Firebase Product: all

### [REQUIRED] Describe the problem

A warning is printed when I try to launch my new react native project using firebase firestore.
Same issue as #2850 but with additional information.

Since it's only a warning that doesn't seem to have any consequence this is not a high priority issue. But it causes confusion.

#### Steps to reproduce:

using react native 0.66
npx react-native init MyApp --template react-native-template-typescript@6.8.0
cd MyApp
yarn add firebase@9.1.3
`yarn start` in one terminal and `yarn ios` in another

This results in the following warning:
> warn Package firebase has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /home/user/rnfirestorebug/node_modules/firebase/package.json

But firebase (firestore is what I tested) seems to work anyways.

#### Relevant Code:
https://github.com/ottob/rnfirestorebug

**Comment by byCedric** [comment]
I think this is more of an issue from Node itself. The new `exports` field was introduced as a good alternative for `main`, to simply have multiple entry points. But in practice, it behaves more like a guard to prevent "private" or non-exported packages. 

In React Native and other platforms combining node + native code, we often have to fetch information about the package. Some good examples are [validating if the user installed a compatible package version](https://github.com/expo/expo-cli/blob/34d972657bad805ca09bd3956eaad255445ae3de/packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts#L94-L112). Or instructing the native code to [load certain native files from the package directory (which may be different in monorepos)](https://github.com/expo/expo/blob/master/templates/expo-template-bare-minimum/android/app/build.gradle#L85). Without adding `package.json` as exports, we lose the ability to fetch that information. And again, I think that's more an issue caused by Node.

With Expo, we try to work around this issue by [catching the `ERR_PACKAGE_PATH_NOT_EXPORTED` error, and try to manually load the `package.json`](https://github.com/expo/expo-cli/pull/3878/files). But, that's not a great workaround. Adding `package.json` would at least give back the ability to fetch that meta info. Luckily, [there is an ongoing discussion about allowing importing the `package.json`, even when it's not exported](https://github.com/nodejs/node/issues/33460).

(Sorry for the long story, I thought this might help add some context to the issue)

**Comment by hsubox76** [comment]
Oh it looks like we did do this. https://github.com/firebase/firebase-js-sdk/pull/5646
