### ISSUE TITLE
FR: Expose timestamps on DocumentSnapshot

### ISSUE THREAD

**Issue by forest** [firebase/firebase-js-sdk#570]
The current Node SDK exposes `readTime`, `createTime`, and `updateTime` on the `DocumentSnapshot` class. See: https://github.com/googleapis/nodejs-firestore/blob/f23c167b32dd550df6d659833c162bac9367abd9/src/document.js#L196

It would be great to expose these as well for the Web SDK. 

Something like the below can be added to `DocumentSnapshot` to expose `updateTime`, but more work is required to pass the other two values through from the Serializer.

```
  get updateTime(): Timestamp {
    return this._document!.version.toTimestamp()
  }
```

I'm happy to work on this, but wanted some guidance as to how the team would like this done.

**Comment by schmidt-sebastian** [comment]
Thanks for sending over this feature request. We have considering adding these metadata fields before, but haven't quite found a reasonable to make them work with local edits, offline persistence and latency compensation. Can you let us know what the specific use cases are that you have in mind?

Note that you can use FieldValue.serverTimestamp() if you are just interested in the update time.

**Comment by forest** [comment]
I was starting to add a created and updated timestamp to some of my documents and then saw these values already exist and are updated by firebase. I didn't want to duplicate the work if they existed and could be easily exposed.

Does the NodeJS SDK not have the same syncing issues?

I would still need to add my own timestamps to documents for query and sort anyway I guess, so maybe it isn't worth the effort.

**Comment by schmidt-sebastian** [comment]
The NodeJS Server SDK only ever returns data as sent from the backend. As such, it has access to the metadata that is provided to us. The Mobile Web SDK is written to work over spotty networks, and as such, it returns local edits right away (even before these values are acknowledged by the server). When you make a local edit and see the corresponding event, it is likely that the SDK does not yet know what the correct updateTime is.

**Comment by forest** [comment]
Makes sense. Probably best to close this FR and reconsider in the future.

**Comment by mikelehen** [comment]
Closing, but thanks for the feedback!  For now adding these fields yourself (likely using FieldValue.serverTimestamp()) is the recommended approach and works better with local edits.

**Comment by NawarA** [comment]
I'd like this added as well. 

Consider this approach:

Given you're model is eventually consistent, it should be understood the "create, read, last update timestamps" values will converge to the correct values over time / spotty networks, etc

Also some of the fields are static, like create time, so a spotty network shouldn't effect this value.

Please add this feature. It should be simple to do, and creates consistency in what your Firestore API documentation says it does, and actually does. 

Much appreciated by the way!

**Comment by bseib** [comment]
I have a use case where we want to know the server timestamp when a firestore document is _read_. Consider:

Computer A updates a structure in Firestore with these fields like this:
```
ref.doc(monitorId).set({
  monitorId,
  broadcasterId: this.broadcasterId,
  payload,
  modifiedAt: firebase.firestore.FieldValue.serverTimestamp(),
}, { merge: true })
```

Computer B reads that structure as it is updated. *Or* computer B opens a the webpage `n` minutes later, which reads that structure. Computer B wants to know how many seconds old `modifiedAt` is so that it can display an accurate age since `modifiedAt`. If I use a local timestamp on computer B as the `readTime`, there's skew in the timestamps -- apples and oranges. We want to know the server's notion of `readTime` to get an accurate representation of the document's age since `modifiedAt`.

It seems that the `fromCache` boolean in `DocumentSnapshot`'s `metadata` already serves as a warning that you are reading data from the server or not. So reading a `readTime` field from `metadata` along with the `fromCache` flag would properly tell you what you want to know. Perhaps a more accurate property name would be `serverReadTime`, added to the `metadata`:

![image](https://user-images.githubusercontent.com/1313561/63904094-c9140a80-c9dd-11e9-85d6-18acd7cc4508.png)

The use case I am describing is when two computers are sharing data, specifically wanting to determine the document age & timestamps _strictly_ from the server's perspective. So if I'm offline, `serverReadTime` is moot, and that's perfectly okay.

**Comment by wilhuff** [comment]
That's very interesting!

For documents we've read from the server we'll always have a read time even if you're offline.

For documents that only exist locally (i.e. that have been written but not yet committed to the server) we'd have no read time at all. What do you think of a nullable/optional read time?

**Comment by mikelehen** [comment]
For what it's worth, because of how our synchronization works, we likely won't update the "read time" of a cached document every time you read it .  So I'm not sure we could expose a sane contract for what a "read time" that we surface actually represents since it's basically dependent on details of our synchronization protocol.  The only thing you could assume is that the document is up-to-date at least as of the specified readTime (but that readTime could be days ago even if you just read the document).  So I don't think this is a good solution for your use case.

If the problem you're trying to solve is clock skew then you could make a request to a trusted time source (maybe https://stackoverflow.com/questions/13240530/free-rest-api-to-retrieve-current-datetime-as-string-timezone-irrelevant helps) or even just have the client write a dummy server timestamp to Firestore and use the resolved time as a hint as to your local clock skew.
