### ISSUE TITLE
Type definition mismatch for user.metadata

### ISSUE THREAD

**Issue by mhatvan** [firebase/firebase-js-sdk#5729]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 21.10
  * Browser version: Brave Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
  * Firebase SDK version: 9.3.0
  * Firebase Product: auth

#### Steps to reproduce:

When calling `auth.onAuthStateChanged()`, I want to use `user?.metadata.lastLoginAt` to access the last logged in timestamp.

When I `console.log()` the values of `user?.metadata`, it contains these values:

```
createdAt: "1636562135825"
creationTime: "Wed, 10 Nov 2021 16:35:35 GMT"
lastLoginAt: "1636702595091"
lastSignInTime: "Fri, 12 Nov 2021 07:36:35 GMT"
```

The interface in `auth-public.d.ts` for `UserMetadata` looks like this:

```
/**
 * Interface representing a user's metadata.
 *
 * @public
 */
export declare interface UserMetadata {
    /** Time the user was created. */
    readonly creationTime?: string;
    /** Time the user last signed in. */
    readonly lastSignInTime?: string;
}
```

Therefore, TypeScript reports the property for `lastLoginAt` and `createdAt` as missing, although they exist.

**Comment by sam-gc** [comment]
Hi @mhatvan, this is working as expected. Those two fields are private to the SDK implementation; the public fields expose the same information but in a different format. See:
https://github.com/firebase/firebase-js-sdk/blob/882d86481fb9b269f4ee200a70ecbc6287c822c7/packages/auth/src/core/user/user_metadata.ts#L22-L36

**Comment by mhatvan** [comment]
I do need them in number format.

If they are private to the SDK, why can I access them? Shouldn't every property that the user can consume also be typed and not throw a TS error?

**Comment by sam-gc** [comment]
It's not a property that is intended for the user to consume, which is why it's marked `private`. `private` is simply a TypeScript construct of course, and JavaScript has no concept of "private" members beyond various naming conventions. On the SDK we've chosen to simply follow TypeScript convention.

I'd recommend getting the number format by creating a `Date` object and then calling `getTime()`. We can discuss exposing that field differently or exposing the number value as well, but that's a feature request that changes the SDK surface, which will have to undergo internal consideration.
