### ISSUE TITLE
null is not an object (evaluating 'RCTAsyncStorage.multiMerge')

### ISSUE THREAD

**Issue by haveamission** [firebase/firebase-js-sdk#5767]
* Operating System version: MacOS Monterey Beta 12.1
  * Browser version: Chrome version 96.x
  * Firebase SDK version: 9.5.0
  * Firebase Product: auth, analytics

#### Steps to reproduce:
Upgraded to Expo SDK 43 and got the following error:

![image](https://user-images.githubusercontent.com/10475533/144000560-88995f21-c60a-46f0-9f20-6787ea6a5493.png)

Does not happen if I mock my exports as such:

```javascript
const auth = () => {};

const analytics = () => {};

export default { auth, analytics };
```

#### Relevant Code:

```javascript
import { getAuth, onAuthStateChanged } from "firebase/auth";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { getReactNativePersistence } from "firebase/auth/react-native";
import { getAnalytics } from "firebase/analytics";

let config = {
...
};
let auth = initializeAuth(config, {
  persistence: getReactNativePersistence(AsyncStorage),
});
let analytics = getAnalytics(config);
export default { auth, analytics };
```
I have also tried `let auth = getAuth(config);` with the same result for auth.

Not sure exactly what's causing this issue, but definitely seems to be some confluence of AsyncStorage and Firebase, as that's the only time it ever occurs

**Comment by jbalidiong** [comment]
Hi @haveamission, thanks for reaching out to us. I tried replicating the issue, however, I wasn't able to experience the same behavior.

The first debugging I did was create a blank expo app in SDK 43. I've added the specific dependencies and paste the code you've provided above. I run the `expo start` and select the run on Android/emulator and didn't encounter the null is not an object error.

**Comment by jbalidiong** [comment]
Hi @haveamission, thanks for reaching out to us. I tried replicating, but I wasn't able to reproduce the error.

First attempt on replicating the issue was creating a new expo app in SDK 43. I've added the dependencies and pasted the code you've provided. I ran the expo start and selected the "Run on Android device/emulator" and it ran as expected. Though I always receive a warning message about "Warning: Async Storage has been extracted from react-native core and will be removed in a future release." and use the "@react-native-async-storage/async-storage".

I also tried creating an expo app with an older version of Expo SDK then upgrading it to SDK 43. Added the dependencies and
code but no errors encountered. If you could provide me with a reproducible code, it will help me have a better look into it.
