### ISSUE TITLE
`Uncaught (in promise) unimplemented` being thrown when calling loadBundle from firebase/firestore

### ISSUE THREAD

**Issue by Jac0xb** [firebase/firebase-js-sdk#5838]
### [REQUIRED] Describe your environment

  * Operating System version: 19042.1415
  * Browser version: 95.0.2 (64-bit)
  * Firebase SDK version: 9.6.1
  * Firebase Product: firebase/firestore

### [REQUIRED] Describe the problem

`Uncaught (in promise) unimplemented` being thrown when calling `loadBundle`

Being thrown from:

https://github.com/firebase/firebase-js-sdk/blob/cdada6c68f9740d13dd6674bcb658e28e68253b6/packages/firestore/src/util/byte_stream.ts

#### Relevant Code:

```ts
// where bundle.data is text string of bundle output.

await loadBundle(fs, bundle.data);
```

**Comment by schmidt-sebastian** [comment]
Can you let us know a little more about your setup? Where are you running this? You are likely missing polyfills for TextEncoder, but I cannot say without knowing more about your environment.

**Comment by Jac0xb** [comment]
A react app with firebase/firestore imports.

**Comment by schmidt-sebastian** [comment]
@wu-hui We likely need to use a different TextEncoder/TextDecoder for ReactNative.

@Jac0xb You should be able to work around this in the meantime by polyfilling a TextEncoder such as https://github.com/samthor/fast-text-encoding

**Comment by Jac0xb** [comment]
> @wu-hui We likely need to use a different TextEncoder/TextDecoder for ReactNative.
> 
> @Jac0xb You should be able to work around this in the meantime by polyfilling a TextEncoder such as https://github.com/samthor/fast-text-encoding

Requiring fast texting encoding still throws the error, do I need to override a global with the require?

**Comment by MegaMaddin** [comment]
Hello!

I stumbled across this today, when trying to load a bundle on the client using an `ArrayBuffer` instead of a `ReadableStream` or a `string`. From looking at the traces the error seems to happen once the [toByteStreamReaderHelper](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/util/byte_stream.ts#L33) is called. I guess this function should mimic a readable stream from the passed data array. I don't know if this is intended but the reader property [closed](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/util/byte_stream.ts#L62) is calling `Promise.reject('unimplemented')` upon initialization instead of being a cb/function pointer to it.

Although this error is thrown, the loading of the bundle works as expected. Anyone from Google who can verify my suspicion?
