### ISSUE TITLE
'Component auth has not been registered yet' after getting auth following app init (following docs exactly!)

### ISSUE THREAD

**Issue by Viggo2** [firebase/firebase-js-sdk#5877]
**Environment**
Operating System version: macOS 10.15.2
Browser version: Chrome 97.0.4692.71
Firebase SDK version: 9.something, can't find exact number
Firebase Product: auth

**Describe the problem**
Upon invoking getAuth on the result of a supposedly successful initializeApp call, it throws the following error —

Error: Component auth has not been registered yet

**Steps to reproduce:**
Invoke initializeApp on a valid firebase config
Pass the result of step 1 as a parameter to getAuth
Relevant Code:
```
const firebaseApp = initializeApp(firebaseConfiguration);
const firebaseAuth = getAuth(firebaseApp); // throws
```

**PS**
* I am aware this has been asked before, and I have practically copied it, but I after hours of googling and a question on Stack Overflow I can't get my issue solved.
*  Not passing the result of initializeApp to getAuth throws me an `app/no-app error`. Not sure if this is of use. 
* Also, I have managed to get this to work before, and even after changing which project is initialized to test, it still doesn't work.
* I am following the docs *exactly*, without adding anything else.

I can't do anything with Firebase while this issue is here.

Thanks in advance if you can help.

**Comment by argzdev** [comment]
Hi @Viggo2, perhaps there's a missing step on your setup.

Maybe you could create a clean project, and try the following below:

Assuming you're using `npm`

1. Create a project using npm via cmd
- Use cmd and redirect to your project folder
- Execute `npm init` to create a new project
- After it finishes creating a new project, execute `npm install firebase` to add Firebase to your project.

2. Create a web app in the Firebase console
3. Create a `index.mjs` file in your project folder, add the following code below, and paste the firebaseConfig details from your Firebase console:

```
import { initializeApp } from "firebase/app";
import { getAuth, signInAnonymously } from "firebase/auth";

const firebaseConfig = {
  apiKey: ...,
  authDomain: ...,
  databaseURL: ...,
  projectId: ...,
  storageBucket: ...,
  messagingSenderId: ...,
  appId: ...,
  measurementId: ...
};

const app = initializeApp(firebaseConfig);
const auth = getAuth();

signInAnonymously(auth)
.then(() => {
    console.log("works")
})
.catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    console.log("errorCode: " + errorCode)
});
```

This should work when you run `node index.mjs` from your cmd. If you have further questions about this, you may reach out to our [Firebase support](https://firebase.google.com/support), they can guide you and help you setup your project. With that said, since this doesn't seem like an SDK issue, but rather, a setup issue, I'll be closing this for now. Feel free to ask any follow up questions. Thanks!

**Comment by Viggo2** [comment]
I believe this is what I have already done - what is your suspected missing step? Also BTW, I use JSX in the Node module (this) in `.jsx` files.

Thanks for your effort : )
