### ISSUE TITLE
FR: True passwordless email sign in

### ISSUE THREAD

**Issue by omar2205** [firebase/firebase-js-sdk#5926]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11
  * Browser version: Chrome v97.0.4692.71
  * Firebase SDK version: 9.6.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Add a true way (cross devices) to sign in the user with email. Either a way to subscribe to the user (email verification, display name, and profile picture updates) or some other functionality.

**Comment by sam-gc** [comment]
Hi @omar2205, would you mind expanding a bit on what you'd like to see? Does [Email/Link](https://firebase.google.com/docs/auth/web/email-link-auth) sign in provide the feature set you're looking for?

**Comment by omar2205** [comment]
The problem I'm facing is that the email link auth method doesn't work across devices, it needs to happen on the same device, from signing in to redirecting back to the app. 

It's not possible for users to sign in on the phone and confirm their email on the desktop, where they might be logged in in their email inbox.

For a true passwordless experience, the app needs to send a verification email and wait for the user on any device to confirm it.

**Comment by sam-gc** [comment]
If I understand correctly, you're asking for a sort of (short, for human entry) one-time password that is sent to an email and can be used  for sign in on any device? We will make note of that in the tracking bug (b/217189225). I can't provide any timelines or assurances that we will add this feature, but we will keep this bug open to track interest.

**Comment by omar2205** [comment]
Not necessarily a code. Could be a link, that when visited, triggers the sign-in process.

**Comment by sam-gc** [comment]
That actually already works: the link sent to the user's email will work on any device. The user will just need to provide their email and you'll have to manually call the sign-in function if it's on a different device. You'd do this using the [`signInWithEmailLink`](https://firebase.google.com/docs/reference/js/auth.md#signinwithemaillink) function. (You can use the [`isSignInWithEmailLink`](https://firebase.google.com/docs/reference/js/auth.md#issigninwithemaillink) function when your app loads to present the right UI).

I'm going to go ahead and close this issue for now since the request is met under the current feature set, but feel free to comment / reopen if you're unable to get this to work

**Comment by omar2205** [comment]
How would that work If I tried to sign in from my phone and opened the email on my desktop? I will need to share the link between these devices. When the user visits the link, it should complete the sign-in process on the other device.

**Comment by sam-gc** [comment]
As I understand it, you would like to be able to send a link on `Device A`, follow the link on `Device B`, then have `Device A` sign in as well? That would be a pretty big security vulnerability: one could simply put in the email of a target account, then wait for that target user to unwittingly follow the link. There's no proof that `Device A` owns the account in this case.

**Comment by omar2205** [comment]
Then how would a cross-devices flow work? Send a code with the email?
