### ISSUE TITLE
Firestore: onSnapshot triggers onNext when setDoc fails

### ISSUE THREAD

**Issue by hlynurstef** [firebase/firebase-js-sdk#6026]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Monterey version 12.2.1 (21D62)
  * Browser version: Google Chrome Version 98.0.4758.102 (Official Build) (arm64)
  * Firebase SDK version: 9.6.7
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

When you have a `onSnapshot` listening to a collection and you then separately call `setDoc` that fails for some reason (security rules don't allow it for example), then the `onNext` callback will trigger in the `onSnapshot` with the failed document, then `onNext` will trigger again but with the failed document removed.

Expected:
If setDoc fails, then the `onSnapshot` `onNext` callback should not be triggered.

#### Steps to reproduce:

1. Call `onSnapshot` with a query to some collection
2. Call `setDoc` but make sure it fails (for example by setting `if write: false` to the security rules)
3. Observe that even though `setDoc` failed, `onSnapshot` will still trigger the `onNext` callback with the document we tried to set
4. The `onSnapshot` will then trigger the `onNext` callback again but without the document that we tried to set

#### Relevant Code:

Repo with reproduction:
https://github.com/hlynurstef/setDoc-onSnapshot-bug

Example console output:
```
Snapshot received: []
Before setDoc
Snapshot received: [ { id: 'new-doc' } ]
[2022-02-23T13:12:35.088Z]  @firebase/firestore: Firestore (9.6.7): Connection GRPC stream error. Code: 7 Message: 7 PERMISSION_DENIED: Missing or insufficient permissions.
setDoc error: [FirebaseError: 7 PERMISSION_DENIED: Missing or insufficient permissions.] {
  code: 'permission-denied',
  customData: undefined,
  toString: [Function (anonymous)]
}
Snapshot received: []
```

**Comment by wu-hui** [comment]
Hi @hlynurstef 

The SDK does an optimization called latency-compensation: local writes will surface to matched queries before the server accepts the writes. This is so that user can see they writes quicker than waiting for the network roundtrip (and backend processing). 

In this case, the backend rejects, and the raised snapshot has to be removed. If you do not want to see snapshots until backend accepts the writes, then one option is to use `doc.get({source: server})`. This is not an active listener however. We currently do not have a way to specify whether you want snapshots to be raised only from backend changes, unfortunately.

All in all, the current behavior is likely going to remain unchanged, and we might consider adding some options for users to specify what they want in the future. I am closing this issue for now, but feel free to keep discussing.

Thanks.

**Comment by hlynurstef** [comment]
Hi @wu-hui 

Thanks for the reply. I understand the reasoning behind this behavior, it's however causing unexpected behavior in the application I'm working on (which I can probably solve some other way) but being able to configure this would be great.
