### ISSUE TITLE
Reserved urls import problem.

### ISSUE THREAD

**Issue by Jehong-Ahn** [firebase/firebase-js-sdk#6055]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.1
**Platform:** Windows

### [REQUIRED] Test case

hosting below.
```
<script type="module">
import { initializeApp } from '/__/firebase/9.6.7/firebase-app.js';
import { getFirestore } from '/__/firebase/9.6.7/firebase-firestore.js';

const app = initializeApp({ projectId: "foo" });
const db = getFirestore(app);
console.log(db.type);
</script>
```

### [REQUIRED] Steps to reproduce

None.

### [REQUIRED] Expected behavior

1. No error.
2. The browser requests for two scripts.

### [REQUIRED] Actual behavior

1. Error `Service firestore is not available`
For debug, the firestore provider has no *component* property.
2. Three scripts.
`/__/firebase/9.6.7/firebase-app.js`
`/__/firebase/9.6.7/firebase-firestore.js`
`https://www.gstatic.com/firebasejs/9.6.7/firebase-app.js` - because the local firestore.js imports remote app.js 

If I import from gstatic.com not reserved urls `/__`, there are no problems.

**Comment by dconeybe** [comment]
Hello @Jehong-Ahn. I'm not totally clear on how you are using the Firebase/Firestore SDK. Could you quickly create a GitHub repository that I could clone and reproduce for myself?

**Comment by hsubox76** [comment]
This sounds like a common problem when importing two copies of firebase-app, which seems to be the case here. When that happens, product components like `firestore` register with one of the app copies, and not the other, and when your code runs the one that firestore didn't register with, you'll get that messasge. I'm not sure I understand your explanation for why you need to use the gstatic copy of firebase-app.js in addition to the hosted version ("because the local firestore.js imports remote app.js"), can you explain further?

In any case I don't think this is a Firestore related problem, but it may be a hosted url problem which is worth looking into, if you can clarify.
