### ISSUE TITLE
Callback function registered with onMessage not called on new message after 30 seconds

### ISSUE THREAD

**Issue by tbaud0n** [firebase/firebase-js-sdk#6064]
* Operating System version: Ubuntu 20.04
  * Browser version: Firefox 98.0 (64-bit)
  * Firebase SDK version: 9.6.8
  * Firebase Product: messaging

Steps to reproduce:

1. Get a token
2. Register the onMessage callback
3. Send a notification that should be received by the user
4. The callback is called as expected
5. Wait 1 minute
6. Repeat the step 3
7. The callback func is not called

If messages are received with less 30 seconds of waiting time the callback is called
**This bug happens only with Firefox. The callback is called on each notification received with Google chrome**

```javascript
import { initializeApp } from 'firebase/app';
import { getMessaging, onMessage, getToken } from 'firebase/messaging';

const firebaseApp = initializeApp({/*...*/ });
const messaging = getMessaging(firebaseApp);
const registration = await navigator.serviceWorker.register('/firebase-messaging-sw.js');
getToken(messaging, { vapidKey: MyVapidKey, serviceWorkerRegistration: registration })
    .then((newToken) => {
        if (!newToken) {
            console.log('No registration token available. Request permission to generate one.');
        }

        onMessage(messaging, (payload) => {
            console.info('Received message');
            registration.showNotification(payload.data.title, { body: payload.data.body });
        });
    });

```

**Comment by tbaud0n** [comment]
Hi @jbalidiong, thanks for testing.
Yes, I can reproduce the issue everytime. I'll test with different notification options to ensure that the issue is not related to Firefox and I'll come back to you.

**Comment by jbalidiong** [comment]
I tried it again and I still get all the notification. I also tried creating a scheduled notification with 1 minute gap and the onMessage callback was triggered as intended. I noticed that the `onMessage()` is inside the `getToken()`, by design it should be on the top level. I'll also provide you the [quickstart](https://github.com/firebase/quickstart-js/tree/master/messaging), as that should be working fine, to send test notifications to. If it persists, please provide a minimal but complete example to run it locally and further investigate the issue.
