### ISSUE TITLE
FR: interchangeable use of Timestamp and other objects between frontend and backend

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#6114]
### [REQUIRED] Describe your environment

  * Operating System version: any
  * Browser version: any
  * Firebase SDK version: 9.x
  * Firebase Product: firestore

**Problem description:**
We have code that is shared between our frontend (angular) and backend (google cloud functions node).
The idea is great and for the most part it works like a charm.
However the firebase types always have been very difficult to share, but we've managed.
Now a new problem came up that when we do:
![image](https://user-images.githubusercontent.com/1098243/161296818-a0a0f741-ce3f-4758-b652-849fa5ba0b70.png)
with the import being:
![image](https://user-images.githubusercontent.com/1098243/161296980-6c507422-a718-4922-9e6f-debed8d7146a.png)
we get an error, that we found out after a search is because we're now trying to use the backend implementation in our front-end app.
![image](https://user-images.githubusercontent.com/1098243/161297201-129e46bd-42eb-4115-8545-9a14726d2591.png)

In the end, our request would be the same as mentioned here:
https://github.com/firebase/firebase-js-sdk/issues/4129
is there any progress on using the back-end and front-end types interchangeably?

**Comment by wu-hui** [comment]
This request has come up many times, and we decided not to do it because mixing the client/server types together is not really a good idea, in our opinion.

It used to be the client classes look similar to the server ones, and it is understandable some times it makes things easier to have them compatible. With the V9 SDK, these classes look more different now, and it now makes even less sense to do it.

I will close this request, feel free to keep commenting on if you have a strong opinion, or you have some use cases where compatibility would bring great benefits.

Thanks!

**Comment by laurentpayot** [comment]
@LanderBeeuwsaert maybe https://github.com/firebase/firebase-admin-node/discussions/1238 could be helpful to you…
