### ISSUE TITLE
The js sdk makes request for my firebaseConfig on start, even though I already bundled the config?

### ISSUE THREAD

**Issue by ZYinMD** [firebase/firebase-js-sdk#6170]
### [REQUIRED] Describe your environment

- Operating System version: Win10
- Browser version: Chrome v101
- Firebase SDK version: ^9.6.5
- Firebase Product: auth, firestore, callable functions

#### Steps to reproduce:

- Launch my web app in browser, observe web traffic in the devTools.
- A request will be made to `https://firebase.googleapis.com/v1alpha/projects/-/apps/{{my_app_id}}/webConfig`. The response will be exactly the same as my project config that I have bundled.

Since I already bundled the info, is this request still important? What happens if it fails? 

I have this question because my users are behind certain firewalls that block some firebase traffic and I'm researching on workarounds with proxies, and want to have a good understanding of all firebase traffic. Thanks!

**Comment by hsubox76** [comment]
Are you using Firebase Analytics? This endpoint is used by Firebase Analytics to fetch the measurement ID from your project config dynamically. If this call fails, you should get a warning or error logged to the console. If a measurement ID was provided in your local config object (passed to initializeApp) it will try to use that for analytics instead, and log a warning that it is doing so, although this isn't the recommended usage.

**Comment by hsubox76** [comment]
Yes, using the endpoint is the primary path. Only if it fails will it fall back to using the local measurement ID. Relying on the local measurement ID isn't recommended and the functionality may be removed in the future. The decision was made to rely on the measurement ID from the dynamic config because there are cases where measurement IDs may change in a project on the back end without the local measurement ID being updated.

**Comment by ZYinMD** [comment]
Thanks!
