### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#6266]
I promise to keep only this issue open for questions that might arise.

1. How can I use the [setLogLevel](https://firebase.google.com/docs/reference/js/app.md#setloglevel) function? Same question for [registerVersion](https://firebase.google.com/docs/reference/js/app.md#registerversion) and [onLog](https://firebase.google.com/docs/reference/js/app.md#onlog). I didn't find any examples of these functions online. I am struggling to understand their purpose and how to use them.
2. Do all errors thrown inherit from [FirebaseError](https://firebase.google.com/docs/reference/js/util.firebaseerror.md#firebaseerror_class)? Even when not explicitly said so? For example, the [deleteApp](https://firebase.google.com/docs/reference/js/app.md#deleteapp) method throws an error if I don't call [initializeApp](https://firebase.google.com/docs/reference/js/app.md#initializeapp) beforehand, but this isn't documented.

**Comment by jbalidiong** [comment]
Hi @marcusx2, thanks for reaching out. I noticed that some of your questions are about how to use the API, you can use our [support channel](http://firebase.google.com/support) for these types of inquiries. However, checking our documents, we don't have an example for it. Here is a code snippet on how to use the [`setLogLevel()`](https://firebase.google.com/docs/reference/js/app#setloglevel) and [`onLog()`](https://firebase.google.com/docs/reference/js/app#onlog):

```
import { initializeApp, setLogLevel, onLog} from 'firebase/app';

initializeApp(firebaseConfig);
setLogLevel('debug');

onLog((e) => {
    const { level, message } = e;
      if (level === 'warn') {
        console.log('connection interruption after intial load was success:', message);
      }
      if (level === 'error') {
        console.log('no connection on inital load:', message);
      }
      if(level === 'debug') {
          console.log('debugging logs:', message);
      }
      if(level === 'info') {
          console.log('info: ', message);
      }
  });
```

As stated in our documents, " `setLogLevel()` will set the log level for all Firebase SDK and all of the log types above the current log level are captured". And you can use the `onLog()` to setup custom log handler.

Regarding `registerVersion()`, we're using it for internal purposes and it's publicly exposed because some frameworks also use it for their internal metrics. 

For the `FirebaseError`, we aim to make it so that all errors thrown by the SDK are wrapped in `FirebaseError` but there will always be exceptions that we don't catch and wrap. I'll be closing this for now. Feel free to comment and reopen this issue if you're able to find one, please let us know and we'll add it to our to-do list.

**Comment by hsubox76** [comment]
As mentioned above, for questions about how to best use Firebase, try contacting the support channel:

> Hi @marcusx2, thanks for reaching out. I noticed that some of your questions are about how to use the API, you can use our [support channel](http://firebase.google.com/support) for these types of inquiries.

Or other sources of development expertise such as Stack Overflow. We also have a [discussion board](https://github.com/firebase/firebase-js-sdk/discussions) in this repo, but it may have less frequent replies.

If you find a bug, or something that might be a bug, feel free to open an issue for it.

**Comment by marcusx2** [comment]
What [category](https://firebase.google.com/support) should I pick? None of them seem appropriate for my question. Stackoverflow's firebase section doesn't seem very helpful either since I made [a question](https://stackoverflow.com/questions/72034161/how-can-i-construct-a-user-from-a-user-json) and nobody replied.

The most help I got was from here. I promise I won't bother you guys much, I created just this issue for my questions. Can you please help me? I promise I won't make a question again for at least 6 months. I will truly try not to bother you guys. Thanks for your understanding.
