### ISSUE TITLE
FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error)

### ISSUE THREAD

**Issue by ohjs88** [firebase/firebase-js-sdk#6278]
### [REQUIRED] Describe your environment

  * Operating System version: macOS catalina
  * Browser version: Chrome 100.0.4896.127
  * Firebase SDK version: 9.6.11
  * Firebase Product: app_check

#### Steps to reproduce:

The appcheck library spits the error log indefinitely.

@firebase/app-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).
@firebase/app-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).
@firebase/app-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).
...

The Chrome "Network" tab displays only one 403 message.

https://content-firebaseappcheck.googleapis.com/v1beta/projects/xxx/apps/xxx:web:f5ad206c896ced2ae1b42a:exchangeRecaptchaToken?key=blabla...

{
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED"
  }
}

This is a problem that occurred from today in the service that is operating normally for a few days.

#### Relevant Code:

```javascript
const firebaseapp = initializeApp(firebaseConfig);
const appCheck = initializeAppCheck(firebaseapp, {
  provider: new ReCaptchaV3Provider("my-key"),
  isTokenAutoRefreshEnabled: true,
});
```

**Comment by minuitagency** [comment]
same issue, anybody has the solution? Thanks

**Comment by hsubox76** [comment]
Usually a 403 "App attestation failed" means that the recaptcha request failed, so basically recaptcha decided that the session was not valid. This can happen if there is something odd about the behavior of the session, or in my case one time, because my recaptcha key had an excessive number of requests somehow and was locked. I made a new recaptcha key and registered it in the Firebase console and it worked again.

If you check your reCAPTCHA Admin Console it might be able to tell you if it's been getting errored requests.

Another possible cause is if anyone has changed the reCAPTCHA key registered in the Firebase console.

There should be two sets of requests. The first set should go to the recaptcha endpoint (https://www.google.com/recaptcha/api2/reload) and return a payload that's not very human readable. This gets the reCAPTCHA score for the session which validates if the user is not a bot, etc. The second set of requests should go to the App Check exchange endpoint (https://content-firebaseappcheck.googleapis.com/v1/), and contain the reCAPTCHA score. If the App Check decodes the reCAPTCHA score and finds it insufficient, it will send the 403.

So it might also be worth checking the reCAPTCHA requests (to https://www.google.com/recaptcha/api2/reload) and making sure they came back with some kind of data.

**Comment by obumnwabude** [comment]
It is also worth adding domain names of your app to the Domains section of the recaptcha admin console.

**Comment by hsubox76** [comment]
Were you able to resolve this by looking into if reCAPTCHA was working?

**Comment by NickVanzo** [comment]
I have this problem too, do somebody know how to fix this?

**Comment by feriteja** [comment]
if it's running in localhost environment, The developer's guide now states:

"If you would like to use "localhost" for development, you must add it to the list of domains."

This will only work if you access localhost using 127.0.0.1 rather than localhost

so to solve this just add 127.0.0.1 to Domain in captcha console
