### ISSUE TITLE
FirebaseError: Firebase: Error (auth/network-request-failed) while using Firebase emulator with Android

### ISSUE THREAD

**Issue by PaulWozny** [firebase/firebase-js-sdk#6322]
### Describe your environment

  * Operating System version: macOS 12.3.1
  * Browser version: not sure if is relevant, since I am using firebase-js with expo for React Native
  * Firebase SDK version: 9.8.2
  * Firebase Product: auth
  * **Firebase cli tools**: 11.0.1

### Describe the problem

I am unable to use Firebase simulator from Android device. Invoking functions `createUserWithEmailAndPassword`, `signInWithEmailAndPassword` always return error `auth/network-request-failed`. I confirmed it on multiple virtual and hardware devices.
iOS simulator and web works, the issue is just with Android

#### Steps to reproduce:
- download firebase cli
- `firebase init` -> emulators -> just auth 
- `firebase emulators:start --only auth`
- clone repo https://github.com/PaulWozny/expo-firebase-android-error
- `yarn`
- `expo start`

Be aware that inside `metro.config.js` is a workaround for https://stackoverflow.com/questions/72158122/expo-firebase-authentication-while-trying-to-resolve-module-idb-from-file

#### Relevant Code:

Error log:
```
WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.

Error: ENOENT: no such file or directory, open '/Users/xxxx/Workspace/expo-firebase-android-error/http:/192.168.0.24:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/xxxx/Workspace/expo-firebase-android-error/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/xxxx/Workspace/expo-firebase-android-error/node_modules/metro/src/Server.js:1022:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server._processRequest (/Users/xxxx/Workspace/expo-firebase-android-error/node_modules/metro/src/Server.js:429:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/xxxx/Workspace/expo-firebase-android-error/http:/192.168.0.24:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false'
}

[Unhandled promise rejection: FirebaseError: Firebase: Error (auth/network-request-failed).]
at http://192.168.0.24:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:122281:321 in _createSuperInternal
at node_modules/@firebase/util/dist/index.esm2017.js:791:8 in FirebaseError#constructor
at node_modules/@firebase/util/dist/index.esm2017.js:819:22 in ErrorFactory#create
at node_modules/@firebase/auth/dist/rn/phone-dd9c6425.js:359:10 in _fail
at node_modules/@firebase/auth/dist/rn/phone-dd9c6425.js:943:25 in tslib.__generator$argument_1
at node_modules/tslib/tslib.js:144:21 in step
at node_modules/tslib/tslib.js:125:60 in <anonymous>
at node_modules/tslib/tslib.js:116:50 in rejected
```

**Comment by yuchenshi** [comment]
In https://github.com/PaulWozny/expo-firebase-android-error/blob/fc0b3064e512ae584010e72da5e5adea88c610e8/App.tsx#L38, there are two issues:

1. There's an extra `}` symbol in `http://127.0.0.1:9099}`. I believe that is a typo.
2. Unlike iOS Simulator and web (in your browser), the Android emulator does not run on `127.0.0.1`. See https://firebase.google.com/docs/emulator-suite/connect_firestore#android code snippets for the explanation, but tl;dr in the Android emulator, `10.0.2.2` is the special address that must be used to connect to host ports instead of `127.0.0.1`.

I've noticed that you mentioned using React Native, which allows you to reuse the same code across platforms. This means you'll need some logic in your code to tell if the app is running on Android emulator. I believe React Native may provide a function or constant for that, but I'm going to close this issue since that is outside of the scope of the Firebase JS SDK. Please do report back if you've found a solution, and we'll see if we can improve our documentation somehow.

**Comment by PaulWozny** [comment]
Thanks, it worked! 
> we'll see if we can improve our documentation somehow.
It's edge case when one uses React Native with web version of Firebase, in my case - with Expo.
https://firebase.google.com/docs/emulator-suite/connect_auth#android
![image](https://user-images.githubusercontent.com/11949188/171998462-aac46ee1-bf19-424e-8e52-ccbf8d5ccae0.png)
![image](https://user-images.githubusercontent.com/11949188/171998471-02826257-b0c5-4126-ab27-298761ee8f2d.png)
