### ISSUE TITLE
auth._getAdditionalHeaders is not a function

### ISSUE THREAD

**Issue by stefandouw** [firebase/firebase-js-sdk#6382]
### Describe your environment

  * Operating System version: Windows 10 Pro 19044.1766
  * Browser version: Chrome 102.0.5005.115
  * Firebase SDK version: 9.8.3
  * Firebase Product: auth

### Describe the problem

Making any API request with auth fails due to generic error: auth/network-request-failed. Upon following the stack trace I found that in the function _performApiRequest, additional headers are being retrieved with the function auth._getAdditionalHeaders() however this function doesn't exist on the auth object. This makes it impossible to implement authentication in my product.

![trace](https://user-images.githubusercontent.com/9696122/175280378-ae46e1a8-f18a-4627-8c38-f6d8290d52c7.PNG)

Hopefully this can be resolved soon otherwise I can't go to production.

**Comment by sam-gc** [comment]
Hi @stefandouw, would you mind sharing a small example that demonstrates this issue? The (internal) Auth class does in fact implement this method: 
https://github.com/firebase/firebase-js-sdk/blob/8c52a96edac5b65501ee4eeb234c4bb8e70a5dd5/packages/auth/src/core/auth/auth_impl.ts#L619

(Also worth noting that your screenshot is source-mapped from minified code meaning the function may exist just with a different name, which is why it appears not to exist in the interpreter... Are you able to "step into" that function?)
