### ISSUE TITLE
upgrade @firebase/polyfill core-js

### ISSUE THREAD

**Issue by MHDuke** [firebase/firebase-js-sdk#6503]
npm WARN deprecated core-js@3.6.5: 
`core-js@<3.23.3` is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. 

Please, upgrade your dependencies to `>=3.23.3` of core-js.

**Comment by g-30** [comment]
second this

**Comment by dorji-tshering** [comment]
Same issue here. Just installed firebase right now. I hope it will be resolved soon!

**Comment by MarwanSdeek** [comment]
same issue while installing the latest firebase@9.9.2.

**Comment by playtinum** [comment]
Bump

**Comment by hsubox76** [comment]
So the good news is that `core-js` code isn't used in the code for any Firebase SDK products installed through NPM. It was included in `@firebase/polyfill` package which is currently only bundled into the compat CDN builds (where Firebase is included using script tags, and applying only to urls that end with `-compat.js`). We forgot to remove it from the dependencies in package.json (which is why it's installing during yarn/npm install) but the code isn't imported into any Firebase code.

NPM users and users of the v9 CDN scripts shouldn't need to worry. I'll remove `@firebase/polyfill` from the dependencies and you should stop getting that warning after the next release.

As of v9 we've stopped updating `@firebase/polyfill` and expect users to provide their own so I'll also remove the polyfill import from the compat CDNs.
