### ISSUE TITLE
Electron createUserWithEmail

### ISSUE THREAD

**Issue by marcibk** [firebase/firebase-js-sdk#6749]
Hi there, 
I´am using `"firebase": "^9.12.1"` and electron `"electron": "^21.0.1"`. 
While using development mode on `mainWindow.loadURL("http://localhost:4000"); ` `createUserWithEmailAndPassword` works fine. When using 
```
mainWindow.loadURL(
      url.format({
        pathname: path.join(__dirname, "renderer/index.html"),
        protocol: "file:",
        slashes: true,
      })
    );
```
(production mode) I get 
```
FirebaseError: Firebase: Error (auth/network-request-failed).
    at S (index-909bd8f4.js:474:41)
    at _ (index-909bd8f4.js:448:12)
    at index-909bd8f4.js:1012:31
```

First I thought that the built electron app has no internet, but a fetch request proved this wrong. I have an internet connection. Did some research and found out, that google auth is not working on local files due to security reason, but `createUserWithEmailAndPassword`? Why I get an `auth/network-request-failed` error when using production mode?

**Comment by hsubox76** [comment]
Someone from the auth team can probably provide further answers, but since Electron is kind of a special case I wanted to provide some background for any auth team members looking into this. See [this article](https://medium.com/firebase-developers/using-firebase-in-electron-tips-and-tricks-24ac5b44bf5a) (section: "Issues with signInWithPopup() or signInWithRedirect()") which explains why Electron using the `file://` protocol doesn't play nice with signInWithPopup and signInWithRedirect(). I'm not sure if this sheds any light on issues with `createUserWithEmailAndPassword()` or if it's a completely separate issue, so hopefully someone from the auth team can expand on that.

**Comment by sam-gc** [comment]
Is this code running in the electron "DOM" or is it running in a Node-only process? Sometimes what can happen is that the Node version of the JS SDK is used when in the DOM code, or vice versa. The key is to force your build to use the browser target instead of the Node target
