### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token ..." from v9.8 on

### ISSUE THREAD

**Issue by actionakin** [firebase/firebase-js-sdk#6771]
### [REQUIRED] Describe your environment

  * Operating System version: Linux armv7l (Samsung Tizen TV)
  * Browser version: Safari/537.36
  * Firebase SDK version: 9.8.0 + 
  * Firebase Product: performance, remote config (That I have tested)

### [REQUIRED] Describe the problem

At runtime I'm getting an "Uncaught SyntaxError: Unexpected token ..." error.

#### Steps to reproduce:

I have project bundled with webpack and transpiled via babel to work on a range of Samsung TV models.  I have browserlists set to support Safari 7 as the baseline.    I was able to resolve this by downgrading from the latest version all the way down to v9.7 which works as expected. 

#### Relevant Code:
n/a

**Comment by jfcong** [comment]
Hi @actionakin, can you provide some relevant stack traces/the actual error?

**Comment by actionakin** [comment]
`Uncaught SyntaxError: Unexpected token ...
    at Object.Yg32 (vendors~main.41a8a1e….debug.js:8585)
    at __webpack_require__ (main.536180d….debug.js:86)
    at eval (index.esm2017.js?c6c1:1)
    at Module.xsHj (vendors~main.41a8a1e….debug.js:14572)
    at __webpack_require__ (main.536180d….debug.js:86)
    at eval (index.esm.js?4b38:1)
    at Module.SzhR (vendors~main.41a8a1e….debug.js:7264)
    at __webpack_require__ (main.536180d….debug.js:86)
    at eval (lgj+:16)
    at Module.lgj+ (main.536180d….debug.js:8706)`

**Comment by actionakin** [comment]
The error is happening in this module:
/***/ "Yg32":
/*!******************************************!*\
  !*** ../node_modules/idb/build/index.js ***!
  \******************************************/

**Comment by jfcong** [comment]
Hi @actionakin, can you give us a sample app and steps to reproduce this? The error doesn't seem like it's Performance Monitoring related at first glance since it's happening in a node module.

**Comment by hsubox76** [comment]
I think this was caused by upgrading the `idb` dependency in 9.8.0: https://firebase.google.com/support/release-notes/js#version_980_-_may_06_2022

That would mean something about the build tooling or environment is not compatible with the latest version of `idb`. https://github.com/jakearchibald/idb

I don't suppose you can try to figure out what would need to be changed in `idb` in order to make it work in this environment? Since I don't have access to your specific build setup I can't really debug it myself. If possible, you could also provide a minimal repro an we could look into it. The caveat is that `idb` isn't owned by us, so if we find something wrong with it, we'd either have to ask the maintainer to fix it, or use something else.

**Comment by actionakin** [comment]
Hey @hsubox76,

I figured out the issue with the 2017 Samsung Tizen TV's.  If you look here at the [Web Engine Specifications ES6 support](https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html#JavaScript-(ES6)) you'll see that es6 isn't fully supported, specifically Classes, Default parameter values, & Destructuring assignment syntax.  It seems that in dropping support for ie 11, any non-es6 supporting device has also been dropped.  My solution is to make sure to run firebase modules through babel to transpile it to es5.
