### ISSUE TITLE
firestore request

### ISSUE THREAD

**Issue by CyrusZei** [firebase/firebase-js-sdk#679]
Hi guys, 

I am not sure if I follow along with your docs on firestore security rules and stuffs, but my brain wants to write the rule like this

`allow read: if get(/databases/{database}/documents/privateevents/$(privateeventId)).data.friends[request.auth.uid].invited == true`

tell me why this is not working and maybe you guys could use this as example on how users reads the secuirty rules on the docs ?

Love what you guys are doing, but I think that you are overcomplicating some stuffs :D 
I would more than glad to be a beta tester on the user doc and give you guys feedback

keep upp the good work guys

**Comment by mikelehen** [comment]
Hi @CyrusZei Thanks for reaching out, but this probably isn't the best place to ask for help on Firestore Security Rules unless you think there's a bug in the Firebase JS SDK related to them.  You may want to try asking on https://groups.google.com/forum/#!forum/google-cloud-firestore-discuss or Stack Overflow instead.  And in order for somebody to help you, you'll likely need to either ask a more specific question about a rules feature or provide more context about your situation (especially your data structure) so that somebody can understand what you're trying to do with your rule.  Thanks / sorry!

**Comment by CyrusZei** [comment]
Thanks, man, I sure will do that. It was just a thought and input. Thank you for taking the time
