### ISSUE TITLE
Safari shows inconsistent behaviour when using enableIndexedDbPersistence or enableMultiTabIndexedDbPersistence

### ISSUE THREAD

**Issue by boldtrn** [firebase/firebase-js-sdk#6806]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 11.7.1
  * Browser version: Safari 16.1
  * Firebase SDK version: 9.12.1-9.14.0
  * Firebase Product: firestore

#### Steps to reproduce:

When I enable the IndexedDbPersistence on Safari, sometimes Safari is not showing any query results. I also can't see any network activity with Firestore in the Network tab of the browser. Safari does not reject enabling persistence.

The biggest issue from my side is, that it sometimes works fine, sometimes it doesn't. It works fine on Chrome / Firefox.

We have seen this issue on 9.12.1 and 9.14.0, not sure if this existed before as well.

I think this could be related to https://github.com/firebase/firebase-js-sdk/issues/4076 - where we also faced the same issue and had to disable persistence again https://github.com/firebase/firebase-js-sdk/issues/4076#issuecomment-865380173.

#### Relevant Code:

```javascript

enableMultiTabIndexedDbPersistence(firestore).catch((err) => {
        // This is not called on Safari, so persistence is "enabled"
        console.error('Cannot enable MultiTabPersistence', err);
});

```

**Comment by tom-andersen** [comment]
Thank you for reaching out. This might be difficult to support without a reproducible example.

To help reproduce, does this problem only occur when there are multiple tabs or there is interaction using console?

If you can trigger this problem intermittently, can you provide some debug logs of events leading up to incident.
See https://firebase.google.com/docs/reference/js/firestore_#setloglevel
`firestore.setLogLevel('debug');`

The log along with code that produced log will go a long way in helping us reproduce the problem.

**Comment by tom-andersen** [comment]
Good observation! I looked into the code to see what could be blocking between those timestamps. Having an example that I can debug will be helpful. Could you email the URL to tomandersen@google.com. Thanks! I will do my best to look closer at this as soon as possible.

**Comment by boldtrn** [comment]
Thanks for the quick reply and for looking into this. I have sent you an email with the requested details. Let me know if there is anything else I can do to help.

**Comment by tom-andersen** [comment]
Hey @boldtrn.

Sorry for the less than quick reply this time.

I am experiencing the same problem as you with the site you provided. However, I am also experiencing the Indexed Database access via Develop -> Show Page Resources to be unresponsive as well. That the developer tools become stuck as well indicate to me that the Safari implementation of IndexedDB has entered an unresponsive state. Other than trying to avoid triggering this behaviour, I don't think there is much to be done until Safari provides a more robust implementation of IndexedDb.

You might be able to mitigate the problem by changing the link to navigate without reloading the page. Meaning, instead of `<a href="...">...</a>`, use javascript similar to your other navigation within app. I can confirm that if I navigate away from the page to something like "http://google.com" and then back again, the problem disappears. But if I just navigate around on the site use `<a href="...">...</a>`, the problem persists. This leads me to believe that opening IndexedDb in succession for the same site has a weak spot that brings IndexedDb into an unresponsive state.

Unfortunately, I can also trigger this situation by simply opening additional tabs, to the same site. So this is not a complete work around if your customers use multiple tabs.

I will need a simplified reproducible example to run on my computer to do further work.

**Comment by gunnarmein-ts** [comment]
FWIW, this behavior happens to us ONLY when reloading the page after a Firebase sign-out, thankfully. We are now reloading the page through an automatic redirector on a different domain, in accordance with your suggestion. On Safari only. Seems to work for us so far.
