### ISSUE TITLE
Firebase Callable Functions: Uncaught Error: Service functions is not available 

### ISSUE THREAD

**Issue by pfiadDi** [firebase/firebase-js-sdk#6810]
### [REQUIRED] Describe your environment

  * Operating System version: mac 11.2.1
  * Browser version: Chrome 106
  * Firebase SDK version: 9.10, 9.14.,9.13.X
  * Firebase Product: functions

When I try to initialize functions with:

`const functions = getFunctions(fbApp,"europe-west3")`

I get: Uncaught Error: Service functions is not available 

I post this issue again, because the solutions (reinstall firebase with clean cache, other versions) all didn't work.

I create a repo with a minimum of code I use, where the bug can hopefully be reproduced:

https://github.com/pfiadDi/firebasec-callable-function-bug

In the readme, everything is explained how to reproduce it.

**Comment by pfiadDi** [comment]
I also added a second branch, with only uses cdn imports and no bundler (in my case parcel)
https://github.com/pfiadDi/firebasec-callable-function-bug/tree/without-parcel

Without bundlers it works, so the question is, is it a problem with parcel? Not sure, since the other issues also happend when using bundlers

**Comment by hsubox76** [comment]
Thanks for providing the repro. I don't fully understand the structure of your app but it seems like somehow it seems like `initializeApp()` and `getFunctions()` are being treated like they're being run in separate... runtimes? Or modules? 

 If I put everything in the same file: 
 ```
 //import "babel-polyfill";
import { firebaseConfig } from "../firebaseConfig";
// import { initApp } from "../submodules/elm-firebase-new/ts/init/init";
import { initializeApp } from "firebase/app";

import { getFunctions } from 'firebase/functions';
const fbApp = initializeApp(firebaseConfig(window.location.host));

const functions = getFunctions(fbApp,"europe-west3")
```

It seems fine? It doesn't really seem like you need a wrapper around `initializeApp()`, but you know your own code best so it's up to you how you deal with it. But It seems like whatever's going on in src/index.js and whatever's going on in submodules/elm-firebase-new/ts in your project is being treated like separate namespaces ? somehow. I guess it's parcel or elm or something?

It doesn't seem like a bug with the SDK but let me know if you discover something indicating otherwise and I'll reopen this.
