### ISSUE TITLE
RulesTestEnvironment.clearFirestore() fails with nodejs 18.x

### ISSUE THREAD

**Issue by atsjo** [firebase/firebase-js-sdk#6836]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11
  * Browser version: Chrome/Edge latest/nodjs 18.12.1
  * Firebase SDK version: 9.14 (@firebase/rules-unit-testing 2.0.5)
  * Firebase Product: firestore @firebase/rules-unit-testing

#### Steps to reproduce:

When clearing firestore data after/before running unit tests against the firestore emulator, the RulesTestEnvironment.clearFirestore() method fails with below error. This works fine on nodejs 16.x, might be somehow related to nodejs 18 supporting fetch natively, or maybe related to trying to access emulator via ipv6. Everything else in my tests work fine with node 18, they all complete successfully if not using this method to clear data.

#### Relevant Code:

```
FetchError: request to http://localhost:8080/emulator/v1/projects/task4s-dev/databases/(default)/documents failed, reason: connect ECONNREFUSED ::1:8080
  at ClientRequest.<anonymous> (../../node_modules/node-fetch/lib/index.js:1491:11)
```

**Comment by MarkDuckworth** [comment]
Hi @atsjo, thanks for reporting. We will look into this and get back to you.

**Comment by yuchenshi** [comment]
Context: Node.js 18 has introduced a breaking change that prefers IPv6 over IPv4: https://github.com/nodejs/node/issues/40537 . We have introduced some workarounds to this problem, see previous discussion on https://github.com/firebase/firebase-tools/issues/4741.

The workarounds work the best if you run your tests through `firebase emulators:exec "./your-test-script"` where hosts and ports are automatically discovered. If you must use manual configuration, try specifying `127.0.0.1` explicitly instead of `localhost`.

```js
  env = await firebaseTesting.initializeTestEnvironment({
    projectId: "demo-project",
    firestore: {
      host: "127.0.0.1", // <----
      port: 8080,
    },
    /* ditto for other emulators */
  });
```

I'm closing this since this is ultimately a Node.js issue and there's a limit on what the testing library can do here. Feel free to share more about your use case (including test code samples, command to run the tests, etc., GitHub repo preferred) if you have any ideas to further improve this.

**Comment by atsjo** [comment]
Changing from localhost to 127.0.0.1 worked for me, so problem solved! I didn't really look into solving it, but noticed  ::1 was the address in the error message, so should have tried this myself:-) I'm running this through nx using jest and are also testing some functions via firebase-functions-test. I's running though the @nrwl/jest:jest executor
