### ISSUE TITLE
FR: [api-documenter] Allow specifying custom _project.yaml and _book.yaml paths.

### ISSUE THREAD

**Issue by markmcd** [firebase/firebase-js-sdk#6957]
### Describe your environment

  * Firebase SDK version: HEAD / tag 9.15.0
  * Firebase Product: `firebase-js-sdk` -> `api-documenter`

### Describe the problem

I'd like to be able to use this `api-documenter` fork, but the `Project: ...` and `Book: ...` metadata is hard-coded to use specific paths. Ideally having both point to the same place (`/foo/_project.yaml` and `/foo/_book.yaml`)

#### Relevant Code:

https://github.com/firebase/firebase-js-sdk/blob/49ee786f2b022e65aef45693e1a8b546d889ec10/repo-scripts/api-documenter/src/documenters/MarkdownDocumenter.ts#L172-L178

### Commentary

I realise I could simply fork and edit but it'd be great to work together on a single tool, rather than maintaining separate, nearly-identical forks. This way we can take advantage of future work of each other.

**Comment by hsubox76** [comment]
What's your use case for this fork? For background, we forked it for a very specific use case of customizing the output to work on devsite for Firebase docs and it's currently only consumed by Firebase Cloud Functions, the Firebase Admin SDK, and us, the JS SDK. Admittedly it is a bit hacky because we have such a limited use case. If you have any suggestions to open it up so that you or others could use it without impacting the current consumers, I would be happy to take a look at a PR.
