### ISSUE TITLE
Bug: SDK is still asking for debug token even if it's already correctly configured.

### ISSUE THREAD

**Issue by webbertakken** [firebase/firebase-js-sdk#6967]
### Describe your environment

  * Operating System version: Win 11
  * Browser version: Chrome Version 108.0.5359.126 (Official Build) (64-bit)
  * Firebase SDK version: 9.15.0
  * Firebase Product: App Check

### Describe the problem

When filling the `global.FIREBASE_APPCHECK_DEBUG_TOKEN` parameter before initialising appCheck, you still see the message about having to fill it - even though it already works and you have no steps left to perform.

Example:

```ts
global.FIREBASE_APPCHECK_DEBUG_TOKEN = process.env.REACT_APP_FIREBASE_APP_CHECK_TOKEN
console.log(typeof global.FIREBASE_APPCHECK_DEBUG_TOKEN) // it is indeed set ✅
initializeAppCheck(app, {
  provider: new ReCaptchaV3Provider('some key'),
  isTokenAutoRefreshEnabled: true,
})
```

#### Steps to reproduce:

- Follow this guide: https://firebase.google.com/docs/app-check/web/debug-provider
- Open the app in the browser (dev mode) and find the message reading `App Check debug token: ${token}. You will need to add it to your app's App Check settings in the Firebase console for it to work.`
- Pass the token to `global.FIREBASE_APPCHECK_DEBUG_TOKEN` and verify that it is successfully passed in.
- Note that you still see the message about needing to add it (even though you already did correctly - the reason being that the message is always shown in debug mode)

#### Relevant Code:

It's always logged when debug mode is enabled, even when correctly configured.

See `packages/app-check/src/api.ts:77`:

```ts
  // is called in debug mode.
  if (isDebugMode()) {
    // Do not block initialization to get the token for the message.
    void getDebugToken().then(token =>
      // Not using logger because I don't think we ever want this accidentally hidden.
      console.log(
        `App Check debug token: ${token}. You will need to add it to your app's App Check settings in the Firebase console for it to work.`
      )
    );
  }
```

Debug mode is always enabled when it's set. So both initially when `true`, but also when set to the actual token.

Thank you for you consideration.

**Comment by jbalidiong** [comment]
Hi @webbertakken, thanks for bringing this to our attention. I noticed you've mentioned this issue to your PR. I'll notify an engineer to have this checked. Thank you for your contribution!

**Comment by hsubox76** [comment]
This was actually a feature request from another user who wanted to always know what their current debug token was, even if it was already initialized. I know it seems a little silly if you're using the method where you assign it to `global.FIREBASE_APPCHECK_DEBUG_TOKEN` because you must already know what it is and you stored it in your env variable, but the debug token is also automatically stored in indexeddb if you leave `global.FIREBASE_APPCHECK_DEBUG_TOKEN` set to `true`, so you could have lost the string, which is what happened to this user. We could have a different message based on whether it's been generated for the first time or whether it's been retrieved from storage but that would add a bit more code and we wanted to try and keep the bundle size minimal.

Perhaps we could change the wording of the message to indicate this could happen on the initial token generation or any time afterwards somehow.

**Comment by webbertakken** [comment]
I would argue that if you really lose your token you can log it programatically. 

It doesn't necessarily have to be in your console during the entire development process of every application using this SDK if you ask me.

Happy to close if you're happy with the previous feature request and feel this iteration doesn't add any value.

**Comment by hsubox76** [comment]
I think it all depends on how many users prefer it each way, currently it's technically 50-50 as one user requested it specifically and one user has said it's unhelpful. This is searchable so we can close it, but not lock comments, and anyone with additional feedback can reply if they have further opinions. If there seems like a consensus to remove it, we can reopen and address it.
