### ISSUE TITLE
Large percentage of customers can't access googleapis.com/firebase

### ISSUE THREAD

**Issue by sgehrman** [firebase/firebase-js-sdk#7022]
I wrote a product on firebase and deployed it, but now I get a large percentage of customers who get errors signing in or trying to access data in firebase.  I had no idea this was a known fundamental flaw in firebase.  I can't believe this isn't communicated in your docs. Firebase is a completely useless technology if a large percentage of your use base is blocked.  And I can't reproduce it to even gather data since it works fine for me and my team.

After some googling it seems to be a common issue. Chinese users are blocked and others behind firewalls?  I don't know exact details since it works fine for me in the US.  I have customers in China who can't pay for my app. This is costing me thousands.

I read something about possibly setting up a proxy server, but that sounds like a ton of work.  The client side would have to intercept all calls to googleapis and firebase and route them through a proxy server?  Is this a solution? Is there an open source proxy server that does this? What about the client side? I'm using flutter.  How would I intercept all the calls from the client to go to this proxy server?

This is a total disaster.  Why isn't there a big warning on the top of all the firebase docs?

**Comment by jbalidiong** [comment]
Hi @sgehrman, thanks for reaching out to us. Sorry you’re having a bad experience using Firebase. I understand the frustration, especially after putting a lot of effort into building a great product for it not to work due to some restrictions. And as much as we want to create a place where our products and services are available everywhere, unfortunately this is not the case. That said, I think this would be better discussed with our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact), where you can share project details and what Firebase products that you’re using, so that our agents can explore possible solutions or workarounds.

For what it’s worth, I think this [StackOverflow link](https://stackoverflow.com/questions/42605566/can-firebase-be-used-as-a-database-in-china-now) might help discover your options for getting around the issue. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
