### ISSUE TITLE
Constant auth sign-out/log-out whenever the network changes.

### ISSUE THREAD

**Issue by maccman** [firebase/firebase-js-sdk#7118]
### [REQUIRED] Describe your environment

  * Operating System version: mac
  * Browser version: latest Chrome
  * Firebase SDK version: 9.17.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

We just upgrade Firebase from 9.10.0 to the latest (9.17.2). We are seeing constant auth sign-outs across our user base. We think it's related to network changes, and to this PR:

https://github.com/firebase/firebase-js-sdk/pull/7038

Our app works offline so it's very important that users aren't signed out when the auth request fails due to a network error.

**Comment by maccman** [comment]
@NhienLam this one is a tricky one - because auth fails and the page gets reloaded all at around the same time. It's difficult to capture errors around.

We have reverted this Firebase change in our staging environment and we aren't seeing sign outs. We will deploy to production tomorrow and let you know if we see a decrease in sign-outs.

**Comment by maccman** [comment]
@NhienLam #7038 was a red herring - we are still seeing the issue. Have you had any other reports of it?

**Comment by ocavue** [comment]
I can reproduce this issue with a minimal Firebase setup. And I can confirm that version 9.17.1 is fine. Here is the steps to reproduce as well as a reproduction video recording. 

Steps to reproduce

- Clone https://github.com/firebase/quickstart-js

- Follow the step in https://github.com/firebase/quickstart-js/blob/master/auth/README.md#getting-started to create a Firebase project and run `firebase serve` to start a local dev server (My port is 5002)

- Edit the version numbers in `auth/email-password.html` and change them into `9.17.1`. This is a good version so we will first check the **expected behavior**

  - Make sure that WIFI is connected 

  - Open http://localhost:5002/email-password.html

  - Sign up a new account and sign in

  - Refresh the webpage for several times. 

  - You should see `Firebase sign-in status: Unknown` at first, and then `Firebase sign-in status: Signed in` very quickly. 

  - Turn off WIFI

  - Refresh the webpage for serveral times. 

  - You should see `Firebase sign-in status: Unknown` at first, and then `Firebase sign-in status: Signed in` after about 30 seconds. 

- Change the version number in `auth/email-password.html` to `9.17.2`, which is broken version

  - Make sure that WIFI is connected 

  - Open http://localhost:5002/email-password.html

  - Sign in the previous account 

  - Refresh the webpage for several times.

  - You get `Firebase sign-in status: Signed in`. This is expected

  - Turn off WIFI

  - Refresh the webpage for several times.

  - You will see `Firebase sign-in status: Signed out`. **This is unexpected!**

  - You might need to turn on and off the WIFI for 2~3 times to see the `Signed out` state. 



https://user-images.githubusercontent.com/24715727/224938080-bbd16a63-830c-4454-ad66-f0c7639d8cf8.mp4

**Comment by NhienLam** [comment]
Thanks a lot for the update @maccman and the repro steps @ocavue!
I was able to reproduce it in the quickstart-app as well as the firebase-js-sdk demo app. We found that https://github.com/firebase/firebase-js-sdk/blob/bea604ea33c529e755cc3fcdc0a2ea75d04b9f19/packages/auth/src/core/auth/auth_impl.ts#L311 treats any error other than NETWORK_REQUEST_FAILED as token is invalid and signs user out.

I will create a PR to change it back to `NETWORK_REQUEST_FAILED` which will fix this issue. Apologize for the inconvenience and thank you for bringing this up.
