### ISSUE TITLE
DocumentSnapshot.exists has incosistency in firebase and firebase-admin packages

### ISSUE THREAD

**Issue by ArturAmpilogov** [firebase/firebase-js-sdk#7141]
### Describe your environment

  * Operating System version: Debian 11
  * Browser version: Chrome 111.0.5563.64
  * Firebase SDK version: 
      - firebase: 9.16.0
      - firebase-admin: 11.5.0
  * Firebase Product: database (firestore)

### Describe the problem
There are two NPM packages: `firebase`, which is mostly used in Web frontend applications, and `firebase-admin`, which is usually used in backend NodeJS functions.

1) The `firebase` package is using `@firebase/firestore`, which has the next code for `DocumentSnapshot`:
```
export declare class DocumentSnapshot<T = DocumentData> {
     /**
     * Returns whether or not the data exists. True if the document exists.
     */
    exists(): this is QueryDocumentSnapshot<T>;
}
``` 

2) The `firebase-admin` package is using `@google/cloud`, which has the next code for `DocumentSnapshot`:

```
 export class DocumentSnapshot<T = DocumentData> {

    /** True if the document exists. */
    readonly exists: boolean;
```

In the first case `exists` field is a function, while in the second case it is a boolean field.

It would be nice to have some API consistency for the both cases. It will also simplify a bit helper classes writing, currently it requires checks for a field type to make a switch.

**Comment by ehsannas** [comment]
Thanks for flagging this @ArturAmpilogov . The JS SDK used to have a boolean field too (similar to the Nodejs Admin SDK).

Since web developers are sensitive to the size of the bundles they use, in an effort to reduce the size of the Web (JS) SDK, we made it "modular" / tree-shakable. As a result, the Web SDK (starting with version 9) has diverged in syntax compared to the Nodejs SDK (where the SDK size is not a concern). For example many class methods have turned into standalone functions.

The `exists()` vs `exists` is definitely a tricky one (and we made sure to [document it](https://firebase.google.com/docs/web/modular-upgrade#exists-update)), and I wonder if it could have been avoided. Nevertheless, it's not the only difference between these two SDKs.

**Comment by ArturAmpilogov** [comment]
Thank you @ehsannas.

It would be nice to see consistency for such small props in the future. Guess tree shaking will not save much space there as usually the whole Snaphot type is used with the exists() function or the boolean prop anyway.

Just to clarify where the topic came from. I used a shared helper package between functions and react hosting. There was a need to work with a common Snaphot interface. And now there is a switch checking whether exists is a function or a boolean field.

**Comment by ehsannas** [comment]
I'm sorry for this trouble. In hindsight this difference should have been avoided if possible. We'll strive to keep consistency as much as possible in the future.
