### ISSUE TITLE
Existing photoURL got overwritten with null for Apple Sign in

### ISSUE THREAD

**Issue by BananaCHIU** [firebase/firebase-js-sdk#7159]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11
  * Browser version: Chrome
  * Firebase SDK version: v9
  * Firebase Product: auth (auth, database, storage, etc)
  

#### Steps to reproduce:

1. Create an account using a trusted provider with an email verified (except Apple)
2. PhotoURL is not null and set to be the icon of the account from that provider (Google, Facebook etc.)
3. sign in using Apple
4. PhotoURL got overwritten with null

I know it is an excepted behavior for apple to not provide photoURL, but it is troublesome when the firebase user has a valid photoURL prior to the apple sign in / account link

**Comment by DellaBitta** [comment]
Hi @BananaCHIU,

Have you linked the Apple account to the Firebase user account created in step 1?  I ask because in step 3, you only mention signing in using Apple. If the account from step 1 is not linked to an Apple account, then signing in with Apple would create a new user, which would explain why the user's photoURL is null.

Thanks!
