### ISSUE TITLE
Firestore with offline persistence incorrectly throws 'multiple tabs open' error

### ISSUE THREAD

**Issue by gizmodus** [firebase/firebase-js-sdk#720]
### Describe your environment

  * Operating System version: Android 6.0.1 - Android System WebView 66.0.3359.126
  * Firebase SDK version: 4.12.1-1
  * Firebase Product: firestore

### Describe the problem

I'm using Firestore with offline persistence enabled in an Ionic project that runs on Android as a standalone app (Android System WebView). Since I updated Android System WebView to the latest version, firestore is throwing the following error: 'Unhandled Promise rejection: There is another tab open with offline persistence enabled. Only one such tab is allowed at a time. The other tab must be closed or persistence must be disabled.'

As the the application runs in standalone mode there is of course no other tab open. Many users confirmed that they have the same issue on their phone.
The problem can be fixed if the Android System WebView updates are uninstalled.

#### Steps to reproduce:

I can not reproduce the problem as it only appears in the bundled app on Android. In Desktop Chrome the problem does not appear.

Log output with log level set to 'debug':

```
[2018-04-23T19:30:09.773Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: Opening database: firestore/[DEFAULT]/swim-coach-62d6b/main
vendor.js:142437 
[2018-04-23T19:30:09.929Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: GET owner owner {"ownerId":"X4UFPtF3GDvFzKd84JCa","leaseTimestampMs":1524511458400}
vendor.js:142437 
[2018-04-23T19:30:09.943Z]  @firebase/firestore: Firestore (4.10.1) [IndexedDbPersistence]: No valid owner. Acquiring owner lease. Current owner: {"ownerId":"X4UFPtF3GDvFzKd84JCa","leaseTimestampMs":1524511458400} New owner: {"ownerId":"BROWdCcPk9QpH4m5McjF","leaseTimestampMs":1524511809942}
vendor.js:142437 
[2018-04-23T19:30:09.953Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: PUT owner owner {"ownerId":"BROWdCcPk9QpH4m5McjF","leaseTimestampMs":1524511809942}
vendor.js:142437 
[2018-04-23T19:30:10.005Z]  @firebase/firestore: Firestore (4.10.1) [IndexedDbPersistence]: Starting transaction: Start LocalStore
vendor.js:142437 
[2018-04-23T19:30:10.014Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: GET owner owner {"ownerId":"X4UFPtF3GDvFzKd84JCa","leaseTimestampMs":1524511458400}
vendor.js:142437 
[2018-04-23T19:30:10.021Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: Aborting transaction.
polyfills.js:3 Unhandled Promise rejection: There is another tab open with offline persistence enabled. Only one such tab is allowed at a time. The other tab must be closed or persistence must be disabled. ; Zone: <root> ; Task: IDBRequest.addEventListener:success ; Value: Error: There is another tab open with offline persistence enabled. Only one such tab is allowed at a time. The other tab must be closed or persistence must be disabled.
```

Clearing local storage and IndexedDB does not solve the problem.

#### Relevant Code:

```javascript
firebase.initializeApp({
  apiKey: '***',
  authDomain: '***',
  databaseURL: '***',
  projectId: '***',
  storageBucket: '',
  messagingSenderId: '***'
});

firebase.firestore.setLogLevel('debug');

try {
  this.firestore = firebase.firestore();

  this.firestore.enablePersistence()
  .catch((error) => {
    console.warn('Offline support not available');
  });
} catch (error) {
  console.warn('Offline support not available');
  this.firestore = firebase.firestore();
}
```

**Comment by mikelehen** [comment]
@gizmodus Can you let us know what version of Android System WebView you upgraded from (the one that works)?  Thanks.

**Comment by mikelehen** [comment]
After some internal discussions, we have a theory for how this could happen.  We currently have code that ignores when an IndexedDb transaction is aborted because we assume that we are the only ones to abort the transaction: https://github.com/firebase/firebase-js-sdk/blob/bfa8a5e453fd7925d5ffd1bf739731a8109b454f/packages/firestore/src/local/simple_db.ts#L259

But it turns out that IndexedDb can also internally abort a transaction due to quota exceeded.  And so what may be happening here is that you've exceeded quota and we are ignoring the error from IndexedDb.

It's still not completely clear why this is only happening with the upgraded System Web View. Perhaps the default quota was changed or something.

We'll take a look at improving this in the future, although it may be the case that you'll still get an error it will just be a quota error instead of the multiple tabs error. :-/

**Comment by gizmodus** [comment]
@mikelehen Thank you for your fast response! Unfortunately, I can't say which was the last working version of Android System WebView. If you uninstall it, it directly resets to the factory version which would probably be the one being shipped with Android 6.0.1.

Good that you already have a suspicion what the source of the error could be. If I knew that it is a quota limit that would help too, because then I could restructure application logic to prevent that.

Let me know if I can test a new version, then I'd be happy to provide you with the log output.
Thanks for your effort!

**Comment by gizmodus** [comment]
@mikelehen So I did some investigation and it turns out - as you suspected - that transaction.onabort is triggered with a QuotaExceededError. Do you think this is a WebView / Chrome bug in the newest update?

I cleared local storage afterwards and restarted the application. Now I get a new error:

**Firestore (4.10.1): INTERNAL UNHANDLED ERROR:  Version change transaction was aborted in upgradeneeded event handler.**

The full log with is here:

```
[2018-04-26T18:37:01.299Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: Opening database: firestore/[DEFAULT]/swim-coach-62d6b/main
vendor.js:142437 [2018-04-26T18:37:01.350Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: Database "firestore/[DEFAULT]/swim-coach-62d6b/main" requires upgrade from version: 0
vendor.js:142437 [2018-04-26T18:37:01.386Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: GET targetGlobal targetGlobalKey null
vendor.js:142437 [2018-04-26T18:37:01.395Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: PUT targetGlobal targetGlobalKey {"highestTargetId":0,"highestListenSequenceNumber":0,"lastRemoteSnapshotVersion":{"seconds":0,"nanos":0},"targetCount":0}
vendor.js:142437 [2018-04-26T18:37:09.469Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: COUNT targets
vendor.js:142437 [2018-04-26T18:37:09.489Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: PUT targetGlobal targetGlobalKey {"highestTargetId":0,"highestListenSequenceNumber":0,"lastRemoteSnapshotVersion":{"seconds":0,"nanos":0},"targetCount":0}
vendor.js:142437 [2018-04-26T18:37:12.422Z]  @firebase/firestore: Firestore (4.10.1) [SimpleDb]: Database upgrade to version 2 complete
main.js:98 Offline support not available
vendor.js:142449 [2018-04-26T18:37:12.467Z]  @firebase/firestore: Firestore (4.10.1): INTERNAL UNHANDLED ERROR:  Version change transaction was aborted in upgradeneeded event handler.
polyfills.js:3 Unhandled Promise rejection: Version change transaction was aborted in upgradeneeded event handler. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Version change transaction was aborted in upgradeneeded event handler. 
```

Can you make anything out of this? Or is this another Chrome bug?

**Comment by mikelehen** [comment]
@gizmodus I'm not sure...  The fact that it's an aborted error makes me suspect that you're (still) hitting a quota-exceeded issue.  How are you clearing local storage?  Is it possible you're still over quota?  (unfortunately I'm really not sure how quota works, especially in a WebView)

**Comment by gizmodus** [comment]
@mikelehen By the way, I found some resources about Android System WebView. I would love to report a bug there but I wouldn't even know what to report. 

Overview:
https://www.chromium.org/developers/androidwebview/android-webview-beta

Bug Tracker:
https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3AMobile%3EWebView+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

**Comment by mikelehen** [comment]
Thanks! I am pinging some folks internally so we can figure out what may have changed recently...  I'll let you know what I find out.

**Comment by gizmodus** [comment]
So, I did some more investigation and found the source of the problem: Internal storage was low on my phone!!!
Well, there were still around 500MB left on my Nexus 5 but this seemed to be enough to throw a QuotaExceededError and block access to IndexedDB. After I freed up some space everything worked like a charm again.

@mikelehen I think it would be really helpful if the QuotaExceededError was logged directly to the console, maybe even with a hint that this might be due to low storage. I guess there are a lot of people out there with full storage on there phone who run into this problem and go crazy. Thanks for your effort!

**Comment by mikelehen** [comment]
@gizmodus Aha! That's great to know.  Thank you very much for tracking this down and following up.  Your report has been very valuable and we will definitely improve the error handling around this to make sure that quota errors are surfaced properly with as much helpful info as we can provide.

**Comment by paulstelzer** [comment]
@mikelehen Hi Mike, I have to re-open this topic again. I created a cordova/ionic app with Firebase / Firestore integration. After my app launches, people came up to me saying the app is not working and at first, I could not find out the reason (one user had the same android device like me).

Finally, after research, I found the issue: QuotaExceededError through indexeddb when enabling persistence on firestore (like @gizmodus mentioned). If user have not enough free space, Firestore (with persistence enabled) will not work. This occurs mostly on cheap Android devices, mostly from Samsung, because there is just small free space. Firestore relies on indexeddb with enabled persistence (if I am right), so that's the reason its not working.

Afterwards I implemented sqlite into my Android App to save data (and not saving data via indexeddb) and implemented a "without firestore mode". I also created events in Firebase Analytics to check how many people are affected on this and it's around 15 percent of the Android user of my app.

My question to you: How would you solve this issue? At the moment I consider to not enable persistence on Firestore and save the data manually through my own storage system ( in my case sqlite). Or do you have an another idea?

**Comment by mikelehen** [comment]
@paulstelzer Thanks very much for reaching out. Just to be clear, you believe that ~15% of your Android users are hitting the QuotaExceededError?  That's extremely useful to know.

As for workarounds, we have https://github.com/firebase/firebase-js-sdk/issues/720 open which will make this error much clearer (rather than multiple tabs open, it'll report the QuotaExceeded error), but it won't actually solve the underlying issue. :-/

Unfortunately we are at the mercy of the IndexedDb implementation's quota enforcement and so I don't have a good workaround for you.  As painful as it is (for us and for you), your usage of SQLite may be the best option for now.  That said, I'm going to reach out to the team that works on the Chrome WebView implementation and see if this level of quota exceeded errors is expected.  

Thanks again for reaching out!

**Comment by paulstelzer** [comment]
@mikelehen As soon as you integrated to call the QuotaExceeded error, i can tell you a value more in detail ;) At the moment 15 percent is also if the user has no internet connection ( I do not seperate between quota and internet connection). Maybe 14 percent have no internet and 1 percent has quota :D But as I saw that many people give a 1 star rating because of that (before i did the workaround), it is possible, that 4-6 percent can have this issue.

But as I said: As soon as you report the QuotaExceeded error, i can tell you more ;)

**Comment by mikelehen** [comment]
@paulstelzer Haha. Got it, thanks. I'll see if we can get that expedited. :-)

**Comment by paulstelzer** [comment]
@mikelehen Here for you the Console logs what happened on Quota Exceeded Error. My source code for enablePersistence()

```
    firebase.firestore().enablePersistence()
      .then(() => {
        this.persistence = true;
        console.log('enabled Persistence')
      })
      .catch((err) => {
        this.persistence = false;
        console.error('[ERROR] enablePersistence', err);
      })
```

![chrome_2018-05-14_17-55-10](https://user-images.githubusercontent.com/20501666/40008669-2d423d58-57a0-11e8-93ae-aac91db67411.jpg)

I wonder why he still enable persistence although he is in the catch block and the error occurs? It would be great if enablePersistence() will not be executed on Quota Exceeded Error - so Firestore not try to use Indexeddb. Then my app would work, too - just without it.

So if he wants to save data from Firestore, he cannot:

![chrome_2018-05-14_17-55-39](https://user-images.githubusercontent.com/20501666/40008671-2da5dd68-57a0-11e8-958b-b3bc8d4c0f70.jpg)

**Comment by mikelehen** [comment]
Thanks @paulstelzer! Yes, once we fix #720 then your .catch() callback should be executed and subsequent operations should continue to work (just without persistence).

**Comment by gizmodus** [comment]
@paulstelzer 
@mikelehen 
I found a workaround to prevent firestore from crashing if memory is low. There is a method to check how much storage is available. Now you can dynamically enable offline if the phone can handle it.

```javascript
try {
    navigator.storage.estimate().then((data) => {
      if ((data.quota - data.usage) > (2 * 1024 * 1024)) {
        // Enable offline persistence
      } else {
        // Do not enable offline persistence
      }
    });
  } catch (error) {
    // Error (most probably because the browser does not support the storage function and therefore is not Chrome)
    // -> Enable offline persistence
  }
```

**Comment by mikelehen** [comment]
Ahh, nice!

Just FYI- I got in touch with a member of the Chrome team and was informed that the heuristic will be changing in an upcoming release (see https://crbug.com/838816). It sounds like you'll only get the quota exceeded error if the remaining free space is less than 2GB _and_ less than 10% of device storage (i.e. it'll use the minimum as the threshold).  This should help with low-storage devices (less than 20GB).

Meanwhile, we'll work on fixing #720. If you happen to know an easy way to trigger the QuotaExceeded error (in vanilla Chrome, ideally), let me know. :-)

**Comment by paulstelzer** [comment]
@mikelehen My approach was to save a test variable with small input to indexeddb - then I wachted if the quota eceeded error occurs or not ;)

**Comment by schmidt-sebastian** [comment]
#823 will go out in the next release and allows Firestore to gracefully handle "no quota" scenarios.

If the SDK runs out of quote while it is being used, we will raise a DOMException with error code 22 (quota exceeded). To also handle these low quota scenarios, you may still want to keep the check you added in your [earlier comment](https://github.com/firebase/firebase-js-sdk/issues/720#issuecomment-388931328).

**Comment by paulstelzer** [comment]
@schmidt-sebastian I updated to firebase@5.0.3, but still the same errors on enablePersistence()

`DOMException: Version change transaction was aborted in upgradeneeded event handler.`

He still execute enable persistence although quota exceeded.

PS: Is it better to start a new issue?

**Comment by schmidt-sebastian** [comment]
Looks like I missed this error in my local testing. We will get this fix into the next release.

I re-opened this issue as is since it already has all the required context. Thanks for checking with us!

**Comment by holmberd** [comment]
> If you happen to know an easy way to trigger the QuotaExceeded error (in vanilla Chrome, ideally), let me know. :-)

@mikelehen Just for future reference you can trigger and test this in Chrome by launching the browser with flag `--user-data-dir` pointing at a smaller volume, e.g. `sudo mount -t tmpfs -o size=1G tmpfs /mnt/mytmpfs`

**Comment by jimmykane** [comment]
Hi this error is back for some reason. Any tips?

**Comment by schmidt-sebastian** [comment]
@jimmykane Nothing comes to mind right away, can you provide logs from your device?

**Comment by mikelehen** [comment]
@jimmykane Since this issue has been closed for a while, can you pleas open this as a brand new issue with full repro steps and your log output (from `firebase.firestore.setLogLevel('debug')`)? Thanks!

**Comment by jimmykane** [comment]
@mikelehen  sure. It will take some time though. Its a prod logs that produce this. I cannot get this on local unfortunately.
