### ISSUE TITLE
`Cannot find namespace 'firebase'.ts(2503)` for with `firebase/compat/app` and `"moduleResolution": "bundler"`

### ISSUE THREAD

**Issue by segevfiner** [firebase/firebase-js-sdk#7279]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 13.3.1 (a)
  * Browser version: Google Chrome 113.0.5672.63
  * Firebase SDK version: 9.21.0
  * Firebase Product: sdk (auth, database, storage, etc)

### [REQUIRED] Describe the problem
With the new `"moduleResolution": "bundler"` mode of TypeScript 5.0+, TypeScript errors on attempting to access any type from the `firebase` global namespace with `firebase/compat/app` and friends imported. It works with `"moduleResolution": "node"`.

#### Steps to reproduce:

1. Clone https://github.com/segevfiner/firebase-types-issue
2. `pnpm i`
3. `pnpm type-check`.
4. If you set `"moduleResolution": "node"` in `tsconfig.app.json` it will work, but it should work with the new `moduleResolution` mode as well.

#### Relevant Code:

https://github.com/segevfiner/firebase-types-issue

**Comment by hsubox76** [comment]
Are you seeing this error when you run `pnpm type-check` or just in the IDE tooltip? We've only been able to see it in the tooltip but the tsc compliation seems to finish with no errors?

**Comment by hsubox76** [comment]
Ok, the immediate issue is that when you use `moduleResolution: bundler`, `firebase/compat/app` grabs typings from here (just firebase/app-compat types):
https://github.com/firebase/firebase-js-sdk/blob/master/packages/app-compat/package.json#L14

instead of here (giant index.d.ts file for all compat typings, the expected type source for compat users):
https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/package.json#L231

Not sure why there's individual compat package typings, I didn't think they worked. Will dig further into it.

**Comment by hsubox76** [comment]
I think it's something we overlooked in https://github.com/firebase/firebase-js-sdk/pull/6307 . We should have copied what was in the top level `typings` field into the `exports.types` field. Should be able to fix.

**Comment by hsubox76** [comment]
We're still going to try to fix this either way but I'm just curious why you're using the compat libraries, is it a legacy application that you're not ready to migrate?

**Comment by segevfiner** [comment]
Yep. It's an application we are going to migrate someday, but it's hard to get time for tech debt where I work at.

**Comment by Sejal1101** [comment]
Kindly assign me this issue , if it still exists
