### ISSUE TITLE
User Properties present only in the first event analytics  

### ISSUE THREAD

**Issue by Donhv** [firebase/firebase-js-sdk#7345]
### Operating System

macOS

### Browser Version

Chrome

### Firebase SDK Version

9.22.1

### Firebase SDK Product:

Analytics

### Describe your project's tooling

React app with webpack 4

### Describe the problem

I have some challenge with the user_properties specifically in our web application.
When I look at the events in DebugView the user_properties are showing correctly for all events that a user generated.
However, when I look at the data in BigQuery and log with google-analytics-debugger, the user_properties are present only in the first event which the user got, 

### Steps and code to reproduce issue

 setUserProperties(analytics, data);
logEvent(analytics,...}) // can see all user properties under format up.xxxx with google-analytics-debugger
logEvent(analytics,...}) // cannot see any user properties although see all user param

**Comment by robert-ou** [comment]
+1, same issue

**Comment by khacbac** [comment]
+1, same issue

**Comment by datdt56** [comment]
Same issue here

**Comment by jbalidiong** [comment]
Hi @Donhv, thanks for bringing this to our attention. I was able to reproduce the behavior using the debugger extension. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by jbalidiong** [comment]
@datdt56, just a quick update. I've tested it using `gtag.js` and I was still able to replicate the behavior. With that, this might be a Google Analytics issue rather than Firebase SDK. In that case, you may want to file a ticket via [Google Analytics support](https://support.google.com/analytics/contact/ghelp) channel. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
