### ISSUE TITLE
Firebase web push notification don't track "opens/click" count in service worker

### ISSUE THREAD

**Issue by ssabalak** [firebase/firebase-js-sdk#7350]
### Operating System

macOS Ventura 13.3

### Browser Version

Google Chrome 114.0.5735.90

### Firebase SDK Version

9.22.1

### Firebase SDK Product:

Analytics, Messaging

### Describe your project's tooling

Next.JS 12.3.1
Firebase SDK 9.22.1
I use service-worker for receive web push notification

### Describe the problem

1. I send web push notification through Firebase Console
2. I receive notification in background
3. When I click to notification, notification opened

But when I check in Firebase Console, opened notification count always zero

### Steps and code to reproduce issue

1. Create firebase web app in firebase console
2. Create Next.JS 12 project
3. Install last firebase client sdk for web (firebase^9.22.1)
4. Firebase [messaging](https://firebase.google.com/docs/cloud-messaging/js/client) and [analytics](https://firebase.google.com/docs/analytics/get-started?platform=web) configured to Next.JS by default from firebase documentation
5. Create firebase-messaging-sw.js and put this code

`importScripts(
  'https://www.gstatic.com/firebasejs/9.22.1/firebase-app-compat.js',
);
importScripts(
  'https://www.gstatic.com/firebasejs/9.22.1/firebase-messaging-compat.js',
);

// your config
const firebaseConfig = {};
firebase.initializeApp(firebaseConfig);
firebase.messaging();
`

6. After that, push notifications will work. But opened notification count always zero in firebase console
7. I checked over https site, but It's also don't send statistic about opened notification count
<img width="994" alt="Screenshot 2023-06-05 at 19 10 15" src="https://github.com/firebase/firebase-js-sdk/assets/8100159/d9d64500-b506-47bd-aba0-a612c1106b9d">

**Comment by DellaBitta** [comment]
Hi @ssabalak,

This seems very similar to #7200. Essentially those events are sent through the Google Analytics service, and you will need to configure Google Analytics to send those events to the Firebase Console.

As recommend in that other thread I think this is a backend configuration question which would  be better discussed with our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact), where you can share project details and what Firebase products that you’re using, so that our agents can explore possible solutions or workarounds.

I hope this helps! If you still run into issues after Google Analytics configuration and with the help of Firebase Support then please create a new issue here and link this one to it. Thanks!
