### ISSUE TITLE
Fix Web Worker support for persisting

### ISSUE THREAD

**Issue by garrett-wombat** [firebase/firebase-js-sdk#7364]
### Operating System

macOS Venture 13.2.1

### Browser Version

Brave 1.51.114

### Firebase SDK Version

9.22

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Vite build (rollup)

### Describe the problem

When querying documents within a service worker, the files are not cached within indexDB persistanc storage.
This seems to have once been an issue `https://github.com/firebase/firebase-js-sdk/pull/2197` but the 'forceOwningTab' setting doesn't seem to exist within the web sdk v9.

### Steps and code to reproduce issue

- create basic firestore project, with 
```
export const firestore = initializeFirestore(_firebase, {
  ignoreUndefinedProperties: true,
  localCache: persistentLocalCache({
    tabManager: persistentMultipleTabManager(),
    cacheSizeBytes: CACHE_SIZE_UNLIMITED,
  }),
});
```

- create service worker that queries a document not already queried
- indexDB is not populated (you can query the same document within the main thread) and it populates just fine.

**Comment by jbalidiong** [comment]
Hi @garrett-wombat, thanks for reaching out to us. This seems to be related to #6962. Does this code snippet about `forceOwnership ` help you with your issue?

```
const db = getFirestore(app)

enableIndexedDbPersistence(db, { forceOwnership: !globalThis.localStorage }) // forceOwnership for web worker
.then(() => console.log("Offline persistence enabled"))
.catch(error => {
    switch (error.code) {
        case 'failed-precondition':
            console.log("Offline persistence already enabled in another tab")
            break
        case 'unimplemented':
            console.log("Offline persistence not supported by browser")
            break
        default:
            console.error(error)
    }
})
```

**Comment by garrett-wombat** [comment]
I think so yes, but `enableIndexedDbPersistence` is deprecated in vs 9. And when i try and use it the enable cache through the old way it throws on error about firestore already being initialized

```
export const firestore = initializeFirestore(_firebase, {
  ignoreUndefinedProperties: true,
  // localCache: persistentLocalCache({
  //   tabManager: persistentMultipleTabManager(),
  //   cacheSizeBytes: CACHE_SIZE_UNLIMITED,
  // }),
});

// enableMultiTabIndexedDbPersistence(firestore)
enableIndexedDbPersistence(firestore, { forceOwnership: true })
  .then(() => console.log("Enabled offline persistence"))
  .catch((error) => {
    if (error.code == "failed-precondition") {
      // Multiple tabs open, persistence can only be enabled
      // in one tab at a a time.
      // ...
    } else if (error.code == "unimplemented") {
      // The current browser does not support all of the
      // features required to enable persistence
      // ...
    }
  });
```
Also, im not sure this old utility function enableds the multiTap cache that i need.

**Comment by garrett-wombat** [comment]
Update: It looks like this will work as a patch, but same issue still exists. When this `enableIndexedDbPersistence` is removed. It will break all service workers / web workers offline persistence.

THis is the config that ended up working
```
export const firestore = initializeFirestore(_firebase, {
  ignoreUndefinedProperties: true,
//  localCache: persistentLocalCache({
//    tabManager: persistentMultipleTabManager(),
//    cacheSizeBytes: CACHE_SIZE_UNLIMITED,
//  }),
});

// enableMultiTabIndexedDbPersistence(firestore)
enableIndexedDbPersistence(firestore, { forceOwnership: true })
  .then(() => {
    // eslint-disable-next-line
     console.log("Enabled offline persistence") 
   })
  .catch((error) => {
    if (error.code == "failed-precondition") {
      // Multiple tabs open, persistence can only be enabled
      // in one tab at a a time.
      // ...
    } else if (error.code == "unimplemented") {
      // The current browser does not support all of the
      // features required to enable persistence
      // ...
    }
  });
  ```

**Comment by garrett-wombat** [comment]
Oh in the v9 syntax, user. Im pretty sure i needed multiTabManager here though. But maybe i'm thinking about auth persistance. Is there a place with some details about the differences between these two tabManager strategies, i cant seem to find it anywhere.

**Comment by dconeybe** [comment]
Surprisingly, I wasn't able to find much documentation about this publicly.

Here is a summary though. Note that "multiTabManager" won't work in a web worker because of its need to use local storage, which isn't available in web workers. That's why you must use single tab persistence in web workers.

### Persistence not enabled (the default)
When `FirestoreSettings.localCache` is not set, it defaults to `MemoryLocalCache`. In this mode, all data downloaded by Firestore is stored in memory. If the user closes the tab then all of that information is lost. The next time they navigate to the web site they have to re-download everything.

In this mode, the web site may be safely opened in multiple tabs. Each tab will have its own independent in-memory cache and each will operate independently. For example, if tab 1 downloads a document into its in-memory cache then tab 2 accesses the same document it will re-download it into its own in-memory cache.

Note that by default the `MemoryLocalCache` uses a very aggressive cache invalidation strategy (`MemoryEagerGarbageCollector`) that can lead to re-downloading previously-downloaded documents. This is done to avoid unbounded growth of the in-memory cache. Using `MemoryLruGarbageCollector` instead will use a less aggressive cache invalidation strategy at the cost of a larger memory footprint.

###  Persistence enabled, single-tab mode
When `FirestoreSettings.localCache` is set to `PersistentLocalCache` with `PersistentSingleTabManager` then all data downloaded by Firestore is stored in an indexeddb database. If the user closes the tab then all of that information is persisted, and the next time they navigate to the web site they can use the previously-cached data instead of re-downloading it.

However, due to a limitation of indexeddb, only 1 tab can access a given indexeddb database; therefore, if the web site is opened in other tabs simultaneously then only one of them will get access to the indexeddb cache and the others will fall back to in-memory cache.

If all of Firestore is running in a web worker then multiple tabs to the same web site will share that web worker, effectively implementing "multi-tab mode", as described in the next section.

###  Persistence enabled, multi-tab mode
When `FirestoreSettings.localCache` is set to `PersistentLocalCache` with `PersistentMultipleTabManager ` then the behavior is the same as `PersistentSingleTabManager` _except_ that if the web site is opened in multiple tabs then they all coordinate usage of the same indexeddb database for the local cache.

Using an "election" process, the tabs decide on a "primary" tab. The "primary" tab is the one that accesses the indexeddb database on behalf of the other tabs. These "elections" occur regularly and the "primary" tab can change from one tab to another, such as if one of the tabs is closed or moved to the background.

The tabs use local storage to communicate, one of the only means available for inter-tab communication. Since web workers do _not_ support local storage, this mode will not work in web workers.

**Comment by laurentpayot** [comment]
@garrett-wombat I updated #6962
