### ISSUE TITLE
Patchy offline support!

### ISSUE THREAD

**Issue by andycwk** [firebase/firebase-js-sdk#738]
* Operating System version: ios 11 ish!
  * Firebase SDK version: 4.10.1
  * Firebase Product: firestore (auth, database, storage, etc)

Angular:
5.0.3

Firebase:
4.10.1

AngularFire:
5.0.0-rc.6

Other (e.g. Ionic/Cordova, Node, browser, operating system):
Ionic 3
cordova 8.0.0

### [REQUIRED] Describe the problem
Hi Guys!
Originally posted over on https://github.com/angular/angularfire2/issues/1584

I've been developing an Ionic 3 app using AngularFire2 to provide Firestore support and all has been going well!

I've now decided to enable offline support and this is where things are starting to get interesting!

With the wifi & mobile data disabled..

a) Start the app - all is ok
b) Kill the app
c) start the app (without any delay) - and hope all is ok

About 50% of the time the app fails to completely load, I've spent the day debugging and have pinned it down to the firestore.enablePersistence() precondition failing :(

At this point I'm stumped as in reality the deployed app should be acting as a single browser tab, closing the app should be closing the tab but it's acting like the instance is still running after the app has been killed :/

Any thoughts from the crowd?

ps. After reading through the various open/closed issues I have a feeling it might be linked to the 5 second lease on the db instance - could this be the case - if so maybe something should be mentioned in the docs (or it has, and I've missed it) :/

#### Steps to reproduce:
With the wifi & mobile data disabled..

a) Start the app - all is ok
b) Kill the app
c) start the app (without any delay) - and hope all is ok

**Comment by mikelehen** [comment]
cc/ @schmidt-sebastian 

Thanks for the report.  Do you know what happens under the cover when you "kill" the ionic app?  We hook the window unload event to ensure our lease gets cleaned up: https://github.com/firebase/firebase-js-sdk/blob/5adab2cf12a6e3825aa0d6810897bc92004347e4/packages/firestore/src/local/indexeddb_persistence.ts#L347

This works fine in a browser, but I guess not in an ionic app (at least not with however you are killing it)?  How exactly are you killing it?  Will users of your app be killing it in the same way? Or could this essentially be a "debug-only" issue that your users won't usually see?

**Comment by mikelehen** [comment]
Hehe.  True...  I'm guessing when you kill the app like that, we don't get a chance to do any cleanup and so the lease will remain. :-/

A few options to move forward:
- Just ignore it.  As long as users don't kill the app and then immediately restart it, they shouldn't run into it. And if they just wait 5 seconds and try again, it'll work.
- @schmidt-sebastian is currently working on multi-tab support which should resolve this.
- If you really wanted, you could maybe poke into IndexedDb and delete the lease on startup. Normally this would be a bad idea because it ensures that the active tab loses the lease and stops working, but in the case of ionic I assume there's only ever one tab of use and so this would be okay.

@schmidt-sebastian We could consider adding logic to try to detect ionic and other "single-tab" environments and just assume that any lease not held by the currently executing client is invalid (since any other "tab" must be stale).  But I'm not sure if this is worth doing given multi-tab's progress.

**Comment by mikelehen** [comment]
Sounds good! And yes, this is now officially on our radar. :-)  Thanks for reporting it!

**Comment by sengoontoh** [comment]
following

**Comment by sengoontoh** [comment]
Can anyone show how to peek into IndexedDB and delete the lease?
