### ISSUE TITLE
Component analytics has not been registered yet

### ISSUE THREAD

**Issue by nikitadubyk** [firebase/firebase-js-sdk#7480]
### Operating System

Windows 10

### Browser Version

Chrome 114.0.5735.199 

### Firebase SDK Version

10.0.0

### Firebase SDK Product:

Analytics, Installations, Logger

### Describe your project's tooling

React app with Webpack

### Describe the problem

Hi, I'm trying to upgrade firebase from 9.22.2 to 10.0.0 and during build I get the error "Component analytics has not been registered yet". At the same time locally the project starts and works normally. The problem disappears if you roll back to 9.22.2.
At the same time I checked in the build the config is the same as in the local build. What can be the problem?

### Steps and code to reproduce issue

```
import { getAnalytics, logEvent, Analytics } from 'firebase/analytics';
import { initializeApp, FirebaseApp, FirebaseOptions } from 'firebase/app';

const config = process.env.REACT_APP_FIREBASE_CONFIG

let app: FirebaseApp;
let analytics: Analytics;

app = initializeApp(config);
analytics = getAnalytics(app);

if (process.env.NODE_ENV === 'production') {
   logEvent(analytics, 'page_view', { name: pageName, page_title: pageName });
 }
```
![image](https://github.com/firebase/firebase-js-sdk/assets/73419198/f151ff6e-0dd7-4e49-baca-04bdbb0fa134)

**Comment by jbalidiong** [comment]
Hi @nikitadubyk, thanks for reaching out to us.  I tried replicating, but I wasn't able to reproduce the error. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by nikitadubyk** [comment]
@jbalidiong today tried to make an example, but locally everything works on both new project and main project (I compared app after initialize in both projects, everywhere the same comes). That said, the build locally works too, but the staging crashes after merge. Most likely I won't be able to recreate the problem on the new project(

**Comment by ginagr** [comment]
I'm experiencing a similar issue with my Angular project when upgrading to from 9 to 10 (@angular/fire@7.5.0 stayed the same as before). Also tried to make an example but couldn't replicate unfortunately.

<img width="498" alt="Screenshot 2023-07-20 at 3 16 18 PM" src="https://github.com/firebase/firebase-js-sdk/assets/16846028/8916a1fb-d9a5-45f8-84e7-9a11d5863a6b">

**Comment by hsubox76** [comment]
This issue usually happens with a messy npm/yarn update, where some of the Firebase packages get updated and some don't, for mysterious npm/yarn reasons (maybe the lockfile). The solution is usually to delete node_modules and any lockfiles (package-lock, yarn.lock) and reinstall. That seems like the case here since it's not a problem on a fresh project. Let us know if that doesn't work.

**Comment by ginagr** [comment]
hi @hsubox76 I updated to 10.0 and ran `rm -rf node_modules/ yarn.lock .angular/cache && yarn install` just to be certain and am still seeing the same error unfortunately

**Comment by hsubox76** [comment]
The other main cause of this problem is when you're importing `firebase/app` from one source and trying to pass it to the get()/initialize() function of `firebase/analytics` (or auth, or some other product library) from another source. Sometimes this happens when someone is importing `app` in one place, that is resolving to the CJS file, and also tries to import `app` in another part of their code, that is resolving to the ESM file, which can happen with SSR applications sometimes. Sometimes it's a race condition or timing issue. It's hard to tell without a reproduction.

If it's not happening in a fresh app I don't think it's a bug in the SDK, but if anyone can provide a repro, we can try to help you debug it.

**Comment by nikitadubyk** [comment]
With the new version of firebase the error is gone, thanks for your help)
