### ISSUE TITLE
onBackgroundMessage not fired when notification key is removed from payload

### ISSUE THREAD

**Issue by timbolimboslice** [firebase/firebase-js-sdk#7521]
### Operating System

macOs 13.4

### Browser Version

Chrome/115

### Firebase SDK Version

9.23

### Firebase SDK Product:

Messaging

### Describe your project's tooling

JS

### Describe the problem

I want to handle displaying notifications in the background myself using `onBackgroundMessage`. As per the documentation, I removed the `notification` key from the payload. 

However, once I did that, the `onBackgroundMessage` method is no longer invoked. 

<img width="946" alt="Screenshot 2023-08-02 at 2 53 44 PM" src="https://github.com/firebase/firebase-js-sdk/assets/11657201/c398ee1a-39aa-4daa-a2d4-ce1dc7d804b6">
<br/><br/>

I setup a breakpoint in `sw-listeners.ts` and the function seems to exit on this line even though the `notification` property is undefined.

<img width="1194" alt="Screenshot 2023-08-02 at 4 09 21 PM" src="https://github.com/firebase/firebase-js-sdk/assets/11657201/10f1817f-07bf-477c-a58c-b305893cb0c8">
<br/><br/>

I can also see that in the "Push Message" background service, the payload data is coming through as expected.

### Steps and code to reproduce issue

Here is my code from firebase-messaging-sw.js (with the config x'ed out):

```
// Scripts for firebase and firebase messaging
importScripts('https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.23.0/firebase-messaging-compat.js');

// Initialize the Firebase app in the service worker by passing the generated config
var firebaseConfig = {
    apiKey: "XXXX",
    authDomain: "XXXX",
    databaseURL: "XXXX",
    projectId: ""XXXX",
    storageBucket: ""XXXX",
    messagingSenderId: ""XXXX",
    appId: ""XXXX",
    measurementId: ""XXXX"
};

firebase.initializeApp(firebaseConfig);

// Retrieve firebase messaging
const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
    console.debug("from onBackgroundMessage");
    console.debug(payload);
    const notificationTitle = "FROM SW: " + payload.data.title;
    const notificationOptions = {
        body: payload.data.body ? payload.data.body : null,
        icon: payload.data.image ? payload.data.image : null,
        image: payload.data.image ? payload.data.image : null,
        data: payload.data.url ? { url: payload.data.url } : null
    };

    self.registration.showNotification(notificationTitle,
        notificationOptions);
});

self.addEventListener('push', (event) => {
    console.debug("PUSH");
    console.debug(event);
});`
```

**Comment by jbalidiong** [comment]
Hi @timbolimboslice, thanks for reaching out to us. I tried replicating the behavior using your code and I wasn't able to replicate the behavior. I removed the notification parameter in the `messages:send` request and `onBackgroundMessage` was triggered. If I can replicate the issue, I can have a better look into it. Can you provide the payload of the request you are using?

**Comment by IFOV37** [comment]
I believe we found the same issue or something similar that may aid this issue.  Whether or not we use onBackgroundMessage [or let the FCM SDK handle the notification automatically] (regardless of OS windows/mac/iOS/android), we are seeing "this site has updated in the background" - likely because either events aren't getting registered or the methods aren't being triggered. When opening an app, on first notification sent, the console logs are almost always showing the site background notification AND showing that the events (push, onnotificationclick, and pushsubscriptionchange) handles must be added on the initial evaluation of the worker script.  However, once everything is running, notifications seem to flow fine.

To replicate the behave, you can go into the chrome service workers and stop the given firebase-messaging-sw.  Once stopped, send a notification (or data message if you are using onBackgroundMessage). You will see the service worker is triggered to start again, but wherever the showNotification promise is being used (even when handled automatically) it seems like the service worker is finishing before the promise is returned, so its not waiting, thus the "site has been updated in the background".  onBackgroundMessage is also ignored when triggered from a push event/notification on all devices, so the devices fail to notify users once the service worker is stopped.

**Comment by timbolimboslice** [comment]
@jbalidiong Apologies on the late reply, I was out on vacation the past week. Here is the payload:

```
{
  "message": {
    "token": "XXXX",
    "data": {
      "title": "Schlitterbahn's Tragic Slide",
      "body": "Jeff Henry often said that his goal in life was to make customers of his family’s legendary water parks happy—“to put a smile on their faces, to give them a thrill or two.” It was a beautiful vision. Until it went horribly wrong.",
      "image": "https://img.texasmonthly.com/2018/07/HR_SCHLITTERBAHN2_0818.jpg?auto=compress&crop=faces&fit=scale&fm=pjpg&h=198&ixlib=php-3.3.1&q=45&w=300&wpsize=post-thumbnail",
      "url": "https://texasmonthly.localhost/true-crime/jeff-henry-verruckt-schlitterbahns-tragic-slide/",
      "tracking_name": "ll5vcmiv_568908"
    },
    "fcm_options": {
      "analytics_label": "ll5vcmiv_568908"
    },
    "webpush": {
      "data": {
        "title": "Schlitterbahn's Tragic Slide",
        "body": "Jeff Henry often said that his goal in life was to make customers of his family’s legendary water parks happy—“to put a smile on their faces, to give them a thrill or two.” It was a beautiful vision. Until it went horribly wrong.",
        "image": "https://img.texasmonthly.com/2018/07/HR_SCHLITTERBAHN2_0818.jpg?auto=compress&crop=faces&fit=scale&fm=pjpg&h=198&ixlib=php-3.3.1&q=45&w=300&wpsize=post-thumbnail",
        "url": "https://texasmonthly.localhost/true-crime/jeff-henry-verruckt-schlitterbahns-tragic-slide/",
        "tracking_name": "ll5vcmiv_568908"
      },
      "fcm_options": {
        "analytics_label": "ll5vcmiv_568908",
        "link": "https://texasmonthly.localhost/true-crime/jeff-henry-verruckt-schlitterbahns-tragic-slide/"
      }
    }
  }
}
```

@IFOV37 Thank you for that information, I believe that was the issue. Once I stopped the service worker and started it again, the background handling started working as expected.

<img width="377" alt="Screenshot 2023-08-10 at 7 48 02 PM" src="https://github.com/firebase/firebase-js-sdk/assets/11657201/4e001ac6-b766-47af-9683-cfa65f0be39a">
