### ISSUE TITLE
Auth: requested action is invalid - Works with 9.23, fails with 10.x

### ISSUE THREAD

**Issue by woutersteven** [firebase/firebase-js-sdk#7529]
### Operating System

PWA

### Browser Version

Chrome 115

### Firebase SDK Version

10.0.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Ionic 7.3.1 / Angular 16.2.2

### Describe the problem

Using firebase v10.0.0, v10.1.0, v10.2.0 or v10.3.0. the authentication flows break in a PWA setup and using signInWithGoogle. The error message in the browser is: "**requested action is invalid**". The PWA is hosted at Firebase with a custom domain, and both the custom domain and "localhost" are added to the list of authorised domains.

Downgrading to firebase v9.23 resolves the issue which is currently a work-around, and suggests that the configuration itself is correct. 

### Steps and code to reproduce issue

When using firebase v10.* I did notice a redirect containing a version number in the querystring to:

https:///__/auth/handler?
apiKey=&
appName=%5BDEFAULT%5D&
authType=signInViaRedirect&
redirectUrl=http%3A%2F%2Flocalhost%3A8101%2Fpages%2Flogin&
v=9.23.0

Which i found odd considering I'm not using v9.23. However I've no idea what the issue is. Has anybody else encountered the issue?

**Comment by prameshj** [comment]
Can you try comparing the URLs when using v9 and v10?

Is the `v=` the only difference in both?

You can try inspecting the network traces of the success and failure case too..

**Comment by prameshj** [comment]
Thanks! I notcied a couple of things:

1) I see the authType shows "signInViaPopup", but i think the issue was previously on signInViaRedirect, correct? The redirect URL is computed here - https://github.com/firebase/firebase-js-sdk/blob/e30d7a6522fd3be0c30a82ee054b271a68c03fde/packages/auth/src/platform_browser/popup_redirect.ts#L95, this is where we set the provider ID - https://github.com/firebase/firebase-js-sdk/blob/e30d7a6522fd3be0c30a82ee054b271a68c03fde/packages/auth/src/core/util/handler.ts#L86 and scopes is set few lines below. Can you confirm that you are passing in the correct "provider" parameter to signInWithRedirect or signInWithPopup? Any chance it is  mistakenly triggering it for an Email/Password or similar provider?
