### ISSUE TITLE
Firestore - typescript has no access to `snapshot._document.createTime.timestamp`

### ISSUE THREAD

**Issue by davidbielik** [firebase/firebase-js-sdk#7544]
### Operating System

any

### Browser Version

any

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Using typescript:

```typescript
import {
  CollectionReference,
  DocumentData,
  collection,
  getFirestore,
} from 'firebase/firestore';

const firestore = getFirestore({...});

export const getCollectionRef = <T = DocumentData>(collectionName: string) => {
  return collection(firestore, collectionName) as CollectionReference<T>;
};
```

### Describe the problem

Typescript definitions do not provide a way to access the `snapshot._document.createTime` property.

### Steps and code to reproduce issue

```typescript
getDocs(collection(firestore, 'users') as CollectionReference<{foo: string}>).then(snapshots => {
  // @ts-expect-error missing typescript definition
  snapshots.docs[0]._document.createTime;
})
```
<img width="982" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/7410770/cee267db-31ae-4dd6-b4d3-55482a9afccc">

but the `_document` is defined:

<img width="454" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/7410770/a9e32261-7328-4900-8446-df46bf5fe57f">

**Comment by dconeybe** [comment]
Hi @davidbielik. Thank you for the bug report. Note that `_document` is _not_ part of Firestore's public interface (it's a "private" variable). As a result, the behavior and even presence of `_document` is not guaranteed and we do not support using it directly. So, unfortunately, I cannot give guidance to using it correctly.

However, for createTime specifically, I can say that we intentionally do not expose it from the public API surface. This is because it doesn't have a defined meaning when the document has never been retrieved from the server, such as if the document was created by the client while offline and is served from the local cache.

**Comment by davidbielik** [comment]
Understood, thanks!
