### ISSUE TITLE
FCM Fail To Send android

### ISSUE THREAD

**Issue by HarryB15** [firebase/firebase-js-sdk#7550]
### Operating System

11

### Browser Version

N/A

### Firebase SDK Version

11.2.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Ionic angular project

### Describe the problem

I am developing an ionic angular app, the app has two firebase projects one for dev environment and another for live, I have set up cloud messaging on both. I had successfully set up FCM on my dev project and it was working on both iOS and android, however im now trying to switch over to the live project and for iOS all I had to do was change the googleservice-info.plist file to match the new project and then push notifications would work, however this is not the case for android. I have tried updating the google-services.json file to match the new project however this doesn't fix it, I'm not sure what else to try as I'm getting no error messages, they are just not sending. I believe everything is configured correctly in my project as all the other services I use in my firebase project have switched over successfully.

### Steps and code to reproduce issue

Set up two projects, configure fcm on both, in angular project have one environment set up for each project. 
Once fcm working on android in one environment attempt to get it working in the other environment

**Comment by jbalidiong** [comment]
Hi @HarryB15. Apologies for the delay, and thanks for providing detailed steps on how to reproduce the issue. I wasn't able to replicate the behavior you've experienced. I was able to receive the notification from the original (dev) project and the new (prod) project. Please make sure that the configuration like `appId` in your `capacitor.config.ts` is the same to app in your project console. I verified that it's working fine for the SDKs. That said, I think this would be better discussed with our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact), where you can share project details and what Firebase products that you’re using, so that our agents can explore possible solutions or workarounds.
 
I'll be closing this issue now. If you encounter another issue, feel free to create a new one. Thanks!
