### ISSUE TITLE
Microsoft Edge 42.17134.1.0: messaging().getToken() returns exception

### ISSUE THREAD

**Issue by henrylearn2rock** [firebase/firebase-js-sdk#757]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 
  * Firebase SDK version: 4.13.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
With notification permission granted, messaging().getToken() resolves into an exception:  {code: 20, message: "AbortError", name: "AbortError"}

#### Steps to reproduce:

1. setup basic service worker
2. request permission:  firebase.messaging().requestPermission()
3. get token: firebase.messaging().getToken()

#### Relevant Code:

```javascript
firebase.messaging().getToken()
.then(token => console.log(token))
.catch(e => console.error(e)
```

However, this notification demo works, (not fcm): https://whatwebcando.today/local-notifications.html

**Comment by mmermerkaya** [comment]
Edge is not yet in our list of supported browsers.

That demo works because it's not using the [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API), which is the API FCM uses to get push messages from the server. [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) (that is demoed in that page) is the API that only _displays_ a notification.

Edge 17 (released just 3 days ago) [does support Push API](https://www.caniuse.com/#feat=push-api), and we're currently working on making FCM available on Edge.

**Comment by rubensbiork** [comment]
Hi @mmermerkaya.
Any updates on that?
Thanks
