### ISSUE TITLE
beforeAuthStateChanged not working

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7621]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

index.html with source tag.

### Describe the problem

`beforeAuthStateChanged`'s callback simply does not trigger. It is my understanding that the callback should run before the `onAuthStateChanged` one, but it never does. It doesn't matter if it's an old or new user. If I sign out, then sign in. It never triggers.

### Steps and code to reproduce issue

```
var result = await signInWithPopup(auth, new GoogleAuthProvider());

beforeAuthStateChanged(auth,
    user => {
        if (user) {
            console.log("== BEFORE USER ==");
            console.log(user);
        } else {
            console.log("user signed out and/or deleted");
        }
     }
);
			
onAuthStateChanged(auth,
    user => {
	if (user) {
		console.log("== USER ==");
		console.log(user);
	} else {
		console.log("user signed out and/or deleted");
	}
    }
);
```

**Comment by marcusx2** [comment]
Sorry this was my mistake. `beforeAuthStateChanged` can't be called **after** the `signInWithPopup`, it must be called **before**. If I call it before, it works. 

I guess it makes sense? I'll leave the issue open just in case it's a bug and should work even if called after.

If it's working as intended, can the docs be updated to clarify this? It's not so obvious that this method can't be called just like `onAuthStateChanged` and actually requires it to be called **before** any sign in method.

**Comment by DellaBitta** [comment]
Hi @marcusx2,

I think the issue here is that the code uses `await` which will block until the sign in process completes:

```
var result = await signInWithPopup(auth, new GoogleAuthProvider())
```

In my testing I receive the `beforeAuthStateChanged` event if I change the above code to:

```
var promise = signInWithPopup(auth, new GoogleAuthProvider());
beforeAuthStateChanged(auth, function(u) {
  logOutput("beforeAuthStateChanged");
})
var result = await promise;
```

In the end, the `beforeAuthStateChanged` listener doesn't need to be set up before invoking `signInWithPopup`, but it does need to be registered before the sign in operation completes. On the other hand, the `onAuthStateChanged` event is triggered whenever the listener is set up, which is why you receive the event even if you register the callback after the sign in operation has completed.

I hope this helps!
