### ISSUE TITLE
FR: set custom domain for callable functions once

### ISSUE THREAD

**Issue by harrisonlo** [firebase/firebase-js-sdk#7622]
### Operating System

n/a

### Browser Version

n/a

### Firebase SDK Version

10.3.0

### Firebase SDK Product:

Functions

### Describe your project's tooling

React app

### Describe the problem

I have firebase functions masked under a custom domain with a load balancer. Currently the way to use that domain is to pass an additional param to every `getFunctions()` in the app. Perhaps we can add a field in the options of `initializeApp()` which has auth domain, database url, etc.

### Steps and code to reproduce issue

Something like:
```javascript
initializeApp({  functionsDomain: 'https://api.domain.com'  })
```

**Comment by hsubox76** [comment]
This is a possibility, but it wouldn't just involve modifying the JS SDK code - we would also have to make this change across all client SDKs, plus add it to the backend configuration and the console, so that would involve a lot of teams.

In the meantime, could you work around this by only calling getFunctions() once and just importing that result everywhere you use it?

**Comment by harrisonlo** [comment]
@hsubox76 Understood. I already have an abstraction hook for `getFunctions()` but couldn't apply it everywhere. Upon further thought however, I realized there is a way to do that, so I'm going to close this issue. Thanks!
