### ISSUE TITLE
fetchSignInMethodsForEmail returns empty array for an existing user

### ISSUE THREAD

**Issue by YonatanKra** [firebase/firebase-js-sdk#7644]
### Operating System

Mac OS Ventura

### Browser Version

Chrome

### Firebase SDK Version

10.4.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

It's a vanilla JS web application inside a Tauri desktop app.

### Describe the problem

I'm using Firebase Email and Password Authentication.

I can see the user in my Firebase console, and the user can log in and log out.

In my code, I'm doing this:

const signInMethods = await fetchSignInMethodsForEmail(getAuth(), email);

But signInMethods is an empty array (as opposed to the expected ['password']).

Any idea why this should happen?

### Steps and code to reproduce issue

See this method: https://github.com/YonatanKra/tauri-demo/blob/add-firebase-auth/src/components/auth/auth.ts#L9

You can clone the project, checkout the `add-firebase-auth` branch.

You need to setup an `.env` file with the following details:

VITE_FIREBASE_APP_KEY=***Key***
VITE_FIREBASE_MESSAGING_SENDER_ID=***SID***
VITE_FIREBASE_PROJECT_ID=***PID***
VITE_FIREBASE_APP_ID=***AID***

(replace the details with true details - I can supply my own privately if needed).

Then run: `npm i && npm run dev` to see the UI in the browser.

When you sign in for the first time, it works fine, and the user appears in the Firebase console.

When you refresh the page and log in again, the app is trying to register the user again because `fetchSignInMethodsForEmail` returns an empty array (even though the user has a sign in method (`pasword`).

Any idea why this happens?

**Comment by DellaBitta** [comment]
Hi @YonatanKra,

I wasn't able to reproduce this in my own personal test app, though I had to change the code you posted because `fetchSignInMethodsForEmail` isn't marked `async`. Instead I used the promise's `.then(...)` method [as described here](https://firebase.google.com/docs/auth/web/email-link-auth#differentiating_emailpassword_from_email_link).

Just out of curiosity, do you have any guarantee that the Auth SDK has finished initialization before you attempt to use it? This [documentation provides two methods for tracking if a user is logged in or not](https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user). It looks like you're using the second option which comes with a caveat that `auth.currentUser` might be null because the auth object has not finished initializing.

**Comment by YonatanKra** [comment]
Thanks for the quick response.

Here are some answers to your question:
1. The auth is initialized according to its own data:
<img width="200" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/6459899/a13f8294-615f-4a67-9a46-c279310d78ed">
2. I debugged `fetchSignInMethodsForEmail` internally and I see that the response it gets from the REST API is undefined:
<img width="491" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/6459899/929bc43c-4191-4713-896b-0126fae9b9b0">

It seems like there's an issue with my account maybe? Because I also tried the REST API directly - with the same results (returns undefined).

**Comment by DellaBitta** [comment]
Hm, yes, perhaps it's at the account level. I recommend opening a [Firebase Support Ticket](https://firebase.google.com/support/troubleshooter/contact) so our backend team can look into the problem. I'll leave this GitHub Issue open, too, in case you learn any information from them that is pertinent to those of us on the Web SDK team. Thanks!

**Comment by prameshj** [comment]
Can you also share when this project was created and if [email enumeration protection](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection) was enabled on it?

**Comment by YonatanKra** [comment]
@prameshj 
This project was created last week. Brand new.
I did not enable email enumeration.
Thanks :)

**Comment by YonatanKra** [comment]
Update: 
* I've upgraded to `Identity Platform`, but it didn't help.
* I've opened an issue with Firebase support
Thanks :)

**Comment by prameshj** [comment]
This behavior change is due to the[ Email Enumeration protection feature](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection) that is enabled by default on new projects (created on or after Sep 15). There is an option to [disable the feature,](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection#disable) in case your app relies on this functionality. We recommend not relying on this functionality in the long term, since it can pose a security risk.
