### ISSUE TITLE
revokeAccessToken documentation missing

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7802]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

There seems to be a new method, [revokeAccessToken](https://firebase.google.com/docs/auth/web/apple#token-revocation), but I can't find any documentation on it.

### Steps and code to reproduce issue

Already described.

**Comment by DellaBitta** [comment]
I see that [the documentation exists in our source base](https://github.com/firebase/firebase-js-sdk/blob/0d29adc974d72f93552dad53ebd8b4ecab2ce810/docs-devsite/auth.md?plain=1#L602) but it's not propagating up to the published reference docs for some reason. I'll tag this as a bug so that the Auth team can look into it. Nice catch, and thanks!

**Comment by DellaBitta** [comment]
Hi @marcusx2,

The documentation has been published and can be [found here](https://firebase.google.com/docs/reference/js/auth#revokeaccesstoken) now. Sorry for the inconvenience, and thanks for creating this issue!
