### ISSUE TITLE
Firestore query listeners overlapping when running with Firebase Emulators

### ISSUE THREAD

**Issue by ANDREYDEN** [firebase/firebase-js-sdk#7820]
### Operating System

MacOS Monterey

### Browser Version

Chrome/119.0.6045.159

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Node.js

### Describe the problem

When listening to 2 firestore queries while connected to emulators, one of the queries receives events from the other one.

Related links:
- firebase/flutterfire#11460
- [SO question](https://stackoverflow.com/questions/76863694/flutter-firestore-query-listeners-overlapping-when-running-in-firebase-emulators)

### Steps and code to reproduce issue

Here is [the repo](https://github.com/ANDREYDEN/listener_bug) with detailed repro steps and full code.

## Summary:

Firestore DB (production and emulators):

```
items:
  item#1:
    tags: ['foo']
  item#2:
    tags: ['foo']
  item#3:
    tags: ['bar']
```

Code:

```
const itemsRef = collection(db, 'items')

const q1 = query(itemsRef, where('tags', 'array-contains', 'foo'))
onSnapshot(q1, (snapshot) => {
  console.log(`Got items from query 1: ${snapshot.docs.length}`)
})

onSnapshot(itemsRef, (snapshot) => {
  console.log(`Got items from query 2: ${snapshot.docs.length}`)
})
```

Output when connected to emulators:
```
Got items from query 1: 2
Got items from query 2: 2
Got items from query 2: 3
```

Output when running in production:
```
Got items from query 1: 2
Got items from query 2: 3
```

**Comment by milaGGL** [comment]
Hi @ANDREYDEN, thank you for reporting this issue. 

While listening to above 2 queries, getting the below response is an intended behaviour.
```
Got items from query 1: 2
Got items from query 2: 2
Got items from query 2: 3
```
When we kick off the listener for the first query, SDK tries to raise the initial snapshot from cache, but since it is empty, SDK will wait for server response to return 2 documents. As for the second query, SDK  raises the initial snapshot from cache first, where we have 2 documents matches the query, and then when the server responds with the query 2 results (which differ from the cached results), it creates a new snapshot. 
You can console out the snapshot's metadata to check if it is raised from cache or not.

Regarding the discrepancy in behavior between the emulator and production environments, my hypothesis is that the production backend's response time might be longer than that of the emulator. Consequently, when the SDK attempts to generate the initial snapshot for the second query, the cache might not have finished populating with the results from the first query, therefore, no snapshot is raised from cache. Could you please experiment by inserting a setTimeout between these two listeners to observe any changes in the outcome?

**Comment by ANDREYDEN** [comment]
Thank you for the answer @milaGGL, as you described, the first snapshot from query 2 does indeed come from cache:
```
Got items from query 1: 2 (from cache: false)
Got items from query 2: 2 (from cache: true)
Got items from query 2: 3 (from cache: false)
```

Furthermore, I can confirm your hypothesis about production data by inserting a timeout between the listeners. This code produces the same result as above when running without emulators:
```
const itemsRef = collection(db, 'items')
const q1 = query(itemsRef, where('tags', 'array-contains', 'foo'))

;(async () => {
  onSnapshot(q1, (snapshot) => {
    console.log(`Got items from query 1: ${snapshot.docs.length} (from cache: ${snapshot.metadata.fromCache})`)
  })
  
  await new Promise((resolve) => setTimeout(resolve, 1000))
  
  onSnapshot(itemsRef, (snapshot) => {
    console.log(`Got items from query 2: ${snapshot.docs.length} (from cache: ${snapshot.metadata.fromCache})`)
  })
})();
```

Now the only question I have left is about the caching mechanism: why would the cache for the 2nd query be the same as for the 1st one although they are totally different. To exaggerate the example, consider the items collection containing 1000 items where only 1 of them has a tag of `foo`. This would mean that if when I'm listening for ALL items (query 2) I would get 1 item for a split second (from the cache of the 1st query) and then 1000 items the very next. Doesn't that seem odd?

**Comment by milaGGL** [comment]
Hi @ANDREYDEN , good question. The outcome retrieved from the cache always relies on the existing cache contents. If you switch the order of the queries you mentioned above, populate the large number of documents first, then look for more specific query result, the consistency between initial snapshot and second snapshots would significantly improve. 

Plus, in a real world, it is less likely that we will start our query from an empty cache, unlike in a testing environment. 

If you lean towards a snapshot more aligned with the "server result," you can screen the results using the metadata "fromCache" and disregard any snapshots that aren't synchronized with the backend. However, this might impact certain SDK features such as latency compensation and offline support.
