### ISSUE TITLE
Failed to execute 'createObjectStore' on 'IDBDatabase': The database is not running a version change transaction.

### ISSUE THREAD

**Issue by praveenfsdev** [firebase/firebase-js-sdk#7829]
### Operating System

iOS 15, 16, 17 and Mac OS X 10.15

### Browser Version

Safari, Mobile Safari and Chrome Mobile ios.

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Auth, Database

### Describe your project's tooling

React with typescript

### Describe the problem

Here is the error message which I was receiving from Bugsnag(Error tracking tool).
![Screenshot from 2023-12-01 11-22-24](https://github.com/firebase/firebase-js-sdk/assets/149364485/9cabde93-36b2-42b7-8358-b7d2797ead53)
This error is not occurring always when I load the app. But this is happening often( around 4 times a day) for an users.

### Steps and code to reproduce issue

There are no dedicated steps to reproduce. This is reproducing some times when an app is loading on ios and Mac os browsers.

**Comment by Stanzilla** [comment]
same here

**Comment by hsubox76** [comment]
We can try to catch this error so it doesn't crash the app but I would also like to get at the root cause. According to the IndexedDB spec and the `idb` library docs, `createObjectStore()` shouldn't throw if called inside an upgrade callback, so something in the stack (Safari, the `idb` library, etc.) is not following spec. One thing that would be really helpful here would be to get a strong idea of what browsers it does and does not happen in. So far we've found that it happens in:
- Safari on MacOS
- any browser on iOS (which are all the same engine as Safari)

Does this happen on any non-Safari, non-iOS browsers?

**Comment by Stanzilla** [comment]
Checked our Sentry database since we get a lot of these as well, all mobile iOS Chrome & Safari.
