### ISSUE TITLE
TypeError: undefined is not an object when evaluating ref._location.path

### ISSUE THREAD

**Issue by longtailnyc** [firebase/firebase-js-sdk#7844]
### Operating System

MacOS 13.1

### Browser Version

Safari 16.2

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Storage

### Describe your project's tooling

1. Typescript 4.9.5
2. React 18.2.0
3. react with node (main app) written in Typescript 4.9.5
4. A library project (Library) written in Typescript 4.9.5

Check on the image for some structure
![Screenshot 2023-12-07 at 12 56 40 PM](https://github.com/firebase/firebase-js-sdk/assets/3911307/00a5ca8b-4f6d-48a4-aaf8-9e54b9d81bd5)

### Describe the problem

In the library, when calling ref function to create storage reference, an error is thrown with the following message
TypeError: undefined is not an object (evaluating 'ref._location.path')

Note: storage parameter for the ref function in library is passed from the main app.

### Steps and code to reproduce issue

1. create a library that has getURL function with a param of FirebaseStorage type
2. Create a main app and initiate app
3. In main app, create storage reference
4. Call Library.getURL function and pass in storage reference
5. See the error

**Comment by DellaBitta** [comment]
Hi @longtailnyc,

I wasn't able to successfully reproduce this by [creating a new React app](https://legacy.reactjs.org/docs/create-a-new-react-app.html#create-react-app) with the typescript template  and adding the Storage reference creation and getDownloadURL call to the source of App.tsx.

```
async function getURL() : Promise<any> {
  let storage = getStorage(app);
  const pathRef = ref(storage, "images/test.txt");
  console.log("pathRef ", pathRef);
  const url =  getDownloadURL(pathRef);
  console.log("downloadURL", url);
  return url;
}
```

Invoking this function produces expected results and output when the file 'images/test.txt' exists in Storage.

Can you provide a minimal app that reproduces this issue? Thanks!

**Comment by tzuhaohuang** [comment]
Hi @DellaBitta , I'm part of the team at @longtailnyc 

We've created a public library for you to test, and you can install this library in your react project.
Repo url: https://github.com/Longtail-Education/test-library.git
Package url: https://github.com/Longtail-Education/test-library/pkgs/npm/test-library

Please follow the readme to get everything set up.

Here is a screenshot of 6 testings.
![Screenshot 2023-12-14 at 2 29 14 PM](https://github.com/firebase/firebase-js-sdk/assets/18216145/ce8187d4-4d8b-48dd-ac3b-751e64ebe25f)

We are testing on Firestore and Storage both and neither of them works in a "library" environment.
We use the logics as follow
1. use getFirestore()/getStorage() in the functions
2. pass in FirebaseApp as function param, and use getFirestore(app)/getStorage(app) in the functions
3. pass in Firestore/FirebaseStorage as function param, and use them directly in the functions.

Feel free to check the source file/package.json.

PS: I understand this issue is about storage but in our test, firestore is also not working. So do I need to create a new issue?

Thanks

**Comment by longtailnyc** [comment]
Hi,

my coworker @tzuhaohuang provided a reply above with information needed.

Thanks

**Comment by tzuhaohuang** [comment]
Hi, @DellaBitta 

Any update on this issue?

Any information is appreciated.

Thanks

**Comment by tzuhaohuang** [comment]
We added 3 more tests and these new tests are using **gs://** path when creating a storage reference.
Please see tag 0.1.1 in repo, test7 to test9. Github package is also updated.

test7 produces the same result as test4, which is 

> test7 error: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).

test8 and test9 produces new errors we've never seen before

> test8 error: Firebase Storage: To use ref(service, url), the first argument must be a Storage instance. (storage/invalid-argument)

> test9 error: Firebase Storage: To use ref(service, url), the first argument must be a Storage instance. (storage/invalid-argument)

Right now we are using alternative ways to pass in download urls into our react component library we created.
But ideally we'd like to let component itself get the download urls.

Any updates is greatly appreciated.

**Comment by hsubox76** [comment]
I'm a little confused about this. I'm not sure what you are trying to do with the library but I don't understand how these tests can work. I don't see `initializeApp` anywhere, so there isn't an app, which is why you'd expect to get all these errors. Have you just tried to run this code locally, without making a library?

You must run `initializeApp()` before you can call `getStorage` or `getFirestore` and if you're doing it in some different context, it won't be automatically detected in the global scope and you must pass it the result explicitly to `getStorage()` or `getFirestore()`.

Are you calling `initializeApp` somewhere else? I'm not sure where these test functions are getting their parameters passed in from.
