### ISSUE TITLE
Web Certificate Public key in Firebase Console UI is incorrect/truncated

### ISSUE THREAD

**Issue by kimfucious** [firebase/firebase-js-sdk#7857]
### Operating System

n/a

### Browser Version

n/a

### Firebase SDK Version

n/a

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Flutter app configured with Flutter Fire

### Describe the problem

This is a report of a bug in the Firebase Console on the web, not for the SDK itself.

For the record, I'm using Chrome on a Mac.

When a web push certificate is created under project settings => cloud messaging, the public key is not displayed in full.

This is sure to cause frustration as copying that key from the UI and pasting it into code that needs a vapid key will fail.

At present there is no button to copy the key to the clipboard, so the only way to get to the key from the UI is to inspect it using dev tools and copy it from there.

PS:  I very much appreciate the recent dark mode enhancements to the console.  Nice work 🌮!

### Steps and code to reproduce issue

1. Go for Firebase Console in an existing project
2. Go to Project Settings
3. Go to Cloud Messaging
4. Create a Web Push certificate
5. View the public key in the UI
6. Compare it to the actual key
7. Note that the key in the UI is not correct

**Comment by jbalidiong** [comment]
Hi @kimfucious, based on your info, it seems like you're having an issue with the Web Certificate Public Key on the Firebase UI. As the issue is related to the console, please file a ticket via our [support channel](https://firebase.google.com/support) so the FCM team will be able to get your project details and investigate it in our backend. With this, I'll now close the ticket.
