### ISSUE TITLE
FR: Better error message for using FCM with http

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7885]
### Operating System

macOS 13.6.1

### Browser Version

Safari 17.1

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

When using the cloud messaging api with http instead of https, the following error is thrown

`Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser)`.

However, I think this error is misleading. Even though the browser supports the api, the real issue is that http protocol is being used instead of https. I request that a specific error for using the wrong protocol be raised instead.

### Steps and code to reproduce issue

Already described.

**Comment by looptheloop88** [comment]
Hi @marcusx2, thanks for the feedback. This is working as expected. FCM is only supported on sites served over HTTPS due to its use of service workers, which are only available on HTTPS sites. The [`isSupported()`](https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging-compat/src/messaging-compat.ts#L56) method doesn't directly check if the site is running on HTTP or HTTPS, rather it has conditions to validate if all required APIs exist or supported by the browser.
