### ISSUE TITLE
getToken hangs

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7889]
### Operating System

macOS 13.6.3

### Browser Version

Safari 17.2

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

[getToken](https://firebase.google.com/docs/reference/js/messaging_.md#gettoken) suddenly stopped working and now it just hangs. The promise never fulfills or rejects. Seems like I'm not the first to report this issue either, with a quick google search it was reported before.

Don't know if it's related or not, but the problem happened after I started playing with the [quick-start](https://github.com/firebase/firebase-js-sdk/issues/7886#issuecomment-1862778410), when sending a test message at some point I deleted all the FCM registration tokens using the firebase console 

<img width="638" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/5656275/e6a8f0f6-6c23-43bc-ae15-93d6ee6853ed">
, 

and now I can't get a new one.

### Steps and code to reproduce issue

I have no idea. I didn't do anything special. I was struggling to get the notification but I was getting the token. Now I can't even get the token ;_;. I also tried creating new vapid keys, to no avail. I can't use the api at all at this point.

**Comment by marcusx2** [comment]
I managed to "fix" the problem by uploading the build to [netlify](https://app.netlify.com). With the build hosted there I can get the token, but I can no longer test locally with [ws --https](https://www.npmjs.com/package/local-web-server). Still, no notifications, but at least the [onMessage](https://firebase.google.com/docs/reference/js/messaging_.md#onmessage) works. So the message is being delivered, but I can't for the life of me get notifications to work.

**Comment by looptheloop88** [comment]
Hi @marcusx2, I wasn't able to replicate this issue. The FCM token is getting generated and refreshed successfully when I open the app using the latest version of Google Chrome and Safari 17.2. Also, both browsers are able to receive the test messages I sent via notifications composer console.

I am not really sure if your local server set up is the one causing the issue. But by just using the quickstart project, you may run the `npm run dev` command and your app will be hosted on localhost. You just need to update the service worker script and use [these](https://github.com/firebase/quickstart-js/blob/master/messaging/firebase-messaging-sw.js#L10-L37) lines of codes, instead of [these](https://github.com/firebase/quickstart-js/blob/master/messaging/firebase-messaging-sw.js#L1-L8) ones.

**Comment by marcusx2** [comment]
> You just need to update the service worker script and use [these](https://github.com/firebase/quickstart-js/blob/master/messaging/firebase-messaging-sw.js#L10-L37) lines of codes, instead of [these](https://github.com/firebase/quickstart-js/blob/master/messaging/firebase-messaging-sw.js#L1-L8) ones.

Yes like I said, I am able to trigger the onMessage, with the app hosted on netlify. Locally it doesn't work anymore, and never mind notifications. I only managed to get them 2 or 3 times and never again. I guess this can be closed, I have nothing else to offer.
