### ISSUE TITLE
error in docs regarding web Namespaced api

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7891]
### Operating System

macOS 13.6.3

### Browser Version

Safari 17.2

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

The docs regarding the [Namespaced api](https://firebase.google.com/docs/cloud-messaging/js/receive#web-namespaced-api) has an error. It's written

```
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-messaging.js');
```

when it should be

```
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-messaging-compat.js');
```

add "-compat".

### Steps and code to reproduce issue

Already described.

**Comment by looptheloop88** [comment]
Hi @marcusx2, the documentation for web namespaced API is correct. Since the web modular API starts with version 9, its compat version also starts with version 9. As for the code snippet you mentioned, both versions 8 and compat 9 will work. See links below of your reference:

- https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js (OK)
- https://www.gstatic.com/firebasejs/8.10.1/firebase-app-compat.js (NOK)
- https://www.gstatic.com/firebasejs/9.0.0/firebase-app-compat.js (OK)
- https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js (OK)
