### ISSUE TITLE
getDoc() is never resolved nor rejected

### ISSUE THREAD

**Issue by AnthonyLzq** [firebase/firebase-js-sdk#7911]
### Operating System

macOS 14.1.2 23B92 arm64

### Browser Version

Brave on macOS (Chrome 120 on macOS (Sonoma))

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Remix

### Describe the problem

For some reason, `getDoc` function does not work when I use `fireabse/firestore/lite`, but without `lite`, it does.

### Steps and code to reproduce issue

When I try to do the following:

```ts
import { initializeApp } from 'firebase/app'
import { getFirestore, doc, getDoc } from 'firebase/firestore/lite'

const firebaseConfig = { /* some attributes here */ }
const firebaseApp = initializeApp(firebaseConfig)
const db = getFirestore(firebaseApp)
const clientRef = doc(db, 'users', id)
const clientSnap = await getDoc(clientRef)

// the above part never resolves
```

But if I change the code to use:

```ts
import { getFirestore, doc, getDoc } from 'firebase/firestore'
```

Instead of:

```ts
import { getFirestore, doc, getDoc } from 'firebase/firestore/lite'
```

It works fine

**Comment by MarkDuckworth** [comment]
@AnthonyLzq, I'm unable to reproduce this with Firebase v10.7.1 on Brave browser or Chrome. Can you enable debug logging for the Firestore package and send us the logs?

Add this line during the setup to write Firestore SDK logs.

```
setLogLevel('debug');
```

**Comment by AnthonyLzq** [comment]
I'm sorry I couldn't provide more context. I'll try to give you a minimal example today.

**Comment by luizfelmach** [comment]
Same issue here with addDoc. Im using 10.7.1 too.

**Comment by MarkDuckworth** [comment]
@luizfelmach, can you provide logs from the Firestore SDK that capture when the issue occurs for you?

```
setLogLevel('debug');
```

**Comment by luizfelmach** [comment]
> @luizfelmach, can you provide logs from the Firestore SDK that capture when the issue occurs for you?
> 
> ```
> setLogLevel('debug');
> ```

I discovered that the environment variables were not working in Next.js even with NEXT_PUBLIC. So the problem wasn't in firebase. However, it would be interesting if firebase returned an error if it was unable to connect. I believe that a maxtimeout and return an error so that you don't spend hours trying to find the error.

**Comment by MarkDuckworth** [comment]
@luizfelmach, thanks for the follow up. That sounds like [expected behavior for `addDoc()` when offline](https://firebase.google.com/docs/reference/js/firestore_#adddoc). If the write cannot be sent to the backend because the SDK cannot connect, then the write will be cached in the SDK and sent when the SDK can connect again. This is part of offering a seamless online and offline support in the SDK. Unfortunately, it sounds like this was a source of confusion for you today.

**Comment by luizfelmach** [comment]
Okay. Sorry about that and thanks for the help.

**Comment by luizfelmach** [comment]
> @luizfelmach, thanks for the follow up. That sounds like [expected behavior for `addDoc()` when offline](https://firebase.google.com/docs/reference/js/firestore_#adddoc). If the write cannot be sent to the backend because the SDK cannot connect, then the write will be cached in the SDK and sent when the SDK can connect again. This is part of offering a seamless online and offline support in the SDK. Unfortunately, it sounds like this was a source of confusion for you today.

Okay. Sorry about that and thanks for the help.
