### ISSUE TITLE
`signInWithCustomToken` not working on Safari

### ISSUE THREAD

**Issue by KrisLau** [firebase/firebase-js-sdk#7997]
### Operating System

iOS 16.4

### Browser Version

16.5

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

React with Vite

### Describe the problem

So I'm trying to implement an auto login for my website when the user is logged in on the app and viewing it in the webview on the app. Currently, I'm passing my userID to my website that's displayed in my React Native app's webview via query parameters. Then in the useEffect for the website, I retrieve the custom token from my backend and signInWithCustomToken from firebase. For some reason, the auto login works on Android but not on iOS. I think it's a Safari issue:

- https://www.reddit.com/r/Firebase/comments/13r8kkq/firebase_auth_signinwithcustomtoken_not_working/
- https://stackoverflow.com/questions/71446206/firebase-auth-signinwithcustomtoken-on-safari-web-extension-not-working

### Steps and code to reproduce issue

Try to `signInWithCustomToken` on Chrome and Safari. On Chrome, it will work but on Safari, it will fail with no error.

**Comment by ianbranda** [comment]
I am running into the same issue with a browser extension. Everything works fine on Firefox and Chrome, but Safari suddenly stopped working. 

Both signInWithCustomToken and onAuthStateChanged seem to be affected. Neither of them are creating any responses, errors or otherwise. Auth is working fine in the web client I've built, but not in the extension. I wonder if it's less of an issue with Safari itself and more to do with the application build?

**Comment by pragatimodi** [comment]
Hi, thanks for reporting this bug!
Can you check if there's a network request that goes through via the extension?
