### ISSUE TITLE
Google Popup Auth Overides Twitter Popup data on Authentication Tab

### ISSUE THREAD

**Issue by loarsaw** [firebase/firebase-js-sdk#8028]
### Operating System

Windows 11

### Browser Version

Chrome/121.0.6167.185

### Firebase SDK Version

9.18.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Nextjs - 13.2.4
Firebase - 9.18.0

### Describe the problem

I have Two Login Methods 
1. Login with Google (Popup)
2. Login with Twitter (Popup)

If you are logged in with Google you can link you twitter as one recieves an error code
```
auth/account-exists-with-different-credential
```

If I signup with Google and then use the button that  login with Twitter then  am recieving the above mentioned error  but  if signup with twitter  and then again login with Google I dont recieve ```auth/account-exists-with-different-credential and twitter is overriden by Google login method and now upon login with twitter

Step 1 : Signup with Google

<img width="250" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/84080351/2c23c0b5-d0c3-40ff-a3a5-b200b5de2c7b">

Step 2 : Sign Up  with twitter , Since already there with Google it will throw an error and we can use 
```
linkWithPopup(auth.currentUser, provider);
```
and then
<img width="247" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/84080351/cbf7d1d6-81de-44be-9b5d-8111e116db7c">

Deleted User now start with twitter
<img width="252" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/84080351/5686a370-6904-4ab1-ba07-81ab85783014">

Now If I use Google 
<img width="263" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/84080351/5eb671e6-eaf5-4a24-8b52-55ec70bbee5f">

Woosh !

### Steps and code to reproduce issue

```jsx
export async function twitterSignIn() {
  const provider = new TwitterAuthProvider();
  try {
    const result = await signInWithPopup(auth, provider);
    const user = result.user;
    console.log("IN TWIS");
    const { isNewUser }= getAdditionalUserInfo(result);
    console.log(isNewUser);
    if (isNewUser) {
      await setUserProfile(user, 13);
    }
  } catch (error) {
    if (error.code == "auth/account-exists-with-different-credential") {
         googleSignIn().then(() => {
            linkWithPopup(auth.currentUser, provider);
          });
        },
      });
    }
  }
}
```

```jsx
export async function googleSignIn(randomNumber: number) {
  const provider = new GoogleAuthProvider();
  console.log("INPR");
  try {
    const result = await signInWithPopup(auth, provider);
    const user = result.user;
    console.log("DOne")
    console.log(user);
    const { isNewUser }: any = getAdditionalUserInfo(result);
    console.log(isNewUser);
    if (isNewUser) {
      await setUserProfile(user, randomNumber);
    }
  } catch (error: any) {
    if (error.code == "auth/account-exists-with-different-credential") {
   
    
          twitterSignIn().then(()=>{
          linkWithPopup(auth.currentUser, provider);})
  
  
    console.log(error);
  }
}
```

**Comment by shaffy9633** [comment]
Im facing the same exact issue,. It works for google and apple, but not for twitter. Say I currently have a password authenticated with x@gmail.com. When i log in via apple (x@gmail.com), it logs me into that same account that was password authenticated + links this new apple credential as well. The same happens for google. But for twitter, it basically throws the error 'auth/account-exists-with-different-credential' instead of logging me and linking. Hopefully somebody can attend to this as it seems very fixable

**Comment by NhienLam** [comment]
Hi, thank you for reaching out! This is working as expected because we don't take Twitter as an authoritative provider. You can find the list of trusted and untrusted providers at https://firebase.google.com/docs/auth/users#verified_email_addresses.

When account linking is enabled for the project, the behavior is:

1. When user signs in with a **trusted** provider (eg. Google) then signs in with **untrusted** provider (eg. Twitter) with the same email, auth/account-exists-with-different-credential will be thrown.

2. When user signs in with an **untrusted** provider (eg. Twitter) then signs in with a different **trusted** provider (eg. Google) with the same email, the trusted provider overwrites the untrusted provider. If the user attempts to sign in again with Twitter, it will cause an error requiring account linking.

I will be closing this bug. Feel free to reopen if you have anymore questions or concerns. Thank you!
