### ISSUE TITLE
[firestore] set with merge true should not send data that has not changed in local cache.

### ISSUE THREAD

**Issue by cedvdb** [firebase/firebase-js-sdk#8047]
### Operating System

windows

### Browser Version

chrome 122

### Firebase SDK Version

10.0.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Flutter app

### Describe the problem

Original issue was posted on the flutterfire repository, but this is applicable to the js sdk.

**Describe the bug**

When using `_ref.set(data, { merge: true })`, all properties will be sent over the network even if the locally persisted version contained some of those properties. 

For example:

  - locally persisted object `{ windows: 1, bathrooms: 1, toilets 1 }`
  - `ref.set({ windows: 1, bathrooms: 1, toilets 2 }, { merge: true }` => sends `{ windows: 1, bathrooms: 1, toilets 2 }` over the network.
  - In the above there was no need to send `{ windows: 1, bathrooms: 1}`. It could have just sent `{ toilets: 2 }` as it is the only property that changed when diffing against the local persistence.

The issue with this is that this might introduce unintended overwrites in the event that two users try to update the same record at the same time.
 
### Steps to reproduce

Here is an example where an user overrides an update from another user. The example is written in dart as the original issue was posted on flutterfire.

https://github.com/cedvdb/firebase-repro/tree/firestore_merge

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart';

void main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.settings =
      const Settings(persistenceEnabled: true);

  final house = House(windows: 1, bathrooms: 1, toilets: 1);

  final housesRef =
      FirebaseFirestore.instance.collection('houses').withConverter(
    fromFirestore: (snapshot, options) {
      final data = snapshot.data();
      if (data == null) return null;
      return House.fromMap(data);
    },
    toFirestore: (value, options) {
      return value?.toMap() ?? {};
    },
  );

  //  initial save
  await housesRef.doc('house-id').set(house);

  await Future.wait([
    // user 1 update
    housesRef.doc('house-id').set(house.copyWith(toilets: 2), SetOptions( merge: true )),
    // user 2 update
    housesRef.doc('house-id').set(house.copyWith(windows: 2), SetOptions( merge: true )),
  ]);

  print('done');

  // expected result: { bathrooms: 1, toilets: 2, windows: 2 }
  // actual result: variable
}

class House {
  final int windows;
  final int bathrooms;
  final int toilets;

  House({
    required this.windows,
    required this.bathrooms,
    required this.toilets,
  });

  House copyWith({
    int? windows,
    int? bathrooms,
    int? toilets,
  }) {
    return House(
      windows: windows ?? this.windows,
      bathrooms: bathrooms ?? this.bathrooms,
      toilets: toilets ?? this.toilets,
    );
  }

  Map<String, dynamic> toMap() => {
        'windows': windows,
        'toilets': toilets,
        'bathrooms': bathrooms,
      };

  factory House.fromMap(Map<String, dynamic> map) {
    return House(
      windows: map['windows'],
      bathrooms: map['bathrooms'],
      toilets: map['toilets'],
    );
  }
}
```

### Expected behavior

The local cache should be checked against and properties that are the same as in the local cache should not be sent over the network to avoid unintended overrides between users.

### Why send the properties inside the set method at all in my example ?

static typing in dart :

```
    housesRef.doc('house-id').set(house.copyWith(toilets: 2), SetOptions( merge: true ));
    // vs
    housesRef.doc('house-id').update( { 'toiletts': 2 });  // oops, should be "toilets" instead of "toiletts"
```

### Steps and code to reproduce issue

[Here is a sample project, add your own firebase config before running it](https://github.com/cedvdb/firebase-repro/tree/firestore_merge)

**Comment by cherylEnkidu** [comment]
Hi @cedvdb,

Could you give us more explanation for your desire behaviour? 

For example in case: `{ windows: 1, bathrooms: 1, toilets 1 }`

User A sends `{ toilets: 2 }`, and User B sends `{ bathrooms:  2}`, the expected result will be `{ windows: 1, bathrooms: 2, toilets 2 }`?

**Comment by cherylEnkidu** [comment]
Hi @cedvdb ,

Thank you for your explanation. 

`set` is make to define the whole document. With merge set to `true`, it is just for easy coding, not to serve the update purpose. 

I understand using `set` is more convenient in your code. However, it is Firestore intended behaviour to have `set` with merge set to true different from `update`.

**Comment by cedvdb** [comment]
> Is there an use case for sending the properties that are already in the persisted cache when merge is true ?
 
 If not, I suggest reconsidering the behavior.

**Comment by cherylEnkidu** [comment]
For the `set` operation, there are some developer's apps reply on the current behaviour. Changing this behaviour will be a breaking change so it is unlikely for the SDK to execute differently.

**Comment by cherylEnkidu** [comment]
Hi @cedvdb ,

I totally understand you would like a more convenient way to manage your app. However, what stop us from changing the current definition is not only because there are users relying on this.

In theory, to avoid breaking changes, the SDK can introduce another option to `set` to have the same effect as `update`. However, it is unlikely for us to do so. Since in the API design, we try to avoid introduce two ways (not including convenient functions) to achieve the same goal. If the SDK do have such API, it will cause a lot of troubles for our developers to distinguish the differences. 

Here, by definition, `set` and `update` serve the different purposes. `set` is make to define the whole document, so the latest change acts as the source of truth. It is not about sending cache data to the backend. Cache data only helps local device to display the data sooner. Even without cache data, the backend won't behave differently.

In your case, please considering creating your own helper functions to support coding. Thank you for your understanding :)

**Comment by cedvdb** [comment]
> In your case, please considering creating your own helper functions to support coding.
 
 I have one but that's beside the point. This could benefit a wider audience than just me but I'll stop pushing since at this point it's a design decision.

 > It is not about sending cache data to the backend. Cache data only helps local device to display the data sooner. Even without cache data, the backend won't behave differently.
 
 It is not clear if you understood the issue with this sentence. Just to be clear for future readers:
 
 If I have `{ windows: 1, toilets: 1 }` in my local cache, and use `docRef.set({ windows: 1}, merge: true)`, I believe what should be sent over the network is `{}` (no update).  If I use `docRef.set({ windows: 1, toilets: 2}, merge: true)` I believe what should be sent over the network is  `{ toilets: 2 }`

**Comment by cherylEnkidu** [comment]
Hi @cedvdb ,

Thank you for the further details. The short answer is the team is unlikely to change the existing design. But I would like to explain more about it.

The design vision for `set` is, the user sees version A, he/she wants to change it to version B. The document version can only be B or C (if another user overwrites the document at the same time). Since the document is been treated as a whole object, the final version cannot be a combination of B and C.

`set` with `merge: true` is only been served as a syntax sugar, it is still part of `set` family. Which means, when it changes the document, it defines all of it. 

If the concurrency issue affects app's performance, there are some other APIs can be considered, for example `transaction`.

Thank you for your understanding.
