### ISSUE TITLE
angularfire2 test suite broken in 5.0.1 & 5.0.2

### ISSUE THREAD

**Issue by jamesdaniels** [firebase/firebase-js-sdk#809]
### [REQUIRED] Describe your environment

  * Operating System version: osx + travis
  * Firebase SDK version: 5.0.2
  * Firebase Product: firestore, core

### [REQUIRED] Describe the problem

This may be indicative of a larger problem but running the angularfire test suite against JS SDK 5 results in the following failure:

```
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the CDN builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

https://www.gstatic.com/firebasejs/5.0.0/firebase-<PACKAGE>.js
'
HeadlessChrome 0.0.0 (Mac OS X 10.13.3) ERROR: {code: 'app/duplicate-service', message: 'Firebase: Firebase service named 'firestore' already registered (app/duplicate-service).', name: 'firestore'}
HeadlessChrome 0.0.0 (Mac OS X 10.13.3) ERROR
  {
    "message": "Uncaught Error: Cannot instantiate firebase-firestore - be sure to load firebase-app.js first.\nat node_modules/firebase/firebase-firestore.js:1:322538\n\nError: Cannot instantiate firebase-firestore - be sure to load firebase-app.js first.\n    at firebase (node_modules/firebase/firebase-firestore.js:1:322561)\n    at node_modules/firebase/firebase-firestore.js:1:322678",
    "str": "Uncaught Error: Cannot instantiate firebase-firestore - be sure to load firebase-app.js first.\nat node_modules/firebase/firebase-firestore.js:1:322538\n\nError: Cannot instantiate firebase-firestore - be sure to load firebase-app.js first.\n    at firebase (node_modules/firebase/firebase-firestore.js:1:322561)\n    at node_modules/firebase/firebase-firestore.js:1:322678"
  }
```

#### Steps to reproduce:

I have a WIP branch with a bunch of changes here https://github.com/angular/angularfire2/pull/1615 that's experiencing it but you can just checkout master, update the `package.json`, run `yarn` and `yarn test` and experience it for yourself.

Also see our canary test https://travis-ci.org/angular/angularfire2/jobs/376185513

#### Relevant Code:

https://github.com/angular/angularfire2

**Comment by jshcrowthe** [comment]
The issue is an Angularfire issue not a firebase package issue. The issue here is happening because of the documented breaking changes in the `v4` to `v5` update. Specifically:

- > Refactored the top-level Firebase entrypoints (e.g. `import firebase from 'firebase';`) to additionally include the Firestore and Functions components which were previously excluded by default. Developers using these bundles will find a warning in the browser console instructing them how to include only the components they are using, which will improve the performance of their applications.
- > `QuerySnapshot.docChanges()` is now a method that optionally takes an includeMetadataChanges option. By default, even when listening to a query with `{ includeMetadataChanges:true }`, metadata-only document changes are suppressed in `docChanges()`.

The following updates will fix the issue:
- Remove the separate `firebase-firestore.js` include from here: https://github.com/angular/angularfire2/blob/master/karma.conf.js#L29 (loading firestore twice breaks things)
- Refactor from `docChanges` to `docChanges()`
  - https://github.com/angular/angularfire2/blob/master/src/firestore/collection/changes.ts#L18
  - https://github.com/angular/angularfire2/blob/master/src/firestore/collection/changes.ts#L28
