### ISSUE TITLE
New 5.x component imports broken

### ISSUE THREAD

**Issue by vincentwoo** [firebase/firebase-js-sdk#820]
It seems like Firebase changed the surface of its top-level import module. Previously, this would work:

```js
import * as firebase from 'firebase/app'
import 'firebase/database'

firebase.initializeApp(...)
```

Now, the object returned from importing firebase/app has everything that it used to provide scoped under the key "default", so you have to do:

```js
import * as firebase from 'firebase/app'
import 'firebase/database'

firebase.default.initializeApp(...)
```

This seems like an oversight.

**Comment by merlinnot** [comment]
Use
```
import firebase from 'firebase/app';
import 'firebase/database';
```

**Comment by paulstelzer** [comment]
As @merlinnot says and do not forget (if you are using TypeScript) to add 

`"allowSyntheticDefaultImports": true`

to your tsconfig.json

**Comment by bricepepin** [comment]
Using `import firebase from '@firebase/app';` instead of `import firebase from 'firebase/app';` avoid the need of `"allowSyntheticDefaultImports": true` for me.

**Comment by mmermerkaya** [comment]
Closing this as the issue seems to be resolved.

I think all our docs recommend the style @merlinnot mentioned. Please let us know if that's not the case.

For Typescript, I'd recommend turning on `esModuleInterop` instead of `allowSyntheticDefaultImports`. `esModuleInterop` implicitly turns on synthetic default imports, and has other benefits as well. The TypeScript team "highly recommends applying it both to new and existing projects". See [TS 2.7 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) for more information (search for "esModuleInterop", it's close to the bottom of the page).

**Comment by vincentwoo** [comment]
I think https://firebase.google.com/docs/web/setup#sdk_imports_and_implicit_initialization is a bit light on details for the analogous case in module importing
