### ISSUE TITLE
Provide an example to subscribe to a topic!

### ISSUE THREAD

**Issue by 0wwafa** [firebase/firebase-js-sdk#8472]
### Operating System

n/a

### Environment (if applicable)

Chrome latest (128)

### Firebase SDK Version

10.13.1

### Firebase SDK Product(s)

Messaging

### Project Tooling

notepad++

### Detailed Problem Description

What I need:

In a webapp (no server code), I want to:
register the service worker for push notifications
get the token and subscribe it to TOPIC "test topic"

There seems to be no way to do this simple thing!
Why?!

### Steps and code to reproduce issue

iid.googleapis can be used but only with service account and server code, which is stupid because FCM and IID **are** servers.

in messaging **there must be** a mechanism to subscribe not just to the "page" but to a topic!

please provide it.
or add an authentication method to iid.googleapis that authenticates with the application config object and not the service account.

**Comment by 0wwafa** [comment]
@jbalidiong do not close this issue. and read again carefully https://github.com/firebase/firebase-js-sdk/issues/8469#issuecomment-2325346406

**Comment by jbalidiong** [comment]
Hi @0wwafa, apologies for the delay in response and if we misunderstood your question in the previous issue you filed. We thought you were asking for custom implementation or something similar, which is best directed to our developer community channels such as Stack Overflow or via Firebase support channel. Please note that this channel is mainly used to report SDK related issues, bugs or feature requests. We also advised our developers to follow the template when filing an issue, including any additional information that we can use to answer or resolve the issue.

We [rolled out a lot of changes](https://firebase.google.com/support/release-notes/js) this past few years in the Firebase JS SDK, especially on how the SDK is being imported and used in the app. Since [version 9](https://firebase.google.com/support/release-notes/js#version_900_-_august_25_2021), the JS SDK uses a modular API and we suggest our developers use it instead of the namespaced API.

While we recommend using the SDK via npm, you may also set it up using [CDN](https://firebase.google.com/docs/web/alt-setup#from-the-cdn) _(see the list of [available SDK from CDN](https://firebase.google.com/docs/web/learn-more#libraries-cdn))_ and import the SDK in your static HTML page:

```
  <body>
  <!-- Insert this script at the bottom of the HTML, but before you use any Firebase services -->
  <script type="module">
    import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.13.1/firebase-app.js'

    // If you enabled Analytics in your project, add the Firebase SDK for Google Analytics
    import { getAnalytics } from 'https://www.gstatic.com/firebasejs/10.13.1/firebase-analytics.js'

    // Add Firebase products that you want to use
    import { getAuth } from 'https://www.gstatic.com/firebasejs/10.13.1/firebase-auth.js'
    import { getFirestore } from 'https://www.gstatic.com/firebasejs/10.13.1/firebase-firestore.js'
  </script>
  </body>
```

Next, add your Firebase configuration object, and then initialize Firebase in your app:

```
  const firebaseConfig = {
    // ...
  };

  const app = initializeApp(firebaseConfig);
```

Once Firebase is already initialized, proceed with [adding FCM in your client app](https://firebase.google.com/docs/cloud-messaging/js/client#web). You may use this [quickstart project](https://github.com/firebase/quickstart-js/tree/master/messaging) as your reference, specifically the [`main.ts`](https://github.com/firebase/quickstart-js/blob/master/messaging/main.ts) file which has the FCM implementation code snippets.

You also have an inquiry on how to subscribe to a user or web app instance in a topic. Per checking, this feature is not available in the FCM JS SDK. You may need to use a server with Admin SDK or REST API implementation for topic subscription.

There's already an internal request filed for this feature, but we can't provide any timeline or assurance if this will be implemented soon. If there's anything else I can help you with, just let me know.

**Comment by 0wwafa** [comment]
@jbalidiong 
No. I need a simple way to SEND a notification to a GROUP from a WEBAPP.
Before I was using iid.googleapis.com with authorization key=
but google removed it.
and also now FCM SEND has problems because with the new api it does not have CORS.

please read again the issue.

**Comment by jbalidiong** [comment]
Apologies if it still doesn't align with your use-case. We highly advise that sending a message to other devices to show a notification should be done only from a trusted environment such as the Firebase console, your development machine, a server or on Cloud Function. Then your app invokes the server-side code that ensures the call is authorized and then trigger the FCM API. Doing this from the device itself might pose a security risk as you're including your keys into the app, people with malicious intent can now get that key and send any messages to all users of your app.

For guidance regarding using v1, you can refer to our [documentation](https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-topics). Here is a sample snippet for the send request:

```
POST https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send HTTP/1.1

Content-Type: application/json
Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA
{
  "message":{
    "topic" : "foo-bar",
    "notification" : {
      "body" : "This is a Firebase Cloud Messaging Topic Message!",
      "title" : "FCM Message"
      }
   }
}
```

For what it's worth, you can explore a [sample FCM function that sends notifications for new followers](https://github.com/firebase/functions-samples/tree/main/Node-1st-gen/fcm-notifications).

> Sending the notification is done using the Firebase Admin SDK. The Web client writes the individual device tokens to the realtime database which the Function uses to send the notification.

**Comment by 0wwafa** [comment]
Nope. You must create a method to allow a WEBAPP to send a notification (to another  user of the same webapp).
Directly!
We are in 2024!!! It's time you allow a real peer to peer method.
Having to use a server just to do a POST and a token request is dumb.

**Comment by 0wwafa** [comment]
And that's why people use less and less firebase.
Especially after the last "update".
About security, I have 30 years of experience in the field and trust me, if there is someone that does not implement security correctly it's google! I tried to contact them and they didn't even bother to answer, while their services are mostly open to anyone.
