### ISSUE TITLE
Firebase Analytics don't log my events in console

### ISSUE THREAD

**Issue by imalitavakoli** [firebase/firebase-js-sdk#8501]
### Operating System

Windows 11

### Environment (if applicable)

Chrome 128

### Firebase SDK Version

10.13.1

### Firebase SDK Product(s)

Analytics

### Project Tooling

Vanilla JavaScript

### Detailed Problem Description

I don't see my events being logged in the '[DebugView](https://console.firebase.google.com/project/_/analytics/debugview)' (or 'Realtime Analytics' page) of my Firebase project!

### Steps and code to reproduce issue

After creating my test project in Firebase Console, I receive a Config Object, right? So I used my Config and wrote the following simple codes:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      http-equiv="Cache-control"
      content="no-cache, no-store, must-revalidate"
    />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <title>Firebase test</title>
    <base href="./" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, shrink-to-fit=no"
    />
  </head>

  <body>
    Hello :)
    <button onclick="logMyEvent()">Log an event</button>
    
    <script type="module">
      import { initializeApp } from "https://www.gstatic.com/firebasejs/10.13.1/firebase-app.js";
      import { getAnalytics, logEvent } from "https://www.gstatic.com/firebasejs/10.13.1/firebase-analytics.js";
    
      const firebaseConfig = {
        apiKey: "xxx",
        authDomain: "xxx.firebaseapp.com",
        projectId: "xxx",
        storageBucket: "xxx.appspot.com",
        messagingSenderId: "000",
        appId: "xxx000",
        measurementId: "G-xxx"
      };
    
      const app = initializeApp(firebaseConfig);
      const analytics = getAnalytics(app);

      logEvent(analytics, 'test_init', { 'data': 'init' });

      window.logMyEvent = function() {
        console.log('Button was clicked!', analytics); // `analytics` is already defined.
        logEvent(analytics, 'test_button_click', { 'data': 'click' });
      };
    </script>
  </body>
</html>
```

As you can see this is just a basic Firebase Analytics implementation! But I don't see my events being logged in the '[DebugView](https://console.firebase.google.com/project/_/analytics/debugview)' (or 'Realtime Analytics' page) of my Firebase project... Am I missing something?

In the 'DebugView', I also see this message: '_Debug Device: 0, No devices available_', although I have already installed '[Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna)' Chrome extension and turned it on.

In the '_Network_' tab of my Chrome browser's '_Developer Tools_', I can see that as soon as I load the page, `https://firebase.googleapis.com/v1alpha/projects/-/apps/xxx000/webConfig` API calls happens, and I receive `200 OK` response. But that's it! No other API calls will get out of my web-page after I click my button to log a new event! To me everything looks correct! But why it's not working?!

Any help is appreciated. Thanks in advance.

**Comment by jbalidiong** [comment]
Hi @imalitavakoli, thanks for reaching out to us. I tried replicating the behavior you've mentioned but I wasn't able to encounter the any issue seeing my events in the debugView console. Here is what I noticed during the replication:

- Upon initialization, `firebase-app.js` and `firebase-analytics.js` return status 200.
-  After the webConfig request returns status 200, this will follow requesting to `https://www.googletagmanager.com/gtag/js`
- After enabling the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) Chrome extension you'll see this in your developer console.

<img width="865" alt="Screenshot 2024-09-20 at 10 39 48 PM" src="https://github.com/user-attachments/assets/5c2172e0-4a47-4a9d-ad39-147164adc3a3">
- This will log the initials events like page_view, session_start etc. I noticed that logEvent code from initialization run successfully.

```
      logEvent(analytics, 'test_init', { 'data': 'init' });
```
<img width="443" alt="Screenshot 2024-09-20 at 11 01 02 PM" src="https://github.com/user-attachments/assets/86c5c64b-0be7-4745-ad0c-d7d1ce55048f">

It was also loaded in the DebugView:
<img width="293" alt="Screenshot 2024-09-20 at 11 02 13 PM" src="https://github.com/user-attachments/assets/c54a2673-2b33-4803-a319-ac72a36736ee">


For guidance here is what I did for connecting the app to the debugView:
- Run the app with Live Server if you're using VS code studio 
- Open the developer console and enable the Google Analytics Debugger extension.
- Open the DebugView on the Firebase console, you should be able on the drop down menu the device to debug.

If the issue persists, it may be within your project. That said, I think this would be better discussed with our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact), where you can share project details and what Firebase products that you’re using, so that our agents can explore possible solutions or workarounds. I verified that it's working fine for the SDKs.

P.S. Viewing the file on the browser will return an error `Unallowed document protocol. Aborting hit.`

**Comment by imalitavakoli** [comment]
Well, my code seems correct, right? I also see that `firebase-app.js` and `firebase-analytics.js` return status 200. webConfig request returns status 200. And then `https://www.googletagmanager.com/gtag/js` requests happen that return status 307.

But maybe my problem is from the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) Chrome extension! Because This is the warning that Chrome gives me about this extension:
![01](https://github.com/user-attachments/assets/3599af99-4e65-48b8-ad1d-3730b3abc460)

I also cannot see the '_Google Tag_' message in my developer console. How you see it?
**Is this extension still relevant?** Or I should use another one?

Apart from the extension issue, **when I also click my button to log a new event, no other API calls get out of my web-page!** As if nothing happens by clicking the button!
