### ISSUE TITLE
Signing in with email link replaces existing  Github / Microsoft OAuth providers

### ISSUE THREAD

**Issue by dsl101** [firebase/firebase-js-sdk#8559]
### Operating System

Any

### Environment (if applicable)

Firefox 131

### Firebase SDK Version

10.13.2

### Firebase SDK Product(s)

Auth

### Project Tooling

Vue / Quasar

### Detailed Problem Description

Microsoft and Github OAuth providers are erased from user authentication providers after using sign in with email link. Our app is configured for OAuth via Google, Apple, Microsoft & Github, and sign in with email link. If a user signs up with a Google or Apple account, and then subsequently requests a sign in by email link, the email provider is added to their auth record as an additional provider, and they can still use their Google / Apple account to sign in.

But when creating an account via Microsoft or Github OAuth, if they then request an email link using the same email address as supplied by their OAuth account, the provider is _replaced_ by the email provider, and they can no longer use their OAuth account to sign in.

### Steps and code to reproduce issue

1. Configure OAuth & Email link sign up / sign in options, specifically "Link accounts that use the same email"
2. Sign up using Microsoft or Github OAuth provider
3. Sign out
4. Sign in using email link, using the same email address as configured for the OAuth provider in 2
5. User is successfully signed in, but their authentication record now only shows `password` in the auth user `providers` array
6. User can not now log in using the OAuth provider from 2, client side error is `auth/account-exists-with-different-credential`

By contrast, Apple and Google OAuth users show `[ "apple.com", "password" ]` and `[ "google.com", "password" ]` respectively in the `providers` array after using sign in with link.

As a side note, I'm curious why the provider is shown as `password` and not `emailLink`. On the client side, looking up the provider via `fetchSignInMethodsForEmail()` returns `providerId: "emailLink"`.

**Comment by DellaBitta** [comment]
Hi @dsl101,

The account linking and updating of providers, etc, is all handled on the backend and is beyond the scope of support that we can give in this SDK repository. Please open a ticket with [Firebase Support](https://firebase.google.com/support/troubleshooter/contact). This will put you in contact with the support team that works on the Firebase service.

I'm going to close this issue since I don't think we can help you much, but please do link to this ticket when you file a new issue with the Firebase Support team. Thanks!
