### ISSUE TITLE
Package `firebase-frameworks` is not compatible with firebase@v11

### ISSUE THREAD

**Issue by service-paradis** [firebase/firebase-js-sdk#8594]
### Operating System

Any

### Environment (if applicable)

Any

### Firebase SDK Version

11.0.1

### Firebase SDK Product(s)

Functions

### Project Tooling

NextJs using `frameworksBackend` hosting

### Detailed Problem Description

I updated Firebase dependency to v11 and got the following error:

```bash
  npm error peerOptional firebase@"^9.9.0 || ^10.0.0" from firebase-frameworks@0.11.4
  npm error node_modules/firebase-frameworks
  npm error   firebase-frameworks@"^0.11.0" from the root project
```

The package `firebase-frameworks` would need to be updated to be compatible with Firebase V11 (https://github.com/FirebaseExtended/firebase-framework-tools/blob/main/packages/firebase-frameworks/package.json#L56).

### Steps and code to reproduce issue

Update your Firebase dependency to v11 in a project using framework hosting.
Run `npm install` and look at the error.

I wanted to open an issue in the https://github.com/FirebaseExtended/firebase-framework-tools repo, but unfortunately, issues are not enabled there.

**Comment by looptheloop88** [comment]
Hi @service-paradis, thanks for patiently waiting. I reached out to our engineers to know where this issue is best directed.

For `firebase-frameworks` related issues, you may file it on [`firebase-tools`](https://github.com/firebase/firebase-tools/issues) repository. I will close this issue now, but feel free to reopen if you have any other concerns.

**Comment by service-paradis** [comment]
Ok, thank you @looptheloop88. I will try to open this issue on the firebase-tools repo!
