### ISSUE TITLE
Impossible to set icon via (Notification Composer)[GUI]

### ISSUE THREAD

**Issue by Mateostin** [firebase/firebase-js-sdk#8636]
### Operating System

Ubuntu 24.04

### Environment (if applicable)

Chrome 129.0.6668.58

### Firebase SDK Version

10.14.1

### Firebase SDK Product(s)

Messaging

### Project Tooling

JavaScript SDK libraries from the CDN

### Detailed Problem Description

Is there any way to override the imported firebase-js-sdk configuration for displaying push notifications in a service worker that was send via "Notification Composer"? I know that when sending notifications (data messages) via the API, this is possible, and I can do it. However, my problem is that I would like to be able to send push notifications from the Notification Composer, but there, I can't set the "Icon", this is crucial for us. Is there any workaround, for example, writing code before importing and overriding the default function, similar to the situation when i do something like this for change the "click_action"

```javascript
self.addEventListener('notificationclick', function(event) {
    // here my code for override the click_action URL
});
``` 

Why is it not possible to directly set the icon from the GUI? it's weird and unintuitive because it seems like a basic feature, just like setting the "image". Especially if we know that icon would be attached if we send notification by API (data message) and have this code in "firebase-messaging-sw.js":

```javascript
messaging.onBackgroundMessage((payload) => {
    console.log(
        '[firebase-messaging-sw.js] Received background message ',
        payload
    );

    if (!payload.notification) {
        const notificationTitle = 'My title';
        const notificationOptions = {
            body: 'My body msg',
            image: 'url-to-my-image',
            icon: 'url-to-my-icon',
            badge: 'url-to-my-badge',
        };

        // Show the notification
        self.registration.showNotification(notificationTitle, notificationOptions);
    }
});
``` 

Why this parameters cannot be set in "Notification Composer" by using "Additional options" for example like this:
![image](https://github.com/user-attachments/assets/f1ebf906-7994-41fe-89e3-36279d665600)

### Steps and code to reproduce issue

Send push notification from Notification Composer

**Comment by dlarocque** [comment]
Hi @Mateostin, I am not sure if I fully understand the issue. I see in the [reference documentation](https://firebase.google.com/docs/reference/js/messaging_sw.notificationpayload.md#notificationpayloadicon) that if the `icon` is not present in the notification request, FCM will use the icon found in your apps manifest.
Are you requesting to be able to send `icon` from the Notification Composer in the Firebase Console? If so, please submit this to [Firebase Support](https://firebase.google.com/support/troubleshooter/report/bugs) so that the Firebase Console team (not us) can see it.

As a temporary workaround, you could try adding an event listener on `'push'` events, then try overriding the payload to set the icon. Alternatively, you could use [patch-package](https://www.npmjs.com/package/patch-package) to override the behaviour of the SDK in [externalizePayload.ts](https://github.com/firebase/firebase-js-sdk/blob/main/packages/messaging/src/helpers/externalizePayload.ts#L64). I have not tried either of these myself, so I am not certain whether they will solve your issue.
