### ISSUE TITLE
This browser is not supported or 3rd party cookies and data may be disabled.

### ISSUE THREAD

**Issue by sriramkp** [firebase/firebase-js-sdk#865]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 7
  * Firebase SDK version: 5.0.1
  * Firebase Product: auth
  * Browser: Chrome

### [REQUIRED] **Login functionality is not working in chrome browser and giving the error message:

{code: "auth/web-storage-unsupported", message: "This browser is not supported or 3rd party cookies and data may be disabled."}

#### Relevant Code:

```
private oAuthSignIn(provider) {

    return this.afAuth.auth.signInWithPopup(provider)
      .then((credential) => this.saveUserInfo(credential.user))
      .catch(error => this.handleSignInError(error));
  }

signInWithGoogle() {

    const provider = new firebase.auth.GoogleAuthProvider();
    return this.oAuthSignIn(provider);
  }
```

**Comment by sriramkp** [comment]
Its disabled, by-default in my browser. It will happen with many other users and we cant ask every user to enable third-party cookie in their browsers. Because of this we will lose some user base.

Kindly let us know how to handle this scenario with any code changes that we can make.

**Comment by bojeil-google** [comment]
The underlying communication protocol we use depend on this. We have no plans to support this right now.

If this is an issue for you, you can use 3P libraries to get the OAuth credential (for example [google sign in library for JS](https://developers.google.com/identity/sign-in/web/) supports this environment) and then sign in to Firebase using the obtained ID token or access token with `signInWithCredential` or `signInAndRetrieveDataWithCredential`.

**Comment by bpetetot** [comment]
I had this issue because I used a custom domain. You have to correctly configure the domain, set it as `authDomain` and set correct redirect URLs in providers. You can see it in the firebase documentation:
 
![image](https://user-images.githubusercontent.com/516360/40915441-65873bac-67fc-11e8-93fa-9c8f5e28f8e0.png)

https://firebase.google.com/docs/auth/web/google-signin?authuser=0

**Comment by hiepxanh** [comment]
@bpetetot you are right if I block cookie of 2 but not 1, it will show this error
![image](https://user-images.githubusercontent.com/16970990/50403793-37ac2300-07d4-11e9-919c-24fcc07e9e3a.png)

**Comment by savaratkar** [comment]
@bpetetot solution is perfect. 
If your issue is on localhost you can comfortably disable third party cookies set by *.firebase.com.
If you are looking for a solution on your production environment. Then you need to follow steps provided by @bpetetot, which is also summarized here:
https://firebase.google.com/docs/auth/web/google-signin#customizing-the-redirect-domain-for-google-sign-in 
Also you need to connect your firebase host to your custom domain (I am assuming your app is not hosted on firebase hosting and that is only why you are getting this issue.). Follow the steps here:
https://stackoverflow.com/questions/52218777/firebase-auth-customized-redirect-domain-prompts-neterr-cert-common-name-inv#answer-52309442

Good luck!
This issue is old, my post is help for others.
