### ISSUE TITLE
When user try with facebook login auth/missing-identifier is being returned

### ISSUE THREAD

**Issue by spdecodeup** [firebase/firebase-js-sdk#8678]
### Operating System

windows 11

### Environment (if applicable)

Chrome 131.0.6778.139

### Firebase SDK Version

11.0.2

### Firebase SDK Product(s)

Auth

### Project Tooling

React app with webpack and vite

### Detailed Problem Description

When user try to login with there facebook account and user don't have email address in their profile. I am encounter with an error like this auth/missing-identifier.

### Steps and code to reproduce issue

await signInWithPopup(auth, facebookProvider);

**Comment by hsubox76** [comment]
I think we need some more information here. Is this a new user whose very first sign-in is with Facebook, or is this an existing user that had already created an account some other way (for example, with email/password, or Google sign-in) and they're now additionally trying to sign in with Facebook login?

Does the user not have an "email address in their profile" in their existing account in your project, or they don't have an email address in their Facebook profile (I don't think this is possible?). If it's the first one, what's the other sign-in method they used before Facebook, or how was their user account created?

**Comment by spdecodeup** [comment]
Hi @DellaBitta ,

Thanks for your insights! As per the video, our settings are enabled for both public_profile and email. The user has indeed shared their email address, but the issue seems to be that they’ve changed their Facebook email address. We reached out to Firebase Support, and they informed us that this issue is stemming from the SDK.

It seems like the SDK is not properly syncing the updated email address after the change, which could be causing the issue. We’ll keep troubleshooting on this front and will look into any further SDK updates or potential workarounds.

Let me know if you have any additional suggestions!

**Comment by DellaBitta** [comment]
Hi @spdecodeup,

I'm sorry that I misunderstood the issue yesterday. I didn't quite get the fact that the user later changed their email sharing setting.

I tested this quite a bit today and I never encountered the `auth/missing-identifier` error you originally mentioned. However I was able to reproduce the behavior where the email address never propagates to the Firebase account, even after deleting the Firebase Auth account in the console and generating a new one after the user's Facebook account's sharing configuration has changed.

Unfortunately I still think this is a service issue and you should reopen your older ticket with Firebase Support. Feel free to ask them to reach out to me if they have questions but I hope I have enough information in this ticket for them to investigate this further. I ensured that the errant email data was not being cached on the client side, and I have ways that this can be tested by the support team.

Here's what I've dug up today:

There seems to be an issue with caching information between the Firebase project and the Facebook project. I'm not sure if this is on the Facebook service side or the Firebase service side.

I ended up creating two Facebook projects, each with identical permissions to be able to view the user's email addresses (`Use cases` -> `Authenticate and request data from users with Facebook login` -> `Customize` -> `email` -> `Add`).

At first my Facebook user account had its email sharing settings set to `Only Me` (https://accountscenter.facebook.com/personal_info -> `Personal Details` -> `Contact Info` -> *click on email address* -> `visibility`).  I linked the Facebook App to Firebase App using the `App Id` and `App Secret` provided by Facebook. I also configured the `OAuth redirect URI` in the Facebook App.

I signed in with my Facebook user account credentials -- the resulting Firebase user didn't have an email address. I then went to my Facebook user account and made my email address public. I deleted the user in the Firebase console and signed in again. Still no email, as you reported.

A note: whenever testing a new configuration I delete the user in the Firebase console so that each has a new `User UID` after signing in with the Facebook provider to try to avoid getting cached data from the service.

Then, with my email address still marked as public in my Facebook user account, I created a new Facebook App and replaced the Facebook `App Id` and `App Secret` in my Firebase project console with the new Facebook App credentials. I deleted my Facebook user in the Firebase console and signed in using the Facebook provider. The resulitng new Firebase user has an email address!

As a final test I reconfigured the Firebase console to use the originaln Facebook App.  I deleted the user in the Firebase console and deleted all local data in the browser (click the icon next to the URL, `Cookies and site data` -> `Manage on-device site data` -> delete all of the options). I confirmed that the local cache of user data is cleared (`Inspect` -> `Application` -> `IndexedDB` -> `firebaseLocalStorageDb` shouldn't exist any more, if it does click `Delete database`).

Without changing my email sharing settings in my Facebook user account (which is still set to public) I signed in again and the resulting Firebase account didn't have an email address.

I flip back and forth between the two Facebook projects in the Firebase console without touching my Facebook user account settings, deleting the user in the Firebase console and then signing in. A Firebase user account created with the first Facebook app doesn't have an email address, whereas a Firebase user account created with the second Facebook app does.

Finally, local storage aside, one can see the Firebase service response for each configuration's users via `Inspector` -> `Network` -> `accounts.lookup`. The responses with the first Facebook app doesn't include an email address, whereas the second Facebook app configuration does.

I hope this helps you and the Firebase support team!

**Comment by spdecodeup** [comment]
Hi @DellaBitta ,
Thank you for your response. I tried implementing the same steps, but I am still encountering the same error. It might be an issue with my configuration. Could you please share the configuration you used for Facebook?

I have attached my configuration and a video demonstrating the error I’m encountering.

![Image](https://github.com/user-attachments/assets/94bb1e4d-ab87-468c-b3eb-eca33402c8e1)
https://github.com/user-attachments/assets/44f22aad-ee48-46ed-90e4-eefdd771b35d

**Comment by DellaBitta** [comment]
I have been testing without setting scopes:

```
const attemptSignIn = async () => {
  if (auth !== null) {
    await auth.authStateReady();
    if (auth.currentUser === null) {
      signInWithPopup(auth, new FacebookAuthProvider());
    } else {
      console.log("A user is already signed in.");
    }
  }
}

Though I just had a succssful sign in with your code (that sets scopes) and I'm sorry to say that I still didn't encounter an error. 

Is there any chance that you can create an minimal app that reproduces the error and share it with us?

**Comment by DellaBitta** [comment]
Also, our SDK doesn't have the text `missing-identifier` in it.  Where do you see the error?

**Comment by spdecodeup** [comment]
Hello @DellaBitta ,
Here is the minimal app of my project.

[firebaseDemo.zip](https://github.com/user-attachments/files/18211223/firebaseDemo.zip)

**Comment by DellaBitta** [comment]
Hi @spdecodeup, 

Thanks for putting it together so quickly, but unfortunately I can't reproduce the error with your example test app. Also I should note that the reported error string doesn't exist in our SDK source base. It would be interesting to hear where the error is being reported (console log, network response, result object, etc) and a stack trace of the error. I'd also suggest re-opening a ticket with Firebase Support since it appears that this is a problem at the Project level.

**Comment by spdecodeup** [comment]
Hi @DellaBitta @hsubox76 ,
Thank for the support the issue got resolved and we are encounter that issue because of the fetchSignInMethodsForEmail(auth, email).
