### ISSUE TITLE
"Firebase Error: There is another tab opened with offline persistence enabled" in Cordova app

### ISSUE THREAD

**Issue by rtm** [firebase/firebase-js-sdk#887]
### Describe your environment

  * Operating System version: Android 7.1.1/Cordova
  * Firebase SDK version: 4.10.0_____
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
When launching the app, on certain devices, sporadically, the following is displayed:

![image](https://user-images.githubusercontent.com/24391/40785441-227e1996-6506-11e8-9760-b2556ad3bfd7.png)

There is another, related (?) problem which occurs:

![image](https://user-images.githubusercontent.com/24391/40785907-5c1ab5dc-6507-11e8-98be-18cbc880c4e1.png)

What could account for such errors? Obviously, in a Webview on a phone we don't have "tabs" which could conflict with each other.

**Comment by schmidt-sebastian** [comment]
Thanks for this report! 

It sounds like you are hitting https://github.com/firebase/firebase-js-sdk/issues/720, which was fixed in Firebase 5.0.4 (https://github.com/firebase/firebase-js-sdk/pull/823). In older releases, we didn't properly detect low-quota scenarios on some newer Android systems.

Do you mind updating your Firebase dependency? If you are still hitting this issue with the newest version of Firestore, please re-open this issue.

**Comment by rtm** [comment]
Thanks, I'm still validating this fix.

But in any case would one not hope that the dependency on firebase in `angularfire2@5.0.0-rc10` would have been updated to `5.0.4` (right now it's `^5.0.3`), or are you separate teams?

**Comment by mikelehen** [comment]
@jamesdaniels or @davideast might be able to help with that (not sure what angularfire's dependency update cadence is).
