### ISSUE TITLE
Auth-types and storage-types should depend on util

### ISSUE THREAD

**Issue by mmermerkaya** [firebase/firebase-js-sdk#952]
Both of these packages depend on `@firebase/util` but don't have this dependency listed in their `package.json` files.

https://github.com/firebase/firebase-js-sdk/blob/3c064a3a60fa4eb558012839cf9a77913996876a/packages/auth-types/index.d.ts#L18

https://github.com/firebase/firebase-js-sdk/blob/3c064a3a60fa4eb558012839cf9a77913996876a/packages/storage-types/index.d.ts#L18

This causes issues like #900.

**Comment by hsubox76** [comment]
I've been looking into this and am not 100% sure but I think that since users npm install firebase and not the individual packages, and the firebase/app package (and others) include `@firebase/util` as a dependency, it will always be available for auth-types and storage-types.

I think what may have possibly happened in issue #900 is that the fix (changing 2 arguments to 1) was part of a major version bump for `@firebase/util` from 1.2.0 to 2.0.0?  And the user may have just run npm update, which doesn't update major versions.  It seems like a full reinstall as in issue #787 fixed problems like this for other people by forcing install of 2.0.0?

In principle it seems like it would make sense to add @firebase/util as a dependency but I've noticed none of the other "-types" packages have any actual "dependencies" in `package.json`, just peerDependencies (specifically `@firebase/app-types`, which they all import in the same way as `@firebase/util`) and devDependencies (on typescript), and I'm not sure if there's a reason for that.

For safety I could maybe add `@firebase/util` to the peerDependencies where `@firebase/app-types` already is.  This won't automatically install it for users but it will give a warning if it's behind and let them know to do the major update.

**Comment by hsubox76** [comment]
Actually I can't reproduce how upgrading the `firebase` package would fail to upgrade `@firebase/util` so I guess the above guess is not correct.

Looks like every other "*-types" package that imports `@firebase/util` does not specify it as a dependency in `package.json`, but all the others (app, database, messaging, testing) do specify it as a dependency in the main package (e.g., "database-types" doesn't but "database" does).  Since the *-types can't be installed independently, they'll always have it if the main package does.

The main `auth` and `storage` packages don't depend on it, only their corresponding *-types do, so I guess it makes sense to put it in `auth-types` and `storage-types` package.json dependencies.

**Comment by mmermerkaya** [comment]
Sounds good, thanks :slightly_smiling_face:
